import type { SixLangString } from "../engine.contract";

export const MAYAN_SEALS: Record<
  string,
  {
    color: "blue" | "red" | "white" | "yellow";
    narrative: SixLangString;
    symbol: string;
  }
> = {
  dog: {
    color: "white",
    narrative: {
      en: "White Dog (Oc): The power of love and loyalty. You are here to embody the wisdom of the heart, honoring your companions and following your true passion.",
      es: "Perro Blanco (Oc): El poder del amor y la lealtad. Estás aquí para encarnar la sabiduría del corazón.",
      fr: "Chien Blanc (Oc) : Le pouvoir de l'amour et de la loyauté. Vous êtes ici pour incarner la sagesse du cœur.",
      ja: "白い犬（オク）：愛と忠誠の力。あなたは心の知恵を体現し、仲間を尊重し、真の情熱に従うためにここにいます。",
      ko: "화이트 독 (옥): 사랑과 충성의 힘. 당신은 가슴의 지혜를 구현하고, 동료를 존중하며 진정한 열정을 따르기 위해 여기에 있습니다.",
      zh: "白狗（Oc）：爱和忠诚的力量。你在这里体现心灵的智慧，尊重你的伙伴并追随你真实的激情。",
    },
    symbol: "🐕",
  },
  dragon: {
    color: "red",
    narrative: {
      en: "Red Dragon (Imix): The primordial mother energy. You are here to nurture new beginnings and trust the flow of life. Birth and primal trust.",
      es: "Dragón Rojo (Imix): La energía madre primordial. Estás aquí para nutrir nuevos comienzos y confiar en el flujo de la vida. Nacimiento y confianza primordial.",
      fr: "Dragon Rouge (Imix) : L'énergie mère primordiale. Vous êtes ici pour nourrir de nouveaux départs et faire confiance au flux de la vie. Naissance et confiance primale.",
      ja: "赤い竜（イーミッシュ）：原初の母なるエネルギー。新しい始まりを育み、生命の流れを信頼するためにここにいます。誕生と根源的な信頼。",
      ko: "레드 드래곤 (이미쉬): 원초적 어머니 에너지. 새로운 시작을 양육하고 삶의 흐름을 신뢰하기 위해 여기에 있습니다.",
      zh: "红龙（Imix）：原始的母亲能量。你在这里孕育新的开始，信任生命的流动。诞生和原始的信任。",
    },
    symbol: "🐉",
  },
  eagle: {
    color: "blue",
    narrative: {
      en: "Blue Eagle (Men): The power of vision and mind. You are here to see from a higher perspective, envisioning the global future and keeping a clear focus.",
      es: "Águila Azul (Men): El poder de la visión y la mente.",
      fr: "Aigle Bleu (Men) : Le pouvoir de la vision et de l'esprit.",
      ja: "青い鷲（メン）：ヴィジョンと精神の力。あなたは高い視点から見渡し、地球規模の未来を構想し、明確な焦点を維持するためにここにいます。",
      ko: "블루 이글 (멘): 비전과 정신의 힘. 당신은 높은 관점에서 바라보며, 지구적 미래를 구상하고 명확한 집중을 유지하기 위해 여기에 있습니다.",
      zh: "蓝鹰（Men）：远见和思想的力量。你在这里从更高的角度观察，展望全球未来并保持清晰的专注。",
    },
    symbol: "🦅",
  },
  earth: {
    color: "red",
    narrative: {
      en: "Red Earth (Caban): The power of synchronicity and evolution. You are here to track the signs of the universe, evolving in alignment with planetary wisdom.",
      es: "Tierra Roja (Caban): El poder de la sincronicidad y la evolución.",
      fr: "Terre Rouge (Caban) : Le pouvoir de la synchronicité et de l'évolution.",
      ja: "赤い地球（カバン）：シンクロニシティと進化の力。あなたは宇宙のサインを追跡し、惑星の知恵と調和して進化するためにここにいます。",
      ko: "레드 어스 (카반): 동시성과 진화의 힘. 당신은 우주의 신호를 추적하며, 행성적 지혜와 나란히 진화하기 위해 여기에 있습니다.",
      zh: "红地球（Caban）：同步性和进化的力量。你在这里追踪宇宙的迹象，与行星智慧保持一致地进化。",
    },
    symbol: "🌍",
  },
  hand: {
    color: "blue",
    narrative: {
      en: "Blue Hand (Manik): The power of healing and accomplishment. You are here to manifest through action, healing yourself and others as you complete your work.",
      es: "Mano Azul (Manik): El poder de la sanación y el logro. Estás aquí para manifestar a través de la acción, sanando.",
      fr: "Main Bleue (Manik) : Le pouvoir de la guérison et de l'accomplissement. Vous êtes ici pour manifester par l'action, tout en guérissant.",
      ja: "青い手（マニク）：癒しと成就の力。あなたは行動を通じて実現し、仕事を完了させながら自分自身と他者を癒すためにここにいます。",
      ko: "블루 핸드 (매닉): 치유와 성취의 힘. 당신은 행동을 통해 실현하며, 일을 완성해 나가면서 자신과 타인을 치유하기 위해 여기에 있습니다.",
      zh: "蓝手（Manik）：疗愈和成就的力量。你在这里通过行动表现，在完成工作的同时疗愈自己和他人。",
    },
    symbol: "👋",
  },
  human: {
    color: "yellow",
    narrative: {
      en: "Yellow Human (Eb): The power of free will and wisdom. You are here to exercise your choice, influence your environment responsibly, and accumulate wisdom.",
      es: "Humano Amarillo (Eb): El poder del libre albedrío y la sabiduría. Estás aquí para ejercer tu elección.",
      fr: "Humain Jaune (Eb) : Le pouvoir du libre arbitre et de la sagesse. Vous êtes ici pour exercer votre choix.",
      ja: "黄色い人（エブ）：自由意志と知恵の力。あなたは自らの選択を行使し、責任を持って環境に影響を与え、知恵を蓄積するためにここにいます。",
      ko: "옐로우 휴먼 (에브): 자유 의지와 지혜의 힘. 당신은 자신의 선택을 실행하고, 책임감 있게 환경에 영향을 미치며, 지혜를 축적하기 위해 여기에 있습니다.",
      zh: "黄人（Eb）：自由意志和智慧的力量。你在这里行使你的选择权，负责任地影响你的环境，并积累智慧。",
    },
    symbol: "👤",
  },
  mirror: {
    color: "white",
    narrative: {
      en: "White Mirror (Etznab): The power of reflection and order. You are here to see the truth clearly, cutting through illusions and maintaining a sacred sword of wisdom.",
      es: "Espejo Blanco (Etznab): El poder del reflejo y el orden.",
      fr: "Miroir Blanc (Etznab) : Le pouvoir de la réflexion et de l'ordre.",
      ja: "白い鏡（エツナブ）：反射と秩序の力。あなたは真実を明確に見極め、幻想を断ち切り、神聖な知恵の剣を維持するためにここにいます。",
      ko: "화화이트 미러 (에츠납): 반사와 질서의 힘. 당신은 진실을 명확히 보고, 환상을 가로지르며 지혜의 신성한 칼을 유지하기 위해 여기에 있습니다.",
      zh: "白镜（Etznab）：反射和秩序的力量。你在这里看清真相，打破幻象并持守神圣的智慧之剑。",
    },
    symbol: "🪞",
  },
  monkey: {
    color: "blue",
    narrative: {
      en: "Blue Monkey (Chuen): The power of magic and play. You are here to disrupt illusions with humor and approach life with a playful, creative spirit.",
      es: "Mono Azul (Chuen): El poder de la magia y el juego. Estás aquí para romper ilusiones con humor.",
      fr: "Singe Bleu (Chuen) : Le pouvoir de la magie et du jeu. Vous êtes ici pour briser les illusions avec humour.",
      ja: "青い猿（チュエン）：魔法と遊びの力。あなたはユーモアで幻想を打破し、遊び心のある創造的な精神で人生にアプローチするためにここにいます。",
      ko: "블루 몽키 (츄엔): 마법과 유희의 힘. 당신은 유머로 환상을 깨트리고 장난기 넘치고 창의적인 정신으로 삶에 접근하기 위해 여기에 있습니다.",
      zh: "蓝猴（Chuen）：魔法和游戏的力量。你在这里用幽默打破幻象，以游戏和创造的精神对待生活。",
    },
    symbol: "🐒",
  },
  moon: {
    color: "red",
    narrative: {
      en: "Red Moon (Muluc): Universal water and the flow of emotions. You are here to purify your being through feelings and remain open to life's constant movement.",
      es: "Luna Roja (Muluc): El agua universal y el flujo de emociones. Estás aquí para purificar tu ser.",
      fr: "Lune Rouge (Muluc) : L'eau universelle et le flux des émotions. Vous êtes ici pour purifier votre être.",
      ja: "赤い月（ムルク）：普遍的な水と感情の流れ。あなたは感情を通じて自己を浄化し、人生の絶え間ない動きに対してオープンであるためにここにいます。",
      ko: "레드 문 (물룩): 우주적 물과 감정의 흐름. 당신은 느낌을 통해 자신의 존재를 정화하고 삶의 끊임없는 움직임에 열려 있기 위해 여기에 있습니다.",
      zh: "红月（Muluc）：大同之水和情绪的流动。你在这里通过感受净化自身，并对生活不断的运动保持开放。",
    },
    symbol: "🌙",
  },
  night: {
    color: "blue",
    narrative: {
      en: "Blue Night (Akbal): The power of the subconscious and dreams. You are here to dive deep into the darkness to bring hidden treasures and abundance to light.",
      es: "Noche Azul (Akbal): El poder del subconsciente y los sueños. Estás aquí para sumergirte en la oscuridad y traer tesoros ocultos y abundancia a la luz.",
      fr: "Nuit Bleue (Akbal) : Le pouvoir du subconscient et des rêves. Vous êtes ici pour plonger dans l'obscurité pour ramener les trésors cachés et l'abondance à la lumière.",
      ja: "青い夜（アクバル）：潜在意識と夢の力。あなたは隠された宝と豊かさを光の中に持ち出すために、暗闇の中に深く入り込むためにここにいます。",
      ko: "블루 나이트 (악발): 잠재의식과 꿈의 힘. 당신은 숨겨진 보물과 풍요로움을 빛으로 가져오기 위해 어둠 속으로 깊이 들어가기 위해 여기에 있습니다.",
      zh: "蓝夜（Akbal）：潜意识和梦想的力量。你在这里深入黑暗，将隐藏的宝藏和丰盛带入光明。",
    },
    symbol: "🌃",
  },
  seed: {
    color: "yellow",
    narrative: {
      en: "Yellow Seed (Kan): The potential for flourishing. You are here to target your goals, plant ideas, and nurture growth with focused awareness. Awareness and flowering.",
      es: "Semilla Amarilla (Kan): El potencial para florecer. Estás aquí para apuntar a tus metas, plantar ideas y nutrir el crecimiento con conciencia enfocada.",
      fr: "Graine Jaune (Kan) : Le potentiel d'épanouissement. Vous êtes ici pour cibler vos objectifs, planter des idées et nourrir la croissance avec une conscience focalisée.",
      ja: "黄色い種（カン）：開花の可能性。あなたは目標を定め、アイデアを植え、集中した意識で成長を育むためにここにいます。気づきと開花。",
      ko: "옐로우 시드 (칸): 번영을 위한 잠재력. 당신은 목표를 설정하고, 아이디어를 심고, 집중된 인식으로 성장을 양육하기 위해 여기에 있습니다.",
      zh: "黄种子（Kan）：繁荣的潜力。你在这里设定目标、播种创意，并以专注的意识培育成长。觉察与开花。",
    },
    symbol: "🌱",
  },
  serpent: {
    color: "red",
    narrative: {
      en: "Red Serpent (Chicchan): Life force and primordial instinct. You embody vitality and the power of the awakened body. Survival and physical transformation.",
      es: "Serpiente Roja (Chicchan): Fuerza vital e instinto primordial. Encarnas la vitalidad y el poder del cuerpo despierto. Supervivencia y transformación física.",
      fr: "Serpent Rouge (Chicchan) : Force vitale et instinct primordial. Vous incarnez la vitalité et le pouvoir du corps éveillé. Survie et transformation physique.",
      ja: "赤い蛇（チチャン）：生命力と原始的な本能。あなたは活力と目覚めた肉体の力を体現しています。生存と肉体的な変容。",
      ko: "레드 서펀트 (치찬): 생명력과 원초적 본능. 당신은 활력과 깨어난 몸의 힘을 구현합니다. 생존과 신체적 변형.",
      zh: "红蛇（Chicchan）：生命力和原始本能。你体现了活力和觉醒身体的力量。生存与身体转化。",
    },
    symbol: "🐍",
  },
  skywalker: {
    color: "red",
    narrative: {
      en: "Red Skywalker (Ben): The power of space and exploration. You are here to bridge heaven and earth, expanding your territory and seeking vertical adventures.",
      es: "Caminante del Cielo Rojo (Ben): El pilar entre el cielo y la tierra. Exploras y expands la conciencia.",
      fr: "Voyageur du Ciel Rouge (Ben) : Le pilier entre le ciel et la terre. Vous explorez et élargissez la conscience.",
      ja: "赤い空歩く者（ベン）：空間と探究の力。あなたは天と地を橋渡しし、自らの領域を拡大し、垂直的な冒険を求めるためにここにいます。",
      ko: "레드 스카이워커 (벤): 공간과 탐험의 힘. 당신은 하늘과 땅을 연결하고, 영역을 확장하며 수직적 모험을 추구하기 위해 여기에 있습니다.",
      zh: "红天行者（Ben）：空间和探索的力量。你在这里架起天地的桥梁，扩展你的领地并寻求垂直的冒险。",
    },
    symbol: "🚀",
  },
  star: {
    color: "yellow",
    narrative: {
      en: "Yellow Star (Lamat): The power of art and elegance. You are here to beautify the world, finding harmony and creating brilliance through artistic expression.",
      es: "Estrella Amarilla (Lamat): El poder del arte y la elegancia. Estás aquí para embellecer el mundo.",
      fr: "Étoile Jaune (Lamat) : Le pouvoir de l'art et de l'élégance. Vous êtes ici pour embellir le monde.",
      ja: "黄色い星（ラマト）：芸術と気品の力。あなたは芸術的な表現を通じて調和を見出し、輝きを創造することで世界を美しくするためにここにいます。",
      ko: "옐로우 스타 (라맛): 예술과 우아함의 힘. 당신은 예술적 표현을 통해 조화를 찾고 찬란함을 창조하며 세상을 아름답게 하기 위해 여기에 있습니다.",
      zh: "黄之星（Lamat）：艺术和优雅的力量。你在这里美化世界，通过艺术表达寻找和谐并创造光辉。",
    },
    symbol: "⭐",
  },
  storm: {
    color: "blue",
    narrative: {
      en: "Blue Storm (Cauac): The power of self-generation and energy. You are here to catalyze transformation, through the purifying energy of the internal thunder.",
      es: "Tormenta Azul (Cauac): El poder de la autogeneración y la energía.",
      fr: "Tempête Bleue (Cauac) : Le pouvoir de l'auto-génération et de l'énergie.",
      ja: "青い嵐（カワク）：自己発生とエネルギーの力。あなたは内なる雷の浄化エネルギーを通じて、変容を促すためにここにいます。",
      ko: "블루 스톰 (카왁): 자기 발생과 에너지의 힘. 당신은 내면의 번개라는 정화 에너지를 통해 변형을 촉진하기 위해 여기에 있습니다.",
      zh: "蓝风暴（Cauac）：自我产生和能量的力量。你在这里通过内在雷电的净化能量催化转化。",
    },
    symbol: "⚡",
  },
  sun: {
    color: "yellow",
    narrative: {
      en: "Yellow Sun (Ahau): The power of enlightenment and universal fire. You are here to radiate unconditional love, embodying the solar mastery of consciousness.",
      es: "Sol Amarillo (Ahau): El poder de la iluminación y el fuego universal.",
      fr: "Soleil Jaune (Ahau) : Le pouvoir de l'illumination et du feu universel.",
      ja: "黄色い太陽（アハウ）：悟りと普遍的な火の力。あなたは無条件の愛を放射し、意識の太陽的な熟達を体現するためにここにいます。",
      ko: "옐로우 선 (아하우): 깨달음과 우주적 불꽃의 힘. 당신은 무조건적인 사랑을 발산하며, 의식의 태양적 숙달을 체현하기 위해 여기에 있습니다.",
      zh: "黄太阳（Ahau）：启蒙和宇宙之火的力量。你在这里放射无条件的爱，体现意识的太阳精通。",
    },
    symbol: "☀️",
  },
  warrior: {
    color: "yellow",
    narrative: {
      en: "Yellow Warrior (Cib): The power of intelligence and fearlessness. You are here to question everything, following your inner truth with courage and cosmic grace.",
      es: "Guerrero Amarillo (Cib): El poder de la inteligencia y el valor.",
      fr: "Guerrier Jaune (Cib) : Le pouvoir de l'intelligence et du courage.",
      ja: "黄色い戦士（キブ）：知性と大胆不敵さの力。あなたはあらゆることに疑問を投げかけ、勇気と宇宙の恩寵を持って内なる真実に従うためにここにいます。",
      ko: "옐로우 워리어 (킵): 지성과 두려움 없음의 힘. 당신은 모든 것에 의문을 제기하며, 용기와 우주적 은총으로 내면의 진리를 따르기 위해 여기에 있습니다.",
      zh: "黄战士（Cib）：智慧和无畏的力量。你在这里质疑一切，带着勇气和宇宙的恩典追随你内心的真理。",
    },
    symbol: "🛡️",
  },
  wind: {
    color: "white",
    narrative: {
      en: "White Wind (Ik): The breath of spirit. You are here to communicate, channel divine messages, and inspire others through words. Communication and spirit.",
      es: "Viento Blanco (Ik): El aliento del espíritu. Estás aquí para comunicar, canalizar mensajes divinos e inspirar a otros a través de las palabras. Comunicación y espíritu.",
      fr: "Vent Blanc (Ik) : Le souffle de l'esprit. Vous êtes ici pour communiquer, canaliser des messages divins et inspirer les autres par les mots. Communication et esprit.",
      ja: "白い風（イーク）：精霊の息吹。あなたはコミュニケーションをとり、神聖なメッセージを伝え、言葉で他者にインスピレーションを与えるためにここにいます。",
      ko: "화이트 윈드 (익): 영의 숨결. 당신은 소통하고, 신성한 메시지를 전달하며, 말로 타인에게 영감을 주기 위해 여기에 있습니다.",
      zh: "白风（Ik）：灵性之气。你在这里沟通、传达神圣信息，并用言语激励他人。沟通与灵性。",
    },
    symbol: "🌬️",
  },
  wizard: {
    color: "white",
    narrative: {
      en: "White Wizard (Ix): The power of timelessness and receptivity. You are here to live in the present moment, manifesting through stillness and shamanic wisdom.",
      es: "Mago Blanco (Ix): El poder de la atemporalidad y la receptividad.",
      fr: "Magicien Blanc (Ix) : Le pouvoir de l'intemporalité et de la réceptivité.",
      ja: "白い魔法使い（イシュ）：永遠と受容性の力。あなたは今この瞬間に生き、静寂とシャーマニックな知恵を通じて実現するためにここにいます。",
      ko: "화이트 위저드 (익스): 영원함과 수용성의 힘. 당신은 현재의 순간에 살며, 고요함과 샤머니즘적 지혜를 통해 실현하기 위해 여기에 있습니다.",
      zh: "白巫师（Ix）：永恒和感受的力量。你在这里活在当下，通过寂静和萨满智慧来表现。",
    },
    symbol: "🧙",
  },
  world_bridger: {
    color: "white",
    narrative: {
      en: "White World-Bridger (Cimi): The power of death and transformation. You are here to let go of what no longer serves, bridging worlds through release and surrender.",
      es: "Enlazador de Mundos Blanco (Cimi): El poder de la muerte y la transformación. Estás aquí para soltar lo que ya no sirve, uniendo mundos.",
      fr: "Enlaceur des Mondes Blanc (Cimi) : Le pouvoir de la mort et de la transformation. Vous êtes ici pour lâcher ce qui ne sert plus, reliant les mondes.",
      ja: "白い世界の橋渡し（キミー）：死と変容の力。あなたはもはや役に立たないものを手放し、解放と委ねを通じて世界を橋渡しするためにここにいます。",
      ko: "화이트 월드브리저 (키미): 죽음과 변형의 힘. 당신은 더 이상 도움이 되지 않는 것을 놓아주고, 해방과 항복을 통해 세계를 연결하기 위해 여기에 있습니다.",
      zh: "白世界桥（Cimi）：死亡和转化的力量。你在这里放下不再有用的东西，通过释放和降服来架起世界的桥梁。",
    },
    symbol: "🌉",
  },
};

export const MAYAN_TONES: Record<number, SixLangString> = {
  1: {
    en: "Magnetic Tone: You attract and unify. You initiate new cycles with a clear purpose and magnetic presence.",
    es: "Tono Magnético: Atraes y unificas. Inicias nuevos ciclos con propósito.",
    fr: "Ton Magnétique : Vous attirez et unifiez. Vous initiez de nouveaux cycles.",
    ja: "磁気の音（1）：あなたは引きつけ、統一します。明確な目的と磁石のような存在感で新しいサイクルを開始します。",
    ko: "마그네틱 톤: 당신은 끌어당기며 통합합니다. 명확한 목적과 매력적인 존재감으로 새로운 주기를 시작합니다.",
    zh: "磁性音调：你吸引并统一。你带着清晰的目标和磁性的存在感开启新周期。",
  },
  2: {
    en: "Lunar Tone: You polarize and stabilize. You challenge norms and find balance through duality.",
    es: "Tono Lunar: Polarizas y estabilizas.",
    fr: "Ton Lunaire : Vous polarisez et stabilisez.",
    ja: "月の音（2）：あなたは分極化し、安定させます。規範に挑戦し、二元性を通じてバランスを見出します。",
    ko: "루나 톤: 당신은 양극화하며 안정시킵니다. 규범에 도전하고 이원성을 통해 균형을 찾습니다.",
    zh: "月亮音调：你极化并稳定。你挑战规范，通过二元性寻找平衡。",
  },
  3: {
    en: "Electric Tone: You activate and bond. You serve as a catalyst for movement and connection.",
    es: "Tono Eléctrico: Activas y vinculas.",
    fr: "Ton Électrique : Vous activez et liez.",
    ja: "電気の音（3）：あなたは活性化し、繋ぎます。動きとつながりのための触媒としての役割を果たします。",
    ko: "일렉트릭 톤: 당신은 활성화하며 결합합니다. 움직임과 연결을 위한 촉매제 역할을 합니다.",
    zh: "电力音调：你激活并结合。你是运动和连接的催化剂。",
  },
  4: {
    en: "Self-Existing Tone: You define and measure. You bring structure and form to your ideas.",
    es: "Tono Autoexistente: Defines y mides.",
    fr: "Ton Auto-Existant : Vous définissez et mesurez.",
    ja: "自己存在の音（4）：あなたは定義し、測定します。アイデアに構造と形を与えます。",
    ko: "셀프 이그지스팅 톤: 당신은 정의하고 측정합니다. 아이디어에 구조와 형태를 부여합니다.",
    zh: "自我存在音调：你定义并衡量。你为想法带来结构和形式。",
  },
  5: {
    en: "Overtone Tone: You empower and command. You radiate authority and take the lead in action.",
    es: "Tono Entonado: Empoderas y mandas.",
    fr: "Ton Harmonique : Vous donnez du pouvoir et commandez.",
    ja: "倍音の音（5）：あなたは力を与え、命じます。権威を放射し、行動において率先して指揮をとります。",
    ko: "오버톤 톤: 당신은 권한을 부여하고 명령합니다. 권위를 발산하며 행동에 앞장섭니다.",
    zh: "超频音调：你赋能并指挥。你散发权威并在行动中处于领导地位。",
  },
  6: {
    en: "Rhythmic Tone: You balance and organize. You find equality and flow through efficient movement.",
    es: "Tono Rítmico: Equilibras y organizas.",
    fr: "Ton Rythmique : Vous équilibrez et organisez.",
    ja: "リズムの音（6）：あなたはバランスをとり、組織化します。効率的な動きを通じて平等と流れを見出します。",
    ko: "리드믹 톤: 당신은 균형을 잡고 조직합니다. 효율적인 움직임을 통해 평등과 흐름을 찾습니다.",
    zh: "韵律音调：你平衡并组织。你通过高效的运动寻找平等和流动。",
  },
  7: {
    en: "Resonant Tone: You channel and inspire. You direct mystical forces and find center in spirit.",
    es: "Tono Resonante: Canalizas y sintonizas.",
    fr: "Ton Résonnant : Vous canalisez et inspirez.",
    ja: "共振の音（7）：あなたはチャネルとなり、鼓舞します。神秘的な力を導き、精神において中心を見出します。",
    ko: "레조넌트 톤: 당신은 통로가 되어 영감을 줍니다. 신비로운 힘을 인도하고 영 안에서 중심을 찾습니다.",
    zh: "共振音调：你引导并启发。你引导神秘力量并在灵性中找到中心。",
  },
  8: {
    en: "Galactic Tone: You harmonize and model. You embody integrity and live in alignment with universal cycles.",
    es: "Tono Galáctico: Armonizas y modelas.",
    fr: "Ton Galactique : Vous harmonisez et modélisez.",
    ja: "銀河の音（8）：あなたは調和し、模範となります。誠実さを体現し、普遍的なサイクルと同調して生きます。",
    ko: "갤럭틱 톤: 당신은 조화를 이루고 모델이 됩니다. 정직을 체현하고 우주적 주기와 정렬되어 살아갑니다.",
    zh: "银河音调：你和谐并模仿。你体现诚信并与宇宙周期保持一致。",
  },
  9: {
    en: "Solar Tone: You pulse and realize. You manifest your intentions through strong determination.",
    es: "Tono Solar: Pulsas y realizas.",
    fr: "Ton Solaire : Vous pulsez et réalisez.",
    ja: "太陽の音（9）：あなたは鼓動し、実現します。強い意志を持って意図を具現化します。",
    ko: "솔라 톤: 당신은 맥동하며 실현합니다. 강한 결단력을 통해 의도를 구체화합니다.",
    zh: "太阳音调：你脉动并实现。你通过坚定的决心表现你的意图。",
  },
  10: {
    en: "Planetary Tone: You perfect and produce. You bring projects to manifestation and full fruition.",
    es: "Tono Planetario: Perfeccionas y produces.",
    fr: "Ton Planétaire : Vous perfectionnez et produisez.",
    ja: "惑星の音（10）：あなたは完成させ、作り出します。プロジェクトを具現化し、完全な実りをもたらします。",
    ko: "플래너터리 톤: 당신은 완벽하게 만들고 생산합니다. 프로젝트를 구체화하고 완전한 결실을 맺게 합니다.",
    zh: "行星音调：你完善并产生。你使项目具体化并达到完全的成果。",
  },
  11: {
    en: "Spectral Tone: You release and dissolve. You let go of the old to make room for liberation and new light.",
    es: "Tono Espectral: Liberas y disuelves.",
    fr: "Ton Spectral : Vous libérez et dissolvez.",
    ja: "スペクトルの音（11）：あなたは解放し、溶かします。解放と新しい光のための空間を作るために、古いものを手放します。",
    ko: "스펙트럴 톤: 당신은 해방하고 용해합니다. 해방과 새로운 빛을 위한 공간을 만들기 위해 낡은 것을 놓아줍니다.",
    zh: "光谱音调：你释放并溶解。你放下旧事物，为解放和新光芒腾出空间。",
  },
  12: {
    en: "Crystal Tone: You dedicate and universalize. You share knowledge and cooperate for the collective good.",
    es: "Tono Cristal: Te dedicas y universalizas.",
    fr: "Ton Cristal : Vous dédiez et universalisez.",
    ja: "水晶の音（12）：あなたは奉仕し、普遍化します。知識を共有し、全体の利益のために協力します。",
    ko: "크리스탈 톤: 당신은 헌신하고 보편화합니다. 지식을 공유하고 공동의 이익을 위해 협력합니다.",
    zh: "水晶音调：你奉献并普遍化。你分享知识并为集体利益而合作。",
  },
  13: {
    en: "Cosmic Tone: You endure and transcend. You complete the journey and prepare for the next cosmic octave.",
    es: "Tono Cósmico: Trasciendes y perduras.",
    fr: "Ton Cosmique : Vous transcendez et perdurez.",
    ja: "宇宙の音（13）：あなたは耐え、超越します。旅を完了し、次の宇宙のオクターブに備えます。",
    ko: "코스믹 톤: 당신은 감내하고 초월합니다. 여정을 완료하고 다음 우주적 옥타브를 준비합니다.",
    zh: "宇宙音调：你忍受并超越。你完成旅程并为下一个宇宙音阶做准备。",
  },
};

export const COLOR_MEANINGS: Record<string, SixLangString> = {
  blue: {
    en: "Blue (West): Transformation and change. The power to transform and transcend limitations.",
    es: "Azul (Oeste): Transformación y cambio. El poder de transformar y trascender las limitaciones.",
    fr: "Bleu (Ouest) : Transformation et changement. Le pouvoir de transformer et de transcender les limitations.",
    ja: "青 (西): 変容と変化。変容し、制限を超越する力。",
    ko: "블루 (서쪽): 변화와 변형. 변화시키고 한계를 초월하는 힘.",
    zh: "蓝 (西): 转化和改变。转化和超越限制的力量。",
  },
  red: {
    en: "Red (East): Initiation, birth, and new beginnings. The power to start and the courage to begin.",
    es: "Rojo (Este): Iniciación, nacimiento y nuevos comienzos. El poder de comenzar y el coraje para empezar.",
    fr: "Rouge (Est) : Initiation, naissance et nouveaux départs. Le pouvoir de commencer et le courage de débuter.",
    ja: "赤 (東): 開始、誕生、新しい始まり。始める力と始める勇気。",
    ko: "레드 (동쪽): 시작, 탄생, 새로운 시작. 시작하는 힘과 시작할 용기.",
    zh: "红 (东): 启动、诞生和新的开始。开始的力量和开始的勇气。",
  },
  white: {
    en: "White (North): Refinement and purification. The power to clarify and refine what has been initiated.",
    es: "Blanco (Norte): Refinamiento y purificación. El poder de aclarar y refinar lo que se ha iniciado.",
    fr: "Blanc (Nord) : Raffinement et purification. Le pouvoir de clarifier et d'affiner ce qui a été inicié.",
    ja: "白 (北): 洗練と浄化。開始されたものを明確にし、洗練する力。",
    ko: "화이트 (북쪽): 정제와 정화. 시작된 것을 명확히 하고 정제하는 힘.",
    zh: "白 (北): 提炼和净化。澄清和提炼已启动事物的力量。",
  },
  yellow: {
    en: "Yellow (South): Ripening and harvest. The power to manifest fully and share abundance.",
    es: "Amarillo (Sur): Maduración y cosecha. El poder de manifestar plenamente y compartir la abundancia.",
    fr: "Jaune (Sud) : Mûrissement et récolte. Le pouvoir de manifester pleinement et de partager l'abondance.",
    ja: "黄 (南): 成熟と収穫。完全に顕現し、豊かさを分かち合う力。",
    ko: "옐로우 (남쪽): 익음과 수확. 완전히 현현하고 풍요를 나누는 힘.",
    zh: "黄 (南): 成熟和收获。完全显化和分享丰盛的力量。",
  },
};

export const SEAL_ORDER = [
  "dragon",
  "wind",
  "night",
  "seed",
  "serpent",
  "world_bridger",
  "hand",
  "star",
  "moon",
  "dog",
  "monkey",
  "human",
  "skywalker",
  "wizard",
  "eagle",
  "warrior",
  "earth",
  "mirror",
  "storm",
  "sun",
];

export const TONE_ACTIONS: Record<number, SixLangString> = {
  1: {
    en: "unifying purpose",
    es: "propósito unificador",
    fr: "but unificateur",
    ja: "目的の統一",
    ko: "목적 통합",
    zh: "统一目标",
  },
  2: {
    en: "identifying challenges",
    es: "identificación de desafíos",
    fr: "identification des défis",
    ja: "挑戦の特定",
    ko: "도전 식별",
    zh: "识别挑战",
  },
  3: {
    en: "activating service",
    es: "activación de servicio",
    fr: "activation du service",
    ja: "奉仕の活性化",
    ko: "봉사 활성화",
    zh: "激活服务",
  },
  4: {
    en: "defining form",
    es: "definición de forma",
    fr: "définition de forme",
    ja: "形の定義",
    ko: "형태 정의",
    zh: "定义形态",
  },
  5: {
    en: "empowering radiance",
    es: "empoderamiento del resplandor",
    fr: "autonomisation de l'éclat",
    ja: "輝きの付与",
    ko: "빛남 부여",
    zh: "赋能光芒",
  },
  6: {
    en: "organizing balance",
    es: "organización del equilibrio",
    fr: "organisation de l'équilibre",
    ja: "バランスの組織化",
    ko: "균형 조직",
    zh: "组织平衡",
  },
  7: {
    en: "channeling attunement",
    es: "canalización de sintonía",
    fr: "canalisation de l'accordage",
    ja: "共鳴のチャネリング",
    ko: "조율 채널링",
    zh: "引导调谐",
  },
  8: {
    en: "modeling integrity",
    es: "modelado de integridad",
    fr: "modélisation de l'intégrité",
    ja: "誠実さのモデリング",
    ko: "무결성 모델링",
    zh: "建模诚信",
  },
  9: {
    en: "realizing intention",
    es: "realización de intención",
    fr: "réalisation de l'intention",
    ja: "意図の実現",
    ko: "의도 실현",
    zh: "实现意图",
  },
  10: {
    en: "perfecting manifestation",
    es: "perfeccionamiento de la manifestación",
    fr: "perfectionnement de la manifestation",
    ja: "顕現の完成",
    ko: "현현 완성",
    zh: "完善显化",
  },
  11: {
    en: "liberating release",
    es: "liberación y descarga",
    fr: "libération et relâchement",
    ja: "解放と放出",
    ko: "해방 방출",
    zh: "解放释放",
  },
  12: {
    en: "dedicating cooperation",
    es: "dedicación a la cooperación",
    fr: "dévouement à la coopération",
    ja: "協力への献身",
    ko: "협력 헌신",
    zh: "奉献合作",
  },
  13: {
    en: "cosmic presence",
    es: "presencia cósmica",
    fr: "présence cosmique",
    ja: "宇宙的存在感",
    ko: "우주적 존재",
    zh: "宇宙存在",
  },
};
