import { SixLangString } from "../engine.contract";

/**
 * MBTI Deep Shard Data
 * Cognitive functions and MBTI type deep data separated from logic.
 */

export const COGNITIVE_FUNCTIONS: Record<
  string,
  { name: SixLangString; narrative: SixLangString }
> = {
  Fe: {
    name: {
      en: "Extraverted Feeling",
      es: "Sentiment Extravertido",
      fr: "Sentiment Extraverti",
      ja: "外向的感情",
      ko: "외향 감정",
      zh: "外向情感",
    },
    narrative: {
      en: "You naturally attune to others' emotions and work to maintain group harmony. You express care outwardly.",
      es: "Te sintonizas naturalmente con las emociones de otros y trabajas para mantener la armonía del grupo. Expresas tu interés hacia afuera.",
      fr: "Vous vous accordez naturellement aux émotions des autres et travaillez pour maintenir l'harmonie du groupe. Vous exprimez vos soins vers l'extérieur.",
      ja: "他者の感情に自然に同調し、グループの調和を維持するために働きます。外向的にケアを表現します。",
      ko: "다른 사람들의 감정에 자연스럽게 공감하고 그룹 조화를 유지하기 위해 노력합니다. 배려를 밖으로 표현합니다.",
      zh: "你自然地与他人的情感同调，努力保持群体和谐。你外向地表达关怀。",
    },
  },
  Fi: {
    name: {
      en: "Introverted Feeling",
      es: "Sentimiento Introvertido",
      fr: "Sentiment Introverti",
      ja: "内向的感情",
      ko: "내향 감정",
      zh: "内向情感",
    },
    narrative: {
      en: "You have a deep inner value system that guides your decisions. You feel intensely but process emotions internally.",
      es: "Tienes un profundo sistema de valores internos que guía tus decisiones. Sientes intensamente pero procesas las emociones internamente.",
      fr: "Vous avez un système de valeurs internes profond qui guide vos décisions. Vous ressentez intensément mais traitez les émotions intérieurement.",
      ja: "決定を導く深い内面の価値システムがあります。強烈に感じますが、感情を内部で処理します。",
      ko: "결정을 안내하는 깊은 내면의 가치 체계가 있습니다. 강렬하게 느끼지만 감정을 내면적으로 처리합니다.",
      zh: "你有一个指导决策的深层内在价值体系。你强烈地感受，但在内心处理情绪。",
    },
  },
  Ne: {
    name: {
      en: "Extraverted Intuition",
      es: "Intuición Extravertida",
      fr: "Intuition Extravertie",
      ja: "外向的直観",
      ko: "외향 직관",
      zh: "外向直觉",
    },
    narrative: {
      en: "You see possibilities everywhere, generating ideas rapidly and exploring novel connections. Your mind naturally branches out.",
      es: "Ves posibilidades en todas partes, generando ideas rápidamente y explorando conexiones nuevas. Tu mente se ramifica naturalmente.",
      fr: "Vous voyez des possibilités partout, générant des idées rapidement et explorant de nouvelles connexions. Votre esprit se ramifie naturellement.",
      ja: "どこにでも可能性を見出し、アイデアを素早く生成し、新しいつながりを探求します。あなたの思考は自然に枝分かれします。",
      ko: "어디서나 가능성을 보고, 빠르게 아이디어를 생성하며 새로운 연결을 탐구합니다. 당신의 생각은 자연스럽게 뻗어나갑니다.",
      zh: "你到处看到可能性，快速产生想法并探索新的联系。你的思想自然地向外延伸。",
    },
  },
  Ni: {
    name: {
      en: "Introverted Intuition",
      es: "Intuición Introvertida",
      fr: "Intuition Introvertie",
      ja: "内向的直観",
      ko: "내향 직관",
      zh: "内向直觉",
    },
    narrative: {
      en: "You perceive patterns beneath the surface, seeing the future implications of current events. Your insights often come as sudden realizations.",
      es: "Percibes patrones bajo la superficie, viendo las implicaciones futuras de los eventos actuales.",
      fr: "Vous percevez des modèles sous la surface, voyant les implications futures des événements actuels. Vos intuitions viennent souvent comme des réalisations soudaines.",
      ja: "表面下のパターンを知覚し、現在の出来事の将来への影響を見ます。洞察は突然の気づきとして現れます。",
      ko: "표면 아래의 패턴을 인지하고, 현재 사건의 미래 함의를 봅니다. 통찰력은 종종 갑작스러운 깨달음으로 옵니다.",
      zh: "你能感知表面下的模式，看到当前事件的未来影响。你的洞察力常以突然的顿悟形式出现。",
    },
  },
  Se: {
    name: {
      en: "Extraverted Sensing",
      es: "Sensación Extravertida",
      fr: "Sensation Extravertie",
      ja: "外向的感覚",
      ko: "외향 감각",
      zh: "外向感觉",
    },
    narrative: {
      en: "You are fully present in the moment, absorbing sensory experiences intensely. You notice concrete details others miss.",
      es: "Estás completamente presente en el momento, absorbiendo experiencias sensoriales intensamente. Notas detalles concretos que otros pasan por alto.",
      fr: "Vous êtes pleinement présent dans l'instant, absorbant intensément les expériences sensorielles. Vous remarquez des détails concrets que les autres manquent.",
      ja: "瞬間に完全に存在し、感覚的体験を強烈に吸収します。他の人が見逃す具体的な詳細に気づきます。",
      ko: "순간에 완전히 몰입하여 감각적 경험을 강렬하게 흡수합니다. 다른 사람들이 놓치는 구체적인 세부 사항을 알아차립니다.",
      zh: "你完全活在当下，强烈地吸收感官体验。你注意到别人忽略的具体细节。",
    },
  },
  Si: {
    name: {
      en: "Introverted Sensing",
      es: "Sensación Introvertida",
      fr: "Sensation Introvertie",
      ja: "内向的感覚",
      ko: "내향 감각",
      zh: "内向感觉",
    },
    narrative: {
      en: "You store detailed memories of past experiences, comparing present situations to what has worked before.",
      es: "Almacenas recuerdos detallados de experiencias pasadas, comparando situaciones presentes con lo que funcionó antes.",
      fr: "Vous stockez des souvenirs détaillés des expériences passées, comparant les situations présentes à ce qui a fonctionné auparavant.",
      ja: "過去の経験の詳細な記憶を蓄積し、現在の状況を以前うまくいったことと比較します。",
      ko: "과거 경험의 상세한 기억을 저장하고, 현재 상황을 이전에 효과가 있었던 것과 비교합니다.",
      zh: "你储存过去经历的详细记忆，将现在的情况与以前有效的方法进行比较。",
    },
  },
  Te: {
    name: {
      en: "Extraverted Thinking",
      es: "Pensamiento Extravertido",
      fr: "Pensée Extravertie",
      ja: "外向的思考",
      ko: "외향 사고",
      zh: "外向思维",
    },
    narrative: {
      en: "You organize the external world for maximum efficiency. You naturally structure systems, set goals, and measure results.",
      es: "Organizas el mundo externo para máxima eficiencia. Estructuras sistemas, estableces metas y mides resultados.",
      fr: "Vous organisez le monde extérieur pour une efficacité maximale. Vous structurez naturellement les systèmes, fixez des objectifs et mesurez les résultats.",
      ja: "最大効率のために外部世界を整理します。自然にシステムを構造化し、目標を設定し、結果を測定します。",
      ko: "외부 세계를 최대 효율성을 위해 조직합니다. 자연스럽게 시스템을 구조화하고, 목표를 설정하며, 결과를 측정합니다.",
      zh: "你为最大效率组织外部世界。你自然地构建系统、设定目标并衡量结果。",
    },
  },
  Ti: {
    name: {
      en: "Introverted Thinking",
      es: "Pensamiento Introvertido",
      fr: "Pensée Introvertie",
      ja: "内向的思考",
      ko: "내향 사고",
      zh: "内向思维",
    },
    narrative: {
      en: "You build internal frameworks of logic, seeking to understand how things work at a fundamental level.",
      es: "Construyes marcos internos de lógica, buscando entender cómo funcionan las cosas a nivel fundamental.",
      fr: "Vous construisez des cadres logiques internes, cherchant à comprendre comment les choses fonctionnent à un niveau fondamental.",
      ja: "内部論理フレームワークを構築し、物事が根本的なレベルでどのように機能するかを理解しようとします。",
      ko: "내부적 논리 프레임워크를 구축하여 근본적인 수준에서 사물이 어떻게 작동하는지 이해하려 합니다.",
      zh: "你建立内部逻辑框架，试图从根本层面理解事物如何运作。",
    },
  },
};

export const MBTI_DEEP_DATA: Record<
  string,
  {
    challenges: SixLangString[];
    growthPath: SixLangString;
    lifeImplications: SixLangString;
    strengths: SixLangString[];
    typeNarrative: SixLangString;
    worldview: SixLangString;
  }
> = {
  ENFP: {
    challenges: [
      {
        en: "Difficulty following through on projects (shiny object syndrome)",
        es: "Dificultad para completar proyectos (síndrome del objeto brillante)",
        fr: "Difficulté à mener les projets à terme (syndrome de l'objet brillant)",
        ja: "プロジェクトをやり遂げるのが難しい（新しいものに目移りする症候群）",
        ko: "프로젝트 완수 어려움 (반짝이는 물체 증후군)",
        zh: "难以坚持完成项目（新事物综合症）",
      },
      {
        en: "May overlook practical details in pursuit of ideas",
        es: "Puede pasar por alto detalles prácticos al perseguir ideas",
        fr: "Peut négliger les détails pratiques à la poursuite d'idées",
        ja: "アイデアを追求するあまり、実用的な詳細を見落とすことがある",
        ko: "아이디어 추구에서 실용적 세부 사항을 간과할 수 있음",
        zh: "在追求想法时可能忽视实际细节",
      },
      {
        en: "Can be emotionally reactive under stress",
        es: "Puede ser emocionalmente reactivo bajo estrés",
        fr: "Peut être émotionnellement réactif sous stress",
        ja: "ストレス下で感情的に反応することがある",
        ko: "스트레스 하에서 감정적으로 반응할 수 있음",
        zh: "压力下可能产生情绪化反应",
      },
    ],
    growthPath: {
      en: "Develop your Si (discipline and follow-through) and Te (systematic execution). Practice finishing what you start, create routines, and learn to sit with discomfort rather than seeking constant novelty.",
      es: "Desarrolla tu Si (disciplina y seguimiento) y Te (ejecución sistemática). Practica terminar lo que comienzas, crea rutinas y aprende a convivir con la incomodidad en lugar de buscar novedad constante.",
      fr: "Développez votre Si (discipline et suivi) et Te (exécution systématique). Pratiquez la finition de ce que vous commencez, créez des routines et apprenez à rester avec l'inconfort plutôt que de chercher constamment la nouveauté.",
      ja: "Si（規律と粘り強さ）とTe（体系的な実行）を開発してください。始めたことを最後までやり遂げる練習をし、ルーチンを作り、絶えず新しさを求めるのではなく、不快感と向き合うことを学びましょう。",
      ko: "Si(규율과 완수)와 Te(체계적 실행)을 개발하세요. 시작한 것을 끝내는 연습, 루틴 만들기, 끊임없는 새로움을 찾기보다 불편함과 함께 앉는 법을 배우세요.",
      zh: "发展你的Si（纪律与坚持）和Te（系统执行）。练习有始有终，建立常规，并学会忍受不适而不是不断寻求新奇。",
    },
    lifeImplications: {
      en: "Your enthusiasm is contagious - you inspire and energize others. Relationships are passionate but require grounding. Career should offer variety and meaning; routine work drains you. Your ideas can change the world if you learn to execute them.",
      es: "Tu entusiasmo es contagioso; inspiras y das energía a los demás. Las relaciones son apasionadas pero requieren conexión a tierra. La carrera debe ofrecer variedad y significado; el trabajo rutinario te agota. Tus ideas pueden cambiar el mundo si aprendes a ejecutarlas.",
      fr: "Votre enthousiasme est contagieux - vous inspirez et dynamisez les autres. Les relations sont passionnées mais nécessitent un ancrage. La carrière doit offrir variété et sens ; le travail routinier vous épuise. Vos idées peuvent changer le monde si vous apprenez à les exécuter.",
      ja: "あなたの情熱は伝染し、他の人を鼓舞し活力を与えます。人間関係は情熱的ですが、地に足をつける必要があります。キャリアは多様性と意味を提供すべきです。型通りの仕事はあなたを消耗させます。実行することを学べば、あなたのアイデアは世界を変えることができます。",
      ko: "열정이 전염성이 있습니다 - 다른 사람들에게 영감을 주고 에너지를 줍니다. 관계는 열정적이지만 그라운딩이 필요합니다. 직업은 다양성과 의미를 제공해야 합니다; 일상적인 일이 당신을 지치게 합니다. 실행을 배우면 아이디어가 세상을 바꿀 수 있습니다.",
      zh: "你的热情具有感染力——你激励并为他人注入活力。人际关系热烈但需要扎根。职业应该提供多样性和意义；常规工作会耗尽你的精力。如果你学会执行，你的想法可以改变世界。",
    },
    strengths: [
      {
        en: "Infectious enthusiasm and energy",
        es: "Entusiasmo y energía infecciosos",
        fr: "Enthousiasme et énergie contagieux",
        ja: "伝染性の高い熱意とエネルギー",
        ko: "전염성 있는 열정과 에너지",
        zh: "极具感染力的热情和能量",
      },
      {
        en: "Ability to see possibilities others miss",
        es: "Capacidad para ver posibilidades que otros pasan por alto",
        fr: "Capacité à voir les possibilités que les autres manquent",
        ja: "他の人が見逃す可能性を見出す能力",
        ko: "다른 사람들이 놓치는 가능성을 보는 능력",
        zh: "洞察他人漏掉可能性的能力",
      },
      {
        en: "Natural connector of people and ideas",
        es: "Conector natural de personas e ideas",
        fr: "Connecteur naturel de personnes et d'idées",
        ja: "人とアイデアの自然なコネクター",
        ko: "사람과 아이디어의 자연스러운 연결자",
        zh: "天生的人员和想法连接者",
      },
      {
        en: "Deep authenticity and value-driven life",
        es: "Autenticidad profunda y vida impulsada por valores",
        fr: "Authenticité profonde et vie guidée par les valeurs",
        ja: "深い誠実さと価値観に基づいた人生",
        ko: "깊은 진정성과 가치 중심의 삶",
        zh: "深厚的真实感和价值观驱动的生活",
      },
    ],
    typeNarrative: {
      en: "The Campaigner (ENFP): You are a possibility machine, radiating warmth and generating ideas at lightning speed. Your Ne-Fi combination means you see the world as full of potential waiting to be explored, filtered through a deep sense of personal values.",
      es: "El Activista (ENFP): Eres una máquina de posibilidades, irradias calidez y generas ideas a la velocidad del rayo. Tu combinación Ne-Fi significa que ves el mundo lleno de potencial esperando ser explorado, filtrado a través de un profundo sentido de valores personales.",
      fr: "Le Militant (ENFP): Vous êtes une machine à possibilités, rayonnant de chaleur et générant des idées à la vitesse de l'éclair. Votre combinaison Ne-Fi signifie que vous voyez le monde comme plein de potentiel attendant d'être exploré, filtré par un sens profond des valeurs personnelles.",
      ja: "運動家 (ENFP): あなたは可能性の塊であり、温かさを放ち、電光石火の速さでアイデアを生み出します。Ne-Fiの組み合わせにより、あなたは世界を一連の個人的な価値観を通してフィルタリングされた、探求されるのを待っている無限の可能性に満ちた場所として見ています。",
      ko: "활동가 (ENFP): 가능성 기계로, 따뜻함을 발산하고 번개같은 속도로 아이디어를 생성합니다. Ne-Fi 조합은 깊은 개인적 가치를 통해 필터링된, 탐구되기를 기다리는 잠재력으로 가득 찬 세상으로 봅니다.",
      zh: "竞选者 (ENFP)：你是一台可能性机器，散发着温暖并以闪电般的速度产生想法。你的Ne-Fi组合意味着你将世界视为充满等待探索的潜力，并透过深厚的个人价值观进行过滤。",
    },
    worldview: {
      en: "Life is an adventure to be lived fully. You see connections and possibilities everywhere. Authenticity matters deeply - you cannot pretend to be someone you're not. Every person you meet might become a friend.",
      es: "La vida es una aventura que debe vivirse plenamente. Ves conexiones y posibilidades en todas partes. La autenticidad importa profundamente; no puedes fingir ser alguien que no eres. Cada persona que conoces podría convertirse en un amigo.",
      fr: "La vie est une aventure à vivre pleinement. Vous voyez des connexions et des possibilités partout. L'authenticité importe profondément - vous ne pouvez pas prétendre être quelqu'un que vous n'êtes pas. Chaque personne que vous rencontrez pourrait devenir un ami.",
      ja: "人生は十二分に生きるべき冒険です。どこにでもつながりと可能性を見出します。誠実さは非常に重要です。自分ではない誰かのふりをすることはできません。出会うすべての人が友人になる可能性があります。",
      ko: "삶은 완전히 살아야 할 모험입니다. 어디서나 연결과 가능성을 봅니다. 진정성이 깊이 중요합니다 - 자신이 아닌 다른 사람인 척할 수 없습니다. 만나는 모든 사람이 친구가 될 수 있습니다.",
      zh: "人生是一场必须充实度过的冒险。你到处看到联系和可能性。真实性非常重要——你不能伪装成别人。你遇到的每个人都可能成为朋友。",
    },
  },
  INFJ: {
    challenges: [
      {
        en: "May feel misunderstood due to complex inner world",
        es: "Puede sentirse incomprendido debido a su complejo mundo interno",
        fr: "Peut se sentir incompris en raison d'un monde intérieur complexe",
        ja: "複雑な内面世界のため、誤解されていると感じることがある",
        ko: "복잡한 내면 세계로 인해 오해받을 수 있음",
        zh: "由于内心世界复杂，可能感到被误解",
      },
      {
        en: "Tendency to absorb others' emotions",
        es: "Tendencia a absorber las emociones de los demás",
        fr: "Tendance à absorber les émotions des autres",
        ja: "他者の感情を吸収する傾向",
        ko: "다른 사람의 감정을 흡수하는 경향",
        zh: "倾向于吸收他人的情绪",
      },
      {
        en: "Perfectionism about ideals can lead to disappointment",
        es: "El perfeccionismo sobre los ideales puede llevar a la decepción",
        fr: "Le perfectionnisme concernant les idéaux peut mener à la déception",
        ja: "理想に対する完璧主義が落胆につながることがある",
        ko: "이상에 대한 완벽주의가 실망으로 이어질 수 있음",
        zh: "对理想的完美主义可能导致失望",
      },
    ],
    growthPath: {
      en: "Develop your Se (physical presence) and Ti (logical clarity). Practice grounding exercises, speak your truth directly, and accept that you cannot save everyone - boundaries are necessary.",
      es: "Desarrolla tu Se (presencia física) y Ti (claridad lógica). Practica ejercicios de conexión a tierra, di tu verdad directamente y acepta que no puedes salvar a todos; los límites son necesarios.",
      fr: "Développez votre Se (présence physique) et Ti (clarté logique). Pratiquez des exercices d'ancrage, dites votre vérité directement et acceptez que vous ne pouvez pas sauver tout le monde - les limites sont nécessaires.",
      ja: "Se（肉体的な存在感）とTi（倫理的な明快さ）を開発してください。グラウンディングのエクササイズを実践し、真実を直接語り、すべての人を救うことはできないことを受け入れてください。境界線が必要です。",
      ko: "Se(물리적 존재)와 Ti(논리적 명확성)를 개발하세요. 그라운딩 운동을 연습하고, 진실을 직접 말하며, 모든 사람을 구할 수 없다는 것을 수용하세요 - 경계가 필요합니다.",
      zh: "发展你的Se（身体临在）和Ti（逻辑清晰）。练习扎根练习，直接说出你的真理，并接受你无法拯救每个人——设定界限是必要的。",
    },
    lifeImplications: {
      en: "You deeply understand human nature, making you a natural counselor and advocate. Relationships are intense and meaningful, but you need solitude to recharge. Your career should involve purpose - meaning matters more than money.",
      es: "Comprendes profundamente la naturaleza humana, lo que te convierte en un consejero y defensor natural. Las relaciones son intensas y significativas, pero necesitas soledad para recargar energías. Tu carrera debe involucrar un propósito; el sentido importa más que el dinero.",
      fr: "Vous comprenez profondément la nature humaine, ce qui fait de vous un conseiller et un avocat naturel. Les relations sont intenses et significatives, mais vous avez besoin de solitude pour vous ressourcer. Votre carrière doit avoir un but - le sens importe plus que l'argent.",
      ja: "あなたは人間性を深く理解しており、自然なカウンセラーやアドボケイトとなります。人間関係は強烈で意味のあるものですが、充電のために孤独が必要です。キャリアには目的が必要です。お金よりも意味が重要です。",
      ko: "인간 본성을 깊이 이해하여 자연스러운 상담사와 옹호자입니다. 관계는 강렬하고 의미 있지만, 재충전을 위해 고독이 필요합니다. 직업은 목적을 포함해야 합니다 - 의미가 돈보다 중요합니다.",
      zh: "你深谙人性，是天生的顾问和倡导者。人际关系强烈且有意义，但你需要独处来充电。你的职业生涯应该涉及使命感——意义比金钱更重要。",
    },
    strengths: [
      {
        en: "Deep empathy and understanding of human motivation",
        es: "Empatía profunda y comprensión de la motivación humana",
        fr: "Profonde empathie et compréhension de la motivation humaine",
        ja: "深い共感と人間の動機の理解",
        ko: "깊은 공감과 인간 동기 이해",
        zh: "深厚的同理心和对人类动机的理解",
      },
      {
        en: "Visionary insight into people and systems",
        es: "Visión perspicaz de las personas y los sistemas",
        fr: "Vision perspicace des gens et des systèmes",
        ja: "人々やシステムに対する先見の明のある洞察",
        ko: "사람과 시스템에 대한 비전 있는 통찰력",
        zh: "对人和系统的远见卓识",
      },
      {
        en: "Able to inspire others toward meaningful goals",
        es: "Capaz de inspirar a otros hacia metas significativas",
        fr: "Capable d'inspirer les autres vers des objectifs significatifs",
        ja: "意味のある目標に向かって他の人を鼓舞することができる",
        ko: "의미 있는 목표를 향해 다른 사람들에게 영감을 줄 수 있음",
        zh: "能够激励他人实现有意义的目标",
      },
      {
        en: "Rare combination of intuition and compassion",
        es: "Combinación rara de intuición y compasión",
        fr: "Combinaison rare d'intuition et de compassion",
        ja: "直感と思いやりという稀な組み合わせ",
        ko: "직관과 연민의 희귀한 조합",
        zh: "直觉与慈悲心灵的罕见结合",
      },
    ],
    typeNarrative: {
      en: "The Advocate (INFJ): You are a quiet visionary, perceiving the deeper currents beneath human interaction. Your Ni-Fe combination allows you to understand what people need, often before they know it themselves. You are driven by a sense of purpose larger than yourself.",
      es: "El Defensor (INFJ): Eres un visionario tranquilo, percibes las corrientes más profundas debajo de la interacción humana. Tu combinación Ni-Fe te permite entender lo que la gente necesita, a menudo antes de que ellos mismos lo sepan. Te impulsa un sentido de propósito más grande que tú mismo.",
      fr: "L'Avocat (INFJ): Vous êtes un visionnaire tranquille, percevant les courants profonds sous l'interaction humaine. Votre combinaison Ni-Fe vous permet de comprendre ce dont les gens ont besoin, souvent avant qu'ils ne le sachent eux-mêmes. Vous êtes guidé par un sens du but plus grand que vous-même.",
      ja: "提唱者 (INFJ): あなたは静かな先見の明を持つ人であり、人間関係の下にある深い流れを察知します。Ni-Feの組み合わせにより、人々が自分で気づく前に、彼らが何を必要としているかを理解することができます。自分自身よりも大きな目的意識に突き動かされています。",
      ko: "옹호자 (INFJ): 인간 상호작용 아래의 더 깊은 흐름을 인지하는 조용한 비전가입니다. Ni-Fe 조합이 사람들이 스스로 알기 전에 무엇이 필요한지 이해할 수 있게 합니다. 자신보다 더 큰 목적 의식에 의해 움직입니다.",
      zh: "倡导者 (INFJ)：你是一位宁静的愿景家，洞察人类互动下的深层潮流。你的Ni-Fe组合让你能洞悉人们的需求，往往在他们自己意识到之前。你受到超越自我的使命感驱使。",
    },
    worldview: {
      en: "You see the world through the lens of meaning and potential. Every person has a story; every situation has deeper significance. You believe in transformation and work quietly toward a better future.",
      es: "Ves el mundo a través del lente del significado y el potencial. Cada persona tiene una historia; cada situación tiene un significado más profundo. Crees en la transformación y trabajas silenciosamente hacia un futuro mejor.",
      fr: "Vous voyez le monde à travers le prisme du sens et du potentiel. Chaque personne a une histoire ; chaque situation a une signification plus profonde. Vous croyez en la transformation et travaillez tranquillement pour un avenir meilleur.",
      ja: "あなたは意味と可能性のレンズを通して世界を見ています。誰もがストーリーを持っており、あらゆる状況には深い意義があります。あなたは変容を信じ、より良い未来に向けて静かに活動しています。",
      ko: "의미와 잠재력의 렌즈를 통해 세상을 봅니다. 모든 사람에게 이야기가 있고; 모든 상황에 더 깊은 의미가 있습니다. 변화를 믿고 더 나은 미래를 향해 조용히 노력합니다.",
      zh: "你透过意义和潜力的镜头看待世界。每个人都有一个故事；每个情境都有更深层的意义。你相信转变，并为更美好的未来默默努力。",
    },
  },
  INTJ: {
    challenges: [
      {
        en: "May appear cold or dismissive of emotions",
        es: "Puede parecer frío o despectivo con las emociones",
        fr: "Peut sembler froid ou méprisant envers les émotions",
        ja: "冷淡、または感情を無視しているように見えることがある",
        ko: "차갑거나 감정을 무시하는 것처럼 보일 수 있음",
        zh: "可能显得冷漠或不重视情感",
      },
      {
        en: "Perfectionism can lead to paralysis or burnout",
        es: "El perfeccionismo puede llevar a la parálisis o al agotamiento",
        fr: "Le perfectionnisme peut mener à la paralysie ou à l'épuisement",
        ja: "完璧主義が麻痺や燃え尽き症候群につながることがある",
        ko: "완벽주의가 마비나 번아웃으로 이어질 수 있음",
        zh: "完美主义可能导致瘫痪或倦怠",
      },
      {
        en: "Difficulty accepting ideas that don't fit your framework",
        es: "Dificultad para aceptar ideas que no encajan en tu marco",
        fr: "Difficulté à accepter des idées qui ne correspondent pas à votre cadre",
        ja: "自分の枠組みに合わないアイデアを受け入れるのが難しい",
        ko: "프레임워크에 맞지 않는 아이디어 수용 어려움",
        zh: "难以接受不符合你框架的想法",
      },
    ],
    growthPath: {
      en: "Your growth lies in developing your Se (sensory awareness) and Fi (emotional attunement). Practice being present in your body and expressing emotions openly.",
      es: "Tu crecimiento radica en desarrollar tu Se (conciencia sensorial) y Fi (sintonización emocional). Practica estar presente en tu cuerpo y expresar emociones abiertamente.",
      fr: "Votre croissance réside dans le développement de votre Se (conscience sensorielle) et Fi (accord émotionnel). Pratiquez la présence dans votre corps et l'expression ouverte des émotions.",
      ja: "あなたの成長はSe（感覚的気づき）とFi（感情の同調）を開発することにあります。自分の身体の存在を感じ、感情を率直に表現する練習をしましょう。",
      ko: "성장은 Se(감각 인식)와 Fi(감정 조율) 개발에 있습니다. 몸에 존재하는 연습, 감정을 공개적으로 표현하기.",
      zh: "你的成长在于发展你的Se（感官觉察）和Fi（情感协调）。练习身在当下并公开表达情感。",
    },
    lifeImplications: {
      en: "In relationships, you bring depth and dedication but may need to consciously express affection. In career, you excel in strategic roles but should guard against isolation. Your vision inspires others - learn to communicate it in accessible terms.",
      es: "En las relaciones, aportas profundidad y dedicación, pero puedes necesitar expresar afecto conscientemente. En la carrera, sobresales en roles estratégicos pero debes cuidarte del aislamiento. Tu visión inspira a otros; aprende a comunicarla en términos accesibles.",
      fr: "Dans les relations, vous apportez profondeur et dévouement mais devrez peut-être exprimer consciemment votre affection. En carrière, vous excellez dans les rôles stratégiques mais devez éviter l'isolement. Votre vision inspire les autres - apprenez à la communiquer en termes accessibles.",
      ja: "人間関係において、あなたは深みと献身をもたらしますが、意識的に愛情を表現する必要があるかもしれません。キャリアでは、戦略的な役割で優れていますが、孤立に注意する必要があります。あなたのビジョンは他の人々にインスピレーションを与えます - それを分かりやすい言葉で伝える方法を学びましょう。",
      ko: "관계에서 깊이와 헌신을 가져오지만 의식적으로 애정을 표현해야 할 수 있습니다. 직업에서 전략적 역할에 탁월하지만 고립에 대해 주의해야 합니다. 당신의 비전이 다른 사람들에게 영감을 줍니다 - 접근 가능한 용어로 전달하는 법을 배우세요.",
      zh: "在人际关系中，你带来深度和奉献，但可能需要有意识地表达情感。在职业生涯中，你擅长战略角色，但应防范孤立。 your vision 激励他人——学会用通俗易懂的方式沟通。",
    },
    strengths: [
      {
        en: "Strategic vision that sees years ahead",
        es: "Visión estratégica que ve años hacia adelante",
        fr: "Vision stratégique qui voit des années à l'avance",
        ja: "数年先を見越す戦略的ビジョン",
        ko: "수년 앞을 내다보는 전략적 비전",
        zh: "预见未来数年的战略眼光",
      },
      {
        en: "Deep independent thinking",
        es: "Pensamiento independiente profundo",
        fr: "Pensée indépendante profonde",
        ja: "深い独立的思考",
        ko: "깊은 독립적 사고",
        zh: "深邃的独立思考",
      },
      {
        en: "Efficient execution of complex plans",
        es: "Ejecución eficiente de planes complejos",
        fr: "Exécution efficace de plans complexes",
        ja: "複雑な計画の効率的な実行",
        ko: "복잡한 계획의 효율적 실행",
        zh: "高效执行复杂计划",
      },
      {
        en: "Rare ability to see patterns others miss",
        es: "Habilidad rara para ver patrones que otros pasan por alto",
        fr: "Capacité rare à voir les modèles que les autres manquent",
        ja: "他の人が見逃すパターンを見抜く稀な能力",
        ko: "다른 사람들이 놓치는 패턴을 보는 희귀한 능력",
        zh: "洞察他人忽略模式的罕见能力",
      },
    ],
    typeNarrative: {
      en: "The Architect (INTJ): You are a strategic mastermind, seeing the world as a system to be understood and optimized. Your Ni-Te creates a powerful engine for long-term vision executed with precision.",
      es: "El Arquitecto (INTJ): Eres un cerebro estratégico, ves el mundo como un sistema para ser entendido y optimizado. Tu Ni-Te crea un motor poderoso para una visión a largo plazo ejecutada con precisión.",
      fr: "L'Architecte (INTJ): Vous êtes un maître stratégique, voyant le monde comme un système à comprendre et à optimiser. Votre Ni-Te crée un moteur puissant pour une vision à long terme exécutée avec précision.",
      ja: "建築家 (INTJ): あなたは戦略的なマスターマインドであり、世界を理解し最適化すべきシステムとして見ています。Ni-Teは、精密に実行される長期的なビジョンのための強力なエンジンを作り出します。",
      ko: "건축가 (INTJ): 전략적 마스터마인드로, 세상을 이해하고 최적화할 시스템으로 봅니다. Ni-Te 조합이 정밀하게 실행되는 장기 비전을 만듭니다.",
      zh: "建筑师 (INTJ)：你是一位战略大师，将世界视为一个需要理解和优化的系统。你的Ni-Te组合为精准执行的长期愿景创造了强大的动力。",
    },
    worldview: {
      en: "You see reality as something that can be improved through systematic thinking. Inefficiency frustrates you; elegant solutions delight you. You believe competence should be rewarded and that truth matters more than feelings.",
      es: "Ves la realidad como algo que puede mejorarse mediante el pensamiento sistemático. La ineficiencia te frustra; las soluciones elegantes te deleitan. Crees que la competencia debe ser recompensada y que la verdad importa más que los sentimientos.",
      fr: "Vous voyez la réalité comme quelque chose qui peut être amélioré par la pensée systématique. L'inefficacité vous frustre ; les solutions élégantes vous ravissent. Vous croyez que la compétence doit être récompensée et que la vérité importe plus que les sentiments.",
      ja: "あなたは現実を、体系的な思考を通じて改善できるものとして見ています。非効率性はあなたを失望させ、エレガントな解決策はあなたを喜ばせます。能力は報われるべきであり、真実は感情よりも重要であると信じています。",
      ko: "현실을 체계적 사고를 통해 개선될 수 있는 것으로 봅니다. 비효율성이 당신을 좌절시키고; 우아한 해결책이 기쁘게 합니다. 역량이 보상받아야 하고 진실이 감정보다 중요하다고 믿습니다.",
      zh: "你认为现实可以通过系统性思考来改进。低效让你沮丧，优雅的解决方案让你欣喜。你相信能力应该得到回报，真理比情感更重要。",
    },
  },
  ISFJ: {
    challenges: [
      {
        en: "Difficulty saying no, leading to burnout",
        es: "Dificultad para decir que no, lo que lleva al agotamiento",
        fr: "Difficulté à dire non, menant à l'épuisement",
        ja: "「いいえ」と言うのが難しく、燃え尽き症候群につながる",
        ko: "'아니오'라고 말하기 어려움, 번아웃으로 이어짐",
        zh: "难以拒绝，导致倦怠",
      },
      {
        en: "May suppress own needs to care for others",
        es: "Puede suprimir sus propias necesidades para cuidar a los demás",
        fr: "Peut supprimer ses propres besoins pour prendre soin des autres",
        ja: "他者の世話をするために自分のニーズを抑えることがある",
        ko: "다른 사람을 돌보기 위해 자신의 필요를 억제할 수 있음",
        zh: "可能为了照顾他人而压抑自己的需求",
      },
      {
        en: "Resistant to change even when necessary",
        es: "Resistente al cambio incluso cuando es necesario",
        fr: "Résistant au changement même lorsque nécessaire",
        ja: "必要なときでも変化に抵抗する",
        ko: "필요할 때도 변화에 저항적",
        zh: "即使必要也抵制改变",
      },
    ],
    growthPath: {
      en: "Develop your Ne (openness to new possibilities) and Ti (independent judgment). Practice saying no, try new experiences, and remember that taking care of yourself enables you to care for others.",
      es: "Desarrolla tu Ne (apertura a nuevas posibilidades) y Ti (juicio independiente). Practica decir que no, intenta nuevas experiencias y recuerda que cuidarte a ti mismo te permite cuidar a los demás.",
      fr: "Développez votre Ne (ouverture aux nouvelles possibilités) et Ti (jugement indépendant). Pratiquez le fait de dire non, essayez de nouvelles expériences et rappelez-vous que prendre soin de vous vous permet de prendre soin des autres.",
      ja: "Ne（新しい可能性への開放性）とTi（独立した判断）を開発してください。「いいえ」と言う練習をし、新しい経験を試み、自分自身のケアをすることが他者のケアにつながることを忘れないでください。",
      ko: "Ne(새로운 가능성에 대한 열린 마음)와 Ti(독립적 판단)를 개발하세요. '아니오'라고 말하는 연습, 새로운 경험 시도, 자신을 돌보는 것이 다른 사람을 돌볼 수 있게 한다는 것을 기억하세요.",
      zh: "发展你的Ne（对新可能性的开放性）和Ti（独立判断）。练习拒绝，尝试新体验，并记住照顾好自己才能照顾他人。",
    },
    lifeImplications: {
      en: "You are the reliable foundation others depend on. Relationships are nurturing and stable. Career should involve helping others in practical ways. Your attention to detail and memory for what matters to people makes you invaluable.",
      es: "Eres la base confiable en la que otros dependen. Las relaciones son enriquecedoras y estables. La carrera debe implicar ayudar a los demás de manera práctica. Tu atención al detalle y memoria para lo que importa a las personas te hace invaluable.",
      fr: "Vous êtes la fondation fiable sur laquelle les autres comptent. Les relations sont nourrissantes et stables. La carrière doit impliquer d'aider les autres de manière pratique. Votre attention aux détails et votre mémoire pour ce qui compte pour les gens vous rendent inestimable.",
      ja: "あなたは他者が頼りにする信頼できる基盤です。人間関係は育成重視で安定しています。キャリアは実用的な方法で他者を助けることを伴うべきです。細部への注意と、人々にとって重要なことへの記憶は、あなたをかけがえのない存在にします。",
      ko: "다른 사람들이 의지하는 신뢰할 수 있는 기반입니다. 관계는 양육적이고 안정적입니다. 직업은 실용적인 방식으로 다른 사람을 돕는 것을 포함해야 합니다. 세부 사항에 대한 주의와 사람들에게 중요한 것에 대한 기억이 당신을 귀중하게 만듭니다.",
      zh: "你是他人依赖的可靠基础。人际关系滋养且稳定。职业生涯应该涉及以实际方式帮助他人。你对细节的关注和对他人重要事物的记忆使你变得无价。",
    },
    strengths: [
      {
        en: "Exceptional reliability and follow-through",
        es: "Fiabilidad excepcional y seguimiento",
        fr: "Fiabilité exceptionnelle et suivi",
        ja: "卓越した信頼性とやり抜く力",
        ko: "뛰어난 신뢰성과 완수",
        zh: "卓越的可靠性和执行力",
      },
      {
        en: "Deep care and practical service to others",
        es: "Cuidado profundo y servicio práctico a los demás",
        fr: "Soins profonds et service pratique aux autres",
        ja: "他者への深い配慮と実用的なサービス",
        ko: "깊은 돌봄과 다른 사람에 대한 실용적 봉사",
        zh: "深切的关怀和对他人实际的服务",
      },
      {
        en: "Strong memory for personal details",
        es: "Fuerte memoria para detalles personales",
        fr: "Forte mémoire pour les détails personnels",
        ja: "個人的な詳細に対する強い記憶力",
        ko: "개인적 세부 사항에 대한 강한 기억력",
        zh: "对个人细节的强大记忆力",
      },
      {
        en: "Patient and thorough approach to work",
        es: "Enfoque paciente y minucioso del trabajo",
        fr: "Approche patiente et minutieuse du travail",
        ja: "忍耐強く徹底した仕事へのアプローチ",
        ko: "일에 대한 인내심 있고 철저한 접근",
        zh: "耐心且周密的工作方法",
      },
    ],
    typeNarrative: {
      en: "The Defender (ISFJ): You are the quiet guardian, remembering what matters to the people you care about and working steadily to support them. Your Si-Fe combination creates a powerful memory for personal details combined with genuine warmth.",
      es: "El Defensor (ISFJ): Eres el guardián silencioso, recuerdas lo que importa a las personas que te importan y trabajas constantemente para apoyarlas. Tu combinación Si-Fe crea una memoria poderosa para los detalles personales combinada con una calidez genuina.",
      fr: "Le Défenseur (ISFJ): Vous êtes le gardien silencieux, vous souvenant de ce qui compte pour les personnes qui vous sont chères et travaillant régulièrement pour les soutenir. Votre combinaison Si-Fe crée une mémoire puissante pour les détails personnels combinée à une chaleur authentique.",
      ja: "擁護者 (ISFJ): あなたは静かな守護者であり、大切な人々の重要事項を記憶し、彼らを支えるために着実に活動します。Si-Feの組み合わせは、本物の温かさと共に、個人的な詳細に対する強力な記憶力を作り出します。",
      ko: "방어자 (ISFJ): 조용한 수호자로, 당신이 돌보는 사람들에게 중요한 것을 기억하고 그들을 지원하기 위해 꾸준히 노력합니다. Si-Fe 조합이 진정한 따뜻함과 결합된 개인적 세부 사항에 대한 강력한 기억을 만듭니다.",
      zh: "守护者 (ISFJ)：你是一位宁静的守护者，铭记对你在乎的人重要的事情，并稳步工作以支持他们。你的Si-Fe组合创造了对个人细节的强大记忆，并结合了真挚的温暖。",
    },
    worldview: {
      en: "The world works best when people fulfill their responsibilities to each other. You value tradition, stability, and practical care. Service is love made visible - you show you care through action.",
      es: "El mundo funciona mejor cuando las personas cumplen sus responsabilidades entre sí. Valoras la tradición, la estabilidad y el cuidado práctico. El servicio es el amor hecho visible: muestras que te importa a través de la acción.",
      fr: "Le monde fonctionne mieux lorsque les gens remplissent leurs responsabilités les uns envers les autres. Vous appréciez la tradition, la stabilité et les soins pratiques. Le service est l'amour rendu visible - vous montrez que vous vous souciez par l'action.",
      ja: "世界は人々が互いの責任を果たすときに最もよく機能します。あなたは伝統、安定、そして実用的な配慮を尊重します。奉仕は目に見える愛の形です。あなたは行動を通して配慮を示します。",
      ko: "사람들이 서로에 대한 책임을 다할 때 세상이 가장 잘 작동합니다. 전통, 안정, 실용적 돌봄을 중시합니다. 봉사는 보이게 된 사랑입니다 - 행동을 통해 돌봄을 보여줍니다.",
      zh: "当人们履行对他人的责任时，世界运作得最好。你重视传统、稳定和务实的照顾。服务是可见的爱——你通过行动表达关怀。",
    },
  },
};
