import type { SixLangString } from "../engine.contract";

/**
 * Tarot Shard Data
 * Major Arcana cards separated from logic.
 */

export const MAJOR_ARCANA: Record<
  string,
  {
    lucideIcon: string;
    narrative: SixLangString;
    reversed: SixLangString;
    symbol: string;
    upright: SixLangString;
  }
> = {
  chariot: {
    lucideIcon: "Navigation",
    narrative: {
      en: "The Chariot (VII): Victory, will, and determination. You are harnessing opposing forces to move forward with unyielding focus.",
      es: "El Carro (VII): Victoria, voluntad y determinación.",
      fr: "Le Chariot (VII) : Victoire, volonté et détermination.",
      ja: "戦車 (VII): 勝利、意志、決断力。対立する力を制御し、揺るぎない集中力で前進します。",
      ko: "전차 (VII): 승리, 의지, 결단력. 대립하는 힘을 다스려 굴하지 않는 집중력으로 앞으로 나아갑니다.",
      zh: "战车（VII）：胜利、意志和决心。你正驾驭对立的力量，以不屈的专注力向前迈进。",
    },
    reversed: {
      en: "Reversed: Self-discipline issues, lack of direction, aggression.",
      es: "Invertida: Falta de autodisciplina, falta de dirección.",
      fr: "Inversé : Manque d'autodiscipline, manque de direction.",
      ja: "逆位置: 自己規律の問題、方向性の喪失、攻撃性。",
      ko: "역방향: 자기 훈련 부족, 방향 상실, 공격성.",
      zh: "逆位：自律问题、缺乏方向、侵略性。",
    },
    symbol: "🛒",
    upright: {
      en: "Control, willpower, success, action, determination",
      es: "Control, fuerza de voluntad, éxito.",
      fr: "Contrôle, volonté, succès.",
      ja: "制御、意志力、成功、行動、決断力",
      ko: "통제, 의지력, 성공, 행동, 결단력",
      zh: "控制、意志力、成功、行动、决心",
    },
  },
  death: {
    lucideIcon: "Skull",
    narrative: {
      en: "Death (XIII): Transformation and endings. This is not physical death, but the end of a cycle. From the old, the new is born. Embrace necessary endings.",
      es: "La Muerte (XIII): Transformación y finales. Esto no es la muerte física, sino el final de un ciclo. De lo viejo nace lo nuevo. Acepta los finales necesarios.",
      fr: "La Mort (XIII) : Transformation et fins. Ce n'est pas la mort physique, mais la fin d'un cycle. De l'ancien naît le nouveau. Embrassez les fins nécessaires.",
      ja: "死神（XIII）：変容と終わり。これは肉体的な死ではなく、ひとつの周期の終わりです。古いものから新しいものが生まれます。必要な終わりを受け入れましょう。",
      ko: "죽음 (XIII): 변화와 끝. 이것은 육체적 죽음이 아니라 순환의 끝입니다. 오래된 것에서 새것이 태어납니다. 필요한 끝을 받아들이세요.",
      zh: "死神（XIII）：转化和结束。这不是肉体死亡，而是一个周期的结束。从旧中，新诞生。拥抱必要的结束。",
    },
    reversed: {
      en: "Reversed: Resistance to change, stagnation, fear of endings.",
      es: "Invertida: Resistencia al cambio, estancamiento, miedo a los finales.",
      fr: "Inversé : Résistance au changement, stagnation, peur des fins.",
      ja: "逆位置：変化への抵抗、停滞、終わりへの恐れ。",
      ko: "역방향: 변화에 대한 저항, 정체, 끝에 대한 두려움.",
      zh: "逆位：抗拒改变、停滞、恐惧结束。",
    },
    symbol: "☠",
    upright: {
      en: "Endings, transformation, transition, letting go",
      es: "Finales, transformación, transición, dejar ir",
      fr: "Fins, transformation, transition, lâcher prise",
      ja: "終わり、変容、移行、手放すこと",
      ko: "끝, 변화, 전환, 놓아줌",
      zh: "结束、转化、过渡、放手",
    },
  },
  devil: {
    lucideIcon: "Frown",
    narrative: {
      en: "The Devil (XV): Shadow, addiction, and restriction. Beware of the chains you create for yourself through material desire or unhealthy attachments.",
      es: "El Diablo (XV): Sombra, adicción y restricción.",
      fr: "Le Diable (XV) : Ombre, addiction et restriction.",
      ja: "悪魔 (XV): 影、依存、そして束縛。物質的な欲望や不健康な執着を通じて、自ら作り出す鎖に注意してください。",
      ko: "악마 (XV): 그림자, 중독, 구속. 물질적 욕망이나 건강하지 못한 애착을 통해 스스로 만드는 사슬을 조심하세요.",
      zh: "恶魔（XV）：阴影、成瘾和束缚。提防你因物质欲望或病态依恋而为自己制造的锁链。",
    },
    reversed: {
      en: "Reversed: Releasing limiting beliefs, detachment, freedom.",
      es: "Invertida: Liberación, desapego.",
      fr: "Inversé : Libération des croyances limitantes.",
      ja: "逆位置: 制限的な信念の解放、離脱、自由。",
      ko: "역방향: 제한적인 믿음 해방, 초연함, 자유.",
      zh: "逆位：释放限制性信念、超脱、自由。",
    },
    symbol: "👿",
    upright: {
      en: "Shadow self, attachment, addiction, restriction, sexuality",
      es: "Sombra, apego, adicción.",
      fr: "Part d'ombre, attachement, addiction.",
      ja: "シャドウセルフ、執着、依存、束縛、セクシャリティ",
      ko: "그림자 자아, 애착, 중독, 구속, 성적 에너지",
      zh: "阴影自我、依恋、成瘾、束缚、性欲",
    },
  },
  emperor: {
    lucideIcon: "Crown",
    narrative: {
      en: "The Emperor (IV): Authority and structure. He sits on his throne of stone, master of the material world. This card speaks to discipline, leadership, and the power of order.",
      es: "El Emperador (IV): Autoridad y estructura. Se sienta en su trono de piedra, maestro del mundo material.",
      fr: "L'Empereur (IV) : Autorité et structure. Il est assis sur son trône de pierre, maître du monde matériel.",
      ja: "皇帝 (IV): 権威と構造。彼は石の玉座に座り、物質界の主人です。このカードは、規律、リーダーシップ、秩序の力を伝えます。",
      ko: "황제 (IV): 권위와 구조. 그는 돌 왕좌에 앉아 물질 세계의 주인입니다. 이 카드는 규율, 리더십, 질서의 힘을 말합니다.",
      zh: "皇帝（IV）：权威和结构。他坐在石座上，是物质世界的主人。这张牌讲述纪律、领导力和秩序的力量。",
    },
    reversed: {
      en: "Reversed: Domination, rigidity, control issues, tyranny.",
      es: "Invertida: Dominación, rigidez, problemas de control, tiranía.",
      fr: "Inversé : Domination, rigidité, problèmes de contrôle, tyrannie.",
      ja: "逆位置: 支配、硬直性、コントロールの問題、暴政。",
      ko: "역방향: 지배, 경직성, 통제 문제, 폭정.",
      zh: "逆位：支配、僵化、控制问题、暴政。",
    },
    symbol: "♂",
    upright: {
      en: "Authority, structure, control, fatherhood, discipline",
      es: "Autoridad, estructura, control, paternidad, disciplina",
      fr: "Autorité, structure, contrôle, paternité, discipline",
      ja: "権威、構造、制御、父性、規律",
      ko: "권위, 구조, 통제, 부성, 규율",
      zh: "权威、结构、控制、父权、纪律",
    },
  },
  empress: {
    lucideIcon: "Crown",
    narrative: {
      en: "The Empress (III): Abundance and creation. She embodies fertility, beauty, and the nurturing power of nature. This card speaks to creativity, growth, and sensual pleasure.",
      es: "La Emperatriz (III): Abundancia y creación. Ella encarna la fertilidad, la belleza y el poder nutritivo de la naturaleza. Esta carta habla de creatividad, crecimiento y placer sensual.",
      fr: "L'Impératrice (III) : Abondance et création. Elle incarne la fertilité, la beauté et le pouvoir nourricier de la nature. Cette carte parle de créativité, de croissance et de plaisir sensuel.",
      ja: "女帝（III）：豊穣と創造。彼女は豊穣、美、そして自然の育む力を体現しています。このカードは創造性、成長、官能的な喜びを語ります。",
      ko: "여황제 (III): 풍요와 창조. 그녀는 다산, 아름다움, 그리고 자연의 양육 에너지를 구현합니다. 이 카드는 창의성, 성장, 감각적 즐거움을 말합니다.",
      zh: "皇后（III）：丰盛和创造。她体现肥沃、美丽和自然的养育力量。这张牌讲述创造力、成长和感官愉悦。",
    },
    reversed: {
      en: "Reversed: Creative block, dependence, stagnation in growth.",
      es: "Invertida: Bloqueo creativo, dependencia, estancamiento en el crecimiento.",
      fr: "Inversé : Blocage créatif, dépendance, stagnation de la croissance.",
      ja: "逆位置：創造的なブロック、依存、成長の停滞。",
      ko: "역방향: 창작 막힘, 의존, 성장의 정체.",
      zh: "逆位：创造力受阻、依赖、成长停滞。",
    },
    symbol: "♀",
    upright: {
      en: "Femininity, beauty, nature, nurturing, abundance",
      es: "Feminidad, belleza, naturaleza, crianza, abundancia",
      fr: "Féminité, beauté, nature, éducation, abondance",
      ja: "女性性、美、自然、養育、豊穣",
      ko: "여성성, 아름다움, 자연, 양육, 풍요",
      zh: "女性气质、美丽、自然、养育、丰盛",
    },
  },
  fool: {
    lucideIcon: "Footprints",
    narrative: {
      en: "The Fool (0): The beginning of all journeys. You stand at the edge of infinite possibility, carrying only trust and wonder. This card speaks to new beginnings, spontaneity, and the courage to leap into the unknown.",
      es: "El Loco (0): El comienzo de todos los viajes. Estás al borde de posibilidades infinitas, llevando solo confianza y asombro. Esta carta habla de nuevos comienzos, espontaneidad y el coraje de saltar a lo desconocido.",
      fr: "Le Fou (0) : Le début de tous les voyages. Vous vous tenez au bord de possibilités infinies, ne portant que confiance et émerveillement. Cette carte parle de nouveaux départs, de spontanéité et du courage de sauter dans l'inconnu.",
      ja: "愚者（0）：すべての旅の始まり。信頼と驚きだけを持って、無限の可能性の端に立っています。このカードは新しい始まり、自発性, そして未知へ飛び込む勇気を語ります.",
      ko: "바보 (0): 모든 여정의 시작. 신뢰와 경이로움만을 가지고 무한한 가능성의 끝에 서 있습니다. 이 카드는 새로운 시작, 자발성, 그리고 미지로 뛰어들 용기를 말합니다.",
      zh: "愚者（0）：所有旅程的开始。你站在无限可能的边缘，只带着信任和惊奇。这张牌讲述新的开始、自发性和跃入未知的勇气。",
    },
    reversed: {
      en: "Reversed: Recklessness, naivety, poor planning. Take time to consider consequences before leaping.",
      es: "Invertida: Imprudencia, ingenuidad, mala planificación. Tómate un tiempo para considerar las consecuencias antes de saltar.",
      fr: "Inversé : Imprudence, naïveté, mauvaise planification. Prenez le temps de considérer les conséquences avant de sauter.",
      ja: "逆位置：無謀さ、純真さ、計画不足。飛び込む前に結果を考える時間を取ってください。",
      ko: "역방향: 무모함, 순진함, 계획 부족. 뛰어들기 전에 결과를 고려할 시간을 가지세요.",
      zh: "逆位：鲁莽、天真、计划不周。跃入之前花时间考虑后果。",
    },
    symbol: "🃏",
    upright: {
      en: "New beginnings, innocence, spontaneity, free spirit",
      es: "Nuevos comienzos, inocencia, espontaneidad, espíritu libre",
      fr: "Nouveaux départs, innocence, spontanéité, esprit libre",
      ja: "新しい始まり、純真さ、自発性、自由な精神",
      ko: "새로운 시작, 순수함, 자발성, 자유로운 영혼",
      zh: "新的开始、天真、自发性、自由精神",
    },
  },
  hangedMan: {
    lucideIcon: "User",
    narrative: {
      en: "The Hanged Man (XII): Suspension, surrender, and sacrifice. Sometimes you must let go of control to gain a new perspective on life.",
      es: "El Colgado (XII): Suspensión, rendición y sacrificio.",
      fr: "Le Pendu (XII) : Suspension, lâcher-prise et sacrifice.",
      ja: "吊るされた男 (XII): 停滞、降伏、そして犠牲。新しい視点を得るために、時にはコントロールを手放さなければならないこともあります。",
      ko: "매달린 사람 (XII): 정지, 항복, 희생. 때로는 새로운 관점을 얻기 위해 통제를 내려놓아야 합니다.",
      zh: "倒吊人（XII）：悬挂、屈服和牺牲。有时你必须放下控制，以获得对生活的新视角。",
    },
    reversed: {
      en: "Reversed: Stalling, resistance, spiritual withdrawal.",
      es: "Invertida: Estancamiento, resistencia.",
      fr: "Inversé : Retard, résistance.",
      ja: "逆位置: 行き詰まり、抵抗、精神的な引きこもり。",
      ko: "역방향: 지연, 저항, 영적 후퇴.",
      zh: "逆位：拖延、抵抗、灵性撤退。",
    },
    symbol: "🙃",
    upright: {
      en: "Pause, surrender, letting go, new perspectives",
      es: "Pausa, rendición, dejar ir.",
      fr: "Pause, reddition, lâcher-prise.",
      ja: "休止、降伏、手放す、新しい視点",
      ko: "일시 정지, 항복, 놓아줌, 새로운 관점",
      zh: "暂停、屈服、放手、新视角",
    },
  },
  hermit: {
    lucideIcon: "Lamp",
    narrative: {
      en: "The Hermit (IX): Inner guidance and solitude. You are seeking truth within, withdrawing from the noise to find clarity in the silence.",
      es: "El Ermitaño (IX): Guía interior y soledad.",
      fr: "L'Ermite (IX) : Guide intérieur et solitude.",
      ja: "隠者 (IX): 内なる導きと孤独。騒音から離れ、静寂の中に明快さを見出すために、内なる真実を求めています。",
      ko: "은둔자 (IX): 내면의 인도와 고독. 소음에서 벗어나 침묵 속에서 명료함을 찾기 위해 내면의 진실을 구합니다.",
      zh: "隐士（IX）：内在引导和孤独。你正于内在寻求真理，撤离喧嚣，在宁静中心寻找清明。",
    },
    reversed: {
      en: "Reversed: Isolation, loneliness, withdrawal from society.",
      es: "Invertida: Aislamiento, soledad.",
      fr: "Inversé : Isolement, solitude.",
      ja: "逆位置: 孤立、孤独、社会からの引きこもり。",
      ko: "역방향: 고립, 외로움, 사회적 후퇴.",
      zh: "逆位：孤立、孤独、脱离社会。",
    },
    symbol: "🕯️",
    upright: {
      en: "Soul-searching, introspection, being alone, inner guidance",
      es: "Búsqueda interior, introspección.",
      fr: "Recherche de l'âme, introspection.",
      ja: "内面探求、内省、孤独、内なる導き",
      ko: "자아 성찰, 내성, 고독, 내면의 인도",
      zh: "反省、内省、独处、内在引导",
    },
  },
  hierophant: {
    lucideIcon: "Book",
    narrative: {
      en: "The Hierophant (V): Tradition and spiritual authority. This card represents conventional wisdom, formal education, and institutionalized religion or systems.",
      es: "El Sumo Sacerdote (V): Tradición y autoridad espiritual.",
      fr: "Le Hiérophante (V) : Tradition et autorité spirituelle.",
      ja: "教皇 (V): 伝統と精神的な権威。伝統的な知恵、正式な教育、制度化された宗教やシステムを表します。",
      ko: "교황 (V): 전통과 영적 권위. 관습적인 지혜, 공식 교육, 제도화된 종교나 시스템을 나타냅니다.",
      zh: "教皇（V）：传统和灵性权威。代表常规智慧、正规教育和制度化宗教或系统。",
    },
    reversed: {
      en: "Reversed: Rebellion, unconventionality, non-conformity.",
      es: "Invertida: Rebelión, falta de convencionalismo.",
      fr: "Inversé : Rébellion, anticonformisme.",
      ja: "逆位置: 反抗、非伝統的、不適合。",
      ko: "역방향: 반항, 비관습적, 비순응.",
      zh: "逆位：叛逆、非传统、不符合常规。",
    },
    symbol: "🛐",
    upright: {
      en: "Spiritual wisdom, religious beliefs, conformity, tradition",
      es: "Sabiduría espiritual, creencias religiosas, conformidad.",
      fr: "Sagesse spirituelle, croyances religieuses, conformité.",
      ja: "精神的知恵、宗教的信念、適合、伝統",
      ko: "영적 지혜, 종교적 믿음, 순응, 전통",
      zh: "灵性智慧、宗教信仰、规范、传统",
    },
  },
  highPriestess: {
    lucideIcon: "Moon",
    narrative: {
      en: "The High Priestess (II): The keeper of mysteries. She sits at the threshold between worlds, guarding sacred knowledge. Trust your intuition and look beyond the surface.",
      es: "La Suma Sacerdotisa (II): La guardiana de los misterios. Se sienta en el umbral entre mundos, guardando el conocimiento sagrado. Confía en tu intuición y mira más allá de la superficie.",
      fr: "La Grande Prêtresse (II) : La gardienne des mystères. Elle est assise au seuil entre les mondes, gardant la connaissance sacrée. Faites confiance à votre intuition et regardez au-delà de la surface.",
      ja: "女教皇（II）：神秘の守護者。彼女は世界のはざまの境界に座し、神聖な知識を守っています。直感を信じ、表面の先を見つめてください。",
      ko: "여사제 (II): 신비의 수호자. 그녀는 세계 사이의 경계에 앉아 신성한 지식을 지킵니다. 직관을 신뢰하고 표면 너머를 보세요.",
      zh: "女祭司（II）：神秘的守护者。她坐在世界之间的门槛上，守护神圣的知识。相信你的直觉，看透表面。",
    },
    reversed: {
      en: "Reversed: Secrets, disconnection from intuition, surface-level understanding.",
      es: "Invertida: Secretos, desconexión de la intuición, comprensión superficial.",
      fr: "Inversé : Secrets, déconnexion de l'intuition, compréhension superficielle.",
      ja: "逆位置：秘密、直感からの断絶、表面的な理解。",
      ko: "역방향: 비밀, 직관과의 단절, 표면적인 이해.",
      zh: "逆位：秘密、与直觉断开连接、表层理解。",
    },
    symbol: "☽",
    upright: {
      en: "Intuition, sacred knowledge, divine feminine, the subconscious",
      es: "Intuición, conocimiento sagrado, divino femenino, el subconsciente",
      fr: "Intuition, connaissance sacrée, féminin sacré, le subconscient",
      ja: "直感、神聖な知識、神聖な女性性、潜在意識",
      ko: "직관, 신성한 지식, 신성한 여성성, 잠재의식",
      zh: "直觉、神圣知识、神圣女性、潜意识",
    },
  },

  judgement: {
    lucideIcon: "Bell",
    narrative: {
      en: "Judgement (XX): Reflection, reckoning, and awakening. You are hearing a higher call, reviewing your past to step into a new version of yourself.",
      es: "El Juicio (XX): Reflexión, ajuste de cuentas.",
      fr: "Le Jugement (XX) : Réflexion, bilan et éveil.",
      ja: "審判 (XX): 反省、決算、そして目覚め。高次の呼び声を聞き、過去を振り返ることで、新しい自分へと踏み出そうとしています。",
      ko: "심판 (XX): 반성, 심판, 각성. 고차원적인 부름을 듣고 과거를 되돌아보며 새로운 자아로 나아갑니다.",
      zh: "审判（XX）：反省、清算和觉醒。你正听到更高层次的呼唤，回顾过去以步入全新的自我。",
    },
    reversed: {
      en: "Reversed: Self-doubt, inner critic, ignoring the call.",
      es: "Invertida: Duda de uno mismo, autocrítica.",
      fr: "Inversé : Doute de soi, critique intérieure.",
      ja: "逆位置: 自己疑念、内なる批判者、呼び声の無視。",
      ko: "역방향: 자기 의심, 내면의 비판자, 부름을 무시함.",
      zh: "逆位：自我怀疑、内在批判、忽视呼唤。",
    },
    symbol: "🔔",
    upright: {
      en: "Judgement, rebirth, inner calling, absolution",
      es: "Juicio, renacimiento.",
      fr: "Jugement, renaissance.",
      ja: "審判、再生、内なる呼び声、赦免",
      ko: "심판, 재생, 내면의 부름, 사죄",
      zh: "审判、重生、内在呼唤、赦免",
    },
  },
  justice: {
    lucideIcon: "Scale",
    narrative: {
      en: "Justice (XI): Fairness, truth, and the law of cause and effect. You are called to account for your actions and seek balance in all dealings.",
      es: "La Justicia (XI): Justicia, verdad y la ley de causa y efecto.",
      fr: "La Justice (XI) : Équité, vérité et loi de cause à effet.",
      ja: "正義 (XI): 公平、真実、そして因果の法則。自らの行動に責任を持ち、すべての物事において均衡を保つよう求められています。",
      ko: "정의 (XI): 공정함, 진실, 인과응보의 법칙. 당신의 행동에 책임을 지고 모든 거래에서 균형을 찾아야 합니다.",
      zh: "正义（XI）：公平、真理和因果律。你被召要求为自己的行为负责，并在所有事务中寻求平衡。",
    },
    reversed: {
      en: "Reversed: Injustice, lack of accountability, dishonesty.",
      es: "Invertida: Injusticia, falta de rendición de cuentas.",
      fr: "Inversé : Injustice, manque de responsabilité.",
      ja: "逆位置: 不正、無責任、不誠実。",
      ko: "역방향: 불의, 책임 회피, 부정직.",
      zh: "逆位：不公正、缺乏问责、不诚实。",
    },
    symbol: "⚖️",
    upright: {
      en: "Justice, fairness, truth, cause and effect, law",
      es: "Justicia, equidad, verdad.",
      fr: "Justice, équité, vérité.",
      ja: "正義、公正、真実、因果関係、法",
      ko: "정의, 공정, 진실, 인과 관계, 법",
      zh: "正义、公平、真理、因果、法律",
    },
  },
  lovers: {
    lucideIcon: "Heart",
    narrative: {
      en: "The Lovers (VI): Love, harmony, and choice. This card is about deep connections and the crossroads of important life decisions.",
      es: "Los Enamorados (VI): Amor, armonía y elección.",
      fr: "Les Amants (VI) : Amour, harmonie et choix.",
      ja: "恋人 (VI): 愛、調和、そして選択。深い結びつきと、人生の重要な決断の分かれ道を表します。",
      ko: "연인 (VI): 사랑, 조화 그리로 선택. 깊은 연결과 인생의 중요한 결정의 갈림길을 의미합니다.",
      zh: "恋人（VI）：爱情、和谐和选择。关乎深刻的联系和重要人生决定的十字路口。",
    },
    reversed: {
      en: "Reversed: Disharmony, imbalance, misalignment of values.",
      es: "Invertida: Desarmonía, desequilibrio.",
      fr: "Inversé : Disharmonie, déséquilibre.",
      ja: "逆位置: 不調和、不均衡、価値観の不一致。",
      ko: "역방향: 불협화음, 불균형, 가치 불일치.",
      zh: "逆位：失调、不平衡、价值观不一致。",
    },
    symbol: "❤️",
    upright: {
      en: "Love, harmony, relationships, values alignment, choices",
      es: "Amor, armonía, relaciones, alineación de valores.",
      fr: "Amour, harmonie, relations, alignement des valeurs.",
      ja: "愛、調和、関係、価値観の一致、選択",
      ko: "사랑, 조화, 관계, 가치관 일치, 선택",
      zh: "爱情、和谐、关系、价值观一致、选择",
    },
  },
  magician: {
    lucideIcon: "Wand",
    narrative: {
      en: "The Magician (I): Mastery and manifestation. You have all the tools before you. This card speaks to willpower, skill, and the power to turn ideas into reality through focused intention.",
      es: "El Mago (I): Maestría y manifestación. Tienes todas las herramientas ante ti. Esta carta habla de fuerza de voluntad, habilidad y el poder de convertir ideas en reality a través de la intención enfocada.",
      fr: "Le Magicien (I) : Maîtrise et manifestation. Vous avez tous les outils devant vous. Cette carte parle de volonté, de compétence et du pouvoir de transformer les idées en réalité grâce à une intention focalisée.",
      ja: "魔術師（I）：熟達と顕現. あなたの前にすべてのツールがあります. このカードは意志力, スキル, そして集中した意図を通じてアイデアを現実に変える力を語ります.",
      ko: "마법사 (I): 숙달과 현현. 당신 앞에 모든 도구가 있습니다. 이 카드는 의지력, 기술, 그리고 집중된 의도를 통해 아이디어를 현실로 바꾸는 힘을 말합니다.",
      zh: "魔术师（I）：精通和显化。你面前拥有所有工具。这张牌讲述意志力、技能和通过专注意图将想法变为现实的力量。",
    },
    reversed: {
      en: "Reversed: Manipulation, trickery, wasted talent. Beware of using power for selfish ends.",
      es: "Invertida: Manipulación, engaño, talento desperdiciado. Cuidado con usar el poder para fines egoístas.",
      fr: "Inversé : Manipulation, supercherie, talent gâché. Méfiez-vous d'utiliser le pouvoir à des fins égoïstes.",
      ja: "逆位置：操作、策略、無駄な才能。利己的な目的で力を使うことに注意してください。",
      ko: "역방향: 조종, 속임수, 낭비된 재능. 이기적인 목적으로 힘을 사용하는 것을 조심하세요.",
      zh: "逆位：操纵、欺骗、浪费的才能。谨防为私利使用力量。",
    },
    symbol: "🪄",
    upright: {
      en: "Manifestation, resourcefulness, power, inspired action",
      es: "Manifestación, ingenio, poder, acción inspirada",
      fr: "Manifestation, ingéniosité, pouvoir, action inspirée",
      ja: "顕現、機知、力、インスピレーションを受けた行動",
      ko: "현현, 자원활용력, 힘, 영감받은 행동",
      zh: "显化、足智多谋、力量、受启发的行动",
    },
  },
  moon: {
    lucideIcon: "Moon",
    narrative: {
      en: "The Moon (XVIII): Illusion, dreams, and the subconscious. Not everything is as it seems. Navigate through the shadows using your internal light.",
      es: "La Luna (XVIII): Ilusión, sueños y el subconsciente.",
      fr: "La Lune (XVIII) : Illusion, rêves et subconscient.",
      ja: "月 (XVIII): 幻想、夢、そして潜在意識。すべてが見かけ通りではありません。内なる光を頼りに、影の中を進んでください。",
      ko: "달 (XVIII): 환상, 꿈, 잠재의식. 모든 것이 보이는 대로인 것은 아닙니다. 내면의 빛을 이용해 그림자 속을 항해하세요.",
      zh: "月亮（XVIII）：幻象、梦境和潜意识。一切并非如表面所示。利用内在之光穿行于阴影之中。",
    },
    reversed: {
      en: "Reversed: Releasing fear, repressed emotion, clarity.",
      es: "Invertida: Liberación del miedo, claridad.",
      fr: "Inversé : Libération de la peur, clarté.",
      ja: "逆位置: 恐怖の解放、抑圧された感情、明快さ。",
      ko: "역방향: 두려움 해방, 억눌린 감정, 명료함.",
      zh: "逆位：释放恐惧、压抑的情感、清晰。",
    },
    symbol: "🌙",
    upright: {
      en: "Illusion, fear, anxiety, subconscious, intuition",
      es: "Ilusión, miedo, ansiedad.",
      fr: "Illusion, peur, anxiété.",
      ja: "幻想、恐怖、不安、潜在意識、直感",
      ko: "환상, 두려움, 불안, 잠재의식, 직관",
      zh: "幻象、恐惧、焦虑、潜意识、直觉",
    },
  },
  star: {
    lucideIcon: "Star",
    narrative: {
      en: "The Star (XVII): Hope and renewal. After the destruction of the Tower, the Star offers healing light. Trust that the universe holds a place for you.",
      es: "La Estrella (XVII): Esperanza y renovación. Tras la destrucción de la Torre, la Estrella ofrece luz sanadora. Confía en que el universo tiene un lugar para ti.",
      fr: "L'Étoile (XVII) : Espoir et renouveau. Après la destruction de la Tour, l'Étoile offre une lumière guérisseuse. Ayez confiance que l'univers a une place pour vous.",
      ja: "星（XVII）：希望と再生。塔の破壊の後、星は癒しの光をもたらします。宇宙があなたのための場所を持っていることを信じてください。",
      ko: "별 (XVII): 희망과 재생. 탑의 파괴 후, 별은 치유의 빛을 제공합니다. 우주가 당신을 위한 자리를 가지고 있음을 믿으세요.",
      zh: "星星（XVII）：希望和更新。在塔的毁灭之后，星星提供治愈之光。相信宇宙为你留有一席之地。",
    },
    reversed: {
      en: "Reversed: Lack of faith, despair, disconnection from purpose.",
      es: "Invertida: Falta de fe, desesperación, desconexión del propósito.",
      fr: "Inversé : Manque de foi, désespoir, déconnexion du but.",
      ja: "逆位置：信仰の欠如、絶望、目的からの断絶。",
      ko: "역방향: 믿음 부족, 절망, 목적과의 단절.",
      zh: "逆位：缺乏信仰、绝望、与目的断开连接。",
    },
    symbol: "★",
    upright: {
      en: "Hope, faith, purpose, renewal, spirituality",
      es: "Esperanza, fe, propósito, renovación, espiritualidad",
      fr: "Espoir, foi, but, renouveau, spirituelité",
      ja: "希望、信仰、目的、再生、霊性",
      ko: "희망, 믿음, 목적, 재생, 영성",
      zh: "希望、信仰、目的、更新、灵性",
    },
  },
  strength: {
    lucideIcon: "Shield",
    narrative: {
      en: "Strength (VIII): Inner fortitude and compassion. True power comes not from force, but from the gentle mastery of your inner wildness.",
      es: "La Fuerza (VIII): Fortaleza interior y compasión.",
      fr: "La Force (VIII) : Force intérieure et compassion.",
      ja: "力 (VIII): 内面の不屈の勇気と慈悲。真の力は強引さではなく、内なる野性を穏やかに制御することから生まれます。",
      ko: "힘 (VIII): 내면의 불굴의 용기와 자비. 진정한 힘은 강압이 아니라 내면의 야성성을 부드럽게 길들이는 데서 나옵니다.",
      zh: "力量（VIII）：内在坚韧和慈悲。真正的力量并非来自暴力，而是来自对自己内在野性的温柔掌控。",
    },
    reversed: {
      en: "Reversed: Self-doubt, lack of moral courage, raw emotion.",
      es: "Invertida: Duda de uno mismo, falta de coraje.",
      fr: "Inversé : Doute de soi, manque de courage moral.",
      ja: "逆位置: 自己疑念、道徳的勇気の欠如、剥き出しの感情。",
      ko: "역방향: 자기 의심, 도덕적 용기 부족, 가공되지 않은 감정.",
      zh: "逆位：自我怀疑、缺乏道德勇气、原始情绪。",
    },
    symbol: "🦁",
    upright: {
      en: "Strength, courage, persuasion, influence, compassion",
      es: "Fuerza, coraje, persuasión.",
      fr: "Force, courage, persuasion.",
      ja: "力、勇気、説得、影響力、慈悲",
      ko: "힘, 용기, 설득, 영향력, 자비",
      zh: "力量、勇气、说服力、影响力、慈悲",
    },
  },
  sun: {
    lucideIcon: "Sun",
    narrative: {
      en: "The Sun (XIX): Joy, success, and vitality. The Sun shines on all equally, blessing with warmth and clarity. This is a card of celebration and positive outcomes.",
      es: "El Sol (XIX): Alegría, éxito y vitalidad. El Sol brilla sobre todos por igual, bendiciendo con calidez y claridad. Esta es una carta de celebración y resultados positivos.",
      fr: "Le Soleil (XIX) : Joie, succès et vitalité. Le Soleil brille également sur tous, bénissant par sa chaleur et sa clarté. C'est une carte de célébration et de résultats positifs.",
      ja: "太陽（XIX）：喜び、成功、活力。太陽はすべてに等しく輝き、温もりと明晰さで祝福します。これは祝福と前向きな結果のカードです。",
      ko: "태양 (XIX): 기쁨, 성공, 활력. 태양은 모든 것에 동등하게 빛나며 따뜻함과 명료함을 축복합니다. 이것은 축하와 긍정적 결과의 카드입니다.",
      zh: "太阳（XIX）：喜悦、成功和活力。太阳平等地照亮万物，赐予温暖和清晰。这是一张庆祝和积极结果的牌。",
    },
    reversed: {
      en: "Reversed: Inner child issues, overly optimistic, temporary setbacks.",
      es: "Invertida: Problemas del niño interior, excesivamente optimista, contratiempos temporales.",
      fr: "Inversé : Problèmes de l'enfant intérieur, trop optimiste, revers temporaires.",
      ja: "逆位置：インナーチャイルドの問題、楽観的すぎる、一時的な挫折。",
      ko: "역방향: 내면 아이 문제, 지나친 낙관, 일시적 실패.",
      zh: "逆位：内在小孩问题、过于乐观、暂时挫折。",
    },
    symbol: "☀",
    upright: {
      en: "Positivity, fun, warmth, success, vitality",
      es: "Positividad, diversión, calidez, éxito, vitalidad",
      fr: "Positivité, plaisir, chaleur, succès, vitalité",
      ja: "ポジティブさ、楽しさ、暖かさ、成功、活力",
      ko: "긍정, 재미, 따뜻함, 성공, 활력",
      zh: "积极性、乐趣、温暖、成功、活力",
    },
  },

  temperance: {
    lucideIcon: "Cup",
    narrative: {
      en: "Temperance (XIV): Balance, moderation, and patience. You are blending diverse elements to find the middle path and inner peace.",
      es: "La Templanza (XIV): Equilibrio, moderación y paciencia.",
      fr: "La Tempérance (XIV) : Équilibre, modération et patience.",
      ja: "節制 (XIV): 均衡、節度、そして忍耐。多様な要素を混ぜ合わせ、中道と内なる平和を見出そうとしています。",
      ko: "절제 (XIV): 균형, 절제, 인내. 다양한 요소를 섞어 중도와 내면의 평화를 찾고 있습니다.",
      zh: "节制（XIV）：平衡、适度和耐心。你正融合不同的元素，以寻求中道和内在和平。",
    },
    reversed: {
      en: "Reversed: Imbalance, excess, lack of long-term vision.",
      es: "Invertida: Desequilibrio, exceso.",
      fr: "Inversé : Déséquilibre, excès.",
      ja: "逆位置: 不均衡、過剰、長期的な視点の欠如。",
      ko: "역방향: 불균형, 과잉, 장기적 안목 부족.",
      zh: "逆位：失衡、过度、缺乏长期愿景。",
    },
    symbol: "🍷",
    upright: {
      en: "Balance, moderation, patience, purpose",
      es: "Equilibrio, moderación, paciencia.",
      fr: "Équilibre, modération, patience.",
      ja: "バランス、節度、忍耐、目的",
      ko: "균형, 절제, 인내, 목적",
      zh: "平衡、适度、耐心、目的",
    },
  },
  tower: {
    lucideIcon: "Zap",
    narrative: {
      en: "The Tower (XVI): Sudden upheaval and revelation. Structures built on false foundations must fall. Though frightening, this destruction clears the way for truth.",
      es: "La Torre (XVI): Agitación repentina y revelación. Las estructuras construidas sobre cimientos falsos deben caer. Aunque aterradora, esta destrucción despeja el camino a la verdad.",
      fr: "La Tour (XVI) : Bouleversement soudain et révélation. Les structures construites sur de fausses fondations doivent tomber. Bien qu'effrayante, cette destruction ouvre la voie à la vérité.",
      ja: "塔（XVI）：突然の激変と啓示。誤った基盤の上に築かれた構造物は崩れ落ちねばなりません。恐ろしいことですが、この破壊は真実への道を切り拓きます。",
      ko: "탑 (XVI): 갑작스러운 격변과 계시. 거짓 기반 위에 세워진 구조물은 무너져야 합니다. 무섭지만, 이 파괴는 진실을 위한 길을 닦습니다.",
      zh: "塔（XVI）：突然的剧变和启示。建立在虚假基础上的结构必须倒塌。虽然可怕，但这破坏为真理扫清了道路。",
    },
    reversed: {
      en: "Reversed: Avoiding disaster, fear of change, delayed upheaval.",
      es: "Invertida: Evitar el desastre, miedo al cambio, agitación retrasada.",
      fr: "Inversé : Évitement du désastre, peur du changement, bouleversement retardé.",
      ja: "逆位置：災害の回避、変化への恐れ、遅れた激変。",
      ko: "역방향: 재앙 회피, 변화에 대한 두려움, 지연된 격변.",
      zh: "逆位：避免灾难、恐惧改变、延迟的剧变。",
    },
    symbol: "⚡",
    upright: {
      en: "Sudden change, upheaval, chaos, revelation, awakening",
      es: "Cambio repentino, agitación, caos, revelación, despertar",
      fr: "Changement soudain, bouleversement, chaos, révélation, éveil",
      ja: "突然の変化、激変、混沌、啓示、目覚め",
      ko: "갑작스러운 변화, 격변, 혼돈, 계시, 각성",
      zh: "突然的改变、剧变、混乱、启示、觉醒",
    },
  },
  wheel: {
    lucideIcon: "RotateCw",
    narrative: {
      en: "Wheel of Fortune (X): The eternal cycle of fate. What goes up must come down, and what falls shall rise again. Embrace the turning of life's great wheel.",
      es: "La Rueda de la Fortuna (X): El ciclo eterno del destino.",
      fr: "La Roue de Fortune (X) : Le cycle éternel du destin.",
      ja: "運命の輪 (X): 運命の永遠のサイクル。上がるものは下がり、落ちるものは再び上がります。人生の大きな輪の回転を受け入れてください。",
      ko: "운명의 수레바퀴 (X): 운명의 영원한 순환. 오르는 것은 내려와야 하고, 떨어지는 것은 다시 일어납니다. 삶의 거대한 바퀴의 회전을 받아들이세요.",
      zh: "命运之轮（X）：命运的永恒循环。升起的必将降下，跌落的终将升起。拥抱生命巨轮的转动。",
    },
    reversed: {
      en: "Reversed: Bad luck, resistance to change, breaking cycles.",
      es: "Invertida: Mala suerte, resistencia al cambio.",
      fr: "Inversé : Malchance, résistance au changement.",
      ja: "逆位置: 不運、変化への抵抗、悪循環。",
      ko: "역방향: 불운, 변화에 대한 저항, 순환 깨기.",
      zh: "逆位：厄运、抗拒改变、打破循环。",
    },
    symbol: "☸",
    upright: {
      en: "Change, cycles, fate, destiny, turning point",
      es: "Cambio, ciclos, destino, punto de inflexión.",
      fr: "Changement, cycles, destin, tournant.",
      ja: "変化、サイクル、運命、宿命、転換点",
      ko: "변화, 순환, 운명, 숙명, 전환점",
      zh: "改变、循环、命运、宿命、转折点",
    },
  },
  world: {
    lucideIcon: "Globe",
    narrative: {
      en: "The World (XXI): Completion and integration. The final card of the Major Arcana represents achievement, wholeness, and the successful end of a journey.",
      es: "El Mundo (XXI): Finalización e integración. La carta final de los Arcanos Mayores representa logro, totalidad y el final exitoso de un viaje.",
      fr: "Le Monde (XXI) : Achèvement et intégration. La dernière carte des Arcanes Majeurs représente l'accomplissement, la plénitude et la fin heureuse d'un voyage.",
      ja: "世界（XXI）：完了と統合。大アルカナの最後のカードは、達成、全体性、そして旅の成功裡の終わりを表します。",
      ko: "세계 (XXI): 완성과 통합. 메이저 아르카나의 마지막 카드는 성취, 완전함, 그리고 여정의 성공적인 끝을 나타냅니다.",
      zh: "世界（XXI）：完成和整合。大阿卡纳的最后一张牌代表成就、完整性和旅程的圆满结束。",
    },
    reversed: {
      en: "Reversed: Lack of closure, incomplete goals, stagnation.",
      es: "Invertida: Falta de cierre, objetivos incompletos, estancamiento.",
      fr: "Inversé : Manque de clôture, objectifs incomplets, stagnation.",
      ja: "逆位置：閉鎖の欠如、不完全な目標、停滞。",
      ko: "역방향: 마무리 부족, 미완성된 목표, 정체.",
      zh: "逆位：缺乏了结、目标未完成、停滞。",
    },
    symbol: "🌍",
    upright: {
      en: "Completion, integration, accomplishment, travel",
      es: "Finalización, integración, logro, viajes",
      fr: "Achèvement, intégration, accomplissement, voyage",
      ja: "完了、統合、達成、旅行",
      ko: "완성, 통합, 성취, 여행",
      zh: "完成、整合、成就、旅行",
    },
  },
};

export const MINOR_ARCANA: Record<
  string,
  {
    lucideIcon: string;
    narrative: SixLangString;
    reversed: SixLangString;
    suit: string;
    symbol: string;
    upright: SixLangString;
  }
> = {
  ace_of_cups: {
    lucideIcon: "Cup",
    narrative: {
      en: "Ace of Cups: Emotional new beginnings, love, and intuition. Your cup overflows with spiritual and emotional abundance.",
      es: "As de Copas: Amor, intuición.",
      fr: "As de Coupes : Amour, intuition.",
      ja: "カップのエース: 感情的な新しい始まり、愛、そして直感。あなたのカップは精神的、感情的な豊かさで溢れています。",
      ko: "컵 에이스: 감정적인 새로운 시작, 사랑, 직관. 당신의 컵이 영적으로나 감정적으로 풍요로움으로 넘쳐납니다.",
      zh: "圣杯首牌：情感上的新开始、爱情和直觉。你的杯中溢满了灵性和情感的丰盛。",
    },
    reversed: {
      en: "Reversed: Emotional loss, blocked intuition, empty cup.",
      es: "Invertida: Pérdida emocional.",
      fr: "Inversé : Perte émotionnelle.",
      ja: "逆位置: 感情的な喪失、遮断された直感、空のカップ。",
      ko: "역방향: 감정적 상실, 차단된 직관, 비어있는 컵.",
      zh: "逆位：情感失落、直觉受阻、空杯。",
    },
    suit: "Cups",
    symbol: "🍷",
    upright: {
      en: "Love, compassion, creativity, overwhelming emotion",
      es: "Amor, compasión.",
      fr: "Amour, compassion.",
      ja: "愛、慈悲、創造性、圧倒的な感情",
      ko: "사랑, 자비, 창의성, 넘치는 감정",
      zh: "爱情、慈悲、创造力、充沛的情感",
    },
  },
  ace_of_pentacles: {
    lucideIcon: "Coins",
    narrative: {
      en: "Ace of Pentacles: Manifestation, new financial opportunities, and prosperity. A seed of material success is being planted.",
      es: "As de Oros: Prosperidad material.",
      fr: "As de Deniers : Prospérité matérielle.",
      ja: "ペンタクルのエース: 顕現、新しい金銭的な機会、そして繁栄。物質的な成功の種がまかれようとしています。",
      ko: "펜타클 에이스: 현현, 새로운 재정적 기회, 번영. 물질적 성공의 씨앗이 심어지고 있습니다.",
      zh: "星币首牌：显化、新的财务机会和繁荣。物质成功的种子正在播下。",
    },
    reversed: {
      en: "Reversed: Lost opportunity, lack of planning, financial delay.",
      es: "Invertida: Oportunidad perdida.",
      fr: "Inversé : Opportunité manquée.",
      ja: "逆位置: 機会の喪失、計画不足、金銭的な遅延。",
      ko: "역방향: 기회 상실, 계획 부족, 재정적 지연.",
      zh: "逆位：错失机会、缺乏规划、财务延迟。",
    },
    suit: "Pentacles",
    symbol: "🪙",
    upright: {
      en: "Manifestation, prosperity, new job, stability",
      es: "Prosperidad.",
      fr: "Prospérité.",
      ja: "顕現、繁栄、新しい仕事、安定",
      ko: "현현, 번영, 새로운 직업, 안정",
      zh: "显化、繁荣、新工作、稳定",
    },
  },
  ace_of_swords: {
    lucideIcon: "Sword",
    narrative: {
      en: "Ace of Swords: Clarity, breakthrough, and intellectual power. A sharp mind that cuts through confusion to find the truth.",
      es: "As de Espadas: Claridad mental.",
      fr: "As d'Épées : Clarté mentale.",
      ja: "ソードのエース: 明快さ、突破口、そして知的な力。混乱を切り裂き、真実を見出す鋭い知性。",
      ko: "검 에이스: 명료함, 돌파구, 지적 능력. 혼란을 뚫고 진실을 찾는 날카로운 지성.",
      zh: "宝剑首牌：清晰、突破和智力。锐利的思想，穿透混乱寻找真理。",
    },
    reversed: {
      en: "Reversed: Confusion, chaos, lack of clarity.",
      es: "Invertida: Confusión.",
      fr: "Inversé : Confusion.",
      ja: "逆位置: 混乱、カオス、明快さの欠如。",
      ko: "역방향: 혼란, 카오스, 명료함 부족.",
      zh: "逆位：混乱、混沌、缺乏清晰度。",
    },
    suit: "Swords",
    symbol: "🗡️",
    upright: {
      en: "Breakthrough, clarity, sharp mind, victory",
      es: "Claridad, victoria.",
      fr: "Clarté, victoire.",
      ja: "突破、明快さ、鋭い知性、勝利",
      ko: "돌파구, 명료함, 날카로운 지성, 승리",
      zh: "突破、清晰、敏锐的思想、胜利",
    },
  },
  ace_of_wands: {
    lucideIcon: "Flame",
    narrative: {
      en: "Ace of Wands: Inspiration, new opportunities, and potential. A spark of creativity that ignites your passion.",
      es: "As de Bastos: Inspiración, nuevas oportunidades.",
      fr: "As de Bâtons : Inspiration, nouvelles opportunités.",
      ja: "ワンドのエース: インスピレーション、新しい機会、そして可能性。あなたの情熱に火をつける創造性の火花。",
      ko: "지팡이 에이스: 영감, 새로운 기회, 잠재력. 열정을 불지피는 창의성의 불꽃.",
      zh: "权杖首牌：灵感、新机会和潜力。点燃你激情的创造力火花。",
    },
    reversed: {
      en: "Reversed: Delayed starts, creative blocks, lack of motivation.",
      es: "Invertida: Inicios retrasados.",
      fr: "Inversé : Départs retardés.",
      ja: "逆位置: 開始の遅れ、創造的なブロック、モチベーションの欠如。",
      ko: "역방향: 지연된 시작, 창작 막힘, 동기 부족.",
      zh: "逆位：延迟开始、创造力受阻、缺乏动力。",
    },
    suit: "Wands",
    symbol: "🪄",
    upright: {
      en: "Inspiration, new opportunities, growth, potential",
      es: "Inspiración, oportunidades.",
      fr: "Inspiration, opportunités.",
      ja: "鼓舞、新しい機会、成長、可能性",
      ko: "영감, 새로운 기회, 성장, 잠재력",
      zh: "灵感、新机会、成长、潜力",
    },
  },
  eight_of_cups: {
    lucideIcon: "Moon",
    narrative: {
      en: "Eight of Cups: Disillusionment, withdrawal, and moving on. Walking away from what no longer serves your soul.",
      es: "Ocho de Copas: Dejar ir, búsqueda espiritual.",
      fr: "Huit de Coupes : Lâcher-prise, quête spirituelle.",
      ja: "カップの8: 幻滅、撤退、そして前進。もはや魂の糧とならないものから立ち去ります。",
      ko: "컵 8: 환멸, 철수, 나아가기. 더 이상 당신의 영혼에 도움이 되지 않는 것으로부터 걸어 나옵니다.",
      zh: "圣杯八：幻灭、撤退和继续前进。离开那些不再契合你灵魂的事物。",
    },
    reversed: {
      en: "Reversed: Trying one more time, indecision, fear of loss.",
      es: "Invertida: Indecisión.",
      fr: "Inversé : Indécision.",
      ja: "逆位置: 再挑戦、優柔不断、喪失への恐怖。",
      ko: "역방향: 한 번 더 시도함, 우유부단함, 상실에 대한 두려움.",
      zh: "逆位：再试一次、犹豫不决、恐惧失去。",
    },
    suit: "Cups",
    symbol: "🌙",
    upright: {
      en: "Disillusionment, leaving behind, withdrawal, abandoning",
      es: "Buscar algo más profundo.",
      fr: "Chercher quelque chose de plus profond.",
      ja: "幻滅、置き去る、撤退、放棄",
      ko: "환멸, 뒤로하고 떠남, 철수, 버림",
      zh: "幻灭、离开、撤回、放弃",
    },
  },
  eight_of_pentacles: {
    lucideIcon: "Hammer",
    narrative: {
      en: "Eight of Pentacles: Apprenticeship, craftsmanship, and skill development. Diligent work on your craft to achieve mastery.",
      es: "Ocho de Oros: Maestría, aprendizaje.",
      fr: "Ocho de Deniers : Maîtrise, apprentissage.",
      ja: "ペンタクルの8: 見習い、職人技、そしてスキル開発. 熟練を目指して、自分の技術に勤勉に取り組んでいます。",
      ko: "펜타클 8: 견습, 장인 정신, 기술 개발. 장인이 되기 위해 당신의 기술을 부지런히 연마합니다.",
      zh: "星币八：学徒期、工艺和技能开发. 为了精通技艺而勤奋钻研.",
    },
    reversed: {
      en: "Reversed: Lack of focus, perfectionism issues, uninspired work.",
      es: "Invertida: Desinterés.",
      fr: "Inversé : Désintérêt.",
      ja: "逆位置: 集中力の欠如、完璧主義の問題、インスピレーションのない仕事。",
      ko: "역방향: 집중력 부족, 완벽주의 문제, 영감 없는 작업.",
      zh: "逆位：缺乏专注、完美主义问题、作品平庸。",
    },
    suit: "Pentacles",
    symbol: "🔨",
    upright: {
      en: "Apprenticeship, skill development, mastery, quality",
      es: "Dedicación.",
      fr: "Dévouement.",
      ja: "見習い、スキル開発、熟練、品質",
      ko: "견습, 기술 개발, 숙달, 품질",
      zh: "学徒期、技能开发、精通、品质",
    },
  },
  eight_of_swords: {
    lucideIcon: "EyeOff",
    narrative: {
      en: "Eight of Swords: Restriction, imprisonment, and powerless feelings. You are trapped by your own thoughts, even though the prison bars may be illusory.",
      es: "Ocho de Espadas: Sentirse atrapado.",
      fr: "Huit d'Épées : Se sentir piégé.",
      ja: "ソードの8: 束縛、投獄、そして無力感。牢獄の格子が幻であったとしても、あなたは自らの思考に囚われています。",
      ko: "검 8: 구속, 투옥, 무력감. 감옥 창살이 환상일지라도 당신은 자신의 생각에 갇혀 있습니다.",
      zh: "宝剑八：限制、禁锢和无力感。即使监牢的栅栏可能是虚幻的，你仍被自己的思想困住。",
    },
    reversed: {
      en: "Reversed: Self-release, new perspective, freedom from limitations.",
      es: "Invertida: Liberación.",
      fr: "Inversé : Libération.",
      ja: "逆位置: 自らの解放、新しい視点、制限からの自由。",
      ko: "역방향: 스스로 해방됨, 새로운 관점, 제한으로부터의 자유.",
      zh: "逆位：自我解脱、新视角、从限制中获得自由。",
    },
    suit: "Swords",
    symbol: "⛓️",
    upright: {
      en: "Negative thoughts, trapped, powerless, blindspot",
      es: "Limitaciones mentales.",
      fr: "Limites mentales.",
      ja: "否定的な思考、囚われ、無力、死角",
      ko: "부정적인 생각, 갇힘, 무력함, 사각지대",
      zh: "负面思想、困境、无力、盲点",
    },
  },
  eight_of_wands: {
    lucideIcon: "Zap",
    narrative: {
      en: "Eight of Wands: Speed, action, and air travel. Events are moving quickly now; be ready to act.",
      es: "Ocho de Bastos: Rapidez, acción.",
      fr: "Huit de Bâtons : Rapidité, action.",
      ja: "ワンドの8: 速さ、行動、そして空の旅。事態は今、急速に動いています。行動の準備をしてください。",
      ko: "지팡이 8: 속도, 행동, 항공 여행. 상황이 빠르게 전개되고 있습니다. 행동할 준비를 하세요.",
      zh: "权杖八：速度、行动和航空旅行。事情正在快速发展；准备好行动。",
    },
    reversed: {
      en: "Reversed: Delays, frustration, checking progress too often.",
      es: "Invertida: Retrasos frustrantes.",
      fr: "Inversé : Retards frustrants.",
      ja: "逆位置: 遅延、不満、頻繁すぎる進捗確認。",
      ko: "역방향: 지연, 좌절, 너무 잦은 진행 상황 확인.",
      zh: "逆位：延迟、挫折、过于频繁地检查进度。",
    },
    suit: "Wands",
    symbol: "⚡",
    upright: {
      en: "Speed, action, air travel, movement",
      es: "Movimiento rápido.",
      fr: "Mouvement rapide.",
      ja: "速さ、行動、空の旅、移動",
      ko: "속도, 행동, 항공 여행, 움직임",
      zh: "速度、行动、航空旅行、移动",
    },
  },
  five_of_cups: {
    lucideIcon: "Frown",
    narrative: {
      en: "Five of Cups: Regret, failure, and pessimism. Focusing on the spilled cups while others remain full behind you.",
      es: "Cinco de Copas: Pesar, arrepentimiento.",
      fr: "Cinq de Coupes : Regret, tristesse.",
      ja: "カップの5: 後悔、失敗、そして悲観。背後に満たされたカップがあるのに、こぼれたカップだけに目を向けています。",
      ko: "컵 5: 후회, 실패, 비관주의. 뒤에 가득 찬 컵들을 두고 쏟아진 컵들에만 집중하고 있습니다.",
      zh: "圣杯五：后悔、失败和悲观。专注于打翻的杯子，而忽略了身后仍然满着的杯子。",
    },
    reversed: {
      en: "Reversed: Moving on, acceptance, finding peace.",
      es: "Invertida: Aceptación.",
      fr: "Inversé : Acceptation.",
      ja: "逆位置: 前進、受け入れ、平和を見出すこと。",
      ko: "역방향: 나아가기, 수용, 평화 찾기.",
      zh: "逆位：继续前进、接受、寻找平静。",
    },
    suit: "Cups",
    symbol: "😢",
    upright: {
      en: "Regret, failure, disappointment, pessimism",
      es: "Pesar.",
      fr: "Regret.",
      ja: "後悔、失敗、失望、悲観主義",
      ko: "후회, 실패, 실망, 비관주의",
      zh: "后悔、失败、失望、悲观",
    },
  },
  five_of_pentacles: {
    lucideIcon: "Snowflake",
    narrative: {
      en: "Five of Pentacles: Financial loss, poverty, and isolation. A difficult time of material hardship where you may feel left out in the cold.",
      es: "Cinco de Oros: Inestabilidad financiera.",
      fr: "Cinq de Deniers : Instabilité financière.",
      ja: "ペンタクルの5: 金銭的な損失、貧困、そして孤立. 物質的な高難の時期で、疎外感を感じるかもしれません。",
      ko: "펜타클 5: 재정적 손실, 가난, 고립. 물질적인 고난의 시기로, 소외감을 느낄 수 있습니다.",
      zh: "星币五：财务损失、贫困和孤立. 物质匮乏的艰难时期, 你可能感到孤立无援.",
    },
    reversed: {
      en: "Reversed: Recovery from financial loss, finding help, hope returning.",
      es: "Invertida: Alivio financiero.",
      fr: "Inversé : Soulagement financier.",
      ja: "逆位置: 損失からの回復、助けを見つけること、希望の再来。",
      ko: "역방향: 재정적 손실로부터 회복, 도움 찾기, 희망의 귀환.",
      zh: "逆位：从财务损失中恢复、寻得帮助、希望复归。",
    },
    suit: "Pentacles",
    symbol: "🏚️",
    upright: {
      en: "Financial loss, poverty, lack of support, isolation",
      es: "Dificultad material.",
      fr: "Difficulté matérielle.",
      ja: "金銭的な損失、貧困、サポートの欠如、孤立",
      ko: "재정적 손실, 가난, 지원 부족, 고립",
      zh: "财务损失、贫困、缺乏支持、孤立",
    },
  },

  five_of_swords: {
    lucideIcon: "Sword",
    narrative: {
      en: "Five of Swords: Conflict, defeat, and win at any cost. A hollow victory or a bitter disagreement.",
      es: "Cinco de Espadas: Conflicto, victoria vana.",
      fr: "Cinq d'Épées : Conflit, victoire vaine.",
      ja: "ソードの5: 葛藤、敗北、そして手段を選ばぬ勝利。虚しい勝利、あるいは苦い意見の不一致。",
      ko: "검 5: 갈등, 패배, 수단과 방법을 가리지 않는 승리. 공허한 승리나 쓰라린 의견 충돌.",
      zh: "宝剑五：冲突、失败和不惜代价的胜利。一场空洞的胜利或一次痛苦的分歧。",
    },
    reversed: {
      en: "Reversed: Reconciliation, moving on from conflict, resentment.",
      es: "Invertida: Reconciliación.",
      fr: "Inversé : Réconciliation.",
      ja: "逆位置: 和解、紛争からの脱却、恨み。",
      ko: "역방향: 화해, 갈등에서 벗어나기, 원한.",
      zh: "逆位：和解、从冲突中走出、怨恨。",
    },
    suit: "Swords",
    symbol: "🥀",
    upright: {
      en: "Conflict, disagreement, competition, defeat",
      es: "Discordia.",
      fr: "Discorde.",
      ja: "葛藤、意見の不一致、競争、敗北",
      ko: "갈등, 의견 충돌, 경쟁, 패배",
      zh: "冲突、分歧、竞争、失败",
    },
  },
  five_of_wands: {
    lucideIcon: "Sword",
    narrative: {
      en: "Five of Wands: Competition, conflict, and diversity. Healthy competition that pushes you to excel.",
      es: "Cinco de Bastos: Competencia, conflicto.",
      fr: "Cinq de Bâtons : Compétition, conflit.",
      ja: "ワンドの5: 競争、対立、そして多様性。あなたを向上させる健全な競争です。",
      ko: "지팡이 5: 경쟁, 갈등, 다양성. 당신을 뛰어나게 만드는 건강한 경쟁입니다.",
      zh: "权杖五：竞争、冲突和多样性。推动你追求卓越的良性竞争。",
    },
    reversed: {
      en: "Reversed: Avoiding conflict, ending of struggle, internal strife.",
      es: "Invertida: Evitar conflictos.",
      fr: "Inversé : Éviter les conflits.",
      ja: "逆位置: 紛争の回避、闘争の終了、内紛。",
      ko: "역방향: 갈등 회피, 투쟁의 종료, 내분.",
      zh: "逆位：逃避冲突、斗争结束、内讧。",
    },
    suit: "Wands",
    symbol: "⚔️",
    upright: {
      en: "Competition, conflict, rivalry, diversity",
      es: "Competencia, rivalidad.",
      fr: "Compétition, rivalité.",
      ja: "競争、対立、ライバル、多様性",
      ko: "경쟁, 갈등, 라이벌 관계, 다양성",
      zh: "竞争、冲突、对手、多样性",
    },
  },
  four_of_cups: {
    lucideIcon: "Cloud",
    narrative: {
      en: "Four of Cups: Meditation, contemplation, and reevaluation. You may be ignoring new gifts while focused on what you lack.",
      es: "Cuatro de Copas: Meditación, apatía.",
      fr: "Quatre de Coupes : Méditation, apathie.",
      ja: "カップの4: 瞑想、観照、そして再評価。欠けているものに目を向けすぎて、新しい贈り物を見落としているかもしれません。",
      ko: "컵 4: 명상, 관조, 재평가. 부족한 것에 집중하느라 새로운 선물을 무시하고 있을 수 있습니다.",
      zh: "圣杯四：冥想、沉思和重新评估。你可能过于关注所缺乏的，而忽略了新的馈赠。",
    },
    reversed: {
      en: "Reversed: Awareness, choosing to be engaged, acceptance of opportunities.",
      es: "Invertida: Nueva perspectiva.",
      fr: "Inversé : Nouvelle perspective.",
      ja: "逆位置: 意識、関わることの選択、機会の受け入れ。",
      ko: "역방향: 인식, 참여하기로 선택함, 기회 수용.",
      zh: "逆位：觉察、选择参与、接受机会。",
    },
    suit: "Cups",
    symbol: "🧘",
    upright: {
      en: "Meditation, contemplation, apathy, reevaluation",
      es: "Introspección.",
      fr: "Introspection.",
      ja: "瞑想、観照、無関心、再評価",
      ko: "명상, 관조, 무관심, 재평가",
      zh: "冥想、沉思、冷淡、重新评估",
    },
  },
  four_of_pentacles: {
    lucideIcon: "Lock",
    narrative: {
      en: "Four of Pentacles: Security, conservation, and control. Holding on tight to your resources out of a need for safety.",
      es: "Cuatro de Oros: Seguridad, avaricia.",
      fr: "Quatre de Deniers : Sécurité, avarice.",
      ja: "ペンタクルの4: セキュリティ、保全、そして制御。安全を求めるあまり、資源をしっかりと握りしめています。",
      ko: "펜타클 4: 보안, 보존, 통제. 안전을 위해 자원을 꽉 쥐고 있습니다.",
      zh: "星币四：安全、保守和控制. 出于对安全感的渴望, 紧紧抓着你的资源不放.",
    },
    reversed: {
      en: "Reversed: Releasing control, generosity, letting go of possessions.",
      es: "Invertida: Generosidad.",
      fr: "Inversé : Générosité.",
      ja: "逆位置: 制御の解除、寛大さ、所有物を手放すこと。",
      ko: "역방향: 통제 해제, 관대함, 소유물 내려놓기.",
      zh: "逆位：释放控制、大方、放下财物。",
    },
    suit: "Pentacles",
    symbol: "🏰",
    upright: {
      en: "Security, conservation, frugality, boundary setting",
      es: "Estabilidad material.",
      fr: "Stabilité matérielle.",
      ja: "セキュリティ、保全、倹約、境界の設定",
      ko: "보안, 보존, 검소함, 경계 설정",
      zh: "安全、保守、勤俭、设立界限",
    },
  },
  four_of_swords: {
    lucideIcon: "Bed",
    narrative: {
      en: "Four of Swords: Rest, recovery, and contemplation. Taking a break to rejuvenate your mind after a period of stress.",
      es: "Cuatro de Espadas: Descanso mental.",
      fr: "Quatre d'Épées : Repos mental.",
      ja: "ソードの4: 休息、回復、そして観照。ストレスの多い時期を経て、精神をリフレッシュさせるための休息です。",
      ko: "검 4: 휴식, 회복, 관조. 스트레스 기간 이후 정신을 회복하기 위한 휴식 시간.",
      zh: "宝剑四：休息、恢复和沉思。在一段压力时期后休假，以使大脑恢复活力。",
    },
    reversed: {
      en: "Reversed: Restlessness, burnout, returning to work too soon.",
      es: "Invertida: Agotamiento.",
      fr: "Inversé : Épuisement.",
      ja: "逆位置: そわそわする、燃え尽き、早すぎる復帰。",
      ko: "역방향: 안절부절못함, 번아웃, 너무 이른 업무 복귀.",
      zh: "逆位：焦躁不安、精疲力竭、太快重返工作。",
    },
    suit: "Swords",
    symbol: "🛌",
    upright: {
      en: "Rest, relaxation, meditation, recovery",
      es: "Reposo.",
      fr: "Repos.",
      ja: "休息、リラックス、瞑想、回復",
      ko: "휴식, 이완, 명상, 회복",
      zh: "休息、放松、冥想、恢复",
    },
  },
  four_of_wands: {
    lucideIcon: "Home",
    narrative: {
      en: "Four of Wands: Celebration, harmony, and homecoming. A time of joy and stability in your environment.",
      es: "Cuatro de Bastos: Celebración, armonía.",
      fr: "Quatre de Bâtons : Célébration, harmonie.",
      ja: "ワンドの4: 祝い、調和、そして帰還。あなたの周囲の環境において喜びと安定の時期です。",
      ko: "지팡이 4: 축하, 조화, 귀환. 당신의 환경에서 기쁨과 안정의 시간입니다.",
      zh: "权杖四：庆典、和谐和归家。环境中充满喜悦和稳定的时刻。",
    },
    reversed: {
      en: "Reversed: Lack of support, instability, inner private celebration.",
      es: "Invertida: Inestabilidad.",
      fr: "Inversé : Inestabilité.",
      ja: "逆位置: サポートの欠如、不安定、内面的な静かな祝い。",
      ko: "역방향: 지원 부족, 불투명함, 내면의 조용한 축하.",
      zh: "逆位：缺乏支持、不稳定、内在的私人庆祝。",
    },
    suit: "Wands",
    symbol: "💒",
    upright: {
      en: "Celebration, harmony, marriage, home, community",
      es: "Celebración, armonía en el hogar.",
      fr: "Célébration, harmonie au foyer.",
      ja: "お祝い、調和、結婚、家庭、コミュニティ",
      ko: "축하, 조화, 결혼, 가정, 공동체",
      zh: "庆典、和谐、婚姻、家、社群",
    },
  },
  king_of_cups: {
    lucideIcon: "Crown",
    narrative: {
      en: "King of Cups: Emotional balance, wisdom, and mastery over feelings. A steady and compassionate leader who navigates the depths of emotion with grace.",
      es: "Rey de Copas: Sabiduría emocional, control.",
      fr: "Roi de Coupes : Sagesse émotionnelle, contrôle.",
      ja: "カップのキング: 感情のバランス、知恵、そして感情の克服。優雅に感情の深淵を航海する、安定した慈悲深いリーダーです。",
      ko: "컵 킹: 정서적 균형, 지혜, 감정의 숙달. 우아하게 감정의 깊이를 탐색하는 안정적이고 자비로운 리더.",
      zh: "圣杯国王：情感平衡、智慧和对情感的掌控。一位稳重且富有慈悲心的领导者，优雅地驾驭情感的深处。",
    },
    reversed: {
      en: "Reversed: Emotional volatility, manipulation, coldness.",
      es: "Invertida: Inestabilidad emocional.",
      fr: "Inversé : Instabilité émotionnelle.",
      ja: "逆位置: 感情の激しさ、操作、冷淡さ。",
      ko: "역방향: 정서적 불안정, 조종, 냉담함.",
      zh: "逆位：情绪反复无常、操纵、冷酷。",
    },
    suit: "Cups",
    symbol: "🐋",
    upright: {
      en: "Emotional balance, compassion, spiritual, wisdom",
      es: "Serenidad.",
      fr: "Sérénité.",
      ja: "感情的なバランス、慈悲、精神性、知恵",
      ko: "정서적 균형, 자비, 영성, 지혜",
      zh: "情感平衡、慈悲、灵性、智慧",
    },
  },
  king_of_pentacles: {
    lucideIcon: "Crown",
    narrative: {
      en: "King of Pentacles: Material success, abundance, and mastery over resources. A stable leader who commands respect through his prosperity and practical vision.",
      es: "Rey de Oros: Abundancia, éxito material.",
      fr: "Roi de Deniers : Abondance, succès matériel.",
      ja: "ペンタクルのキング: 物質的成功, 豊かさ, そして資源管理の熟達. 繁栄と実用的なビジョンを通じて尊敬を集める安定したリーダー。",
      ko: "펜타클 킹: 물질적 성공, 풍요, 자원 관리의 숙달. 번영과 실용적인 비전을 통해 존경을 받는 안정적인 리더.",
      zh: "星币国王：物质成功、丰足和对资源的掌控. 一位通过繁荣和实际远见赢得尊重的稳重领导者.",
    },
    reversed: {
      en: "Reversed: Greedy, materialistic, obsessive control.",
      es: "Invertida: Obsesión por el dinero.",
      fr: "Inversé : Obsession pour l'argent.",
      ja: "逆位置: 強欲、唯物主義、強迫的な制御。",
      ko: "역방향: 탐욕스러운, 물질주의적인, 강박적인 통제.",
      zh: "逆位：贪婪、物质主义、强迫性控制。",
    },
    suit: "Pentacles",
    symbol: "🐂",
    upright: {
      en: "Abundance, prosperity, security, business acumen",
      es: "Riqueza establecida.",
      fr: "Richesse établie.",
      ja: "豊かさ、繁栄、セキュリティ、ビジネスの洞察力",
      ko: "풍요, 번영, 보안, 비즈니스 감각",
      zh: "丰足、繁荣、安全、商业头脑",
    },
  },
  king_of_swords: {
    lucideIcon: "Crown",
    narrative: {
      en: "King of Swords: Intellectual power, authority, and truth. A master of logic and reason who commands respect through his mental discipline.",
      es: "Rey de Espadas: Autoridad intelectual, justicia.",
      fr: "Roi d'Épées : Autorité intellectuelle, justice.",
      ja: "ソードのキング: 知的な力、権威、そして真実。精神的な規律を通じて尊敬を集める、論理と理性の達人です。",
      ko: "검 킹: 지적 능력, 권위, 진실. 정신적 규율을 통해 존경을 받는 논리와 이성의 대가.",
      zh: "宝剑国王：智力、权威和真理。一位通过精神自律赢得尊重的逻辑与理性大师。",
    },
    reversed: {
      en: "Reversed: Manipulative, tyrannical, abuse of power.",
      es: "Invertida: Crueldad.",
      fr: "Inversé : Cruauté.",
      ja: "逆位置: 操作的、独裁的、権力の乱用。",
      ko: "역방향: 조종적인, 폭군적인, 권력 남용.",
      zh: "逆位：操纵、专横、滥用权力。",
    },
    suit: "Swords",
    symbol: "⚖️",
    upright: {
      en: "Intellectual power, authority, truth, logic",
      es: "Justicia lógica.",
      fr: "Justice logique.",
      ja: "知的な力、権威、真実、論理",
      ko: "지적 능력, 권위, 진실, 논리",
      zh: "智力、权威、真理、逻辑",
    },
  },
  king_of_wands: {
    lucideIcon: "Crown",
    narrative: {
      en: "King of Wands: Visionary leadership, entrepreneurship, and honor. A natural-born leader who commands respect through his vision and integrity.",
      es: "Rey de Bastos: Liderazgo, visión.",
      fr: "Roi de Bâtons : Leadership, vision.",
      ja: "ワンドのキング: 遠見のきくリーダーシップ、起業家精神、そして名誉。ビジョンと誠実さで尊敬を集める、生まれながらのリーダーです。",
      ko: "지팡이 킹: 비전 있는 리더십, 기업가 정신, 명예. 비전과 정직함으로 존경을 받는 타고난 리더.",
      zh: "权杖国王：远见卓识的领导力、企业家精神和荣誉。一位天生的领导者，通过他的远见和正直赢得尊重。",
    },
    reversed: {
      en: "Reversed: Impulsive, unpredictable, tyrannical leader.",
      es: "Invertida: Arrogancia.",
      fr: "Inversé : Arrogance.",
      ja: "逆位置: 衝動的、予測不能、独裁的なリーダー。",
      ko: "역방향: 충동적, 예측 불가능, 폭군적인 리더.",
      zh: "逆位：冲动、不可预测、暴虐的领导者。",
    },
    suit: "Wands",
    symbol: "🦁",
    upright: {
      en: "Natural born leader, vision, entrepreneur, honor",
      es: "Liderazgo inspirador.",
      fr: "Leadership inspirant.",
      ja: "生まれながらのリーダー、ビジョン、起業家、名誉",
      ko: "타고난 리더, 비전, 기업가, 명예",
      zh: "天生领袖、远见、企业家、荣誉",
    },
  },
  knight_of_cups: {
    lucideIcon: "Horse",
    narrative: {
      en: "Knight of Cups: Romance, charm, and imagination. Moving forward with a heart full of dreams and a desire for connection.",
      es: "Caballero de Copas: Romance, propuesta.",
      fr: "Cavalier de Coupes : Romantisme, proposition.",
      ja: "カップのナイト: ロマンス、魅力、そして想像力。夢と繋がりの欲求を胸に秘めて前進します。",
      ko: "컵 기사: 로맨스, 매력, 상상력. 꿈과 연결에 대한망을 가득 품고 앞으로 나아갑니다.",
      zh: "圣杯骑士：浪漫、魅力和想象力。带着充满梦想的心和对关联的渴望前进。",
    },
    reversed: {
      en: "Reversed: Moody, unrealistic expectations, emotional manipulation.",
      es: "Invertida: Falta de sinceridad.",
      fr: "Inversé : Manque de sincérité.",
      ja: "逆位置: 気分屋、非現実的な期待、感情的な操作。",
      ko: "역방향: 변덕스러운 기분, 비현실적인 기대, 감정적 조종.",
      zh: "逆位：情绪化、不切实际的期望、情感操纵。",
    },
    suit: "Cups",
    symbol: "🏇",
    upright: {
      en: "Romance, beauty, knight in shining armor, imagination",
      es: "Afecto.",
      fr: "Affection.",
      ja: "ロマンス、美、光り輝く甲冑の騎士、想像力",
      ko: "로맨스, 아름다움, 빛나는 갑옷을 입은 기사, 상상력",
      zh: "浪漫、美、白马王子、想象力",
    },
  },
  knight_of_pentacles: {
    lucideIcon: "Horse",
    narrative: {
      en: "Knight of Pentacles: Reliability, hard work, and persistence. Moving forward steadily with a focus on long-term results and practical details.",
      es: "Caballero de Oros: Trabajo duro, paciencia.",
      fr: "Cavalier de Deniers : Travail acharné, patience.",
      ja: "ペンタクルのナイト: 信頼性、勤勉、そして粘り強さ。長期的な結果と実用的な詳細に集中しながら着実に前進します。",
      ko: "펜타클 기사: 신뢰성, 노력, 끈기. 장기적인 결과와 실용적인 세부 사항에 집중하며 꾸준히 나아갑니다.",
      zh: "星币骑士：可靠、努力和坚持. 稳步前进，注视着长期结果和实际细节.",
    },
    reversed: {
      en: "Reversed: Feeling stuck, boredom, lack of ambition.",
      es: "Invertida: Estancamiento.",
      fr: "Inversé : Stagnation.",
      ja: "逆位置: 行き詰まり感、退屈、野心の欠如。",
      ko: "역방향: 정체된 느낌, 지루함, 야망 부족.",
      zh: "逆位：停滞不前、乏味、缺乏抱负。",
    },
    suit: "Pentacles",
    symbol: "🏇",
    upright: {
      en: "Hard work, productivity, routine, conservatism",
      es: "Constancia.",
      fr: "Constance.",
      ja: "努力、生産性、ルーチン、保守主義",
      ko: "노력, 생산성, 루틴, 보수주의",
      zh: "努力、生产力、常规、保守主义",
    },
  },
  knight_of_swords: {
    lucideIcon: "Horse",
    narrative: {
      en: "Knight of Swords: Intensity, swift action, and intellectual drive. Charging forward with a sharp mind and a focus on the goal.",
      es: "Caballero de Espadas: Acción rápida, determinación.",
      fr: "Cavalier d'Épées : Action rapide, détermination.",
      ja: "ソードのナイト: 強烈さ、迅速な行動、そして知的な推進力。鋭い知性と目標への集中力を持って突き進みます。",
      ko: "검 기사: 강렬함, 빠른 행동, 지적 추진력. 날카로운 지성과 목표에 대한 집중력을 가지고 돌진합니다.",
      zh: "宝剑骑士：强度、迅速行动和智力驱动。带着敏锐的头脑和对目标的关注向前冲锋。",
    },
    reversed: {
      en: "Reversed: Impulsive action, aggression, lack of focus.",
      es: "Invertida: Precipitación.",
      fr: "Inversé : Précipitation.",
      ja: "逆位置: 衝動的な行動、攻撃性、集中力の欠如。",
      ko: "역방향: 충동적인 행동, 공격성, 집중력 부족.",
      zh: "逆位：冲动行事、侵略性、缺乏专注。",
    },
    suit: "Swords",
    symbol: "🏇",
    upright: {
      en: "Action, speed, ambitious, driven, communicative",
      es: "Rapidez.",
      fr: "Rapidité.",
      ja: "行動、スピード、意欲的、推進力、コミュニケーション",
      ko: "행동, 속도, 야망 있는, 주도적인, 소통하는",
      zh: "行动、速度、野心博博、驱动力、沟通",
    },
  },
  knight_of_wands: {
    lucideIcon: "Horse",
    narrative: {
      en: "Knight of Wands: Action, adventure, and fearlessness. Moving forward with passion and determination.",
      es: "Caballero de Bastos: Acción, pasión.",
      fr: "Cavalier de Bâtons : Action, passion.",
      ja: "ワンドのナイト: 行動、冒険、そして大胆さ。情熱と決断力を持って前進します。",
      ko: "지팡이 기사: 행동, 모험, 대담함. 열정과 결단력을 가지고 앞으로 나아갑니다.",
      zh: "权杖骑士：行动、冒险和无畏。带着激情和决心前进。",
    },
    reversed: {
      en: "Reversed: Impulsive action, hastiness, scattered energy.",
      es: "Invertida: Acción precipitada.",
      fr: "Inversé : Action précipitée.",
      ja: "逆位置: 衝動的な行動、急ぎすぎ、分散したエネルギー。",
      ko: "역방향: 충동적인 행동, 조급함, 분산된 에너지.",
      zh: "逆位：冲动行事、草率、精力分散。",
    },
    suit: "Wands",
    symbol: "🏇",
    upright: {
      en: "Energy, passion, lust, action, adventure",
      es: "Aventura.",
      fr: "Aventure.",
      ja: "エネルギー、情熱、渇望、行動、冒険",
      ko: "에너지, 열정, 갈망, 행동, 모험",
      zh: "能量、激情、欲望、行动、冒险",
    },
  },
  nine_of_cups: {
    lucideIcon: "Smile",
    narrative: {
      en: "Nine of Cups: Contentment, satisfaction, and gratitude. The 'wish' card; emotional fulfillment and happiness.",
      es: "Nueve de Copas: Satisfacción, deseos cumplidos.",
      fr: "Neuf de Coupes : Satisfaction, vœux exaucés.",
      ja: "カップの9: 満足、充足、そして感謝。「願い」のカード。感情的な満たされと幸福。",
      ko: "컵 9: 만족, 충족, 감사. '소원' 카드; 정서적 성취와 행복.",
      zh: "圣杯九：满足、如愿和感激。“愿望”牌；情感上的圆满和幸福。",
    },
    reversed: {
      en: "Reversed: Materialism, overindulgence, lack of inner joy.",
      es: "Invertida: Falta de satisfacción.",
      fr: "Inversé : Manque de satisfaction.",
      ja: "逆位置: 唯物主義、過度な耽溺、内なる喜びの欠如。",
      ko: "역방향: 물질주의, 과도한 탐닉, 내면의 기쁨 부족.",
      zh: "逆位：物质主义、过度纵欲、缺乏内在喜悦。",
    },
    suit: "Cups",
    symbol: "😊",
    upright: {
      en: "Contentment, satisfaction, gratitude, wish come true",
      es: "Deseo cumplido.",
      fr: "Vœu exaucé.",
      ja: "充足、満足、感謝、願いが叶う",
      ko: "만족, 충족, 감사, 소원 성취",
      zh: "满足、圆满、感激、愿望成真",
    },
  },
  nine_of_pentacles: {
    lucideIcon: "TreePine",
    narrative: {
      en: "Nine of Pentacles: Independence, luxury, and self-sufficiency. Enjoying the fruits of your labor in a beautiful and stable environment.",
      es: "Nueve de Oros: Independencia, lujo.",
      fr: "Neuf de Deniers : Indépendance, luxe.",
      ja: "ペンタクルの9: 独立, 贅沢, そして自給自足. 美しく安定した環境で、労働の成果を享受しています。",
      ko: "펜타클 9: 독립, 사치, 자급자족. 아름답고 안정적인 환경에서 노동의 결실을 즐깁니다.",
      zh: "星币九：独立、奢华和自给自足. 在优美稳定的环境中享受劳动的果实.",
    },
    reversed: {
      en: "Reversed: Overspending, reckless spending, financial setbacks.",
      es: "Invertida: Falta de autonomía.",
      fr: "Inversé : Manque d'autonomie.",
      ja: "逆位置: 浪費、無謀な支出、金銭的な後退。",
      ko: "역방향: 과소비, 무모한 지출, 재정적 좌절.",
      zh: "逆位：过度超支、挥霍、财务挫折。",
    },
    suit: "Pentacles",
    symbol: "👑",
    upright: {
      en: "Abundance, luxury, self-sufficiency, financial independence",
      es: "Cosecha.",
      fr: "Récolte.",
      ja: "豊かさ、贅沢、自給自足、経済的独立",
      ko: "풍요, 사치, 자급자족, 재정적 독립",
      zh: "丰饶、奢华、自给自足、财务独立",
    },
  },
  nine_of_swords: {
    lucideIcon: "ZapOff",
    narrative: {
      en: "Nine of Swords: Anxiety, nightmares, and mental anguish. Overwhelming worry that prevents sleep and peace of mind.",
      es: "Nueve de Espadas: Ansiedad, insomnio.",
      fr: "Neuf d'Épées : Anxiété, insomnie.",
      ja: "ソードの9: 不安、悪夢、そして精神的な苦悩。眠りや心の平安を妨げるほどの、圧倒的な悩みです。",
      ko: "검 9: 불안, 악몽, 정신적 고뇌. 수면과 마음의 평화를 방해하는 압도적인 걱정.",
      zh: "宝剑九：焦虑、噩梦和精神痛苦。阻碍睡眠和内心平静的压力担忧。",
    },
    reversed: {
      en: "Reversed: Releasing worry, reaching out, hope returning.",
      es: "Invertida: Alivio mental.",
      fr: "Inversé : Soulagement mental.",
      ja: "逆位置: 悩みの解消、助けを求めること、希望の再来。",
      ko: "역방향: 걱정 해소, 도움 요청, 희망의 귀환.",
      zh: "逆位：释放担忧、寻求帮助、希望复归。",
    },
    suit: "Swords",
    symbol: "😱",
    upright: {
      en: "Anxiety, worry, fear, depression, nightmares",
      es: "Angustia.",
      fr: "Angoisse.",
      ja: "不安、心配、恐怖、憂鬱、悪夢",
      ko: "불안, 걱정, 두려움, 우울, 악몽",
      zh: "焦虑、担忧、恐惧、抑郁、噩梦",
    },
  },
  nine_of_wands: {
    lucideIcon: "ShieldCheck",
    narrative: {
      en: "Nine of Wands: Resilience, courage, and persistence. You are tired but must stand strong for the final push.",
      es: "Nueve de Bastos: Resiliencia, persistencia.",
      fr: "Neuf de Bâtons : Résilience, persistance.",
      ja: "ワンドの9: 回復力、勇気、そして粘り強さ。疲れてはいますが、最後のひと踏ん張りのために強く立っていなければなりません。",
      ko: "지팡이 9: 회복력, 용기, 지속성. 지쳐있지만 마지막 박차를 위해 굳건히 서야 합니다.",
      zh: "权杖九：韧性、勇气和坚持。你虽然疲惫，但必须为最后的冲刺保持坚强。",
    },
    reversed: {
      en: "Reversed: Exhaustion, giving up, paranoia.",
      es: "Invertida: Agotamiento extremo.",
      fr: "Inversé : Épuisement extrême.",
      ja: "逆位置: 疲労困憊、諦め、被害妄想。",
      ko: "역방향: 고갈, 포기, 피해망상.",
      zh: "逆位：精疲力竭、放弃、多疑。",
    },
    suit: "Wands",
    symbol: "🧗",
    upright: {
      en: "Resilience, grit, persistence, test of faith",
      es: "Resiliencia, persistencia.",
      fr: "Résilience, persistance.",
      ja: "回復力、気概、粘り強さ、信念の試練",
      ko: "회복력, 기개, 지속성, 믿음의 시험",
      zh: "韧性、勇气、坚持、信念的考验",
    },
  },
  page_of_cups: {
    lucideIcon: "User",
    narrative: {
      en: "Page of Cups: Sensitivity, creativity, and intuition. A messenger of emotional possibilities and creative insights.",
      es: "Sota de Copas: Intuición, sueños.",
      fr: "Valet de Coupes : Intuition, rêves.",
      ja: "カップのペイジ: 感受性、創造性、そして直感。感情的な可能性と創造的な洞察のメッセンジャー。",
      ko: "컵 페이지: 민감함, 창의성, 직관. 감정적인 가능성과 창의적인 통찰력의 메신저.",
      zh: "圣杯侍从：敏感、创造力和直觉。情感可能性和创意洞察的使者。",
    },
    reversed: {
      en: "Reversed: Emotional immaturity, blocked creativity, escapism.",
      es: "Invertida: Desilusión.",
      fr: "Inversé : Désillusion.",
      ja: "逆位置: 感情的な未熟さ、遮断された創造性、現実逃避。",
      ko: "역방향: 정서적 미성숙, 차단된 창의성, 현실 도피.",
      zh: "逆位：情感不成熟、创意受阻、逃避现实。",
    },
    suit: "Cups",
    symbol: "🐚",
    upright: {
      en: "Sensitivity, creativity, intuition, idealist",
      es: "Nuevas emociones.",
      fr: "Nouvelles émotions.",
      ja: "感受性、創造性、直感、理想主義",
      ko: "민감함, 창의성, 직관, 이상주의자",
      zh: "敏感、创造力、直觉、理想主义",
    },
  },
  page_of_pentacles: {
    lucideIcon: "User",
    narrative: {
      en: "Page of Pentacles: Ambition, desire, and new financial opportunities. A messenger of material potential and practical learning.",
      es: "Sota de Oros: Ambición, estudio.",
      fr: "Valet de Deniers : Ambition, étude.",
      ja: "ペンタクルのペイジ: 野心、欲求、そして新しい財政的機会. 物質的潜在力と実用的な学習のメッセンジャー.",
      ko: "펜타클 페이지: 야망, 열망, 새로운 재정적 기회. 물질적 잠재력과 실용적인 학습의 메신저.",
      zh: "星币侍从：抱负、欲望和新的财务机会. 物质潜力和实际学习的使者.",
    },
    reversed: {
      en: "Reversed: Lack of progress, procrastination, limited vision.",
      es: "Invertida: Falta de compromiso.",
      fr: "Inversé : Manque d'engagement.",
      ja: "逆位置: 進展の欠如、後回し、限られた視野。",
      ko: "역방향: 진전 부족, 미루는 습관, 제한된 안목.",
      zh: "逆位：缺乏进展、拖延、目光短浅。",
    },
    suit: "Pentacles",
    symbol: "📖",
    upright: {
      en: "Manifestation, financial opportunity, skill development",
      es: "Nuevas metas.",
      fr: "Nouveaux objectifs.",
      ja: "顕現、金銭的な機会、スキル開発",
      ko: "현현, 재정적 기회, 기술 개발",
      zh: "显化、财务机会、技能开发",
    },
  },
  page_of_swords: {
    lucideIcon: "User",
    narrative: {
      en: "Page of Swords: Curiosity, mental agility, and new ideas. A messenger of intellectual challenges and sharp insights.",
      es: "Sota de Espadas: Curiosidad, noticias.",
      fr: "Valet d'Épées : Curiosité, nouvelles.",
      ja: "ソードのペイジ: 好奇心、知的な敏捷性、そして新しいアイデア。知的な挑戦と鋭い洞察のメッセンジャー。",
      ko: "검 페이지: 호기심, 지적 민첩성, 새로운 아이디어. 지적 도전과 날카로운 통찰력의 메신저.",
      zh: "宝剑侍从：好奇心、思维敏捷和新想法。智力挑战和锐利洞察的使者。",
    },
    reversed: {
      en: "Reversed: Deception, manipulation, scattered thoughts.",
      es: "Invertida: Malas noticias.",
      fr: "Inversé : Mauvaises nouvelles.",
      ja: "逆位置: 欺瞞、操作、分散した思考。",
      ko: "역방향: 속임수, 조종, 분산된 생각.",
      zh: "逆位：欺骗、操纵、思绪混乱。",
    },
    suit: "Swords",
    symbol: "🪁",
    upright: {
      en: "Curiosity, mental agility, witty, talkative",
      es: "Ideas brillantes.",
      fr: "Idées brillantes.",
      ja: "好奇心、知的な敏捷性、機知に富む、おしゃべり",
      ko: "호기심, 지적 민첩성, 재치 있는, 수다스러운",
      zh: "好奇心、思维敏捷、机智、健谈",
    },
  },
  page_of_wands: {
    lucideIcon: "User",
    narrative: {
      en: "Page of Wands: Inspiration, ideas, and discovery. A messenger of potential and new creative ventures.",
      es: "Sota de Bastos: Inspiración.",
      fr: "Valet de Bâtons : Inspiration.",
      ja: "ワンドのペイジ: インスピレーション、アイデア、そして発見。可能性と新しい創造的なベンチャーのメッセンジャー。",
      ko: "지팡이 페이지: 영감, 아이디어, 발견. 잠재력과 새로운 창의적 벤처의 메신저.",
      zh: "权杖侍从：灵感、想法和发现。潜力和新创意冒险的使者。",
    },
    reversed: {
      en: "Reversed: Lack of direction, procrastination, setbacks.",
      es: "Invertida: Indecisión.",
      fr: "Inversé : Indécision.",
      ja: "逆位置: 方向性の欠如、後回し、挫折。",
      ko: "역방향: 방향성 부족, 미루는 습관, 좌절.",
      zh: "逆位：缺乏方向、拖延、挫折。",
    },
    suit: "Wands",
    symbol: "🧑‍🦯",
    upright: {
      en: "Inspiration, ideas, discovery, limitless potential",
      es: "Nuevas ideas.",
      fr: "Idées nouvelles.",
      ja: "インスピレーション、アイデア、発見、無限の可能性",
      ko: "영감, 아이디어, 발견, 무한한 잠재력",
      zh: "灵感、想法、发现、无限潜力",
    },
  },
  queen_of_cups: {
    lucideIcon: "Crown",
    narrative: {
      en: "Queen of Cups: Empathy, compassion, and intuitive depth. A nurturing presence who understands the mysteries of the heart.",
      es: "Reina de Copas: Empatía, intuición.",
      fr: "Reine de Coupes : Empathie, intuition.",
      ja: "カップのクイーン: 共感、慈悲、そして直感的な深さ。心の神秘を理解する、慈しみ深い存在です。",
      ko: "컵 퀸: 공감, 자비, 직관적 깊이. 마음의 신비를 이해하는 양육적인 존재.",
      zh: "圣杯王后：共情、慈悲和直觉深度。一位理解心灵奥秘的滋养者。",
    },
    reversed: {
      en: "Reversed: Overly sensitive, emotional insecurity, codependency.",
      es: "Invertida: Desequilibrio emocional.",
      fr: "Inversé : Déséquilibre émotionnel.",
      ja: "逆位置: 過敏、感情的な不安定、共依存。",
      ko: "역방향: 지나치게 민감함, 정서적 불안정, 상호 의존.",
      zh: "逆位：过度敏感、情感不安全、相互依赖。",
    },
    suit: "Cups",
    symbol: "🦢",
    upright: {
      en: "Empathy, compassion, intuitive, highly creative",
      es: "Compasión.",
      fr: "Compassion.",
      ja: "共感、慈悲、直感、高い創造性",
      ko: "공감, 자비, 직관, 뛰어난 창의성",
      zh: "共情、慈悲、直觉、极具创造力",
    },
  },
  queen_of_pentacles: {
    lucideIcon: "Crown",
    narrative: {
      en: "Queen of Pentacles: Multi-tasking, practical wisdom, and material comfort. A nurturing leader who balances home and career with grace.",
      es: "Reina de Oros: Generosidad, practicidad.",
      fr: "Reine de Deniers : Générosité, sens pratique.",
      ja: "ペンタクルのクイーン: マルチタスク, 実用的な知恵, そして物質的な快適さ. 家庭とキャリアを優雅に両立させる育成的なリーダー。",
      ko: "펜타클 퀸: 멀티태스킹, 실용적인 지혜, 물질적인 안락함. 가정과 경력을 우아하게 조화시키는 양육적인 리더.",
      zh: "星币王后：多任务处理、实际智慧和物质舒适. 一位优雅地平衡家庭与事业的滋养型领导者.",
    },
    reversed: {
      en: "Reversed: Work-life imbalance, isolation, smothering.",
      es: "Invertida: Desequilibrio material.",
      fr: "Inversé : Déséquilibre matériel.",
      ja: "逆位置: ワークライフバランスの乱れ、孤立、過干渉。",
      ko: "역방향: 일과 삶의 불균형, 고립, 지나친 간섭.",
      zh: "逆位：事业与生活失衡、孤立、窒息感。",
    },
    suit: "Pentacles",
    symbol: "🐇",
    upright: {
      en: "Practical, creature comforts, financial security",
      es: "Seguridad.",
      fr: "Sécurité.",
      ja: "実用的、生活の快適さ、経済的安定",
      ko: "실용적인, 물질적 안락함, 재정적 안정",
      zh: "务实、物质享受、财务安全",
    },
  },
  queen_of_swords: {
    lucideIcon: "Crown",
    narrative: {
      en: "Queen of Swords: Intellectual clarity, independence, and direct communication. A sharp-minded leader who values truth and objectivity.",
      es: "Reina de Espadas: Claridad mental, independencia.",
      fr: "Reine d'Épées : Clarté mentale, indépendance.",
      ja: "ソードのクイーン: 知的な明快さ、独立、そして直接的なコミュニケーション。真実と客観性を重んじる、鋭い知性のリーダーです。",
      ko: "검 퀸: 지적 명료함, 독립성, 직접적인 소통. 진실과 객관성을 중시하는 날카로운 지성의 리더.",
      zh: "宝剑王后：理智清晰、独立和直接沟通。一位重视真理和客观性的头脑敏锐的领导者。",
    },
    reversed: {
      en: "Reversed: Cold, critical, emotionally detached.",
      es: "Invertida: Resentimiento.",
      fr: "Inversé : Ressentiment.",
      ja: "逆位置: 冷淡、批判的、感情的な切り離し。",
      ko: "역방향: 냉담함, 비판적, 정서적으로 분리됨.",
      zh: "逆位：冷酷、挑剔、情感疏离。",
    },
    suit: "Swords",
    symbol: "🦉",
    upright: {
      en: "Complexity, unbiased, objective, sharp truth",
      es: "Sinceridad.",
      fr: "Sincérité.",
      ja: "複雑さ、偏見のない、客観的、鋭い真実",
      ko: "복잡성, 편견 없는, 객관적인, 날카로운 진실",
      zh: "复杂性、不偏不倚、客观、锋利的真相",
    },
  },
  queen_of_wands: {
    lucideIcon: "Crown",
    narrative: {
      en: "Queen of Wands: Confidence, independence, and social intelligence. A vibrant leader who inspires others through her warmth and strength.",
      es: "Reina de Bastos: Confianza, calidez.",
      fr: "Reine de Bâtons : Confiance, chaleur.",
      ja: "ワンドのクイーン: 自信、独立、そして社会的知性。温かさと強さで他者にインスピレーションを与える、活気あるリーダーです。",
      ko: "지팡이 퀸: 자신감, 독립성, 사회적 지성. 따뜻함과 강인함으로 타인에게 영감을 주는 활기찬 리더.",
      zh: "权杖王后：自信、独立和社交智慧。一位充满活力的领导者，通过她的温暖和力量激励他人。",
    },
    reversed: {
      en: "Reversed: Self-absorbed, jealous, manipulative leader.",
      es: "Invertida: Inseguridad.",
      fr: "Inversé : Insécurité.",
      ja: "逆位置: 自己中心的、嫉妬、操り人形のようなリーダー。",
      ko: "역방향: 자기중심적, 질투, 조종하는 리더.",
      zh: "逆位：自我中心、嫉妒、操纵型领导者。",
    },
    suit: "Wands",
    symbol: "🌻",
    upright: {
      en: "Confidence, independence, social butterfly, determinated",
      es: "Determinación.",
      fr: "Détermination.",
      ja: "自信、独立、社交性、決断力",
      ko: "자신감, 독립성, 사교성, 결단력",
      zh: "自信、独立、社交达人、果断",
    },
  },
  seven_of_cups: {
    lucideIcon: "Sparkle",
    narrative: {
      en: "Seven of Cups: Choices, daydreams, and illusion. Many options before you; some are real, and some are just fantasies.",
      es: "Siete de Copas: Opciones, fantasía.",
      fr: "Sept de Coupes : Choix, fantasme.",
      ja: "カップの7: 選択、白昼夢、そして幻想。目の前には多くの選択肢がありますが、中には現実のものもあれば、ただの空想に過ぎないものもあります。",
      ko: "컵 7: 선택, 백일몽, 환상. 당신 앞에 놓인 많은 선택지들 중 일부는 실제이고 일부는 환상일 뿐입니다.",
      zh: "圣杯七：选择、白日梦和幻象。面前有许多选择；有些是真实的，有些只是幻想。",
    },
    reversed: {
      en: "Reversed: Selection, priority, clarity, choosing a path.",
      es: "Invertida: Claridad en la elección.",
      fr: "Inversé : Clarté dans le choix.",
      ja: "逆位置: 選定、優先順位、明快さ、道を選ぶこと。",
      ko: "역방향: 선택, 우선순위, 명료함, 길 선택하기.",
      zh: "逆位：筛选、优先次序、清晰、选择路径。",
    },
    suit: "Cups",
    symbol: "✨",
    upright: {
      en: "Searching for purpose, choices, daydreams, illusion",
      es: "Muchas opciones.",
      fr: "Beaucoup de choix.",
      ja: "目的の探求、選択、白昼夢、幻想",
      ko: "목적 찾기, 선택, 백일몽, 환상",
      zh: "寻找目的、选择、白日梦、幻象",
    },
  },
  seven_of_pentacles: {
    lucideIcon: "Timer",
    narrative: {
      en: "Seven of Pentacles: Patience, investment, and sustainable results. Waiting for the harvest after long periods of hard work.",
      es: "Siete de Oros: Paciencia, recompensa.",
      fr: "Sept de Deniers : Patience, recompensa.",
      ja: "ペンタクルの7: 忍耐、投資、そして持続的な成果. 長い努力の末に収穫を待っています。",
      ko: "펜타클 7: 인내, 투자, 지속 가능한 결과. 오랜 노력 끝에 수확을 기다립니다.",
      zh: "星币七：耐心、投资和可持续成果. 在长期辛勤工作后等待收成.",
    },
    reversed: {
      en: "Reversed: Lack of reward, impatience, limited success.",
      es: "Invertida: Frustración.",
      fr: "Inversé : Frustration.",
      ja: "逆位置: 報酬の欠如、短気、限られた成功。",
      ko: "역방향: 보상 부족, 조바심, 제한적인 성공.",
      zh: "逆位：缺乏回报、不耐烦、成功有限。",
    },
    suit: "Pentacles",
    symbol: "🌱",
    upright: {
      en: "Hard work paying off, investment, sustainable results",
      es: "Patience.",
      fr: "Patience.",
      ja: "努力が実を結ぶ、投資、持続的な成果",
      ko: "노력이 결실을 맺음, 투자, 지속 가능한 결과",
      zh: "付出终有回报、投资、可持续成果",
    },
  },
  seven_of_swords: {
    lucideIcon: "Ghost",
    narrative: {
      en: "Seven of Swords: Deception, stealth, and strategic retreat. Trying to get away with something or taking a risk through cleverness.",
      es: "Siete de Espadas: Engaño, estrategia.",
      fr: "Sept d'Épées : Tromperie, stratégie.",
      ja: "ソードの7: 欺瞞、密かな行動、そして戦略的な撤退。巧妙な知恵を使って何かを回避しようとしたり、リスクを冒そうとしています。",
      ko: "검 7: 속임수, 잠행, 전략적 후퇴. 교묘한 지혜를 통해 무언가를 모면하려 하거나 위험을 감수합니다.",
      zh: "宝剑七：欺骗、潜行和战略撤退。试图蒙混过关或通过聪明才智冒险。",
    },
    reversed: {
      en: "Reversed: Confession, getting caught, coming clean.",
      es: "Invertida: Sinceridad.",
      fr: "Inversé : Sincérité.",
      ja: "逆位置: 告白、隠し事の発覚、潔白を証明すること。",
      ko: "역방향: 고백, 들통남, 결백을 밝힘.",
      zh: "逆位：忏悔、被当场抓获、坦白。",
    },
    suit: "Swords",
    symbol: "🥷",
    upright: {
      en: "Betrayal, deception, getting away with something, stealth",
      es: "Estrategia dudosa.",
      fr: "Stratégie douteuse.",
      ja: "裏切り、欺瞞、何かを回避すること、密かな行動",
      ko: "배신, 속임수, 모면함, 잠행",
      zh: "背叛、欺骗、蒙混过关、潜行",
    },
  },
  seven_of_wands: {
    lucideIcon: "Shield",
    narrative: {
      en: "Seven of Wands: Defensiveness, perseverance, and maintaining control. You are holding your ground against pressure.",
      es: "Siete de Bastos: Perseverancia, defensa.",
      fr: "Sept de Bâtons : Persévérance, défense.",
      ja: "ワンドの7: 防衛、忍耐、そして制御の維持。圧力を受けながらも、自らの立場を堅持しています。",
      ko: "지팡이 7: 방어적 태도, 인내, 통제 유지. 압력에 맞서 당신의 자리를 지키고 있습니다.",
      zh: "权杖七：防御、毅力和保持控制。你正顶住压力，坚守阵地。",
    },
    reversed: {
      en: "Reversed: Giving up, feeling overwhelmed, compromise.",
      es: "Invertida: Sentirse abrumado.",
      fr: "Inversé : Se sentir débordé.",
      ja: "逆位置: 諦め、圧倒される、妥協。",
      ko: "역방향: 포기, 압도당함, 타협.",
      zh: "逆位：放弃、感到不堪重负、妥协。",
    },
    suit: "Wands",
    symbol: "🛡️",
    upright: {
      en: "Perseverance, defense, maintaining control",
      es: "Perseverancia, proteger tu posición.",
      fr: "Persévérance, défense de sa position.",
      ja: "忍耐、防御、制御の維持",
      ko: "인내, 방어, 통제 유지",
      zh: "毅力、防御、保持控制",
    },
  },
  six_of_cups: {
    lucideIcon: "Flower",
    narrative: {
      en: "Six of Cups: Nostalgia, childhood memories, and innocence. Joy found in the past or simple acts of kindness.",
      es: "Seis de Copas: Nostalgia, inocencia.",
      fr: "Six de Coupes : Nostalgie, innocence.",
      ja: "カップの6: 郷愁、子供時代の思い出、そして純粋さ。過去や単純な親切の中に見出される喜び。",
      ko: "컵 6: 향수, 어린 시절의 기억, 순수함. 과거의 기억이나 단순한 친절에서 찾은 기쁨.",
      zh: "圣杯六：怀旧、童年回忆和天真。在过去或简单的善举中发现快乐。",
    },
    reversed: {
      en: "Reversed: Living in the past, stuck in nostalgia, moving forward.",
      es: "Invertida: Superar el pasado.",
      fr: "Inversé : Dépasser le passé.",
      ja: "逆位置: 過去に執着する、郷愁に囚われる、前進する。",
      ko: "역방향: 과거에 살기, 향수에 젖어있음, 앞으로 나아가기.",
      zh: "逆位：沉溺过去、陷入怀旧、向前看。",
    },
    suit: "Cups",
    symbol: "🌸",
    upright: {
      en: "Revisiting the past, childhood memories, innocence, joy",
      es: "Nostalgia positiva.",
      fr: "Nostalgie positive.",
      ja: "過去の再訪、子供時代の思い出、純真さ、喜び",
      ko: "과거 재방문, 어린 시절의 기억, 순수함, 기쁨",
      zh: "重温过去、童年回忆、天真、快乐",
    },
  },
  six_of_pentacles: {
    lucideIcon: "Handshake",
    narrative: {
      en: "Six of Pentacles: Generosity, charity, and sharing wealth. The cycle of giving and receiving is in balance.",
      es: "Seis de Oros: Generosidad, caridad.",
      fr: "Six de Deniers : Générosité, caridad.",
      ja: "ペンタクルの6: 寛大さ、慈善、 そして富の共有. 授受の循環がバランスを保っています。",
      ko: "펜타클 6: 관대함, 자선, 부의 공유. 주고받는 순환이 균형을 이룹니다.",
      zh: "星币六：慷慨、施舍和共享财富. 施与受的循环处于平衡之中.",
    },
    reversed: {
      en: "Reversed: Selfishness, stinginess, debts, misuse of power.",
      es: "Invertida: Injustice.",
      fr: "Inversé : Injustice.",
      ja: "逆位置: 利己主義、けち、負債、権力の乱用。",
      ko: "역방향: 이기심, 인색함, 부채, 권력 남용.",
      zh: "逆位：自私、吝啬、债务、权力滥用。",
    },
    suit: "Pentacles",
    symbol: "🤝",
    upright: {
      en: "Generosity, charity, sharing wealth, giving and receiving",
      es: "Generosidad.",
      fr: "Générosité.",
      ja: "寛大さ、慈善、富の共有、受け渡し",
      ko: "관대함, 자선, 부의 공유, 주고받기",
      zh: "慷慨、施舍、共享财富、施予受",
    },
  },
  six_of_swords: {
    lucideIcon: "Ship",
    narrative: {
      en: "Six of Swords: Transition, moving away, and finding calmer waters. Moving towards a more peaceful future after a difficult time.",
      es: "Seis de Espadas: Transición, aguas tranquilas.",
      fr: "Six d'Épées : Transition, eaux calmes.",
      ja: "ソードの6: 移行、立ち去ること、そして穏やかな場所へ。困難な時期を経て、より平和な未来へと進んでいます。",
      ko: "검 6: 전환, 떠남, 평온한 물가 찾기. 힘든 시간 이후 더 평화로운 미래를 향해 나아갑니다.",
      zh: "宝剑六：过渡、离开并在寻找更平静的水域。在困难时期后，正迈向更和平的未来。",
    },
    reversed: {
      en: "Reversed: Stuck in transition, emotional baggage, resistance to change.",
      es: "Invertida: Resistencia al cambio.",
      fr: "Inversé : Résistance au changement.",
      ja: "逆位置: 移行期から抜け出せない、感情のしこり、変化への抵抗。",
      ko: "역방향: 전환기에 갇힘, 감정적 짐, 변화에 대한 저항.",
      zh: "逆位：陷入过渡、情感包袱、抗拒改变。",
    },
    suit: "Swords",
    symbol: "🚣",
    upright: {
      en: "Transition, change, rite of passage, release",
      es: "Viaje necesario.",
      fr: "Voyage nécessaire.",
      ja: "移行、変化、通過礼儀、解放",
      ko: "전환, 변화, 통과의례, 놓아줌",
      zh: "过渡、改变、过关、释放",
    },
  },
  six_of_wands: {
    lucideIcon: "Trophy",
    narrative: {
      en: "Six of Wands: Victory, public recognition, and success. You are riding high on your achievements.",
      es: "Seis de Bastos: Victoria, reconocimiento público.",
      fr: "Six de Bâtons : Victoire, reconnaissance publique.",
      ja: "ワンドの6: 勝利、公の承認、そして成功。自らの功績を誇りとして前進しています。",
      ko: "지팡이 6: 승리, 대중의 인정, 성공. 당신은 성취를 통해 당당히 나아가고 있습니다.",
      zh: "权杖六：胜利、大众认可和成功。你正因成就而意气风发。",
    },
    reversed: {
      en: "Reversed: Fall from grace, ego issues, lack of recognition.",
      es: "Invertida: Falta de reconocimiento.",
      fr: "Inversé : Manque de reconnaissance.",
      ja: "逆位置: 失脚、エゴの問題、承認の欠如。",
      ko: "역방향: 추락, 자만심 문제, 인정 부족.",
      zh: "逆位：名声扫地、自我问题、缺乏认可。",
    },
    suit: "Wands",
    symbol: "🏆",
    upright: {
      en: "Success, public recognition, progress, self-confidence",
      es: "Éxito, victoria.",
      fr: "Succès, victoire.",
      ja: "成功、公の承認、進歩、自信",
      ko: "성공, 대중의 인정, 진보, 자신감",
      zh: "成功、大众认可、进展、自信",
    },
  },
  ten_of_cups: {
    lucideIcon: "Rainbow",
    narrative: {
      en: "Ten of Cups: Divine love, blissful relationships, and emotional harmony. The ultimate emotional fulfillment.",
      es: "Diez de Copas: Felicidad familiar, armonía.",
      fr: "Dix de Coupes : Bonheur familial, harmonie.",
      ja: "カップの10: 神聖な愛、至福の関係、そして感情的な調和。究極の感情的な充足。",
      ko: "컵 10: 신성한 사랑, 축복받은 관계, 정서적 조화. 궁극적인 정서적 성취.",
      zh: "圣杯十：神圣之爱、幸福的关系和情感和谐。最终的情感圆满。",
    },
    reversed: {
      en: "Reversed: Disconnected family, broken home, struggling relationships.",
      es: "Invertida: Desarmonía familiar.",
      fr: "Inversé : Disharmonie familiale.",
      ja: "逆位置: 疎遠になった家族、壊れた家庭、人間関係の悩み。",
      ko: "역방향: 단절된 가족, 깨진 가정, 어려움을 겪는 관계.",
      zh: "逆位：家庭疏离、家庭破裂、关系挣扎。",
    },
    suit: "Cups",
    symbol: "🌈",
    upright: {
      en: "Divine love, blissful relationships, harmony, alignment",
      es: "Felicidad plena.",
      fr: "Bonheur total.",
      ja: "神聖な愛、至福の関係、調和、アライメント",
      ko: "신성한 사랑, 축복받은 관계, 조화, 정렬",
      zh: "神圣之爱、幸福关系、和谐、一致",
    },
  },
  ten_of_pentacles: {
    lucideIcon: "Home",
    narrative: {
      en: "Ten of Pentacles: Wealth, inheritance, and family legacy. Long-term security and a sense of belonging to something lasting.",
      es: "Diez de Oros: Riqueza familiar, herencia.",
      fr: "Dix de Deniers : Richesse familiar, héritage.",
      ja: "ペンタクルの10: 富、相続、そして家族の遺産. 長期的な安定と、永続的なものへの帰属意識。",
      ko: "펜타클 10: 부, 유산, 가족의 가산. 장기적인 보안과 지속되는 공동체에 대한 소속감.",
      zh: "星币十：财富、继承和家族遗产. 长期安全感及对持久事物的归属感.",
    },
    reversed: {
      en: "Reversed: Family disputes over money, loss of tradition, financial ruin.",
      es: "Invertida: Inestabilidad.",
      fr: "Inversé : Inestabilidad.",
      ja: "逆位置: お金を巡る家族の争い、伝統の喪失、財政的破滅。",
      ko: "역방향: 돈 문제로 인한 가족 분쟁, 전통 상실, 재정적 파멸.",
      zh: "逆位：家庭财务纠纷、传统丧失、财务崩溃。",
    },
    suit: "Pentacles",
    symbol: "🏛️",
    upright: {
      en: "Wealth, inheritance, family legacy, business success",
      es: "Legado.",
      fr: "Héritage.",
      ja: "富、相続、家庭の遺産、ビジネスの成功",
      ko: "부, 유산, 가족의 유산, 사업적 성공",
      zh: "财富、继承、家族遗产、商业成功",
    },
  },
  ten_of_swords: {
    lucideIcon: "Skull",
    narrative: {
      en: "Ten of Swords: Betrayal, rock bottom, and painful endings. The worst is over; now you must pick yourself up and start anew.",
      es: "Diez de Espadas: Traición, derrota.",
      fr: "Dix d'Épées : Trahison, défaite.",
      ja: "ソードの10: 裏切り、どん底、そして苦痛を伴う終わり。最悪の事態は過ぎ去りました。これからは自分を奮い立たせ、新しく始める時です。",
      ko: "검 10: 배신, 최악의 상황, 고통스러운 끝. 최악의 상황은 지났습니다. 이제 다시 일어나 새로 시작해야 합니다.",
      zh: "宝剑十：背叛、跌至谷底和痛苦的结局。最糟糕的已经过去；现在你必须重新振作，从头开始。",
    },
    reversed: {
      en: "Reversed: Recovery, resisting the inevitable, avoiding ruin.",
      es: "Invertida: Reurgir de las cenizas.",
      fr: "Inversé : Renaître de ses cendres.",
      ja: "逆位置: 回復、不可避なことへの抵抗、破滅の回避。",
      ko: "역방향: 회복, 불가피한 것에 저항함, 파멸 회피.",
      zh: "逆位：恢复、抗拒不可避免、逃避毁灭。",
    },
    suit: "Swords",
    symbol: "💀",
    upright: {
      en: "Deep wounds, betrayal, loss, crisis",
      es: "Final doloroso.",
      fr: "Fin douloureuse.",
      ja: "深い傷、裏切り、喪失、危機",
      ko: "깊은 상처, 배신, 상실, 위기",
      zh: "深重伤害、背叛、损失、危机",
    },
  },
  ten_of_wands: {
    lucideIcon: "BaggageClaim",
    narrative: {
      en: "Ten of Wands: Burden, responsibility, and hard work. You are carrying a heavy load, almost at the end of the journey.",
      es: "Diez de Bastos: Carga, responsabilidad.",
      fr: "Dix de Bâtons : Fardeau, responsabilité.",
      ja: "ワンドの10: 負担、責任、そして重労働。重い荷を背負っていますが、旅の終わりはもうすぐです。",
      ko: "지팡이 10: 부담, 책임, 힘든 노동. 무거운 짐을 지고 있으며 여정의 거의 끝에 도달했습니다.",
      zh: "权杖十：负担、责任和辛勤工作。你背负着沉重的负担，几乎快到旅程的终点。",
    },
    reversed: {
      en: "Reversed: Burning out, avoiding responsibility, breakdown.",
      es: "Invertida: Estrés insoportable.",
      fr: "Inversé : Stress insoportable.",
      ja: "逆位置: 燃え尽き、責任逃れ、崩壊。",
      ko: "역방향: 번아웃, 책임 회피, 붕괴.",
      zh: "逆位：精疲力竭、逃避责任、崩溃。",
    },
    suit: "Wands",
    symbol: "🏋️",
    upright: {
      en: "Burden, extra responsibility, hard work, completion",
      es: "Mucha responsabilidad.",
      fr: "Trop de responsabilités.",
      ja: "負担、重責、重労働、完了",
      ko: "부담, 추가된 책임, 힘든 노동, 완성",
      zh: "负担、额外的责任、辛苦工作、完成",
    },
  },
  three_of_cups: {
    lucideIcon: "Users",
    narrative: {
      en: "Three of Cups: Celebration, friendship, and community. Joy shared with those you love.",
      es: "Tres de Copas: Celebración, amistad.",
      fr: "Trois de Coupes : Célébration, amitié.",
      ja: "カップの3: 祝い、友情、そしてコミュニティ。愛する人々との喜びの共有。",
      ko: "컵 3: 축하, 우정, 공동체. 사랑하는 사람들과 나누는 기쁨.",
      zh: "圣杯三：庆典、友谊和社群。与所爱之人共享喜悦。",
    },
    reversed: {
      en: "Reversed: Gossiping, isolation, overindulgence.",
      es: "Invertida: Aislamiento.",
      fr: "Inversé : Isolement.",
      ja: "逆位置: 噂話、孤立、過度な耽溺。",
      ko: "역방향: 가십, 고립, 과도한 탐닉.",
      zh: "逆位：流言蜚语、孤立、过度纵欲。",
    },
    suit: "Cups",
    symbol: "🥂",
    upright: {
      en: "Celebration, friendship, creativity, collaborations",
      es: "Celebración con amigos.",
      fr: "Célébration entre amis.",
      ja: "お祝い、友情、創造性、コラボレーション",
      ko: "축하, 우정, 창의성, 협업",
      zh: "庆典、友谊、创造力、协作",
    },
  },
  three_of_pentacles: {
    lucideIcon: "LayoutTemplate",
    narrative: {
      en: "Three of Pentacles: Teamwork, collaboration, and learning. Building something great through shared skills and dedication.",
      es: "Tres de Oros: Trabajo en equipo, habilidad.",
      fr: "Trois de Deniers : Travail d'équipe, compétence.",
      ja: "ペンタクルの3: チームワーク、コラボレーション、そして学習. 共有されたスキルと献身を通じて, 素晴らしいものを築き上げています.",
      ko: "펜타클 3: 팀워크, 협업, 학습. 공유된 기술과 헌신을 통해 위대한 것을 건설합니다.",
      zh: "星币三：团队合作、协作和学习. 通过共同的技能和奉献精神建设伟大的事业.",
    },
    reversed: {
      en: "Reversed: Lack of teamwork, poor workmanship, competition over collaboration.",
      es: "Invertida: Falta de coordinación.",
      fr: "Inversé : Manque de coordination.",
      ja: "逆位置: チームワークの欠如、粗末な仕事、協力ではなく競争。",
      ko: "역방향: 팀워크 부족, 서툰 솜씨, 협업 대신 경쟁.",
      zh: "逆位：缺乏团队合作、手艺不精、竞争而非协作。",
    },
    suit: "Pentacles",
    symbol: "🧱",
    upright: {
      en: "Teamwork, collaboration, learning, implementation",
      es: "Trabajo en equipo.",
      fr: "Travail d'équipe.",
      ja: "チームワーク、コラボレーション、学習、実行",
      ko: "팀워크, 협업, 학습, 실행",
      zh: "团队合作、协作、学习、执行",
    },
  },
  three_of_swords: {
    lucideIcon: "HeartCrack",
    narrative: {
      en: "Three of Swords: Heartbreak, sorrow, and emotional pain. A necessary release of grief before healing can begin.",
      es: "Tres de Espadas: Dolor emocional.",
      fr: "Trois d'Épées : Douleur émotionnelle.",
      ja: "ソードの3: 失恋、悲しみ、そして感情的な痛み。癒しが始まる前に必要な、悲しみの解放。",
      ko: "검 3: 비탄, 슬픔, 정서적 고통. 치유가 시작되기 전에 필요한 슬픔의 해소.",
      zh: "宝剑三：心碎、悲伤和情感痛苦。在治愈开始之前必要的悲伤释放。",
    },
    reversed: {
      en: "Reversed: Recovery, forgiveness, moving beyond pain.",
      es: "Invertida: Sanación.",
      fr: "Inversé : Guérison.",
      ja: "逆位置: 回復、許し、痛みを乗り越えること。",
      ko: "역방향: 회복, 용서, 고통 너머로 나아가기.",
      zh: "逆位：康复、原谅、超越痛苦。",
    },
    suit: "Swords",
    symbol: "💔",
    upright: {
      en: "Heartbreak, emotional pain, sorrow, grief",
      es: "Dolor.",
      fr: "Douleur.",
      ja: "失恋、感情的な痛み、悲しみ、嘆き",
      ko: "비탄, 정서적 고통, 슬픔, 애도",
      zh: "心碎、情感痛苦、悲伤、忧伤",
    },
  },
  three_of_wands: {
    lucideIcon: "Ship",
    narrative: {
      en: "Three of Wands: Expansion, foresight, and enterprise. Your ships are coming in; your plans are starting to bear fruit and you see the horizon.",
      es: "Tres de Bastos: Expansión, previsión.",
      fr: "Trois de Bâtons : Expansion, prévoyance.",
      ja: "ワンドの3: 拡大、先見の明、そして進取。あなたの船が入港しようとしています。計画が実を結び始め、地平線が見えてきます。",
      ko: "지팡이 3: 확장, 예견, 기업가 정신. 당신의 배들이 들어오고 있습니다. 당신의 계획이 결실을 맺기 시작하고 지평선이 보입니다.",
      zh: "权杖三：扩张、远见和进取。你的船只即将入港；你的计划开始开花结果，你看到了地平线。",
    },
    reversed: {
      en: "Reversed: Playing small, lack of foresight, delays in ships returning.",
      es: "Invertida: Falta de visión.",
      fr: "Inversé : Manque de clairvoyance.",
      ja: "逆位置: 小さくまとまる、先見の明の欠如、成果の遅れ。",
      ko: "역방향: 소극적인 태도, 예견 부족, 지연되는 성과.",
      zh: "逆位：畏首畏尾、缺乏远见、回报延迟。",
    },
    suit: "Wands",
    symbol: "🚢",
    upright: {
      en: "Expansion, foresight, overseas opportunities, enterprise",
      es: "Expansión, visión a largo plazo.",
      fr: "Expansion, vision à long terme.",
      ja: "拡大、先見の明、海外での機会、進取の気性",
      ko: "확장, 예견, 해외 기회, 기업가 정신",
      zh: "扩张、远见、海外机会、进取",
    },
  },
  two_of_cups: {
    lucideIcon: "Heart",
    narrative: {
      en: "Two of Cups: Unified love, partnership, and attraction. A deep connection between two souls.",
      es: "Dos de Copas: Unión, asociación.",
      fr: "Deux de Coupes : Union, partenariat.",
      ja: "カップの2: 統一された愛、パートナーシップ、そして惹かれ合い。二つの魂の間の深い結びつき。",
      ko: "컵 2: 통합된 사랑, 파트너십, 끌림. 두 영혼 사이의 깊은 연결.",
      zh: "圣杯二：统一的爱情、伙伴关系和吸引力。两个灵魂之间的深厚联系。",
    },
    reversed: {
      en: "Reversed: Breakups, disharmony, distrust.",
      es: "Invertida: Desarmonía.",
      fr: "Inversé : Disharmonie.",
      ja: "逆位置: 別れ、不調和、不信感。",
      ko: "역방향: 이별, 불협화음, 불신.",
      zh: "逆位：分手、失调、不信任。",
    },
    suit: "Cups",
    symbol: "💕",
    upright: {
      en: "Unified love, partnership, mutual attraction",
      es: "Amor compartido.",
      fr: "Amour partagé.",
      ja: "統一された愛、パートナーシップ、相互の惹きつけ",
      ko: "통합된 사랑, 파트너십, 상호 끌림",
      zh: "统一的爱情、伙伴关系、相互吸引",
    },
  },
  two_of_pentacles: {
    lucideIcon: "RotateCw",
    narrative: {
      en: "Two of Pentacles: Balance, adaptability, and multitasking. Juggling responsibilities and resources to stay afloat.",
      es: "Dos de Oros: Equilibrio, adaptabilidad.",
      fr: "Deux de Deniers : Équilibre, adaptabilidad.",
      ja: "ペンタクルの2: バランス、適応力、そしてマルチタスク。責任と資源をうまくやりくりし、安定を保とうとしています。",
      ko: "펜타클 2: 균형, 적응력, 멀티태스킹. 책임을 다하고 자원을 관리하며 균형을 유지합니다.",
      zh: "星币二：平衡、适应能力和多任务处理。在责任和资源之间寻找平衡以维持现状。",
    },
    reversed: {
      en: "Reversed: Disorganization, overwhelmed, messy finances.",
      es: "Invertida: Desequilibrio.",
      fr: "Inversé : Déséquilibre.",
      ja: "逆位置: 無秩序、圧倒される、乱れた財政。",
      ko: "역방향: 무질서, 압도당함, 엉망인 재정.",
      zh: "逆位：杂乱无章、不堪重负、财务混乱。",
    },
    suit: "Pentacles",
    symbol: "🤹",
    upright: {
      en: "Balance, adaptability, time management, prioritization",
      es: "Equilibrio.",
      fr: "Équilibre.",
      ja: "バランス、適応力、時間管理、優先順位",
      ko: "균형, 적응력, 시간 관리, 우선순위 설정",
      zh: "平衡、适应力、时间管理、优先级",
    },
  },
  two_of_swords: {
    lucideIcon: "Scan",
    narrative: {
      en: "Two of Swords: Indecision, stalemate, and blocked emotions. You are at a crossroads, unable or unwilling to see the path forward.",
      es: "Dos de Espadas: Indecisión.",
      fr: "Deux d'Épées : Indécision.",
      ja: "ソードの2: 優柔不断、行き詰まり、そして遮断された感情。岐路に立たされ、前進する道が見えない、あるいは見ようとしていない状態です。",
      ko: "검 2: 우유부단함, 교착 상태, 차단된 감정. 갈림길에 서서 앞으로 나아갈 길을 보지 못하거나 보려 하지 않고 있습니다.",
      zh: "宝剑二：犹豫不决、僵局和封闭的情感。你正处于十字路口，无法或不愿看到前方的道路。",
    },
    reversed: {
      en: "Reversed: Confusion, information overload, choosing a side.",
      es: "Invertida: Tomar una decisión.",
      fr: "Inversé : Prendre une décision.",
      ja: "逆位置: 混乱、情報の過多、立場の選択。",
      ko: "역방향: 혼란, 정보 과부하, 한쪽 선택하기.",
      zh: "逆位：混乱、信息过载、选择立场。",
    },
    suit: "Swords",
    symbol: "⚖️",
    upright: {
      en: "Indecision, choices, stalemate, blocked emotions",
      es: "Duda.",
      fr: "Doute.",
      ja: "優柔不断、選択、行き詰まり、遮断された感情",
      ko: "우유부단함, 선택, 교착 상태, 차단된 감정",
      zh: "犹豫不决、选择、僵局、情感受阻",
    },
  },
  two_of_wands: {
    lucideIcon: "Compass",
    narrative: {
      en: "Two of Wands: Planning, future moves, and discovery. You are looking out from your castle, deciding where to take your creative energy next.",
      es: "Dos de Bastos: Planificación, decisiones futuras.",
      fr: "Deux de Bâtons : Planification, mouvements futurs.",
      ja: "ワンドの2: 計画、将来の動き、そして発見。城から外を見渡し、自らの創造的なエネルギーを次にどこへ向けるべきか決めています。",
      ko: "지팡이 2: 계획, 미래의 움직임, 발견. 당신은 성에서 밖을 내다보며 당신의 창의전 에너지를 어디로 가져갈지 결정하고 있습니다.",
      zh: "权杖二：规划、未来举动和发现。你从城堡向外眺望，决定下一步将创造能量带向何处。",
    },
    reversed: {
      en: "Reversed: Fear of the unknown, lack of planning, playing safe.",
      es: "Invertida: Miedo a lo desconocido.",
      fr: "Inversé : Peur de l'inconnu.",
      ja: "逆位置: 未知への恐怖、計画不足、無難な行動。",
      ko: "역방향: 미지에 대한 두려움, 계획 부족, 안전제일.",
      zh: "逆位：对未知的恐惧、缺乏规划、保守行事。",
    },
    suit: "Wands",
    symbol: "🗺️",
    upright: {
      en: "Future planning, progress, decisions, discovery",
      es: "Planificación futura, progreso.",
      fr: "Planification future, progrès.",
      ja: "将来の計画、進歩、決定、発見",
      ko: "미래 계획, 진보, 결정, 발견",
      zh: "未来规划、进展、决定、发现",
    },
  },
};
