import type { SixLangString } from "../engine.contract";

/**
 * ZiWei Shard Data
 * Palaces and Bureau element narratives separated from logic.
 */

export const PALACE_NARRATIVES: Record<string, SixLangString> = {
  career: {
    en: "Career Palace (官禄宫): Professional aptitude, status, and leadership style.",
    es: "Palacio de Carrera (官祿宮): Aptitud profesional y estatus.",
    fr: "Palais de la Carrière (官祿宮) : Aptitude professionnelle et statut.",
    ja: "官禄宮 (官禄宮): 職業的適性、地位、リーダーシップスタイル。",
    ko: "관록궁(官祿宮): 직업적 적성, 지위 및 리더십 스타일.",
    zh: "官禄宫：职业适性、地位和领导风格。",
  },
  children: {
    en: "Children Palace (子女宫): Success, nature, and relationship with descendants. Also reflects creative output and subordinates.",
    es: "Palacio de los Hijos (子女宫): Éxito, naturaleza y relación con los descendientes.",
    fr: "Palais des Enfants (子女宫) : Succès, nature et relation avec les descendants.",
    ja: "子女宮 (子女宮): 子供の成功、性質、関係。また、創造的な成果や部下も反映します。",
    ko: "자녀궁(子女宮): 자녀의 성공, 성격 및 관계. 또한 창의적 결과물과 부하 직원을 반영합니다.",
    zh: "子女宫：后代的成功、性质和关系。也反映创作产出和下属。",
  },
  friends: {
    en: "Friends Palace (奴仆宫): Relationships with employees, subordinates, and general social circles.",
    es: "Palacio de Amigos (奴仆宫): Relaciones con empleados y círculos sociales.",
    fr: "Palais des Amis (奴仆宫) : Relations avec les employés et les cercles sociaux.",
    ja: "奴僕宮 (奴僕宮): 従業員、部下、および一般的な社交界との関係。",
    ko: "노복궁(奴僕宮): 고용인, 하급자 및 일반적인 사회적 서클과의 관계.",
    zh: "交友宫：与雇员、下属及一般社交圈的关系。",
  },
  happiness: {
    en: "Happiness Palace (福德宫): Mental state, spiritual well-being, and internal contentment.",
    es: "Palacio de Felicidad (福德宫): Estado mental y bienestar espiritual.",
    fr: "Palais du Bonheur (福德宫) : État mental et bien-être spirituel.",
    ja: "福徳宮 (福徳宮): 精神状態、精神的幸福、内なる満足感。",
    ko: "복덕궁(福德宮): 정신 상태, 영적 안녕 및 내적 만족.",
    zh: "福德宫：精神状态、精神健康和内在满足感。",
  },
  health: {
    en: "Health Palace (疾厄宫): Physical constitution, potential ailments, and latent hidden problems.",
    es: "Palacio de Salud (疾厄宫): Constitución física y dolencias potenciales.",
    fr: "Palais de la Santé (疾厄宫) : Constitution physique et maux potentiels.",
    ja: "疾厄宮 (疾厄宮): 身体的体質、潜在的な病気、潜在的な隠れた問題。",
    ko: "질액궁(疾厄宮): 신체적 체질, 잠재적 질병 및 숨겨진 잠재적 문제.",
    zh: "疾厄宫：身体体质、潜在疾病和潜伏的隐藏问题。",
  },
  life: {
    en: "Life Palace (命宫): The core of your destiny. This palace reveals your fundamental nature, appearance, and overall trajectory.",
    es: "Palacio de Vida (命宮): El núcleo de su destino. Revela su naturaleza fundamental, apariencia y trayectoria.",
    fr: "Palais de la Vie (命宮) : Le cœur de votre destin. Ce palais révèle votre nature fondamentale, votre apparence et votre trajectoire.",
    ja: "命宮 (命宮): 運命の核心。根本的な本質、外見、人生の全体的な軌跡を明らかにします。",
    ko: "명궁(命宮): 운명의 핵심. 근본적인 본성, 외모, 인생 전체의 궤적을 드러냅니다.",
    zh: "命宫：命运的核心。揭示你的根本本性、外貌和人生整体轨迹。",
  },
  parents: {
    en: "Parents Palace (父母宫): Relationship with parents, authorities, and ancestral heritage.",
    es: "Palacio de Padres (父母宫): Relación con los padres y autoridades.",
    fr: "Palais des Parents (父母宫) : Relations avec les parents et les autorités.",
    ja: "父母宮 (父母宮): 両親、権威、先祖代々の遺産との関係。",
    ko: "부모궁(父母宮): 부모님, 권위자 및 조상의 유산과의 관계.",
    zh: "父母宫：与父母、权威及祖先遗产的关系。",
  },
  property: {
    en: "Property Palace (田宅宫): Real estate, domestic environment, and ancestral inheritance.",
    es: "Palacio de Propiedad (田宅宫): Bienes raíces y entorno doméstico.",
    fr: "Palais de la Propriété (田宅宫) : Immobilier et environnement domestique.",
    ja: "田宅宮 (田宅宮): 不動産、家庭環境、先祖からの継承。",
    ko: "전택궁(田宅宮): 부동산, 가정 환경 및 조상의 유산.",
    zh: "田宅宫：房地产、家庭环境和祖先遗产。",
  },
  siblings: {
    en: "Siblings Palace (兄弟宫): Relationships with brothers, sisters, and close peers. Indicates mutual support and early life social environment.",
    es: "Palacio de Hermanos (兄弟宮): Relaciones con hermanos y compañeros cercanos.",
    fr: "Palais des Frères et Sœurs (兄弟宮) : Relations avec les frères, les sœurs et les pairs proches.",
    ja: "兄弟宮 (兄弟宮): 兄弟、姉妹、親しい仲間との関係。相互支援と初期の社交環境を示します。",
    ko: "형제궁(兄弟宮): 형제, 자매 및 가까운 동료와의 관계. 상호 지원과 초기 사교 환경을 나타냅니다.",
    zh: "兄弟宫：与兄弟姐妹及亲近同辈的关系。表示相互支持和早期生活社交环境。",
  },
  spouse: {
    en: "Spouse Palace (夫妻宫): Marriage and primary partnerships. Reveals the nature of your partner and romantic quality.",
    es: "Palacio del Cónyuge (夫妻宮): Matrimonio y relaciones principales.",
    fr: "Palais du Conjoint (夫妻宮) : Mariage et partenariats principaux.",
    ja: "夫妻宮 (夫妻宮): 結婚と主要なパートナーシップ。パートナーの性質と恋愛の質を明らかにします。",
    ko: "부처궁(夫妻宮): 결혼과 주요 파트너십. 배우자의 성격과 연애의 질을 드러냅니다.",
    zh: "夫妻宫：婚姻和主要伴侣关系。揭示伴侣的性质和恋爱质量。",
  },
  travel: {
    en: "Travel Palace (迁移宫): Mobility, travel, and social reputation outside your home environment.",
    es: "Palacio de Viajes (迁移宫): Movilidad, viajes y reputación social externa.",
    fr: "Palais du Voyage (迁移宫) : Mobilité, voyages et réputation sociale extérieure.",
    ja: "遷移宮 (遷移宮): 移動性、旅行、および家庭外での社会的評判。",
    ko: "천이궁(遷移宮): 이동성, 여행 및 집 밖에서의 사회적 평판.",
    zh: "迁移宫：流动性、旅行以及在家庭环境外的社会声誉。",
  },
  wealth: {
    en: "Wealth Palace (财帛宫): Financial capacity, earning style, and relationship with material resources.",
    es: "Palacio de Riqueza (財帛宮): Capacidad financiera y estilo de ingresos.",
    fr: "Palais de la Richesse (財帛宮) : Capacité financière et style de gain.",
    ja: "財帛宮 (財帛宮): 財務能力、収益スタイル、物質的資源との関係。",
    ko: "재백궁(財帛宮): 재정적 능력, 수익 스타일 및 물질적 자원과의 관계.",
    zh: "财帛宫：财务能力、赚钱风格以及与物质资源的关系。",
  },
};

export const BUREAU_NARRATIVES: Record<string, SixLangString> = {
  earth: {
    en: "Earth Bureau: Your life is built on stability, nurturing, and patience. Like the fertile soil, you support others and create lasting foundations.",
    es: "Bureau de Tierra: Tu vida se construye sobre la estabilidad, el cuidado y la paciencia.",
    fr: "Bureau de la Terre : Votre vie est bâtie sur la stabilité, l'éducation et la patience. Comme un sol fertile, vous soutenez les autres et créez des fondations durables.",
    ja: "土局：あなたの人生は安定、育成、そして忍耐の上に築かれます。肥沃な土壌のように、他者を支え永続的な基盤を作ります。",
    ko: "토국(土局): 당신의 인생은 안정, 양육, 그리고 인내 위에 세워집니다. 비옥한 토양처럼, 다른 사람들을 지지하고 지속적인 기반을 만듭니다.",
    zh: "土局：你的人生建立在稳定、养育和耐心之上。如同肥沃的土壤，你支持他人并创造持久的基础。",
  },
  fire: {
    en: "Fire Bureau: Your life burns with passion, visibility, and transformation. Like flame, you illuminate and inspire, but must manage your energy wisely.",
    es: "Bureau de Fuego: Tu vida arde con pasión, visibilidad y transformación.",
    fr: "Bureau du Feu : Votre vie brûle de passion, de visibilité et de transformation. Comme une flamme, vous illuminez et inspirez, mais vous devez gérer votre énergie avec sagesse.",
    ja: "火局：あなたの人生は情熱、注目、そして変化とともに燃え上がります。炎のように周囲を照らしインスピレーションを与えますが、エネルギーを賢く管理する必要があります。",
    ko: "화국(火局): 당신의 인생은 열정, 가시성, 그리고 변화로 불타오릅니다. 불꽃처럼 조명하고 영감을 주지만, 에너지를 현명하게 관리해야 합니다.",
    zh: "火局：你的人生充满激情、可见性和转化。如同火焰，你照亮并激励他人，但必须明智地管理你的能量。",
  },
  metal: {
    en: "Metal Bureau: Your life is refined through clarity, precision, and boundaries. Like precious metal, you gain value through refinement and discernment.",
    es: "Bureau de Metal: Tu vida se refina a través de la claridad, la precisión y los límites.",
    fr: "Bureau du Métal : Votre vie s'affine par la clarté, la précision et les limites. Comme un métal précieux, vous gagnez de la valeur par le raffinement et le discernement.",
    ja: "金局：あなたの人生は明快さ、精密さ、そして境界を通じて洗練されます。貴金属のように、洗練と洞察を通じて価値を高めます。",
    ko: "금국(金局): 당신의 인생은 명료함, 정밀함, 그리고 경계를 통해 정제됩니다. 귀금속처럼, 정제와 분별을 통해 가치를 얻습니다.",
    zh: "金局：你的人生通过清晰、精确和界限得到精炼。如同贵金属，你通过精炼和辨别获得价值。",
  },
  water: {
    en: "Water Bureau: Your life flows with wisdom, adaptability, and depth. Like water finding its level, you navigate life through intuition and strategic flexibility.",
    es: "Bureau de Agua: Tu vida fluye con sabiduría, adaptabilidad y profundidad.",
    fr: "Bureau de l'Eau : Votre vie s'écoule avec sagesse, adaptabilité et profondeur. Comme l'eau qui trouve son niveau, vous naviguez dans la vie grâce à l'intuition et à la flexibilité stratégique.",
    ja: "水局：あなたの人生は知恵、適応力、そして深みとともに流れます。水平を見つける水のように、直感と戦略的な柔軟性を持って人生を航海します。",
    ko: "수국(수국): 당신의 인생은 지혜, 적응력, 그리고 깊이로 흐릅니다. 수평을 찾는 물처럼, 직관과 전략적 유연성으로 삶을 항해합니다.",
    zh: "水局：你的人生以智慧、适应性和深度流动。如同寻找水平的水，你通过直觉和战略灵活性驾驭人生。",
  },
  wood: {
    en: "Wood Bureau: Your life unfolds through growth, expansion, and benevolence. Like a tree reaching for the sun, you thrive through steady upward progress.",
    es: "Bureau de Madera: Tu vida se desarrolla a través del crecimiento, la expansión y la benevolencia.",
    fr: "Bureau du Bois : Votre vie se déroule à travers la croissance, l'expansion et la bienveillance. Comme un arbre tendant vers le soleil, vous prospérez grâce à un progrès constant vers le haut.",
    ja: "木局：あなたの人生は成長、拡大、そして慈愛を通じて展開します。太陽に向かって伸びる木のように、一歩一歩着実な成長を通じて繁栄します。",
    ko: "목국(木局): 당신의 인생은 성장, 확장, 그리고 자비를 통해 펼쳐집니다. 태양을 향해 뻗어가는 나무처럼, 꾸준한 상향 진전을 통해 번성합니다.",
    zh: "木局：你的人生通过成长、扩展和仁慈展开。如同向着太阳伸展的树木，你通过稳定的向上进步而繁荣。",
  },
};

export const MAIN_STAR_NARRATIVES: Record<string, SixLangString> = {
  ju_men: {
    en: "Ju Men (The Great Gate): Eloquence, research, and analytical depth. You possess the power of speech but may face skepticism from others.",
    es: "Ju Men (La Gran Puerta): Elocuencia, investigación y profundidad analítica.",
    fr: "Ju Men (La Grande Porte) : Éloquence, recherche et profondeur analytique.",
    ja: "巨門 (巨門): 雄弁、研究、分析の深さ。言葉の力を持っていますが、他者から疑念を抱かれる可能性もあります。",
    ko: "거문(巨門): 웅변, 연구, 분석적 깊이. 언어의 힘을 가졌으나 타인으로부터 시비나 의구심을 받을 수 있습니다.",
    zh: "巨门（口舌之星）：雄辩、研究和分析深度。你拥有言语的力量，但也可能面临他人的猜疑。",
  },
  lian_zhen: {
    en: "Lian Zhen (The Judge): Intensity, ambition, and creative talent. You possess strong desires and the power to influence others directly.",
    es: "Lian Zhen (El Juez): Intensidad, ambición y talento creativo.",
    fr: "Lian Zhen (Le Juge) : Intensité, ambition et talent créatif.",
    ja: "廉貞 (判官): 強烈さ、野心、創造的な才能。強い欲求と他者に直接影響を与える力を持っています。",
    ko: "염정(廉貞): 강렬함, 야망, 창의적 재능. 강한 욕구와 타인에게 직접적인 영향을 주는 힘을 지니고 있습니다.",
    zh: "廉贞（囚星）：强度、野心和创造才华。你拥有强烈的欲望和直接影响他人的力量。",
  },
  po_jun: {
    en: "Po Jun (The Army Breaker): Innovation, destruction, and pioneers. You possess the power to reform and rebuild, often breaking tradition.",
    es: "Po Jun (El Rompe Ejércitos): Innovación, destrucción y pioneros.",
    fr: "Po Jun (Le Briseur d'Armée) : Innovation, destruction et pionniers.",
    ja: "破軍 (破軍): 革新、破壊、先駆者。伝統を打ち破り、改革・再建する力を持っています。",
    ko: "파군(破軍): 혁신, 파괴, 개척자. 전통을 깨고 개혁하며 재건하는 힘을 지니고 있습니다.",
    zh: "破军（耗星）：创新、破坏和先锋。你拥有改革和重建的力量，常打破传统。",
  },
  qi_sha: {
    en: "Qi Sha (The 7 Killings): Independence, courage, and breakthrough. You are a risk-taker who thrives through overcoming major challenges.",
    es: "Qi Sha (Los 7 Asesinatos): Independencia, coraje e innovación.",
    fr: "Qi Sha (Les 7 Meurtres) : Indépendance, courage et percée.",
    ja: "七殺 (七殺): 独立性、勇気、突破口。リスクを冒し、大きな課題を克服することで成長します。",
    ko: "칠살(七殺): 독립성, 용기, 돌파력. 위험을 감수하며 중대한 도전을 극복함으로써 번성합니다.",
    zh: "七杀（将星）：独立、勇气和突破。你是一个冒险者，通过克服重大挑战而壮大。",
  },
  tai_yang: {
    en: "Tai Yang (The Sun): Radiance, generosity, and public service. You are driven to illuminate others and thrive in visible roles.",
    es: "Tai Yang (El Sol): Resplandor, generosidad y servicio público.",
    fr: "Tai Yang (Le Soleil) : Éclat, générosity et service public.",
    ja: "太陽 (太陽): 輝き、寛大さ、公共サービス。他者を照らしたいという意欲があり、目立つ役割で成功します。",
    ko: "태양(太陽): 광채, 관대함, 공공 서비스. 타인을 비추고자 하는 열망이 있으며 명성이 따르는 역할에서 번성합니다.",
    zh: "太阳（阳火）：光辉、慷慨和公共服务。你渴望照亮他人，在显赫的角色中表现出色。",
  },
  tai_yin: {
    en: "Tai Yin (The Moon): Intuition, gentleness, and artistic sensibility. You are receptive and possess a deep internal emotional world.",
    es: "Tai Yin (La Luna): Intuición, gentileza y sensibilidad artística.",
    fr: "Tai Yin (La Lune) : Intuition, douceur et sensibilité artistique.",
    ja: "太陰 (月): 直感、優しさ、芸術的感性。受容的で、深い内面的な感情の世界を持っています。",
    ko: "태음(太陰): 직관, 부드러움, 예술적 감수성. 수용적이며 깊은 내면의 정서 세계를 가지고 있습니다.",
    zh: "太阴（阴水）：直觉、温柔和艺术敏感。你很感性，拥有深刻的内心世界。",
  },
  tan_lang: {
    en: "Tan Lang (The Wolf): Social charm, desire, and spiritual growth. You are multifaceted, seeking both material pleasure and occult wisdom.",
    es: "Tan Lang (El Lobo): Carisma social, deseo y crecimiento espiritual.",
    fr: "Tan Lang (Le Loup) : Charme social, désir et croissance spirituelle.",
    ja: "貪狼 (狼): 社交的な魅力、欲求、精神的な成長。多才で、物質的な快楽と神秘的な知恵の両方を求めています。",
    ko: "탐랑(貪狼): 사교적 매력, 욕망, 영적 성장. 다재다능하며 물질적 즐거움과 신비로운 지혜를 동시에 추구합니다.",
    zh: "贪狼（欲望之星）：社交魅力、欲望和灵性成长。你多才多艺，兼求物质享受与玄学智慧。",
  },
  tian_fu: {
    en: "Tian Fu (The Treasury): Abundance, stability, and conservative management. You are a keeper of resources and value security.",
    es: "Tian Fu (La Tesorería): Abundancia, estabilidad y gestión conservadora.",
    fr: "Tian Fu (Le Trésor) : Abondance, stabilité et gestion conservatrice.",
    ja: "天府 (宝庫): 豊かさ、安定、保守的な管理。資源の管理者であり、安全を大切にします。",
    ko: "천부(天府): 풍요, 안정, 보수적 관리. 자원의 관리자이며 보안과 안정을 중시합니다.",
    zh: "天府（库星）：丰盈、稳定和保守管理。你是资源的守护者，注重安全感。",
  },
  tian_ji: {
    en: "Tian Ji (The Advisor): Intelligence, strategy, and adaptability. Your mind is quick and analytical, ideal for problem-solving.",
    es: "Tian Ji (El Asesor): Inteligencia, estrategia y adaptabilidad.",
    fr: "Tian Ji (L'Conseiller) : Intelligence, stratégie et adaptabilité.",
    ja: "天機 (参謀): 知性、戦略、適応力。機敏で分析的な思考を持ち、問題解決に理想的です。",
    ko: "천기(天機): 지혜, 책략, 적응력. 명석하고 분석적인 두뇌를 가졌으며 문제 해결에 탁월합니다.",
    zh: "天机（智星）：智慧、谋略和适应力。你思维敏捷，擅长分析和解决问题。",
  },
  tian_liang: {
    en: "Tian Liang (The Sage): Wisdom, protection, and longevity. You possess a natural authority and often act as a mentor or protector.",
    es: "Tian Liang (El Sabio): Sabiduría, protección y longevidad.",
    fr: "Tian Liang (Le Sage) : Sagesse, protection et longévité.",
    ja: "天梁 (賢者): 知恵、保護、長寿。自然な権威を持ち、しばしばメンターや保護者として行動します。",
    ko: "천량(天梁): 지혜, 보호, 장수. 타고난 권위가 있으며 멘토나 보호자 역할을 수행하곤 합니다.",
    zh: "天梁（荫星）：智慧、保护和长寿。你拥有天然的权威，常担任导师或保护者的角色。",
  },
  tian_tong: {
    en: "Tian Tong (The Child): Emotional enjoyment, harmony, and luck. You value peace and simple pleasures, often blessed with good fortune.",
    es: "Tian Tong (El Niño): Disfrute emocional, armonía y suerte.",
    fr: "Tian Tong (L'Enfant) : Plaisir émotionnel, harmonie et chance.",
    ja: "天同 (子供): 感情的な楽しみ、調和、幸運。平和と単純な喜びを大切にし、しばしば幸運に恵まれます。",
    ko: "천동(天同): 감정적 즐거움, 조화, 행운. 평화와 소박한 즐거움을 소중히 여기며 행운이 따르는 편입니다.",
    zh: "天同（福星）：情绪享受、和谐和运气。你注重和平与简单的追求，常得幸运行运。",
  },
  tian_xiang: {
    en: "Tian Xiang (The Minister): Cooperation, service, and balance. You are a bridge-builder who values harmony and ethical conduct.",
    es: "Tian Xiang (El Ministro): Cooperación, servicio y equilibrio.",
    fr: "Tian Xiang (Le Ministre) : Coopération, service et équilibre.",
    ja: "天相 (宰相): 協力、奉仕、バランス。調和と倫理的な行動を大切にする架け橋のような存在です。",
    ko: "천상(天相): 협력, 봉사, 균형. 조화와 윤리적 행동을 중시하는 가교 역할을 합니다.",
    zh: "天相（印星）：合作、服务和平衡。你是一个桥梁构建者，重视和谐和道德准则。",
  },
  wu_qu: {
    en: "Wu Qu (The General): Decisiveness, financial acumen, and discipline. You are action-oriented and excel in material management.",
    es: "Wu Qu (El General): Decisión, perspicacia financiera y disciplina.",
    fr: "Wu Qu (Le Général) : Décision, sens financier et discipline.",
    ja: "武曲 (将軍): 決断力、財務的洞察力、規律。行動指向で、物質的な管理に長けています。",
    ko: "무곡(武曲): 결단력, 재정적 감각, 규율. 실행 중심적이며 물질적 관리에 뛰어납니다.",
    zh: "武曲（财星）：果断、财商和纪律。你以行动为导向，擅长物质管理。",
  },
  zi_wei: {
    en: "Zi Wei (The Emperor): Leadership, authority, and nobility. You possess a regal presence and natural management abilities.",
    es: "Zi Wei (El Emperador): Liderazgo, autoridad y nobleza.",
    fr: "Zi Wei (L'Empereur) : Leadership, autorité et noblesse.",
    ja: "紫微 (帝王): リーダーシップ、権威、気高さ。威厳のある存在感と天性の管理能力を備えています。",
    ko: "자미(紫微): 리더십, 권위, 고귀함. 제왕의 품격과 타고난 경영 능력을 지니고 있습니다.",
    zh: "紫微（帝星）：领导力、权威和高贵。你拥有王者气派和天赋的管理能力。",
  },
};
