import type { SixLangString } from "../../interpretation/engine.contract";

export const ENNEAGRAM_CORE_NARRATIVES: Record<string, SixLangString> = {
  type1: {
    en: "A seeker of perfection, you carry the heavy burden of idealism. Your soul yearns for a world that matches your internal blueprint of righteousness.",
    es: "Buscador de la perfección, llevas la pesada carga del idealismo. Tu alma anhela un mundo que coincida con tu plano interno de rectitud.",
    fr: "Chercheur de perfection, vous portez le lourd fardeau de l'idéalisme. Votre âme aspire à un monde qui correspond à votre plan interne de droiture.",
    ja: "完璧を追求する探求者よ、あなたは理想主義という重い荷を背負っています。あなたの魂は、内なる正義の青写真に一致する世界を切望しています。",
    ko: "완벽을 추구하는 구도자여, 당신은 이상주의라는 무거운 짐을 지고 있습니다. 당신의 영혼은 내면의 정의로운 청사진과 일치하는 세상을 갈망합니다.",
    zh: "完美的追求者，你肩负着理想主义的重担。你的灵魂向往一个符合你内心正义蓝图的世界。",
  },
  type2: {
    en: "The heart of the collective, you exist in the connections between people. Your love is a force of nature, though you must learn to receive as freely as you give.",
    es: "El corazón de la colectividad, existes en las conexiones entre las personas. Tu amor es una fuerza de la naturaleza, aunque debes aprender a recibir tan libremente como das.",
    fr: "Le cœur de la collectivité, vous existez dans les connexions entre les personnes. Votre amour est une force de la nature, bien que vous deviez apprendre à recevoir aussi librement que vous donnez.",
    ja: "共同体の心よ、あなたは人と人との繋がりの間に存在します。あなたの愛は自然の力ですが、与えるのと同じくらい自由に受け取ることも学ばなければなりません。",
    ko: "공동체의 심장이여, 당신은 사람과 사람 사이의 연결 속에 존재합니다. 당신의 사랑은 거대한 힘이지만, 주는 만큼 자유롭게 받는 법도 배워야 합니다.",
    zh: "集体的心脏，你存在于人与人之间的连接中。你的爱是一种自然的力量，尽管你必须学会像慷慨给予一样自由地接受。",
  },
  type3: {
    en: "The shaper of reality, you turn dreams into tangible success. You are the architect of your own destiny, constantly refining your masterpiece.",
    es: "El modelador de la realidad, conviertes los sueños en éxito tangible. Eres el arquitecto de tu propio destino, perfeccionando constantemente tu obra maestra.",
    fr: "Le façonneur de réalité, vous transformez les rêves en succès tangible. Vous êtes l'architecte de votre propre destin, affinant constamment votre chef-d'œuvre.",
    ja: "現実の形成者よ、あなたは夢を目に見える成功へと変えます。あなたは自らの運命の設計者であり、絶えず自らの傑作を磨き上げています。",
    ko: "현실의 조각가여, 당신은 꿈을 만질 수 있는 성공으로 바꿉니다. 당신은 스스로의 운명을 설계하는 건축가이며, 끊임없이 자신의 걸작을 다듬습니다.",
    zh: "现实的塑造者，你将梦想变为切实的成功。你是你命运的建筑师，不断完善你的杰作。",
  },
  type4: {
    en: "The poet of the soul, you navigate the depths that others fear. Your authenticity is your greatest gift, bringing beauty to the sorrow of the world.",
    es: "El poeta del alma, navegas por las profundidades que otros temen. Tu autenticidad es tu mayor regalo, aportando belleza al dolor del mundo.",
    fr: "Le poète de l'âme, vous naviguez dans les profondeurs que les autres craignent. Votre authenticité est votre plus grand cadeau, apportant de la beauté à la tristesse du monde.",
    ja: "魂の詩人よ、あなたは他者が恐れる深淵を航海します。あなたの真正性は最大の贈り物であり、世界の悲しみに美しさをもたらします。",
    ko: "영혼의 시인이여, 당신은 타인이 두려워하는 심연을 항해합니다. 당신의 진정성은 가장 큰 선물이며, 세상의 슬픔에 아름다움을 부여합니다.",
    zh: "灵魂的诗人，你航行在他人恐惧的深处。你的真实是你最大的礼物，为世界的忧伤带来美丽。",
  },
  type5: {
    en: "The observer of the void, you seek safety in understanding. Your mind is a fortress, accumulating the wisdom necessary to navigate existence.",
    es: "El observador del vacío, buscas seguridad en la comprensión. Tu mente es una fortaleza, acumulando la sabiduría necesaria para navegar la existencia.",
    fr: "L'observateur du vide, vous cherchez la sécurité dans la compréhension. Votre esprit est une forteresse, accumulant la sagesse nécessaire pour naviguer dans l'existence.",
    ja: "虚空の観察者よ、あなたは理解の中に安全を求めます。あなたの精神は要塞であり、存在を航海するために必要な知恵を蓄積しています。",
    ko: "공허의 관찰자여, 당신은 이해함 속에서 안전을 찾습니다. 당신의 정신은 요새와 같으며, 존재를 탐구하는 데 필요한 지혜를 축적합니다.",
    zh: "虚空的观察者，你在理解中寻求安全。你的头脑是一座堡垒，积累着航行于生存所需的智慧。",
  },
  type6: {
    en: "The guardian of the tribe, your vigilance protects what matters. In a chaotic world, you are the watchful eye and the loyal heart.",
    es: "El guardián de la tribu, tu vigilancia protege lo que importa. En un mundo caótico, eres el ojo vigilante y el corazón leal.",
    fr: "Le gardien de la tribu, votre vigilance protège ce qui compte. Dans un monde chaotique, vous êtes l'œil vigilant et le cœur loyal.",
    ja: "部族の守護者よ、あなたの警戒心は重要なものを守ります。混沌とした世界において、あなたは用心深い眼であり、忠実な心です。",
    ko: "부족의 수호자여, 당신의 경계심은 소중한 것들을 지켜냅니다. 혼란스러운 세상에서 당신은 깨어 있는 눈이자 충직한 심장입니다.",
    zh: "部落的守护者，你的警觉保护着重要的事物。在一个混乱的世界里，你是警惕的眼睛和忠诚的心。",
  },
  type7: {
    en: "The traveler of possibilities, you dance across the surface of infinity. Your joy is a spark that ignites the future, avoiding the gravity of the mundane.",
    es: "El viajero de las posibilidades, bailas a través de la superficie del infinito. Tu alegría es una chispa que enciende el futuro, evitando la gravedad de lo mundano.",
    fr: "Le voyageur des possibilités, vous dansez à travers la surface de l'infini. Votre joie est une étincelle qui enflamme l'avenir, évitant la gravité du banal.",
    ja: "可能性の旅人よ、あなたは無限の表面を踊るように渡ります。あなたの喜びは未来を点火する火花であり、日常の重力を避けます。",
    ko: "가능성의 여행자여, 당신은 무한의 표면 위를 춤추듯 건너갑니다. 당신의 기쁨은 미래를 점화하는 불꽃이며, 평범함의 중력을 거부합니다.",
    zh: "可能性的旅行者，你在无限的表面跳舞。你的快乐是点燃未来的火花，避开了平庸的重力。",
  },
  type8: {
    en: "The breaker of chains, you assert your will against the silence. Impact is your language; you rewrite the rules simply by being present.",
    es: "El rompedor de cadenas, afirmas tu voluntad contra el silencio. El impacto es tu lenguaje; reescribes las reglas simplemente con tu presencia.",
    fr: "Le briseur de chaînes, vous affirmez votre volonté contre le silence. L'impact est votre langage ; vous réécrivez les règles simplement en étant présent.",
    ja: "鎖を断ち切る者よ、あなたは沈黙に対して自らの意志を主張します。影響力はあなたの言語であり、あなたは存在するだけでルールを書き換えます。",
    ko: "사슬을 끊는 자여, 당신은 침묵에 맞서 의지를 관철합니다. 영향력이 곧 당신의 언어이며, 당신은 존재하는 것만으로 규칙을 다시 씁니다.",
    zh: "枷锁的打破者，你在沉默中坚持自己的意志。影响力是你的语言；你仅仅通过存在就重写了规则。",
  },
  type9: {
    en: "The vessel of peace, you harmonize the discordant notes of life. You flow like a great river, merging opposing forces into a unified whole.",
    es: "El recipiente de la paz, armonizas las notas discordantes de la vida. Fluyes como un gran río, fusionando fuerzas opuestas en un todo unificado.",
    fr: "Le vaisseau de la paix, vous harmonisez les notes discordantes de la vie. Vous coulez comme un grand fleuve, fusionnant les forces opposées en un tout unifié.",
    ja: "平和の器よ、あなたは人生の不協和音を調和させます。あなたは大河のように流れ、対立する力を一つの全体へと融合させます。",
    ko: "평화의 그릇이여, 당신은 삶의 불협화음을 조화롭게 만듭니다. 당신은 거대한 강물처럼 흘러, 대립하는 힘들을 하나의 전체로 융합합니다.",
    zh: "和平的容器，你协调生活中不和谐的音符。你像大河一样流动，将对立的力量合并为一个统一的整体。",
  },
};

export const MBTI_COSMIC_ROLE: Record<string, SixLangString> = {
  NF: {
    en: "The Healers of Souls",
    es: "Los Sanadores de Almas",
    fr: "Les Guérisseurs d'Âmes",
    ja: "魂の癒やし手たち",
    ko: "영혼의 치유자들",
    zh: "心灵的治愈者",
  },
  NT: {
    en: "The Architects of Systems",
    es: "Los Arquitectos de Sistemas",
    fr: "Les Architectes de Systèmes",
    ja: "システムの設計者たち",
    ko: "시스템의 설계자들",
    zh: "系统的建筑师",
  },
  SJ: {
    en: "The Keepers of Tradition",
    es: "Los Guardianes de la Tradición",
    fr: "Les Gardiens de la Tradition",
    ja: "伝統の守護者たち",
    ko: "전통의 수호자들",
    zh: "传统的守卫者",
  },
  SP: {
    en: "The Dancers of the Moment",
    es: "Los Bailarines del Momento",
    fr: "Les Danseurs de l'Instant",
    ja: "瞬間の踊り手たち",
    ko: "순간의 춤꾼들",
    zh: "当下的舞者",
  },
};
