import { Birthflower } from "../../core/schemas";

export const BIRTHFLOWERS: Birthflower[] = [
  // January
  {
    elementMapping: "FIRE",
    id: "carnation",
    languageOfFlowers: "Pride, Beauty",
    month: 1,
    name: "Carnation",
    season: "WINTER",
  },
  {
    elementMapping: "WOOD",
    id: "snowdrop",
    languageOfFlowers: "Hope, Purity",
    month: 1,
    name: "Snowdrop",
    season: "WINTER",
  },
  {
    elementMapping: "EARTH",
    id: "winter_jasmine",
    languageOfFlowers: "Modesty, Grace",
    month: 1,
    name: "Winter Jasmine",
    season: "WINTER",
  },
  {
    elementMapping: "METAL",
    id: "hellebore",
    languageOfFlowers: "Tranquility",
    month: 1,
    name: "Hellebore",
    season: "WINTER",
  },
  // February
  {
    elementMapping: "WOOD",
    id: "violet",
    languageOfFlowers: "Modesty, Faithfulness",
    month: 2,
    name: "Violet",
    season: "WINTER",
  },
  {
    elementMapping: "WATER",
    id: "primrose",
    languageOfFlowers: "Young love",
    month: 2,
    name: "Primrose",
    season: "WINTER",
  },
  {
    elementMapping: "FIRE",
    id: "iris",
    languageOfFlowers: "Eloquence, Hope",
    month: 2,
    name: "Iris",
    season: "WINTER",
  },
  {
    elementMapping: "METAL",
    id: "crocus",
    languageOfFlowers: "Cheerfulness",
    month: 2,
    name: "Crocus",
    season: "WINTER",
  },
  // March
  {
    elementMapping: "EARTH",
    id: "daffodil",
    languageOfFlowers: "New beginnings",
    month: 3,
    name: "Daffodil",
    season: "SPRING",
  },
  {
    elementMapping: "FIRE",
    id: "cherry_blossom",
    languageOfFlowers: "Spiritual beauty",
    month: 3,
    name: "Cherry Blossom",
    season: "SPRING",
  },
  {
    elementMapping: "WOOD",
    id: "tulip",
    languageOfFlowers: "Perfect love",
    month: 3,
    name: "Tulip",
    season: "SPRING",
  },
  {
    elementMapping: "METAL",
    id: "magnolia",
    languageOfFlowers: "Dignity, Perseverance",
    month: 3,
    name: "Magnolia",
    season: "SPRING",
  },
  // April
  {
    elementMapping: "METAL",
    id: "daisy",
    languageOfFlowers: "Purity, Innocence",
    month: 4,
    name: "Daisy",
    season: "SPRING",
  },
  {
    elementMapping: "FIRE",
    id: "sweet_pea",
    languageOfFlowers: "Blissful pleasure",
    month: 4,
    name: "Sweet Pea",
    season: "SPRING",
  },
  {
    elementMapping: "WATER",
    id: "forget_me_not",
    languageOfFlowers: "True love",
    month: 4,
    name: "Forget-me-not",
    season: "SPRING",
  },
  {
    elementMapping: "WOOD",
    id: "almond_blossom",
    languageOfFlowers: "Hope, Watchfulness",
    month: 4,
    name: "Almond Blossom",
    season: "SPRING",
  },
  // May
  {
    elementMapping: "WATER",
    id: "lily_of_valley",
    languageOfFlowers: "Sweetness, Humility",
    month: 5,
    name: "Lily of the Valley",
    season: "SPRING",
  },
  {
    elementMapping: "FIRE",
    id: "hawthorn",
    languageOfFlowers: "Hope, Happiness",
    month: 5,
    name: "Hawthorn",
    season: "SPRING",
  },
  {
    elementMapping: "EARTH",
    id: "peony",
    languageOfFlowers: "Honor, Wealth",
    month: 5,
    name: "Peony",
    season: "SPRING",
  },
  {
    elementMapping: "WOOD",
    id: "orchid",
    languageOfFlowers: "Refinement, Beauty",
    month: 5,
    name: "Orchid",
    season: "SPRING",
  },
  // June
  {
    elementMapping: "FIRE",
    id: "rose",
    languageOfFlowers: "Love, Passion",
    month: 6,
    name: "Rose",
    season: "SUMMER",
  },
  {
    elementMapping: "WOOD",
    id: "honeysuckle",
    languageOfFlowers: "Devotion, Affection",
    month: 6,
    name: "Honeysuckle",
    season: "SUMMER",
  },
  {
    elementMapping: "WATER",
    id: "jasmine",
    languageOfFlowers: "Sensuality, Grace",
    month: 6,
    name: "Jasmine",
    season: "SUMMER",
  },
  {
    elementMapping: "METAL",
    id: "lavender",
    languageOfFlowers: "Purity, Silence",
    month: 6,
    name: "Lavender",
    season: "SUMMER",
  },
  // July
  {
    elementMapping: "WOOD",
    id: "larkspur",
    languageOfFlowers: "Positivity, Grace",
    month: 7,
    name: "Larkspur",
    season: "SUMMER",
  },
  {
    elementMapping: "WATER",
    id: "water_lily",
    languageOfFlowers: "Purity of heart",
    month: 7,
    name: "Water Lily",
    season: "SUMMER",
  },
  {
    elementMapping: "FIRE",
    id: "lotus",
    languageOfFlowers: "Enlightenment, Purity",
    month: 7,
    name: "Lotus",
    season: "SUMMER",
  },
  {
    elementMapping: "EARTH",
    id: "sunflower",
    languageOfFlowers: "Adoration, Loyalty",
    month: 7,
    name: "Sunflower",
    season: "SUMMER",
  },
  // August
  {
    elementMapping: "METAL",
    id: "gladiolus",
    languageOfFlowers: "Strength, Integrity",
    month: 8,
    name: "Gladiolus",
    season: "SUMMER",
  },
  {
    elementMapping: "FIRE",
    id: "poppy",
    languageOfFlowers: "Imagination, Dream",
    month: 8,
    name: "Poppy",
    season: "SUMMER",
  },
  {
    elementMapping: "EARTH",
    id: "dahlia",
    languageOfFlowers: "Dignity, Elegance",
    month: 8,
    name: "Dahlia",
    season: "SUMMER",
  },
  {
    elementMapping: "WOOD",
    id: "hibiscus",
    languageOfFlowers: "Delicate beauty",
    month: 8,
    name: "Hibiscus",
    season: "SUMMER",
  },
  // September
  {
    elementMapping: "EARTH",
    id: "aster",
    languageOfFlowers: "Wisdom, Faith",
    month: 9,
    name: "Aster",
    season: "AUTUMN",
  },
  {
    elementMapping: "FIRE",
    id: "morning_glory",
    languageOfFlowers: "Affection",
    month: 9,
    name: "Morning Glory",
    season: "AUTUMN",
  },
  {
    elementMapping: "METAL",
    id: "cosmos",
    languageOfFlowers: "Harmony, Balance",
    month: 9,
    name: "Cosmos",
    season: "AUTUMN",
  },
  {
    elementMapping: "WOOD",
    id: "clematis",
    languageOfFlowers: "Mental beauty",
    month: 9,
    name: "Clematis",
    season: "AUTUMN",
  },
  // October
  {
    elementMapping: "FIRE",
    id: "marigold",
    languageOfFlowers: "Passion, Creativity",
    month: 10,
    name: "Marigold",
    season: "AUTUMN",
  },
  {
    elementMapping: "EARTH",
    id: "cosmos",
    languageOfFlowers: "Harmony",
    month: 10,
    name: "Cosmos",
    season: "AUTUMN",
  },
  {
    elementMapping: "WATER",
    id: "camellia",
    languageOfFlowers: "Adoration, Perfection",
    month: 10,
    name: "Camellia",
    season: "AUTUMN",
  },
  {
    elementMapping: "METAL",
    id: "geranium",
    languageOfFlowers: "Gentility",
    month: 10,
    name: "Geranium",
    season: "AUTUMN",
  },
  // November
  {
    elementMapping: "METAL",
    id: "chrysanthemum",
    languageOfFlowers: "Loyalty, Joy",
    month: 11,
    name: "Chrysanthemum",
    season: "AUTUMN",
  },
  {
    elementMapping: "EARTH",
    id: "zinnia",
    languageOfFlowers: "Thoughts of absent friends",
    month: 11,
    name: "Zinnia",
    season: "AUTUMN",
  },
  {
    elementMapping: "FIRE",
    id: "protea",
    languageOfFlowers: "Diversity, Courage",
    month: 11,
    name: "Protea",
    season: "AUTUMN",
  },
  {
    elementMapping: "WOOD",
    id: "anemone",
    languageOfFlowers: "Anticipation",
    month: 11,
    name: "Anemone",
    season: "AUTUMN",
  },
  // December
  {
    elementMapping: "FIRE",
    id: "poinsettia",
    languageOfFlowers: "Celebration, Success",
    month: 12,
    name: "Poinsettia",
    season: "WINTER",
  },
  {
    elementMapping: "METAL",
    id: "holly",
    languageOfFlowers: "Defense, Domestic happiness",
    month: 12,
    name: "Holly",
    season: "WINTER",
  },
  {
    elementMapping: "WATER",
    id: "narcissus",
    languageOfFlowers: "Self-esteem, Vanity",
    month: 12,
    name: "Narcissus",
    season: "WINTER",
  },
  {
    elementMapping: "EARTH",
    id: "orchid",
    languageOfFlowers: "Strength, Beauty",
    month: 12,
    name: "Orchid",
    season: "WINTER",
  },
];

export default BIRTHFLOWERS;
