import type { Birthstone } from "../../core/schemas";

/* eslint-disable no-restricted-syntax */
export const BIRTHSTONES: Birthstone[] = [
  // January
  {
    colorHex: "#8B0000",
    elementMapping: "FIRE",
    id: "garnet",
    meaning: "Protection, Power",
    month: 1,
    name: "Garnet",
  },
  {
    colorHex: "#4C516D",
    elementMapping: "METAL",
    id: "hematite",
    meaning: "Grounding, Focus",
    month: 1,
    name: "Hematite",
  },
  {
    colorHex: "#191970",
    elementMapping: "WATER",
    id: "midnight_sapphire",
    meaning: "Intuition, Depth",
    month: 1,
    name: "Midnight Sapphire",
  },
  {
    colorHex: "#3F4E4F",
    elementMapping: "EARTH",
    id: "onyx",
    meaning: "Strength, Stamina",
    month: 1,
    name: "Onyx",
  },
  // February
  {
    colorHex: "#9966CC",
    elementMapping: "WOOD",
    id: "amethyst",
    meaning: "Wisdom, Sobriety",
    month: 2,
    name: "Amethyst",
  },
  {
    colorHex: "#FFB7C5",
    elementMapping: "FIRE",
    id: "pink_tourmaline",
    meaning: "Love, Compassion",
    month: 2,
    name: "Pink Tourmaline",
  },
  {
    colorHex: "#40E0D0",
    elementMapping: "WATER",
    id: "zircon",
    meaning: "Prosperity, Honor",
    month: 2,
    name: "Zircon",
  },
  {
    colorHex: "#5D3F6A",
    elementMapping: "METAL",
    id: "charoite",
    meaning: "Transformation",
    month: 2,
    name: "Charoite",
  },
  // March
  {
    colorHex: "#7FFFD4",
    elementMapping: "WATER",
    id: "aquamarine",
    meaning: "Serenity, Courage",
    month: 3,
    name: "Aquamarine",
  },
  {
    colorHex: "#8B0000",
    elementMapping: "FIRE",
    id: "bloodstone",
    meaning: "Vitality, Courage",
    month: 3,
    name: "Bloodstone",
  },
  {
    colorHex: "#E0FFFF",
    elementMapping: "METAL",
    id: "white_topaz",
    meaning: "Clarity, Hope",
    month: 3,
    name: "White Topaz",
  },
  {
    colorHex: "#966919",
    elementMapping: "EARTH",
    id: "jasper",
    meaning: "Stability, Comfort",
    month: 3,
    name: "Jasper",
  },
  // April
  {
    colorHex: "#B9F2FF",
    elementMapping: "METAL",
    id: "diamond",
    meaning: "Eternity, Strength",
    month: 4,
    name: "Diamond",
  },
  {
    colorHex: "#F0E68C",
    elementMapping: "EARTH",
    id: "yellow_sapphire",
    meaning: "Wealth, Wisdom",
    month: 4,
    name: "Yellow Sapphire",
  },
  {
    colorHex: "#FF69B4",
    elementMapping: "FIRE",
    id: "morganite",
    meaning: "Divine Love",
    month: 4,
    name: "Morganite",
  },
  {
    colorHex: "#F5F5DC",
    elementMapping: "WOOD",
    id: "rock_crystal",
    meaning: "Clarity, Energy",
    month: 4,
    name: "Rock Crystal",
  },
  // May
  {
    colorHex: "#50C878",
    elementMapping: "WOOD",
    id: "green",
    meaning: "Rebirth, Love",
    month: 5,
    name: "Emerald",
  },
  {
    colorHex: "#008080",
    elementMapping: "WATER",
    id: "chrysocolla",
    meaning: "Communication",
    month: 5,
    name: "Chrysocolla",
  },
  {
    colorHex: "#FF7F50",
    elementMapping: "FIRE",
    id: "carnelian",
    meaning: "Creativity, Boldness",
    month: 5,
    name: "Carnelian",
  },
  {
    colorHex: "#C0C0C0",
    elementMapping: "METAL",
    id: "moonstone",
    meaning: "New beginnings",
    month: 5,
    name: "Moonstone",
  },
  // June
  {
    colorHex: "#EAE0C8",
    elementMapping: "WATER",
    id: "pearl",
    meaning: "Purity, Honesty",
    month: 6,
    name: "Pearl",
  },
  {
    colorHex: "#DCD0FF",
    elementMapping: "METAL",
    id: "alexandrite",
    meaning: "Luck, Love",
    month: 6,
    name: "Alexandrite",
  },
  {
    colorHex: "#98FB98",
    elementMapping: "WOOD",
    id: "jade",
    meaning: "Harmony, Wealth",
    month: 6,
    name: "Jade",
  },
  {
    colorHex: "#BDB76B",
    elementMapping: "EARTH",
    id: "tiger_eye",
    meaning: "Focus, Protection",
    month: 6,
    name: "Tiger Eye",
  },
  // July
  {
    colorHex: "#E0115F",
    elementMapping: "FIRE",
    id: "ruby",
    meaning: "Passion, Vitality",
    month: 7,
    name: "Ruby",
  },
  {
    colorHex: "#FFD700",
    elementMapping: "EARTH",
    id: "citrine",
    meaning: "Success, Abundance",
    month: 7,
    name: "Citrine",
  },
  {
    colorHex: "#00CED1",
    elementMapping: "WATER",
    id: "apatite",
    meaning: "Inspiration",
    month: 7,
    name: "Apatite",
  },
  {
    colorHex: "#8A2BE2",
    elementMapping: "WOOD",
    id: "tanzanite",
    meaning: "Spirituality",
    month: 7,
    name: "Tanzanite",
  },
  // August
  {
    colorHex: "#90EE90",
    elementMapping: "WOOD",
    id: "peridot",
    meaning: "Strength, Balance",
    month: 8,
    name: "Peridot",
  },
  {
    colorHex: "#FF4500",
    elementMapping: "FIRE",
    id: "spinel",
    meaning: "Revitalization",
    month: 8,
    name: "Spinel",
  },
  {
    colorHex: "#000000",
    elementMapping: "METAL",
    id: "black_diamond",
    meaning: "Authority",
    month: 8,
    name: "Black Diamond",
  },
  {
    colorHex: "#DEB887",
    elementMapping: "EARTH",
    id: "sardonyx",
    meaning: "Confidence",
    month: 8,
    name: "Sardonyx",
  },
  // September
  {
    colorHex: "#0F52BA",
    elementMapping: "METAL",
    id: "sapphire",
    meaning: "Wisdom, Royalty",
    month: 9,
    name: "Sapphire",
  },
  {
    colorHex: "#4169E1",
    elementMapping: "WATER",
    id: "lapis_lazuli",
    meaning: "Truth, Wisdom",
    month: 9,
    name: "Lapis Lazuli",
  },
  {
    colorHex: "#FF00FF",
    elementMapping: "FIRE",
    id: "pink_sapphire",
    meaning: "Loyalty, Love",
    month: 9,
    name: "Pink Sapphire",
  },
  {
    colorHex: "#228B22",
    elementMapping: "WOOD",
    id: "green_tourmaline",
    meaning: "Wholeness",
    month: 9,
    name: "Green Tourmaline",
  },
  // October
  {
    colorHex: "#A8C3BC",
    elementMapping: "EARTH",
    id: "opal",
    meaning: "Hope, Creativity",
    month: 10,
    name: "Opal",
  },
  {
    colorHex: "#FFB6C1",
    elementMapping: "FIRE",
    id: "rose_quartz",
    meaning: "Unconditional Love",
    month: 10,
    name: "Rose Quartz",
  },
  {
    colorHex: "#4682B4",
    elementMapping: "WATER",
    id: "blue_lace_agate",
    meaning: "Calmness",
    month: 10,
    name: "Blue Lace Agate",
  },
  {
    colorHex: "#708090",
    elementMapping: "METAL",
    id: "labradorite",
    meaning: "Magic, Protection",
    month: 10,
    name: "Labradorite",
  },
  // November
  {
    colorHex: "#FFC87C",
    elementMapping: "EARTH",
    id: "topaz",
    meaning: "Friendship, Strength",
    month: 11,
    name: "Topaz",
  },
  {
    colorHex: "#E34234",
    elementMapping: "FIRE",
    id: "vermeil",
    meaning: "Affluence",
    month: 11,
    name: "Vermeil",
  },
  {
    colorHex: "#DAA520",
    elementMapping: "WOOD",
    id: "golden_beryl",
    meaning: "Confidence",
    month: 11,
    name: "Golden Beryl",
  },
  {
    colorHex: "#7B3F00",
    elementMapping: "METAL",
    id: "smoky_quartz",
    meaning: "Transmutation",
    month: 11,
    name: "Smoky Quartz",
  },
  // December
  {
    colorHex: "#40E0D0",
    elementMapping: "WATER",
    id: "turquoise",
    meaning: "Protection, Fortune",
    month: 12,
    name: "Turquoise",
  },
  {
    colorHex: "#000080",
    elementMapping: "METAL",
    id: "tanzanite",
    meaning: "Intellect, Insight",
    month: 12,
    name: "Tanzanite",
  },
  {
    colorHex: "#5F9EA0",
    elementMapping: "EARTH",
    id: "blue_zircon",
    meaning: "High Energy",
    month: 12,
    name: "Blue Zircon",
  },
  {
    colorHex: "#0000CD",
    elementMapping: "FIRE",
    id: "blue_topaz",
    meaning: "Success, Love",
    month: 12,
    name: "Blue Topaz",
  },
];
/* eslint-enable no-restricted-syntax */

export default BIRTHSTONES;
