import type { FriendshipStyleQuestion } from "./types";

export const FRIENDSHIP_STYLE_QUESTIONS: FriendshipStyleQuestion[] = [
  {
    id: "1",
    options: [
      {
        id: "a",
        style: "supporter",
        text: {
          zh: "仔细倾听并提供情感支持",
          en: "Listen carefully and offer emotional support",
          es: "Escuchar atentamente y ofrecer apoyo emocional",
          fr: "L'écouter attentivement et lui offrir un soutien émotionnel",
          ja: "注意深く聞き、感情的なサポートを提供する",
          ko: "주의 깊게 듣고 정서적 지지를 제공한다",
        },
        weight: 3,
      },
      {
        id: "b",
        style: "adventurer",
        text: {
          zh: "建议一次冒险或活动来让他们振作起来",
          en: "Suggest an adventure or activity to cheer them up",
          es: "Sugerir una aventura o actividad para animarlos",
          fr: "Lui suggérer une aventure ou une activité pour lui remonter le moral",
          ja: "元気づけるために冒険やアクティビティを提案する",
          ko: "기운을 북돋아 주기 위해 모험이나 활동을 제안한다",
        },
        weight: 3,
      },
      {
        id: "c",
        style: "thinker",
        text: {
          zh: "就他们的处境进行深入交流",
          en: "Have a deep conversation about their situation",
          es: "Tener una conversación profunda sobre su situación",
          fr: "Avoir une conversation profonde sur sa situation",
          ja: "彼らの状況について深い会話をする",
          ko: "그들의 상황에 대해 깊은 대화를 나눈다",
        },
        weight: 3,
      },
      {
        id: "d",
        style: "entertainer",
        text: {
          zh: "试着逗他们笑，让他们打起精神来",
          en: "Try to make them laugh and lift their spirits",
          es: "Intentar hacerlos reír y levantarles el ánimo",
          fr: "Essayer de le faire rire et de lui remonter le moral",
          ja: "彼らを笑わせて気分を上げようとする",
          ko: "그들을 웃게 만들어 기분을 풀어주려 노력한다",
        },
        weight: 3,
      },
      {
        id: "e",
        style: "organizer",
        text: {
          zh: "组织实际帮助或协调他人的支持",
          en: "Organize practical help or coordinate support from others",
          es: "Organizar ayuda práctica o coordinar el apoyo de otros",
          fr: "Organiser une aide pratique ou coordonner le soutien des autres",
          ja: "実用的な助けを組織したり、他の人からのサポートを調整したりする",
          ko: "실질적인 도움을 조직하거나 다른 사람들의 지원을 조정한다",
        },
        weight: 3,
      },
    ],
    scenario: {
      zh: "当朋友度过艰难时期时，你通常会：",
      en: "When a friend is going through a difficult time, you typically:",
      es: "Cuando un amigo está pasando por un momento difícil, normalmente:",
      fr: "Lorsqu'un ami traverse une période difficile, vous avez l'habitude de :",
      ja: "友人が困難な時期を過ごしているとき、あなたは通常：",
      ko: "친구가 힘든 시간을 보낼 때, 당신은 주로:",
    },
  },
  {
    id: "2",
    options: [
      {
        id: "a",
        style: "supporter",
        text: {
          zh: "进行有意义的一对一交流",
          en: "Having meaningful one-on-one conversations",
          es: "Tener conversaciones profundas uno a uno",
          fr: "Avoir des conversations individuelles constructives",
          ja: "意味のある1対1の会話をする",
          ko: "의미 있는 일대일 대화를 나누기",
        },
        weight: 3,
      },
      {
        id: "b",
        style: "adventurer",
        text: {
          zh: "进行一次自发的冒险或尝试新事物",
          en: "Going on a spontaneous adventure or trying something new",
          es: "Ir a una aventura espontánea o probar algo nuevo",
          fr: "Partir pour une aventure spontanée ou essayer quelque chose de nouveau",
          ja: "自発的な冒険に出かけたり、新しいことに挑戦したりする",
          ko: "즉흥적인 모험을 떠나거나 새로운 시도를 하기",
        },
        weight: 3,
      },
      {
        id: "c",
        style: "thinker",
        text: {
          zh: "讨论有趣的话题或分享想法",
          en: "Discussing interesting topics or sharing ideas",
          es: "Discutir temas interesantes o compartir ideas",
          fr: "Discuter de sujets intéressants ou partager des idées",
          ja: "興味深いトピックについて話し合ったり、アイデアを共有したりする",
          ko: "흥미로운 주제에 대해 토론하거나 아이디어를 공유하기",
        },
        weight: 3,
      },
      {
        id: "d",
        style: "entertainer",
        text: {
          zh: "举办或参加有趣的社交聚会",
          en: "Hosting or attending a fun social gathering",
          es: "Organizar o asistir a una reunión social divertida",
          fr: "Organiser ou assister à un rassemblement social amusant",
          ja: "楽しい社交の集まりを主催したり参加したりする",
          ko: "즐거운 소셜 모임을 주최하거나 참석하기",
        },
        weight: 3,
      },
      {
        id: "e",
        style: "organizer",
        text: {
          zh: "按照计划的小组活动进行",
          en: "Following through with planned group activities",
          es: "Seguir con las actividades grupales planeadas",
          fr: "Réaliser les activités de groupe prévues",
          ja: "計画されたグループ活動を実行する",
          ko: "계획된 그룹 활동을 수행하기",
        },
        weight: 3,
      },
    ],
    scenario: {
      zh: "你与朋友理想的周末包括：",
      en: "Your ideal weekend with friends involves:",
      es: "Tu fin de semana ideal con amigos implica:",
      fr: "Votre week-end idéal entre amis comprend :",
      ja: "友人との理想的な週末は：",
      ko: "친구들과 함께하는 이상적인 주말은:",
    },
  },
  {
    id: "3",
    options: [
      {
        id: "a",
        style: "supporter",
        text: {
          zh: "关心每一个人，确保大家都有参与感",
          en: "Check in on individuals and make sure everyone feels included",
          es: "Consultar a las personas y asegurarse de que todos se sientan incluidos",
          fr: "Prendre des nouvelles des individus et s'assurer que tout le monde se sent inclus",
          ja: "個人に声をかけ、全員が含まれていると感じるようにする",
          ko: "개개인을 살피고 모든 사람이 포함되었다고 느끼는지 확인한다",
        },
        weight: 2,
      },
      {
        id: "b",
        style: "adventurer",
        text: {
          zh: "建议新的活动或更改计划",
          en: "Suggest new activities or changes to the plan",
          es: "Sugerir nuevas actividades o cambios en el plan",
          fr: "Suggérer de nouvelles activités ou des modifications au plan",
          ja: "新しいアクティビティや計画の変更を提案する",
          ko: "새로운 활동이나 계획 변경을 제안한다",
        },
        weight: 2,
      },
      {
        id: "c",
        style: "thinker",
        text: {
          zh: "在交流中贡献深刻的见解",
          en: "Contribute thoughtful insights to conversations",
          es: "Aportar ideas reflexivas a las conversaciones",
          fr: "Apporter des réflexions approfondies aux conversations",
          ja: "会話に思慮深い洞察を加える",
          ko: "대화에 사려 깊은 통찰력을 보탠다",
        },
        weight: 2,
      },
      {
        id: "d",
        style: "entertainer",
        text: {
          zh: "保持活力，确保每个人都玩得开心",
          en: "Keep the energy up and make sure everyone's having fun",
          es: "Mantener la energía y asegurarse de que todos se diviertan",
          fr: "Maintenir l'énergie et s'assurer que tout le monde s'amuse",
          ja: "エネルギーを維持し、全員が楽しんでいるようにする",
          ko: "에너지를 유지하고 모든 사람이 즐거워하는지 확인한다",
        },
        weight: 2,
      },
      {
        id: "e",
        style: "organizer",
        text: {
          zh: "帮助协调后勤并确保每个人都按部就班",
          en: "Help coordinate logistics and keep everyone on track",
          es: "Ayudar a coordinar la logística y mantener a todos en el camino",
          fr: "Aider à coordonner la logistique et s'assurer que tout le monde suit",
          ja: "ロジスティクスの調整を助け、全員が計画通りに進むようにする",
          ko: "물류 조정을 돕고 모든 사람이 계획대로 움직이게 한다",
        },
        weight: 2,
      },
    ],
    scenario: {
      zh: "在集体场合下，你通常会：",
      en: "In group settings, you usually:",
      es: "En entornos grupales, normalmente:",
      fr: "Dans un groupe, vous avez l'habitude de :",
      ja: "グループの場では、あなたは通常：",
      ko: "그룹 상황에서 당신은 주로:",
    },
  },
  {
    id: "4",
    options: [
      {
        id: "a",
        style: "supporter",
        text: {
          zh: "确保考虑到每个人的舒适度和需求",
          en: "Make sure everyone's comfort and needs are considered",
          es: "Asegurarse de que se consideren la comodidad y las necesidades de todos",
          fr: "Veiller à ce que le confort et les besoins de chacun soient pris en compte",
          ja: "全員の快適さとニーズが考慮されていることを確認する",
          ko: "모든 사람의 편안함과 요구 사항을 고려한다",
        },
        weight: 3,
      },
      {
        id: "b",
        style: "adventurer",
        text: {
          zh: "研究令人兴奋的活动和待探索的隐藏宝藏",
          en: "Research exciting activities and hidden gems to explore",
          es: "Investigar actividades emocionantes y gemas ocultas para explorar",
          fr: "Rechercher des activités passionnantes et des pépites cachées à explorer",
          ja: "探索すべきエキサイティングなアクティビティや隠れた名所を調査する",
          ko: "탐험할 흥미진진한 활동과 숨겨진 보석 같은 장소를 조사한다",
        },
        weight: 3,
      },
      {
        id: "c",
        style: "thinker",
        text: {
          zh: "寻找有趣的文化或教育体验",
          en: "Find interesting cultural or educational experiences",
          es: "Encontrar experiencias culturales o educativas interesantes",
          fr: "Trouver des expériences culturelles ou éducatives intéressantes",
          ja: "興味深い文化的、教育的な経験を見つける",
          ko: "흥미로운 문화나 교육적 경험을 찾는다",
        },
        weight: 3,
      },
      {
        id: "d",
        style: "entertainer",
        text: {
          zh: "规划有趣的集体活动和社交体验",
          en: "Plan fun group activities and social experiences",
          es: "Planificar actividades grupales divertidas y experiencias sociales",
          fr: "Planifier des activités de groupe amusantes et des expériences sociales",
          ja: "楽しいグループアクティビティや社交的な経験を計画する",
          ko: "즐거운 그룹 활동과 소셜 경험을 계획한다",
        },
        weight: 3,
      },
      {
        id: "e",
        style: "organizer",
        text: {
          zh: "处理后勤、预订和详细行程",
          en: "Handle the logistics, bookings, and detailed itinerary",
          es: "Encargarse de la logística, las reservas y el itinerario detallado",
          fr: "S'occuper de la logistique, des réservations et de l'itinéraire détaillé",
          ja: "ロジスティクス、予約、詳細な旅程を担当する",
          ko: "물류, 예약 및 상세 여정을 처리한다",
        },
        weight: 3,
      },
    ],
    scenario: {
      zh: "在规划集体旅行时，你最有可能：",
      en: "When planning a group trip, you're most likely to:",
      es: "Al planificar un viaje grupal, es más probable que:",
      fr: "Lors de la planification d'un voyage en groupe, vous avez tendance à :",
      ja: "グループ旅行を計画するとき、あなたは主に：",
      ko: "그룹 여행을 계획할 때 당신은 주로:",
    },
  },
  {
    id: "5",
    options: [
      {
        id: "a",
        style: "supporter",
        text: {
          zh: "倾诉他们的问题并获得情感支持时",
          en: "Talk through their problems and get emotional support",
          es: "Hablar de sus problemas y obtener apoyo emocional",
          fr: "Parler de leurs problèmes et obtenir un soutien émotionnel",
          ja: "自分の問題を話し合い、感情的なサポートを受けたいとき",
          ko: "자신의 문제를 이야기하고 정서적 지지를 받고 싶을 때",
        },
        weight: 3,
      },
      {
        id: "b",
        style: "adventurer",
        text: {
          zh: "做一些令人兴奋的事情并跳出常规时",
          en: "Do something exciting and break out of their routine",
          es: "Hacer algo emocionante y salir de su rutina",
          fr: "Faire quelque chose de passionnant et sortir de leur routine",
          ja: "エキサイティングなことをして、日常から脱却したいとき",
          ko: "흥미진진한 일을 하고 일상에서 벗어나고 싶을 때",
        },
        weight: 3,
      },
      {
        id: "c",
        style: "thinker",
        text: {
          zh: "就生活和想法进行有意义的交流时",
          en: "Have a meaningful conversation about life and ideas",
          es: "Tener una conversación significativa sobre la vida y las ideas",
          fr: "Avoir une conversation constructive sur la vie et les idées",
          ja: "人生やアイデアについて意味のある会話をしたいとき",
          ko: "인생과 아이디어에 대해 의미 있는 대화를 나누고 싶을 때",
        },
        weight: 3,
      },
      {
        id: "d",
        style: "entertainer",
        text: {
          zh: "快活、欢笑并忘却烦恼时",
          en: "Have fun, laugh, and forget their worries",
          es: "Divertirse, reír y olvidar sus preocupaciones",
          fr: "S'amuser, rire et oublier leurs soucis",
          ja: "楽しく過ごし、笑い、心配事を忘れたいとき",
          ko: "즐겁게 놀고 웃으며 걱정을 잊고 싶을 때",
        },
        weight: 3,
      },
      {
        id: "e",
        style: "organizer",
        text: {
          zh: "在整理生活或规划某事需要帮助时",
          en: "Get help organizing their life or planning something",
          es: "Obtener ayuda para organizar su vida o planificar algo",
          fr: "Obtenir de l'aide pour organiser leur vie ou planifier quelque chose",
          ja: "生活を整えたり、何かを計画したりするのを手伝ってほしいとき",
          ko: "생활을 정리하거나 무언가를 계획하는 데 도움을 받고 싶을 때",
        },
        weight: 3,
      },
    ],
    scenario: {
      zh: "你的朋友在以下情况下会来找你：",
      en: "Your friends come to you when they want to:",
      es: "Tus amigos acuden a ti cuando quieren:",
      fr: "Vos amis viennent vous voir lorsqu'ils souhaitent :",
      ja: "友人たちは、次のようなときにあなたのところに来ます：",
      ko: "친구들이 다음과 같은 상황일 때 당신을 찾아옵니다:",
    },
  },
  {
    id: "6",
    options: [
      {
        id: "a",
        style: "supporter",
        text: {
          zh: "与亲密朋友进行深度、私人性质的交流时",
          en: "Having deep, personal conversations with close friends",
          es: "Tener conversaciones profundas y personales con amigos cercanos",
          fr: "Avoir des conversations personnelles et profondes avec des amis proches",
          ja: "親しい友人と深く個人的な会話をするとき",
          ko: "친한 친구들과 깊고 개인적인 대화를 나눌 때",
        },
        weight: 2,
      },
      {
        id: "b",
        style: "adventurer",
        text: {
          zh: "结识新朋友并听闻他们的经历时",
          en: "Meeting new people and hearing about their experiences",
          es: "Conocer gente nueva y escuchar sobre sus experiencias",
          fr: "Rencontrer de nouvelles personnes et découvrir leur parcours",
          ja: "新しい人々に会い、彼らの経験について聞くとき",
          ko: "새로운 사람들을 만나고 그들의 경험에 대해 들을 때",
        },
        weight: 2,
      },
      {
        id: "c",
        style: "thinker",
        text: {
          zh: "就想法或话题参与有趣的讨论时",
          en: "Engaging in interesting discussions about ideas or topics",
          es: "Participar en discusiones interesantes sobre ideas o temas",
          fr: "Participer à des discussions intéressantes sur des idées ou des sujets",
          ja: "アイデアやトピックについて興味深い議論に参加するとき",
          ko: "아이디어나 주제에 대해 흥미로운 토론에 참여할 때",
        },
        weight: 2,
      },
      {
        id: "d",
        style: "entertainer",
        text: {
          zh: "成为焦点并款待他人时",
          en: "Being the center of attention and entertaining others",
          es: "Ser el centro de atención y entretener a los demás",
          fr: "Être le centre de l'attention et divertir les autres",
          ja: "注目の的となり、他の人々を楽しませるとき",
          ko: "관심의 중심이 되어 다른 사람들을 즐겁게 할 때",
        },
        weight: 2,
      },
      {
        id: "e",
        style: "organizer",
        text: {
          zh: "看到一个组织良好的活动顺利进行时",
          en: "Seeing a well-organized event come together smoothly",
          es: "Ver que un evento bien organizado se desarrolla sin problemas",
          fr: "Voir un événement bien organisé se dérouler sans accroc",
          ja: "よく組織されたイベントがスムーズに進むのを見るとき",
          ko: "잘 조직된 행사가 순조롭게 진행되는 것을 볼 때",
        },
        weight: 2,
      },
    ],
    scenario: {
      zh: "在社交活动中，你什么时候感到最有活力：",
      en: "At social events, you feel most energized when:",
      es: "En los eventos sociales, te sientes más con energía cuando:",
      fr: "Lors d'événements sociaux, vous vous sentez le plus énergique lorsque :",
      ja: "社交的なイベントで、いつ最も活力を感じますか：",
      ko: "소셜 행사에서 언제 가장 에너지를 느끼나요:",
    },
  },
  {
    id: "7",
    options: [
      {
        id: "a",
        style: "supporter",
        text: {
          zh: "温暖、富有同情心且能提供情感支持",
          en: "Warm, empathetic, and emotionally supportive",
          es: "Cálido, empático y de apoyo emocional",
          fr: "Chaleureux, empathique et un soutien émotionnel",
          ja: "温かく、共感的で、感情的に協力的",
          ko: "따뜻하고 공감하며 정서적으로 지지함",
        },
        weight: 3,
      },
      {
        id: "b",
        style: "adventurer",
        text: {
          zh: "充满热情、随性且满怀故事",
          en: "Enthusiastic, spontaneous, and full of stories",
          es: "Entusiasta, espontáneo y lleno de historias",
          fr: "Enthousiaste, spontané et plein d'histoires",
          ja: "熱狂的で、自発的で、話に満ちている",
          ko: "열정적이고 즉흥적이며 이야기가 가득함",
        },
        weight: 3,
      },
      {
        id: "c",
        style: "thinker",
        text: {
          zh: "体贴、善于反思且求知欲强",
          en: "Thoughtful, reflective, and intellectually curious",
          es: "Reflexivo, meditativo y con curiosidad intelectual",
          fr: "Réfléchi, méditatif et intellectuellement curieux",
          ja: "思慮深く、反省的で、知的好奇心が強い",
          ko: "사려 깊고 성찰적이며 지적 호기심이 많음",
        },
        weight: 3,
      },
      {
        id: "d",
        style: "entertainer",
        text: {
          zh: "幽默、开朗且擅长社交",
          en: "Humorous, upbeat, and socially engaging",
          es: "Humorístico, optimista y socialmente atractivo",
          fr: "Humoristique, optimiste et socialement engageant",
          ja: "ユーモラスで、楽観的で、社交的",
          ko: "유머러스하고 낙천적이며 사교적임",
        },
        weight: 3,
      },
      {
        id: "e",
        style: "organizer",
        text: {
          zh: "实用、信息丰富且组织良好",
          en: "Practical, informative, and well-organized",
          es: "Práctico, informativo y bien organizado",
          fr: "Pratique, informatif et bien organisé",
          ja: "実用的で、有益で、よく組織されている",
          ko: "실용적이고 유익하며 잘 조직됨",
        },
        weight: 3,
      },
    ],
    scenario: {
      zh: "你与朋友的交流风格通常是：",
      en: "Your communication style with friends is typically:",
      es: "Tu estilo de comunicación con los amigos suele ser:",
      fr: "Votre style de communication avec vos amis est généralement :",
      ja: "友人とのコミュニケーションスタイルは通常：",
      ko: "친구들과의 소통 스타일은 주로:",
    },
  },
  {
    id: "8",
    options: [
      {
        id: "a",
        style: "supporter",
        text: {
          zh: "调解并帮助每个人理解彼此的感受",
          en: "Mediate and help everyone understand each other's feelings",
          es: "Mediar y ayudar a que todos entiendan los sentimientos de los demás",
          fr: "Médiatiser et aider chacun à comprendre les sentiments des autres",
          ja: "仲裁し、全員がお互いの感情を理解するのを助ける",
          ko: "중재하고 모두가 서로의 감정을 이해하도록 돕는다",
        },
        weight: 3,
      },
      {
        id: "b",
        style: "adventurer",
        text: {
          zh: "建议一起做些有趣的事情来度过难关",
          en: "Suggest doing something fun together to move past it",
          es: "Sugerir hacer algo divertido juntos para superarlo",
          fr: "Suggérer de faire quelque chose d'amusant ensemble pour passer à autre chose",
          ja: "それを乗り越えるために一緒に楽しいことをすることを提案する",
          ko: "함께 즐거운 일을 하여 갈등을 잊자고 제안한다",
        },
        weight: 2,
      },
      {
        id: "c",
        style: "thinker",
        text: {
          zh: "试着理解根本原因并寻找逻辑解决方案",
          en: "Try to understand the root cause and find logical solutions",
          es: "Tratar de entender la causa raíz y encontrar soluciones lógicas",
          fr: "Essayer de comprendre la cause profonde et trouver des solutions logiques",
          ja: "根本原因を理解し、論理的な解決策を見つけようとする",
          ko: "근본 원인을 이해하고 논리적인 해결책을 찾으려 노력한다",
        },
        weight: 3,
      },
      {
        id: "d",
        style: "entertainer",
        text: {
          zh: "利用幽默来缓解紧张气氛，让心情好起来",
          en: "Use humor to defuse tension and lighten the mood",
          es: "Usar el humor para calmar la tensión y aligerar el ambiente",
          fr: "Utiliser l'humour pour désamorcer la tension et détendre l'atmosphère",
          ja: "ユーモアを使って緊張を和らげ、雰囲気を明るくする",
          ko: "유머를 사용하여 긴장을 완화하고 분위기를 띄운다",
        },
        weight: 2,
      },
      {
        id: "e",
        style: "organizer",
        text: {
          zh: "负责并组织一个结构化的解决方案流程",
          en: "Take charge and organize a structured resolution process",
          es: "Hacerse cargo y organizar un proceso de resolución estructurado",
          fr: "Prendre les choses en main et organiser un processus de résolution structuré",
          ja: "責任を持ち、構造化された解決プロセスを組織する",
          ko: "책임을 지고 구조화된 해결 과정을 조직한다",
        },
        weight: 3,
      },
    ],
    scenario: {
      zh: "当你的朋友圈出现冲突时，你倾向于：",
      en: "When conflicts arise in your friend group, you tend to:",
      es: "Cuando surgen conflictos en tu grupo de amigos, sueles:",
      fr: "Lorsque des conflits surgissent dans votre groupe d'amis, vous avez tendance à :",
      ja: "友人のグループで対立が生じたとき、あなたは通常：",
      ko: "친구 그룹에서 갈등이 생길 때, 당신은 주로:",
    },
  },
  {
    id: "9",
    options: [
      {
        id: "a",
        style: "supporter",
        text: {
          zh: "陪伴朋友并对他们的生活产生积极影响时",
          en: "Be there for friends and make a positive impact on their lives",
          es: "Estar presente para los amigos y tener un impacto positivo en sus vidas",
          fr: "Être présent pour ses amis et avoir un impact positif sur leur vie",
          ja: "友人のためにそばにいて、彼らの人生にいい影響を与えるとき",
          ko: "친구들을 위해 곁에 있어 주고 그들의 삶에 긍정적인 영향을 미칠 때",
        },
        weight: 3,
      },
      {
        id: "b",
        style: "adventurer",
        text: {
          zh: "分享令人兴奋的经历并创造持久的回忆时",
          en: "Share exciting experiences and create lasting memories",
          es: "Compartir experiencias emocionantes y crear recuerdos duraderos",
          fr: "Partager des expériences passionnantes et créer des souvenirs durables",
          ja: "エキサイティングな経験を共有し、長続きする思い出を作るとき",
          ko: "흥미진진한 경험을 공유하고 영원한 추억을 만들 때",
        },
        weight: 3,
      },
      {
        id: "c",
        style: "thinker",
        text: {
          zh: "在深度智力和情感层面上建立联系时",
          en: "Connect on a deep intellectual and emotional level",
          es: "Conectar a un nivel intelectual y emocional profundo",
          fr: "Établir un lien à un niveau intellectuel et émotionnel profond",
          ja: "深い知的、感情的なレベルでつながるとき",
          ko: "깊은 지적, 정서적 수준에서 연결될 때",
        },
        weight: 3,
      },
      {
        id: "d",
        style: "entertainer",
        text: {
          zh: "为他人的生活带来欢乐和笑声时",
          en: "Bring joy and laughter to others' lives",
          es: "Brindar alegría y risas a la vida de los demás",
          fr: "Apporter de la joie et des rires dans la vie des autres",
          ja: "他の人々の人生に喜びと笑いをもたらすとき",
          ko: "다른 사람들의 삶에 기쁨과 웃음을 가져다줄 때",
        },
        weight: 3,
      },
      {
        id: "e",
        style: "organizer",
        text: {
          zh: "保持大家联系并维持强大的集体动力时",
          en: "Keep everyone connected and maintain strong group dynamics",
          es: "Mantener a todos conectados y mantener una sólida dinámica de grupo",
          fr: "Maintenir tout le monde connecté et entretenir une dynamique de groupe forte",
          ja: "全員をつなぎとめ、強力なグループダイナミクスを維持するとき",
          ko: "모두를 연결하고 강력한 그룹 역동성을 유지할 때",
        },
        weight: 3,
      },
    ],
    scenario: {
      zh: "在友谊中，你什么时候感到最充实：",
      en: "You feel most fulfilled in friendships when you can:",
      es: "Te sientes más realizado en tus amistades cuando puedes:",
      fr: "Vous vous sentez le plus épanoui dans vos amitiés lorsque vous pouvez :",
      ja: "友人関係において、いつ最も充実感を感じますか：",
      ko: "친구 관계에서 언제 가장 만족감을 느끼나요:",
    },
  },
  {
    id: "10",
    options: [
      {
        id: "a",
        style: "supporter",
        text: {
          zh: "定期关心并提供持续的情感支持",
          en: "Regularly check in and provide ongoing emotional support",
          es: "Consultar regularmente y brindar apoyo emocional continuo",
          fr: "Prendre régulièrement des nouvelles et fournir un soutien émotionnel continu",
          ja: "定期的に連絡を取り、継続的な感情的サポートを提供する",
          ko: "정기적으로 연락하고 지속적인 정서적 지지를 제공한다",
        },
        weight: 2,
      },
      {
        id: "b",
        style: "adventurer",
        text: {
          zh: "在能见面时计划探访和冒险",
          en: "Plan visits and adventures when you can meet up",
          es: "Planificar visitas y aventuras cuando puedan reunirse",
          fr: "Planifier des visites et des aventures lorsque vous pouvez vous retrouver",
          ja: "会えるときに訪問や冒険を計画する",
          ko: "만날 수 있을 때 방문과 모험을 계획한다",
        },
        weight: 2,
      },
      {
        id: "c",
        style: "thinker",
        text: {
          zh: "在联系时进行有意义的交流",
          en: "Have a meaningful conversation when you do connect",
          es: "Tener una conversación significativa cuando se conectan",
          fr: "Avoir une conversation constructive lorsque vous vous contactez",
          ja: "つながったときに意味のある会話をする",
          ko: "연락이 됐을 때 의미 있는 대화를 나눈다",
        },
        weight: 2,
      },
      {
        id: "d",
        style: "entertainer",
        text: {
          zh: "利用幽默和积极性在虚拟空间保持联系",
          en: "Use humor and positivity to stay connected virtually",
          es: "Usar el humor y la positividad para mantenerse conectados virtualmente",
          fr: "Utiliser l'humour et la positivité pour rester connecté virtuellement",
          ja: "バーチャルでつながりを維持するために、ユーモアとポジティブさを使う",
          ko: "가상으로 연결 상태를 유지하기 위해 유머와 긍정적인 태도를 사용한다",
        },
        weight: 2,
      },
      {
        id: "e",
        style: "organizer",
        text: {
          zh: "安排定期的通话并关注重要的近况",
          en: "Schedule regular calls and keep track of important updates",
          es: "Programar llamadas regulares y estar al tanto de las actualizaciones importantes",
          fr: "Programmer des appels réguliers et se tenir au courant des nouvelles importantes",
          ja: "定期的な通話のスケジュールを立て、重要な更新を把握する",
          ko: "정기적인 통화 일정을 잡고 중요한 업데이트를 추적한다",
        },
        weight: 2,
      },
    ],
    scenario: {
      zh: "你维持远距离友谊的方法是：",
      en: "Your approach to maintaining long-distance friendships is to:",
      es: "Tu enfoque para mantener amistades a larga distancia es:",
      fr: "Votre approche pour entretenir des amitiés à longue distance consiste à :",
      ja: "遠距離の友人と関係を維持するためのあなたのアプローチは：",
      ko: "장거리 친구 관계를 유지하는 당신의 방식은:",
    },
  },
  {
    id: "11",
    options: [
      {
        id: "a",
        style: "supporter",
        text: {
          zh: "Something sentimental that shows I care",
          en: "Something sentimental that shows I care",
          es: "Something sentimental that shows I care",
          fr: "Something sentimental that shows I care",
          ja: "Something sentimental that shows I care",
          ko: "나의 마음을 표현하는 감성적인 것",
        },
        weight: 2,
      },
      {
        id: "b",
        style: "adventurer",
        text: {
          zh: "An experience or something fun to do together",
          en: "An experience or something fun to do together",
          es: "An experience or something fun to do together",
          fr: "An experience or something fun to do together",
          ja: "An experience or something fun to do together",
          ko: "함께 할 수 있는 경험이나 재미있는 것",
        },
        weight: 2,
      },
      {
        id: "c",
        style: "thinker",
        text: {
          zh: "A book or item related to their intellectual interests",
          en: "A book or item related to their intellectual interests",
          es: "A book or item related to their intellectual interests",
          fr: "A book or item related to their intellectual interests",
          ja: "A book or item related to their intellectual interests",
          ko: "그들의 지적 관심사와 관련된 책이나 물건",
        },
        weight: 2,
      },
      {
        id: "d",
        style: "entertainer",
        text: {
          zh: "Something funny or entertaining",
          en: "Something funny or entertaining",
          es: "Something funny or entertaining",
          fr: "Something funny or entertaining",
          ja: "Something funny or entertaining",
          ko: "재미있거나 즐거움을 주는 것",
        },
        weight: 2,
      },
      {
        id: "e",
        style: "organizer",
        text: {
          zh: "Something useful that they practically need",
          en: "Something useful that they practically need",
          es: "Something useful that they practically need",
          fr: "Something useful that they practically need",
          ja: "Something useful that they practically need",
          ko: "그들에게 실질적으로 필요한 유용한 것",
        },
        weight: 2,
      },
    ],
    scenario: {
      zh: "When giving a gift to a friend, you usually focus on:",
      en: "When giving a gift to a friend, you usually focus on:",
      es: "When giving a gift to a friend, you usually focus on:",
      fr: "When giving a gift to a friend, you usually focus on:",
      ja: "When giving a gift to a friend, you usually focus on:",
      ko: "친구에게 선물을 줄 때, 당신은 주로 어디에 중점을 두나요:",
    },
  },
  {
    id: "12",
    options: [
      {
        id: "a",
        style: "supporter",
        text: {
          zh: "Ensure everyone feels comfortable and safe",
          en: "Ensure everyone feels comfortable and safe",
          es: "Ensure everyone feels comfortable and safe",
          fr: "Ensure everyone feels comfortable and safe",
          ja: "Ensure everyone feels comfortable and safe",
          ko: "모두가 편안하고 안전하다고 느끼도록 한다",
        },
        weight: 2,
      },
      {
        id: "b",
        style: "adventurer",
        text: {
          zh: "Suggest a fun activity to break the ice",
          en: "Suggest a fun activity to break the ice",
          es: "Suggest a fun activity to break the ice",
          fr: "Suggest a fun activity to break the ice",
          ja: "Suggest a fun activity to break the ice",
          ko: "어색함을 깨기 위해 재미있는 활동을 제안한다",
        },
        weight: 2,
      },
      {
        id: "c",
        style: "thinker",
        text: {
          zh: "Find common topics they can discuss deeply",
          en: "Find common topics they can discuss deeply",
          es: "Find common topics they can discuss deeply",
          fr: "Find common topics they can discuss deeply",
          ja: "Find common topics they can discuss deeply",
          ko: "그들이 깊이 있게 토론할 수 있는 공통 주제를 찾는다",
        },
        weight: 2,
      },
      {
        id: "d",
        style: "entertainer",
        text: {
          zh: "Tell jokes and keep the energy high",
          en: "Tell jokes and keep the energy high",
          es: "Tell jokes and keep the energy high",
          fr: "Tell jokes and keep the energy high",
          ja: "Tell jokes and keep the energy high",
          ko: "농담을 하고 에너지를 높인다",
        },
        weight: 2,
      },
      {
        id: "e",
        style: "organizer",
        text: {
          zh: "Plan the logistics so the meeting runs smoothly",
          en: "Plan the logistics so the meeting runs smoothly",
          es: "Plan the logistics so the meeting runs smoothly",
          fr: "Plan the logistics so the meeting runs smoothly",
          ja: "Plan the logistics so the meeting runs smoothly",
          ko: "만남이 순조롭게 진행되도록 물류를 계획한다",
        },
        weight: 2,
      },
    ],
    scenario: {
      zh: "When introducing two different friend groups, you:",
      en: "When introducing two different friend groups, you:",
      es: "When introducing two different friend groups, you:",
      fr: "When introducing two different friend groups, you:",
      ja: "When introducing two different friend groups, you:",
      ko: "서로 다른 두 친구 그룹을 소개할 때, 당신은:",
    },
  },
];
