export interface CelticTreeSign {
  animal: string; // Totem Animal
  archetypeKey: string;
  celticName: string; // Beith
  dates: string; // "Dec 24 - Jan 20"
  descriptionKey: string;
  gemstone: string;
  id: string; // birch, rowan, etc.
  keywords: string[];
  meaning: string;
  name: string; // Birch
  ogham: string;
  tree: string; // Birch
  treeKey: string;
}

export const CELTIC_TREES: CelticTreeSign[] = [
  {
    animal: "White Stag",
    archetypeKey: "trees.birch.archetype",
    celticName: "Beith",
    dates: "Dec 24 - Jan 20",
    descriptionKey: "trees.birch.description",
    gemstone: "Rock Crystal",
    id: "birch",
    keywords: ["Ambition", "Leadership", "Discipline"],
    meaning: "New beginnings, change, and fresh starts.",
    name: "Birch",
    ogham: "Beith",
    tree: "The Achiever",
    treeKey: "trees.birch.tree",
  },
  {
    animal: "Green Dragon",
    archetypeKey: "trees.rowan.archetype",
    celticName: "Luis",
    dates: "Jan 21 - Feb 17",
    descriptionKey: "trees.rowan.description",
    gemstone: "Peridot",
    id: "rowan",
    keywords: ["Philosophy", "Protection", "Sensitivity"],
    meaning: "Vision, protection, and inspiration.",
    name: "Rowan",
    ogham: "Luis",
    tree: "The Thinker",
    treeKey: "trees.rowan.tree",
  },
  {
    animal: "Seahorse",
    archetypeKey: "trees.ash.archetype",
    celticName: "Nion",
    dates: "Feb 18 - Mar 17",
    descriptionKey: "trees.ash.description",
    gemstone: "Coral",
    id: "ash",
    keywords: ["Artistic", "Intuitive", "Dreamer"],
    meaning: "Connection, imagination, and free thinking.",
    name: "Ash",
    ogham: "Nion",
    tree: "The Enchanter",
    treeKey: "trees.ash.tree",
  },
  {
    animal: "Hawk",
    archetypeKey: "trees.alder.archetype",
    celticName: "Fearn",
    dates: "Mar 18 - Apr 14",
    descriptionKey: "trees.alder.description",
    gemstone: "Ruby",
    id: "alder",
    keywords: ["Passion", "Courage", "Confidence"],
    meaning: "Guidance, passion, and adventure.",
    name: "Alder",
    ogham: "Fearn",
    tree: "The Trailblazer",
    treeKey: "trees.alder.tree",
  },
  {
    animal: "Sea Serpent",
    archetypeKey: "trees.willow.archetype",
    celticName: "Saille",
    dates: "Apr 15 - May 12",
    descriptionKey: "trees.willow.description",
    gemstone: "Moonstone",
    id: "willow",
    keywords: ["Memory", "Intuition", "Patient"],
    meaning: "Intuition, mystery, and lunar cycles.",
    name: "Willow",
    ogham: "Saille",
    tree: "The Observer",
    treeKey: "trees.willow.tree",
  },
  {
    animal: "Chalice",
    archetypeKey: "trees.hawthorn.archetype",
    celticName: "Uath",
    dates: "May 13 - Jun 9",
    descriptionKey: "trees.hawthorn.description",
    gemstone: "Topaz",
    id: "hawthorn",
    keywords: ["Versatile", "Curious", "Insightful"],
    meaning: "Contradiction, complexity, and passion.",
    name: "Hawthorn",
    ogham: "Uath",
    tree: "The Illusionist",
    treeKey: "trees.hawthorn.tree",
  },
  {
    animal: "White Horse",
    archetypeKey: "trees.oak.archetype",
    celticName: "Duir",
    dates: "Jun 10 - Jul 7",
    descriptionKey: "trees.oak.description",
    gemstone: "Diamond",
    id: "oak",
    keywords: ["Strength", "Generosity", "Helpful"],
    meaning: "Strength, protection, and nurturing.",
    name: "Oak",
    ogham: "Duir",
    tree: "The Stabilizer",
    treeKey: "trees.oak.tree",
  },
  {
    animal: "Unicorn",
    archetypeKey: "trees.holly.archetype",
    celticName: "Tinne",
    dates: "Jul 8 - Aug 4",
    descriptionKey: "trees.holly.description",
    gemstone: "Carnelian",
    id: "holly",
    keywords: ["Noble", "Confident", "Leader"],
    meaning: "Challenge, nobility, and honor.",
    name: "Holly",
    ogham: "Tinne",
    tree: "The Ruler",
    treeKey: "trees.holly.tree",
  },
  {
    animal: "Salmon",
    archetypeKey: "trees.hazel.archetype",
    celticName: "Coll",
    dates: "Aug 5 - Sep 1",
    descriptionKey: "trees.hazel.description",
    gemstone: "Amethyst",
    id: "hazel",
    keywords: ["Clever", "Academic", "Detail-oriented"],
    meaning: "Wisdom, creativity, and knowledge.",
    name: "Hazel",
    ogham: "Coll",
    tree: "The Knower",
    treeKey: "trees.hazel.tree",
  },
  {
    animal: "Swan",
    archetypeKey: "trees.vine.archetype",
    celticName: "Muin",
    dates: "Sep 2 - Sep 29",
    descriptionKey: "trees.vine.description",
    gemstone: "Emerald",
    id: "vine",
    keywords: ["Charming", "Elegant", "Refined"],
    meaning: "Unpredictability, harvest, and emotion.",
    name: "Vine",
    ogham: "Muin",
    tree: "The Equalizer",
    treeKey: "trees.vine.tree",
  },
  {
    animal: "Butterfly",
    archetypeKey: "trees.ivy.archetype",
    celticName: "Gort",
    dates: "Sep 30 - Oct 27",
    descriptionKey: "trees.ivy.description",
    gemstone: "Opal",
    id: "ivy",
    keywords: ["Loyal", "Compassionate", "Spiritual"],
    meaning: "Determination, will, and survival.",
    name: "Ivy",
    ogham: "Gort",
    tree: "The Survivor",
    treeKey: "trees.ivy.tree",
  },
  {
    animal: "White Hound",
    archetypeKey: "trees.reed.archetype",
    celticName: "Ngetal",
    dates: "Oct 28 - Nov 24",
    descriptionKey: "trees.reed.description",
    gemstone: "Jasper",
    id: "reed",
    keywords: ["Truth-seeker", "Fearless", "Investigator"],
    meaning: "Secrets, truth, and inquiry.",
    name: "Reed",
    ogham: "Ngetal",
    tree: "The Inquisitor",
    treeKey: "trees.reed.tree",
  },
  {
    animal: "Black Horse",
    archetypeKey: "trees.elder.archetype",
    celticName: "Ruis",
    dates: "Nov 25 - Dec 22",
    descriptionKey: "trees.elder.description",
    gemstone: "Jet",
    id: "elder",
    keywords: ["Freedom", "Wild", "Honest"],
    meaning: "Transformation, cycle end, and judgment.",
    name: "Elder",
    ogham: "Ruis",
    tree: "The Seeker",
    treeKey: "trees.elder.tree",
  },
  // Nameless Day
  {
    animal: "Black Eagle",
    archetypeKey: "celtic.trees.elder.archetype",
    celticName: "Mistletoe",
    dates: "Dec 23",
    descriptionKey: "celtic.trees.elder.description",
    gemstone: "Black Pearl",
    id: "nameless",
    keywords: ["Mystery", "Potential", "Magic"],
    meaning: "The day that is not a day. Potentiality and magic.",
    name: "Nameless Day",
    ogham: "Nameless",
    tree: "The Void",
    treeKey: "celtic.trees.elder.tree", // Fallback to elder or add nameless to i18n
  },
];
