// Type definitions imported in types.ts

export const DECISION_MAKING_QUESTIONS = {
  en: [
    {
      emoji: "🤔",
      id: "1",
      options: [
        {
          emoji: "📊",
          id: "a",
          scores: {
            analytical: 3,
            cautious: 2,
            collaborative: 1,
            creative: 1,
            decisive: 0,
            intuitive: 0,
          },
          text: "Research extensively and analyze all available data",
        },
        {
          emoji: "💭",
          id: "b",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 2,
            decisive: 2,
            intuitive: 3,
          },
          text: "Go with your gut feeling about what feels right",
        },
        {
          emoji: "👥",
          id: "c",
          scores: {
            analytical: 1,
            cautious: 1,
            collaborative: 3,
            creative: 1,
            decisive: 0,
            intuitive: 0,
          },
          text: "Consult with others and gather different perspectives",
        },
        {
          emoji: "⚡",
          id: "d",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 1,
            decisive: 3,
            intuitive: 2,
          },
          text: "Make a quick decision and move forward",
        },
        {
          emoji: "⚖️",
          id: "e",
          scores: {
            analytical: 2,
            cautious: 3,
            collaborative: 1,
            creative: 0,
            decisive: 0,
            intuitive: 0,
          },
          text: "Take time to carefully weigh all the risks",
        },
        {
          emoji: "💡",
          id: "f",
          scores: {
            analytical: 1,
            cautious: 0,
            collaborative: 1,
            creative: 3,
            decisive: 1,
            intuitive: 1,
          },
          text: "Look for innovative solutions others haven't considered",
        },
      ],
      text: "When facing a major decision, you typically:",
    },
    {
      emoji: "💼",
      id: "2",
      options: [
        {
          emoji: "📋",
          id: "a",
          scores: {
            analytical: 3,
            cautious: 2,
            collaborative: 0,
            creative: 0,
            decisive: 1,
            intuitive: 0,
          },
          text: "Create a detailed comparison spreadsheet of all factors",
        },
        {
          emoji: "🎭",
          id: "b",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 1,
            creative: 2,
            decisive: 1,
            intuitive: 3,
          },
          text: "Imagine yourself in each role and see which feels better",
        },
        {
          emoji: "🗣️",
          id: "c",
          scores: {
            analytical: 1,
            cautious: 1,
            collaborative: 3,
            creative: 1,
            decisive: 0,
            intuitive: 1,
          },
          text: "Ask friends, family, and mentors for their opinions",
        },
        {
          emoji: "🎯",
          id: "d",
          scores: {
            analytical: 1,
            cautious: 0,
            collaborative: 0,
            creative: 1,
            decisive: 3,
            intuitive: 1,
          },
          text: "Choose the one that offers the best immediate opportunity",
        },
        {
          emoji: "🔍",
          id: "e",
          scores: {
            analytical: 2,
            cautious: 3,
            collaborative: 1,
            creative: 0,
            decisive: 0,
            intuitive: 0,
          },
          text: "Thoroughly research both companies and their stability",
        },
        {
          emoji: "🎨",
          id: "f",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 1,
            creative: 3,
            decisive: 1,
            intuitive: 2,
          },
          text: "Consider which role allows for more creative freedom",
        },
      ],
      text: "When you have to choose between two job offers, you:",
    },
    {
      emoji: "🚀",
      id: "3",
      options: [
        {
          emoji: "📈",
          id: "a",
          scores: {
            analytical: 3,
            cautious: 1,
            collaborative: 1,
            creative: 0,
            decisive: 2,
            intuitive: 0,
          },
          text: "Present data and logical arguments for your preferred option",
        },
        {
          emoji: "🧭",
          id: "b",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 2,
            creative: 2,
            decisive: 1,
            intuitive: 3,
          },
          text: "Share your instincts about which direction feels right",
        },
        {
          emoji: "🤝",
          id: "c",
          scores: {
            analytical: 1,
            cautious: 1,
            collaborative: 3,
            creative: 1,
            decisive: 0,
            intuitive: 1,
          },
          text: "Facilitate discussion to find consensus among all members",
        },
        {
          emoji: "⏰",
          id: "d",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 1,
            creative: 1,
            decisive: 3,
            intuitive: 1,
          },
          text: "Advocate strongly for making a decision quickly",
        },
        {
          emoji: "🔬",
          id: "e",
          scores: {
            analytical: 2,
            cautious: 3,
            collaborative: 1,
            creative: 0,
            decisive: 0,
            intuitive: 0,
          },
          text: "Suggest more research before committing to any direction",
        },
        {
          emoji: "🌈",
          id: "f",
          scores: {
            analytical: 1,
            cautious: 0,
            collaborative: 2,
            creative: 3,
            decisive: 1,
            intuitive: 1,
          },
          text: "Propose an innovative approach that combines multiple ideas",
        },
      ],
      text: "In a group project where you need to choose a direction, you:",
    },
    {
      emoji: "🚗",
      id: "4",
      options: [
        {
          emoji: "📊",
          id: "a",
          scores: {
            analytical: 3,
            cautious: 2,
            collaborative: 1,
            creative: 0,
            decisive: 1,
            intuitive: 0,
          },
          text: "Compare specs, reviews, and prices across multiple models",
        },
        {
          emoji: "🛣️",
          id: "b",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 1,
            decisive: 2,
            intuitive: 3,
          },
          text: "Test drive a few and go with the one that feels right",
        },
        {
          emoji: "💬",
          id: "c",
          scores: {
            analytical: 1,
            cautious: 2,
            collaborative: 3,
            creative: 0,
            decisive: 0,
            intuitive: 0,
          },
          text: "Ask friends and read online forums for recommendations",
        },
        {
          emoji: "✅",
          id: "d",
          scores: {
            analytical: 1,
            cautious: 0,
            collaborative: 0,
            creative: 0,
            decisive: 3,
            intuitive: 2,
          },
          text: "Choose quickly once you find one that meets your needs",
        },
        {
          emoji: "🛡️",
          id: "e",
          scores: {
            analytical: 2,
            cautious: 3,
            collaborative: 1,
            creative: 0,
            decisive: 0,
            intuitive: 0,
          },
          text: "Research reliability, resale value, and warranty extensively",
        },
        {
          emoji: "⭐",
          id: "f",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 3,
            decisive: 1,
            intuitive: 1,
          },
          text: "Look for unique features or customization options",
        },
      ],
      text: "When buying a major purchase like a car, you:",
    },
    {
      emoji: "🚨",
      id: "5",
      options: [
        {
          emoji: "🔍",
          id: "a",
          scores: {
            analytical: 3,
            cautious: 2,
            collaborative: 1,
            creative: 1,
            decisive: 1,
            intuitive: 0,
          },
          text: "Gather information and analyze the root cause systematically",
        },
        {
          emoji: "🎯",
          id: "b",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 2,
            decisive: 2,
            intuitive: 3,
          },
          text: "Trust your experience to guide you to a quick solution",
        },
        {
          emoji: "💡",
          id: "c",
          scores: {
            analytical: 1,
            cautious: 1,
            collaborative: 3,
            creative: 2,
            decisive: 0,
            intuitive: 1,
          },
          text: "Bring the team together to brainstorm solutions",
        },
        {
          emoji: "🏃‍♀️",
          id: "d",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 1,
            decisive: 3,
            intuitive: 1,
          },
          text: "Take immediate action to address the most urgent aspects",
        },
        {
          emoji: "⚠️",
          id: "e",
          scores: {
            analytical: 2,
            cautious: 3,
            collaborative: 1,
            creative: 0,
            decisive: 0,
            intuitive: 0,
          },
          text: "Assess all risks before implementing any solution",
        },
        {
          emoji: "🎪",
          id: "f",
          scores: {
            analytical: 1,
            cautious: 0,
            collaborative: 1,
            creative: 3,
            decisive: 1,
            intuitive: 2,
          },
          text: "Look for unconventional approaches to solve the problem",
        },
      ],
      text: "When your team faces an unexpected problem, you:",
    },
    {
      emoji: "🏖️",
      id: "6",
      options: [
        {
          emoji: "📅",
          id: "a",
          scores: {
            analytical: 3,
            cautious: 2,
            collaborative: 1,
            creative: 0,
            decisive: 1,
            intuitive: 0,
          },
          text: "Research destinations, costs, and create detailed itineraries",
        },
        {
          emoji: "❤️",
          id: "b",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 2,
            decisive: 2,
            intuitive: 3,
          },
          text: "Choose a place that intuitively appeals to you",
        },
        {
          emoji: "👨‍👩‍👧‍👦",
          id: "c",
          scores: {
            analytical: 0,
            cautious: 1,
            collaborative: 3,
            creative: 1,
            decisive: 0,
            intuitive: 1,
          },
          text: "Ask for input from family or friends on where to go",
        },
        {
          emoji: "💫",
          id: "d",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 1,
            decisive: 3,
            intuitive: 2,
          },
          text: "Book the first good deal you find",
        },
        {
          emoji: "🛡️",
          id: "e",
          scores: {
            analytical: 2,
            cautious: 3,
            collaborative: 1,
            creative: 0,
            decisive: 0,
            intuitive: 0,
          },
          text: "Carefully consider budget, safety, and weather factors",
        },
        {
          emoji: "🗺️",
          id: "f",
          scores: {
            analytical: 1,
            cautious: 0,
            collaborative: 1,
            creative: 3,
            decisive: 1,
            intuitive: 2,
          },
          text: "Look for unique experiences and off-the-beaten-path destinations",
        },
      ],
      text: "When planning a vacation, your approach is to:",
    },
    {
      emoji: "🍽️",
      id: "7",
      options: [
        {
          emoji: "📖",
          id: "a",
          scores: {
            analytical: 3,
            cautious: 2,
            collaborative: 1,
            creative: 0,
            decisive: 0,
            intuitive: 0,
          },
          text: "Read reviews and ask detailed questions about ingredients",
        },
        {
          emoji: "✨",
          id: "b",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 2,
            decisive: 2,
            intuitive: 3,
          },
          text: "Go with whatever sounds appealing at first glance",
        },
        {
          emoji: "🗣️",
          id: "c",
          scores: {
            analytical: 0,
            cautious: 1,
            collaborative: 3,
            creative: 1,
            decisive: 0,
            intuitive: 1,
          },
          text: "Ask your dining companions for recommendations",
        },
        {
          emoji: "⚡",
          id: "d",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 1,
            decisive: 3,
            intuitive: 2,
          },
          text: "Choose quickly without overthinking it",
        },
        {
          emoji: "🏠",
          id: "e",
          scores: {
            analytical: 1,
            cautious: 3,
            collaborative: 0,
            creative: 0,
            decisive: 1,
            intuitive: 0,
          },
          text: "Stick to familiar dishes to avoid disappointment",
        },
        {
          emoji: "🎭",
          id: "f",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 3,
            decisive: 2,
            intuitive: 2,
          },
          text: "Try the most unique or unusual item on the menu",
        },
      ],
      text: "When choosing what to order at a new restaurant, you:",
    },
    {
      emoji: "💰",
      id: "8",
      options: [
        {
          emoji: "📈",
          id: "a",
          scores: {
            analytical: 3,
            cautious: 2,
            collaborative: 1,
            creative: 0,
            decisive: 1,
            intuitive: 0,
          },
          text: "Research market trends and analyze financial statements",
        },
        {
          emoji: "💫",
          id: "b",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 1,
            decisive: 2,
            intuitive: 3,
          },
          text: "Invest in companies and sectors you have good feelings about",
        },
        {
          emoji: "👨‍💼",
          id: "c",
          scores: {
            analytical: 1,
            cautious: 2,
            collaborative: 3,
            creative: 0,
            decisive: 0,
            intuitive: 0,
          },
          text: "Follow advice from trusted financial advisors or friends",
        },
        {
          emoji: "🚀",
          id: "d",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 2,
            decisive: 3,
            intuitive: 1,
          },
          text: "Make quick decisions to capitalize on market opportunities",
        },
        {
          emoji: "🛡️",
          id: "e",
          scores: {
            analytical: 2,
            cautious: 3,
            collaborative: 1,
            creative: 0,
            decisive: 0,
            intuitive: 0,
          },
          text: "Choose conservative, low-risk investments",
        },
        {
          emoji: "🔬",
          id: "f",
          scores: {
            analytical: 1,
            cautious: 0,
            collaborative: 0,
            creative: 3,
            decisive: 2,
            intuitive: 2,
          },
          text: "Look for innovative startups and emerging technologies",
        },
      ],
      text: "When investing money, your strategy is to:",
    },
    {
      emoji: "⏰",
      id: "9",
      options: [
        {
          emoji: "⚖️",
          id: "a",
          scores: {
            analytical: 3,
            cautious: 1,
            collaborative: 0,
            creative: 0,
            decisive: 2,
            intuitive: 1,
          },
          text: "Quickly analyze the pros and cons of each option",
        },
        {
          emoji: "🎯",
          id: "b",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 1,
            decisive: 2,
            intuitive: 3,
          },
          text: "Go with your first instinct about the best choice",
        },
        {
          emoji: "🗳️",
          id: "c",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 3,
            creative: 1,
            decisive: 1,
            intuitive: 1,
          },
          text: "Quickly poll team members for their preferences",
        },
        {
          emoji: "⚡",
          id: "d",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 1,
            decisive: 3,
            intuitive: 2,
          },
          text: "Make a decision immediately and stick with it",
        },
        {
          emoji: "🛡️",
          id: "e",
          scores: {
            analytical: 1,
            cautious: 3,
            collaborative: 1,
            creative: 0,
            decisive: 1,
            intuitive: 0,
          },
          text: "Choose the safest option that minimizes risk",
        },
        {
          emoji: "🌈",
          id: "f",
          scores: {
            analytical: 1,
            cautious: 0,
            collaborative: 1,
            creative: 3,
            decisive: 2,
            intuitive: 1,
          },
          text: "Find a creative way to combine multiple options",
        },
      ],
      text: "When facing a deadline with multiple options, you:",
    },
    {
      emoji: "💭",
      id: "10",
      options: [
        {
          emoji: "🧠",
          id: "a",
          scores: {
            analytical: 3,
            cautious: 2,
            collaborative: 1,
            creative: 0,
            decisive: 1,
            intuitive: 0,
          },
          text: "Good decisions require thorough analysis and evidence",
        },
        {
          emoji: "💡",
          id: "b",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 2,
            decisive: 2,
            intuitive: 3,
          },
          text: "Trust your instincts - they usually know what's right",
        },
        {
          emoji: "👥",
          id: "c",
          scores: {
            analytical: 1,
            cautious: 1,
            collaborative: 3,
            creative: 1,
            decisive: 0,
            intuitive: 1,
          },
          text: "Two heads are better than one - involve others",
        },
        {
          emoji: "🎢",
          id: "d",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 2,
            decisive: 3,
            intuitive: 2,
          },
          text: "Don't overthink it - make decisions and adjust as needed",
        },
        {
          emoji: "⚖️",
          id: "e",
          scores: {
            analytical: 2,
            cautious: 3,
            collaborative: 1,
            creative: 0,
            decisive: 0,
            intuitive: 0,
          },
          text: "Better safe than sorry - consider all risks first",
        },
        {
          emoji: "🎨",
          id: "f",
          scores: {
            analytical: 1,
            cautious: 0,
            collaborative: 1,
            creative: 3,
            decisive: 1,
            intuitive: 2,
          },
          text: "The best solutions often come from thinking differently",
        },
      ],
      text: "Your philosophy about decision-making is:",
    },
  ],
  ko: [
    {
      emoji: "🤔",
      id: "1",
      options: [
        {
          emoji: "📊",
          id: "a",
          scores: {
            analytical: 3,
            cautious: 2,
            collaborative: 1,
            creative: 1,
            decisive: 0,
            intuitive: 0,
          },
          text: "광범위하게 조사하고 이용 가능한 모든 데이터를 분석한다",
        },
        {
          emoji: "💭",
          id: "b",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 2,
            decisive: 2,
            intuitive: 3,
          },
          text: "무엇이 옳은 느낌인지 직감에 따른다",
        },
        {
          emoji: "👥",
          id: "c",
          scores: {
            analytical: 1,
            cautious: 1,
            collaborative: 3,
            creative: 1,
            decisive: 0,
            intuitive: 0,
          },
          text: "다른 사람들과 상의하고 다양한 관점을 수집한다",
        },
        {
          emoji: "⚡",
          id: "d",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 1,
            decisive: 3,
            intuitive: 2,
          },
          text: "빠르게 결정을 내리고 앞으로 나아간다",
        },
        {
          emoji: "⚖️",
          id: "e",
          scores: {
            analytical: 2,
            cautious: 3,
            collaborative: 1,
            creative: 0,
            decisive: 0,
            intuitive: 0,
          },
          text: "모든 위험을 신중히 검토할 시간을 갖는다",
        },
        {
          emoji: "💡",
          id: "f",
          scores: {
            analytical: 1,
            cautious: 0,
            collaborative: 1,
            creative: 3,
            decisive: 1,
            intuitive: 1,
          },
          text: "다른 사람들이 고려하지 않은 혁신적인 해결책을 찾는다",
        },
      ],
      text: "중요한 결정을 내려야 할 때, 당신은 보통:",
    },
    {
      emoji: "💼",
      id: "2",
      options: [
        {
          emoji: "📋",
          id: "a",
          scores: {
            analytical: 3,
            cautious: 2,
            collaborative: 0,
            creative: 0,
            decisive: 1,
            intuitive: 0,
          },
          text: "모든 요소의 상세한 비교 스프레드시트를 만든다",
        },
        {
          emoji: "🎭",
          id: "b",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 1,
            creative: 2,
            decisive: 1,
            intuitive: 3,
          },
          text: "각 역할에 자신을 상상해보고 어느 것이 더 좋은 느낌인지 본다",
        },
        {
          emoji: "🗣️",
          id: "c",
          scores: {
            analytical: 1,
            cautious: 1,
            collaborative: 3,
            creative: 1,
            decisive: 0,
            intuitive: 1,
          },
          text: "친구, 가족, 멘토들에게 의견을 구한다",
        },
        {
          emoji: "🎯",
          id: "d",
          scores: {
            analytical: 1,
            cautious: 0,
            collaborative: 0,
            creative: 1,
            decisive: 3,
            intuitive: 1,
          },
          text: "즉시 최고의 기회를 제공하는 것을 선택한다",
        },
        {
          emoji: "🔍",
          id: "e",
          scores: {
            analytical: 2,
            cautious: 3,
            collaborative: 1,
            creative: 0,
            decisive: 0,
            intuitive: 0,
          },
          text: "두 회사와 그 안정성을 철저히 조사한다",
        },
        {
          emoji: "🎨",
          id: "f",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 1,
            creative: 3,
            decisive: 1,
            intuitive: 2,
          },
          text: "어느 역할이 더 많은 창의적 자유를 허용하는지 고려한다",
        },
      ],
      text: "두 개의 취업 제안 중에서 선택해야 할 때, 당신은:",
    },
    {
      emoji: "🚀",
      id: "3",
      options: [
        {
          emoji: "📈",
          id: "a",
          scores: {
            analytical: 3,
            cautious: 1,
            collaborative: 1,
            creative: 0,
            decisive: 2,
            intuitive: 0,
          },
          text: "선호하는 옵션에 대한 데이터와 논리적 논거를 제시한다",
        },
        {
          emoji: "🧭",
          id: "b",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 2,
            creative: 2,
            decisive: 1,
            intuitive: 3,
          },
          text: "어느 방향이 옳은 느낌인지에 대한 직감을 공유한다",
        },
        {
          emoji: "🤝",
          id: "c",
          scores: {
            analytical: 1,
            cautious: 1,
            collaborative: 3,
            creative: 1,
            decisive: 0,
            intuitive: 1,
          },
          text: "모든 구성원들 사이에서 합의를 찾기 위한 논의를 촉진한다",
        },
        {
          emoji: "⏰",
          id: "d",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 1,
            creative: 1,
            decisive: 3,
            intuitive: 1,
          },
          text: "빠른 결정을 내리는 것을 강력히 주장한다",
        },
        {
          emoji: "🔬",
          id: "e",
          scores: {
            analytical: 2,
            cautious: 3,
            collaborative: 1,
            creative: 0,
            decisive: 0,
            intuitive: 0,
          },
          text: "어떤 방향에도 집중하기 전에 더 많은 연구를 제안한다",
        },
        {
          emoji: "🌈",
          id: "f",
          scores: {
            analytical: 1,
            cautious: 0,
            collaborative: 2,
            creative: 3,
            decisive: 1,
            intuitive: 1,
          },
          text: "여러 아이디어를 결합하는 혁신적인 접근법을 제안한다",
        },
      ],
      text: "방향을 선택해야 하는 그룹 프로젝트에서 당신은:",
    },
    {
      emoji: "🚗",
      id: "4",
      options: [
        {
          emoji: "📊",
          id: "a",
          scores: {
            analytical: 3,
            cautious: 2,
            collaborative: 1,
            creative: 0,
            decisive: 1,
            intuitive: 0,
          },
          text: "여러 모델의 사양, 리뷰, 가격을 비교한다",
        },
        {
          emoji: "🛣️",
          id: "b",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 1,
            decisive: 2,
            intuitive: 3,
          },
          text: "몇 대를 시승해보고 올바른 느낌이 드는 것을 선택한다",
        },
        {
          emoji: "💬",
          id: "c",
          scores: {
            analytical: 1,
            cautious: 2,
            collaborative: 3,
            creative: 0,
            decisive: 0,
            intuitive: 0,
          },
          text: "친구들에게 묻고 온라인 포럼에서 추천을 읽는다",
        },
        {
          emoji: "✅",
          id: "d",
          scores: {
            analytical: 1,
            cautious: 0,
            collaborative: 0,
            creative: 0,
            decisive: 3,
            intuitive: 2,
          },
          text: "필요를 충족하는 것을 찾으면 빠르게 선택한다",
        },
        {
          emoji: "🛡️",
          id: "e",
          scores: {
            analytical: 2,
            cautious: 3,
            collaborative: 1,
            creative: 0,
            decisive: 0,
            intuitive: 0,
          },
          text: "신뢰성, 재판매 가치, 보증을 광범위하게 조사한다",
        },
        {
          emoji: "⭐",
          id: "f",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 3,
            decisive: 1,
            intuitive: 1,
          },
          text: "독특한 기능이나 커스터마이징 옵션을 찾는다",
        },
      ],
      text: "자동차와 같은 큰 구매를 할 때, 당신은:",
    },
    {
      emoji: "🚨",
      id: "5",
      options: [
        {
          emoji: "🔍",
          id: "a",
          scores: {
            analytical: 3,
            cautious: 2,
            collaborative: 1,
            creative: 1,
            decisive: 1,
            intuitive: 0,
          },
          text: "정보를 수집하고 근본 원인을 체계적으로 분석한다",
        },
        {
          emoji: "🎯",
          id: "b",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 2,
            decisive: 2,
            intuitive: 3,
          },
          text: "경험에 의존하여 빠른 해결책으로 안내한다",
        },
        {
          emoji: "💡",
          id: "c",
          scores: {
            analytical: 1,
            cautious: 1,
            collaborative: 3,
            creative: 2,
            decisive: 0,
            intuitive: 1,
          },
          text: "팀을 모아 해결책을 브레인스토밍한다",
        },
        {
          emoji: "🏃‍♀️",
          id: "d",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 1,
            decisive: 3,
            intuitive: 1,
          },
          text: "가장 긴급한 측면을 해결하기 위해 즉시 행동을 취한다",
        },
        {
          emoji: "⚠️",
          id: "e",
          scores: {
            analytical: 2,
            cautious: 3,
            collaborative: 1,
            creative: 0,
            decisive: 0,
            intuitive: 0,
          },
          text: "어떤 해결책도 실행하기 전에 모든 위험을 평가한다",
        },
        {
          emoji: "🎪",
          id: "f",
          scores: {
            analytical: 1,
            cautious: 0,
            collaborative: 1,
            creative: 3,
            decisive: 1,
            intuitive: 2,
          },
          text: "문제를 해결하기 위한 비관습적인 접근법을 찾는다",
        },
      ],
      text: "팀이 예상치 못한 문제에 직면했을 때, 당신은:",
    },
    {
      emoji: "🏖️",
      id: "6",
      options: [
        {
          emoji: "📅",
          id: "a",
          scores: {
            analytical: 3,
            cautious: 2,
            collaborative: 1,
            creative: 0,
            decisive: 1,
            intuitive: 0,
          },
          text: "목적지, 비용을 조사하고 상세한 일정을 만든다",
        },
        {
          emoji: "❤️",
          id: "b",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 2,
            decisive: 2,
            intuitive: 3,
          },
          text: "직관적으로 매력적인 장소를 선택한다",
        },
        {
          emoji: "👨‍👩‍👧‍👦",
          id: "c",
          scores: {
            analytical: 0,
            cautious: 1,
            collaborative: 3,
            creative: 1,
            decisive: 0,
            intuitive: 1,
          },
          text: "가족이나 친구들에게 어디로 갈지 의견을 구한다",
        },
        {
          emoji: "💫",
          id: "d",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 1,
            decisive: 3,
            intuitive: 2,
          },
          text: "찾은 첫 번째 좋은 거래를 예약한다",
        },
        {
          emoji: "🛡️",
          id: "e",
          scores: {
            analytical: 2,
            cautious: 3,
            collaborative: 1,
            creative: 0,
            decisive: 0,
            intuitive: 0,
          },
          text: "예산, 안전, 날씨 요인을 신중히 고려한다",
        },
        {
          emoji: "🗺️",
          id: "f",
          scores: {
            analytical: 1,
            cautious: 0,
            collaborative: 1,
            creative: 3,
            decisive: 1,
            intuitive: 2,
          },
          text: "독특한 경험과 사람들이 잘 모르는 목적지를 찾는다",
        },
      ],
      text: "휴가를 계획할 때, 당신의 접근법은:",
    },
    {
      emoji: "🍽️",
      id: "7",
      options: [
        {
          emoji: "📖",
          id: "a",
          scores: {
            analytical: 3,
            cautious: 2,
            collaborative: 1,
            creative: 0,
            decisive: 0,
            intuitive: 0,
          },
          text: "리뷰를 읽고 재료에 대해 자세한 질문을 한다",
        },
        {
          emoji: "✨",
          id: "b",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 2,
            decisive: 2,
            intuitive: 3,
          },
          text: "첫눈에 매력적으로 들리는 것을 선택한다",
        },
        {
          emoji: "🗣️",
          id: "c",
          scores: {
            analytical: 0,
            cautious: 1,
            collaborative: 3,
            creative: 1,
            decisive: 0,
            intuitive: 1,
          },
          text: "함께 식사하는 사람들에게 추천을 구한다",
        },
        {
          emoji: "⚡",
          id: "d",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 1,
            decisive: 3,
            intuitive: 2,
          },
          text: "과도하게 생각하지 않고 빠르게 선택한다",
        },
        {
          emoji: "🏠",
          id: "e",
          scores: {
            analytical: 1,
            cautious: 3,
            collaborative: 0,
            creative: 0,
            decisive: 1,
            intuitive: 0,
          },
          text: "실망을 피하기 위해 익숙한 음식을 고수한다",
        },
        {
          emoji: "🎭",
          id: "f",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 3,
            decisive: 2,
            intuitive: 2,
          },
          text: "메뉴에서 가장 독특하거나 특이한 항목을 시도한다",
        },
      ],
      text: "새로운 레스토랑에서 주문할 것을 선택할 때, 당신은:",
    },
    {
      emoji: "💰",
      id: "8",
      options: [
        {
          emoji: "📈",
          id: "a",
          scores: {
            analytical: 3,
            cautious: 2,
            collaborative: 1,
            creative: 0,
            decisive: 1,
            intuitive: 0,
          },
          text: "시장 동향을 연구하고 재무제표를 분석한다",
        },
        {
          emoji: "💫",
          id: "b",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 1,
            decisive: 2,
            intuitive: 3,
          },
          text: "좋은 느낌이 드는 회사와 섹터에 투자한다",
        },
        {
          emoji: "👨‍💼",
          id: "c",
          scores: {
            analytical: 1,
            cautious: 2,
            collaborative: 3,
            creative: 0,
            decisive: 0,
            intuitive: 0,
          },
          text: "신뢰하는 재정 고문이나 친구들의 조언을 따른다",
        },
        {
          emoji: "🚀",
          id: "d",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 2,
            decisive: 3,
            intuitive: 1,
          },
          text: "시장 기회를 활용하기 위해 빠른 결정을 내린다",
        },
        {
          emoji: "🛡️",
          id: "e",
          scores: {
            analytical: 2,
            cautious: 3,
            collaborative: 1,
            creative: 0,
            decisive: 0,
            intuitive: 0,
          },
          text: "보수적이고 저위험 투자를 선택한다",
        },
        {
          emoji: "🔬",
          id: "f",
          scores: {
            analytical: 1,
            cautious: 0,
            collaborative: 0,
            creative: 3,
            decisive: 2,
            intuitive: 2,
          },
          text: "혁신적인 스타트업과 신흥 기술을 찾는다",
        },
      ],
      text: "돈을 투자할 때, 당신의 전략은:",
    },
    {
      emoji: "⏰",
      id: "9",
      options: [
        {
          emoji: "⚖️",
          id: "a",
          scores: {
            analytical: 3,
            cautious: 1,
            collaborative: 0,
            creative: 0,
            decisive: 2,
            intuitive: 1,
          },
          text: "각 옵션의 장단점을 빠르게 분석한다",
        },
        {
          emoji: "🎯",
          id: "b",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 1,
            decisive: 2,
            intuitive: 3,
          },
          text: "최선의 선택에 대한 첫 번째 직감을 따른다",
        },
        {
          emoji: "🗳️",
          id: "c",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 3,
            creative: 1,
            decisive: 1,
            intuitive: 1,
          },
          text: "팀원들에게 그들의 선호도를 빠르게 조사한다",
        },
        {
          emoji: "⚡",
          id: "d",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 1,
            decisive: 3,
            intuitive: 2,
          },
          text: "즉시 결정을 내리고 그것을 고수한다",
        },
        {
          emoji: "🛡️",
          id: "e",
          scores: {
            analytical: 1,
            cautious: 3,
            collaborative: 1,
            creative: 0,
            decisive: 1,
            intuitive: 0,
          },
          text: "위험을 최소화하는 가장 안전한 옵션을 선택한다",
        },
        {
          emoji: "🌈",
          id: "f",
          scores: {
            analytical: 1,
            cautious: 0,
            collaborative: 1,
            creative: 3,
            decisive: 2,
            intuitive: 1,
          },
          text: "여러 옵션을 결합하는 창의적인 방법을 찾는다",
        },
      ],
      text: "여러 옵션이 있는 마감일에 직면했을 때, 당신은:",
    },
    {
      emoji: "💭",
      id: "10",
      options: [
        {
          emoji: "🧠",
          id: "a",
          scores: {
            analytical: 3,
            cautious: 2,
            collaborative: 1,
            creative: 0,
            decisive: 1,
            intuitive: 0,
          },
          text: "좋은 결정은 철저한 분석과 증거가 필요하다",
        },
        {
          emoji: "💡",
          id: "b",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 2,
            decisive: 2,
            intuitive: 3,
          },
          text: "직감을 믿어라 - 보통 무엇이 옳은지 알고 있다",
        },
        {
          emoji: "👥",
          id: "c",
          scores: {
            analytical: 1,
            cautious: 1,
            collaborative: 3,
            creative: 1,
            decisive: 0,
            intuitive: 1,
          },
          text: "한 머리보다 두 머리가 낫다 - 다른 사람들을 참여시켜라",
        },
        {
          emoji: "🎢",
          id: "d",
          scores: {
            analytical: 0,
            cautious: 0,
            collaborative: 0,
            creative: 2,
            decisive: 3,
            intuitive: 2,
          },
          text: "과도하게 생각하지 마라 - 결정을 내리고 필요에 따라 조정하라",
        },
        {
          emoji: "⚖️",
          id: "e",
          scores: {
            analytical: 2,
            cautious: 3,
            collaborative: 1,
            creative: 0,
            decisive: 0,
            intuitive: 0,
          },
          text: "안전한 것이 후회하는 것보다 낫다 - 모든 위험을 먼저 고려하라",
        },
        {
          emoji: "🎨",
          id: "f",
          scores: {
            analytical: 1,
            cautious: 0,
            collaborative: 1,
            creative: 3,
            decisive: 1,
            intuitive: 2,
          },
          text: "최고의 해결책은 종종 다르게 생각하는 것에서 나온다",
        },
      ],
      text: "의사결정에 대한 당신의 철학은:",
    },
  ],
};
