import { LocalizedText } from "@/types/manifest";

import { WesternZodiacSign } from "./types";

export const WESTERN_ZODIAC_DATA: Record<string, WesternZodiacSign> = {
  aquarius: {
    dates: "01.20 - 02.18",
    element: "air",
    id: "aquarius",
    name: {
      cn: "水瓶座",
      en: "Aquarius",
      es: "Acuario",
      fr: "Verseau",
      ja: "水瓶座",
      ko: "물병자리",
    },
    traits: [
      {
        cn: "有创意",
        en: "Original",
        es: "Original",
        fr: "Original",
        ja: "独創的",
        ko: "독창적임",
      },
      {
        cn: "独立",
        en: "Independent",
        es: "Independiente",
        fr: "Indépendant",
        ja: "独立的",
        ko: "독립적임",
      },
    ],
  },
  aries: {
    dates: "03.21 - 04.19",
    element: "fire",
    id: "aries",
    name: {
      cn: "白羊座",
      en: "Aries",
      es: "Aries",
      fr: "Bélier",
      ja: "牡羊座",
      ko: "양자리",
    },
    traits: [
      {
        cn: "勇敢",
        en: "Courageous",
        es: "Valiente",
        fr: "Courageux",
        ja: "勇敢",
        ko: "용감함",
      },
      {
        cn: "坚定",
        en: "Determined",
        es: "Determinado",
        fr: "Déterminé",
        ja: "決断力",
        ko: "단호함",
      },
    ],
  },
  cancer: {
    dates: "06.21 - 07.22",
    element: "water",
    id: "cancer",
    name: {
      cn: "巨蟹座",
      en: "Cancer",
      es: "Cáncer",
      fr: "Cancer",
      ja: "蟹座",
      ko: "게자리",
    },
    traits: [
      {
        cn: "有直觉",
        en: "Intuitive",
        es: "Intuitivo",
        fr: "Intuitif",
        ja: "直感的",
        ko: "직관적임",
      },
      {
        cn: "有保护欲",
        en: "Protective",
        es: "Protector",
        fr: "Protecteur",
        ja: "守護者的",
        ko: "보호 본능이 강함",
      },
    ],
  },
  capricorn: {
    dates: "12.22 - 01.19",
    element: "earth",
    id: "capricorn",
    name: {
      cn: "摩羯座",
      en: "Capricorn",
      es: "Capricornio",
      fr: "Capricorne",
      ja: "山羊座",
      ko: "염소자리",
    },
    traits: [
      {
        cn: "负责任",
        en: "Responsible",
        es: "Responsable",
        fr: "Responsable",
        ja: "責任感がある",
        ko: "책임감 있음",
      },
      {
        cn: "自律",
        en: "Disciplined",
        es: "Disciplinado",
        fr: "Discipliné",
        ja: "規律正しい",
        ko: "규율을 잘 지킴",
      },
    ],
  },
  gemini: {
    dates: "05.21 - 06.20",
    element: "air",
    id: "gemini",
    name: {
      cn: "双子座",
      en: "Gemini",
      es: "Géminis",
      fr: "Gémeaux",
      ja: "双子座",
      ko: "쌍둥이자리",
    },
    traits: [
      {
        cn: "有表现力",
        en: "Expressive",
        es: "Expresivo",
        fr: "Expressif",
        ja: "表現力豊か",
        ko: "표현력이 풍부함",
      },
      {
        cn: "多才多艺",
        en: "Versatile",
        es: "Versátil",
        fr: "Polyvalent",
        ja: "多彩",
        ko: "다재다능함",
      },
    ],
  },
  leo: {
    dates: "07.23 - 08.22",
    element: "fire",
    id: "leo",
    name: {
      cn: "狮子座",
      en: "Leo",
      es: "Leo",
      fr: "Lion",
      ja: "獅子座",
      ko: "사자자리",
    },
    traits: [
      {
        cn: "有创造力",
        en: "Creative",
        es: "Creativo",
        fr: "Créatif",
        ja: "創造的",
        ko: "창의적임",
      },
      {
        cn: "热情",
        en: "Passionate",
        es: "Apasionado",
        fr: "Passionné",
        ja: "情熱的",
        ko: "열정적임",
      },
    ],
  },
  libra: {
    dates: "09.23 - 10.22",
    element: "air",
    id: "libra",
    name: {
      cn: "天秤座",
      en: "Libra",
      es: "Libra",
      fr: "Balance",
      ja: "天秤座",
      ko: "천칭자리",
    },
    traits: [
      {
        cn: "有外交手腕",
        en: "Diplomatic",
        es: "Diplomático",
        fr: "Diplomate",
        ja: "外交的",
        ko: "외교적임",
      },
      {
        cn: "大方",
        en: "Gracious",
        es: "Gracioso",
        fr: "Gracieux",
        ja: "優雅",
        ko: "품격 있음",
      },
    ],
  },
  pisces: {
    dates: "02.19 - 03.20",
    element: "water",
    id: "pisces",
    name: {
      cn: "双鱼座",
      en: "Pisces",
      es: "Piscis",
      fr: "Poissons",
      ja: "魚座",
      ko: "물고기자리",
    },
    traits: [
      {
        cn: "有同情心",
        en: "Compassionate",
        es: "Compasivo",
        fr: "Compatissant",
        ja: "情け深い",
        ko: "동정심이 많음",
      },
      {
        cn: "有艺术气息",
        en: "Artistic",
        es: "Artístico",
        fr: "Artistique",
        ja: "芸術的",
        ko: "예술적임",
      },
    ],
  },
  sagittarius: {
    dates: "11.22 - 12.21",
    element: "fire",
    id: "sagittarius",
    name: {
      cn: "射手座",
      en: "Sagittarius",
      es: "Sagitario",
      fr: "Sagittaire",
      ja: "射手座",
      ko: "궁수자리",
    },
    traits: [
      {
        cn: "大方",
        en: "Generous",
        es: "Generoso",
        fr: "Généreux",
        ja: "寛大",
        ko: "관대함",
      },
      {
        cn: "理想主义",
        en: "Idealistic",
        es: "Idealista",
        fr: "Idéaliste",
        ja: "理想主義的",
        ko: "이상주의적임",
      },
    ],
  },
  scorpio: {
    dates: "10.23 - 11.21",
    element: "water",
    id: "scorpio",
    name: {
      cn: "天蝎座",
      en: "Scorpio",
      es: "Escorpio",
      fr: "Scorpion",
      ja: "蠍座",
      ko: "전갈자리",
    },
    traits: [
      {
        cn: "勇敢",
        en: "Brave",
        es: "Valiente",
        fr: "Courageux",
        ja: "勇敢",
        ko: "용감함",
      },
      {
        cn: "热情",
        en: "Passionate",
        es: "Apasionado",
        fr: "Passionné",
        ja: "情熱的",
        ko: "열정적임",
      },
    ],
  },
  taurus: {
    dates: "04.20 - 05.20",
    element: "earth",
    id: "taurus",
    name: {
      cn: "金牛座",
      en: "Taurus",
      es: "Tauro",
      fr: "Taureau",
      ja: "牡牛座",
      ko: "황소자리",
    },
    traits: [
      {
        cn: "可靠",
        en: "Reliable",
        es: "Confiable",
        fr: "Fiable",
        ja: "信頼できる",
        ko: "신뢰할 수 있음",
      },
      {
        cn: "耐心",
        en: "Patient",
        es: "Paciente",
        fr: "Patient",
        ja: "忍耐強い",
        ko: "인내심",
      },
    ],
  },
  virgo: {
    dates: "08.23 - 09.22",
    element: "earth",
    id: "virgo",
    name: {
      cn: "处女座",
      en: "Virgo",
      es: "Virgo",
      fr: "Vierge",
      ja: "乙女座",
      ko: "처녀자리",
    },
    traits: [
      {
        cn: "忠诚",
        en: "Loyal",
        es: "Leal",
        fr: "Loyal",
        ja: "忠実",
        ko: "충실함",
      },
      {
        cn: "善于分析",
        en: "Analytical",
        es: "Analítico",
        fr: "Analytique",
        ja: "分析的",
        ko: "분석적임",
      },
    ],
  },
};

export const ANIMAL_ZODIAC_DATA: Record<
  string,
  { animal: LocalizedText; name: LocalizedText; traits: LocalizedText[] }
> = {
  dog: {
    animal: {
      cn: "狗",
      en: "Dog",
      es: "Perro",
      fr: "Chien",
      ja: "犬",
      ko: "개",
    },
    name: {
      cn: "狗年",
      en: "Year of the Dog",
      es: "Año del Perro",
      fr: "Année du Chien",
      ja: "戌年",
      ko: "개띠",
    },
    traits: [
      {
        cn: "忠诚",
        en: "Loyal",
        es: "Leal",
        fr: "Loyal",
        ja: "忠実",
        ko: "충성스러운",
      },
      {
        cn: "诚实",
        en: "Honest",
        es: "Honesto",
        fr: "Honnête",
        ja: "正直",
        ko: "정직한",
      },
    ],
  },
  dragon: {
    animal: {
      cn: "龙",
      en: "Dragon",
      es: "Dragón",
      fr: "Dragon",
      ja: "龍",
      ko: "용",
    },
    name: {
      cn: "龙年",
      en: "Year of the Dragon",
      es: "Año del Dragón",
      fr: "Année du Dragon",
      ja: "辰年",
      ko: "용띠",
    },
    traits: [
      {
        cn: "强大",
        en: "Powerful",
        es: "Poderoso",
        fr: "Puissant",
        ja: "力強い",
        ko: "강렬한",
      },
      {
        cn: "有魅力",
        en: "Charismatic",
        es: "Carismático",
        fr: "Charismatique",
        ja: "カリスマ性がある",
        ko: "매혹적인",
      },
    ],
  },
  goat: {
    animal: {
      cn: "羊",
      en: "Goat",
      es: "Cabra",
      fr: "Chèvre",
      ja: "羊",
      ko: "양",
    },
    name: {
      cn: "羊年",
      en: "Year of the Goat",
      es: "Año del Cabra",
      fr: "Année de la Chèvre",
      ja: "未年",
      ko: "양띠",
    },
    traits: [
      {
        cn: "温和",
        en: "Mild",
        es: "Afable",
        fr: "Doux",
        ja: "穏やか",
        ko: "온화한",
      },
      {
        cn: "有艺术感",
        en: "Artistic",
        es: "Artístico",
        fr: "Artistique",
        ja: "芸術的",
        ko: "예술적인",
      },
    ],
  },
  horse: {
    animal: {
      cn: "马",
      en: "Horse",
      es: "Caballo",
      fr: "Cheval",
      ja: "馬",
      ko: "말",
    },
    name: {
      cn: "马年",
      en: "Year of the Horse",
      es: "Año del Caballo",
      fr: "Année du Cheval",
      ja: "午年",
      ko: "말띠",
    },
    traits: [
      {
        cn: "充满活力",
        en: "Energetic",
        es: "Enérgico",
        fr: "Énergique",
        ja: "精力的",
        ko: "정열적인",
      },
      {
        cn: "爱好自由",
        en: "Freedom-loving",
        es: "Amante de la libertad",
        fr: "Aimant la liberté",
        ja: "自由を愛する",
        ko: "자유로운",
      },
    ],
  },
  monkey: {
    animal: {
      cn: "猴",
      en: "Monkey",
      es: "Mono",
      fr: "Singe",
      ja: "猿",
      ko: "원숭이",
    },
    name: {
      cn: "猴年",
      en: "Year of the Monkey",
      es: "Año del Mono",
      fr: "Année du Singe",
      ja: "申年",
      ko: "원숭이띠",
    },
    traits: [
      {
        cn: "聪明",
        en: "Clever",
        es: "Astuto",
        fr: "Malin",
        ja: "利口",
        ko: "영리한",
      },
      {
        cn: "活泼",
        en: "Sprightly",
        es: "Vivaz",
        fr: "Vif",
        ja: "活발",
        ko: "재기발랄한",
      },
    ],
  },
  ox: {
    animal: { cn: "牛", en: "Ox", es: "Buey", fr: "Bœuf", ja: "牛", ko: "소" },
    name: {
      cn: "牛年",
      en: "Year of the Ox",
      es: "Año del Buey",
      fr: "Année du Bœuf",
      ja: "丑年",
      ko: "소띠",
    },
    traits: [
      {
        cn: "勤奋",
        en: "Diligent",
        es: "Diligente",
        fr: "Diligent",
        ja: "勤勉",
        ko: "성실한",
      },
      {
        cn: "可靠",
        en: "Dependable",
        es: "Fiable",
        fr: "Fiable",
        ja: "信頼できる",
        ko: "믿음직한",
      },
    ],
  },
  pig: {
    animal: {
      cn: "猪",
      en: "Pig",
      es: "Cerdo",
      fr: "Cochon",
      ja: "豚",
      ko: "돼지",
    },
    name: {
      cn: "猪年",
      en: "Year of the Pig",
      es: "Año del Cerdo",
      fr: "Année du Cochon",
      ja: "亥年",
      ko: "돼지띠",
    },
    traits: [
      {
        cn: "慷慨",
        en: "Generous",
        es: "Generoso",
        fr: "Généreux",
        ja: "気前が良い",
        ko: "너그러운",
      },
      {
        cn: "乐观",
        en: "Optimistic",
        es: "Optimista",
        fr: "Optimiste",
        ja: "楽観的",
        ko: "낙천적인",
      },
    ],
  },
  rabbit: {
    animal: {
      cn: "兔",
      en: "Rabbit",
      es: "Conejo",
      fr: "Lapin",
      ja: "兎",
      ko: "토끼",
    },
    name: {
      cn: "兔年",
      en: "Year of the Rabbit",
      es: "Año del Conejo",
      fr: "Année du Lapin",
      ja: "卯年",
      ko: "토끼띠",
    },
    traits: [
      {
        cn: "温柔",
        en: "Gentle",
        es: "Gentil",
        fr: "Gentil",
        ja: "優しい",
        ko: "상냥한",
      },
      {
        cn: "谨慎",
        en: "Prudent",
        es: "Prudente",
        fr: "Prudent",
        ja: "慎重",
        ko: "신중한",
      },
    ],
  },
  rat: {
    animal: { cn: "鼠", en: "Rat", es: "Rata", fr: "Rat", ja: "鼠", ko: "쥐" },
    name: {
      cn: "鼠年",
      en: "Year of the Rat",
      es: "Año del Rata",
      fr: "Année du Rat",
      ja: "子年",
      ko: "쥐띠",
    },
    traits: [
      {
        cn: "机敏",
        en: "Witty",
        es: "Ingenioso",
        fr: "Spirituel",
        ja: "機知に富む",
        ko: "재치 있는",
      },
      {
        cn: "适应力强",
        en: "Adaptable",
        es: "Adaptable",
        fr: "Adaptable",
        ja: "適応力がある",
        ko: "적응력이 뛰어난",
      },
    ],
  },
  rooster: {
    animal: {
      cn: "鸡",
      en: "Rooster",
      es: "Gallo",
      fr: "Coq",
      ja: "鶏",
      ko: "닭",
    },
    name: {
      cn: "鸡年",
      en: "Year of the Rooster",
      es: "Año del Gallo",
      fr: "Année du Coq",
      ja: "酉年",
      ko: "닭띠",
    },
    traits: [
      {
        cn: "勤劳",
        en: "Hard-working",
        es: "Trabajador",
        fr: "Travailleur",
        ja: "勤勉",
        ko: "부지런한",
      },
      {
        cn: "准确",
        en: "Accurate",
        es: "Preciso",
        fr: "Précis",
        ja: "正確",
        ko: "정확한",
      },
    ],
  },
  snake: {
    animal: {
      cn: "蛇",
      en: "Snake",
      es: "Serpiente",
      fr: "Serpent",
      ja: "蛇",
      ko: "뱀",
    },
    name: {
      cn: "蛇年",
      en: "Year of the Snake",
      es: "Año del Serpiente",
      fr: "Année du Serpent",
      ja: "巳年",
      ko: "뱀띠",
    },
    traits: [
      {
        cn: "睿智",
        en: "Wise",
        es: "Sabio",
        fr: "Sage",
        ja: "賢い",
        ko: "지혜로운",
      },
      {
        cn: "神秘",
        en: "Mysterious",
        es: "Misterioso",
        fr: "Mystérieux",
        ja: "神秘的",
        ko: "신비로운",
      },
    ],
  },
  tiger: {
    animal: {
      cn: "虎",
      en: "Tiger",
      es: "Tigre",
      fr: "Tigre",
      ja: "虎",
      ko: "호랑이",
    },
    name: {
      cn: "虎年",
      en: "Year of the Tiger",
      es: "Año del Tigre",
      fr: "Année du Tigre",
      ja: "寅年",
      ko: "호랑이띠",
    },
    traits: [
      {
        cn: "勇敢",
        en: "Brave",
        es: "Valiente",
        fr: "Brave",
        ja: "勇敢",
        ko: "용맹한",
      },
      {
        cn: "自信",
        en: "Confident",
        es: "Confiado",
        fr: "Confiant",
        ja: "自信に満ちた",
        ko: "자신감 넘치는",
      },
    ],
  },
};

export const SYNERGY_TEMPLATES: Record<string, LocalizedText> = {
  description: {
    cn: "作为生于{animal}年、拥有{sajuElement}能量的{westernSign}座，结合你的{bloodType}型血特质，你散发出{adjective}的魅力。",
    en: "As a {westernSign} born in the Year of the {animal} with {sajuElement} energy, you radiate a {adjective} charm combined with your Type {bloodType} traits.",
    es: "Como un {westernSign} nacido en el año del {animal} con energía {sajuElement}, irradias un encanto {adjective} combinado con tus rasgos de Tipo {bloodType}.",
    fr: "En tant que {westernSign} né l'année du {animal} avec l'énergie {sajuElement}, vous rayonnez d'un charme {adjective} combiné à vos traits de Type {bloodType}.",
    ja: "{sajuElement}の気運を持って生まれた{animal}年の{westernSign}であるあなたは、{bloodType}型の特性が組み合わさり、{adjective}な魅力を放ちます。",
    ko: "{sajuElement}의 기운을 타고난 {animal}띠 {westernSign}인 당신은, {bloodType}형의 특성이 결합되어 {adjective}한 매력을 발산합니다.",
  },
  title: {
    cn: "命运的和弦：你的身份",
    en: "Harmony of Destiny: Your Ontology",
    es: "Armonía del Destino: Tu Identidad",
    fr: "Harmonie du Destin : Votre Identité",
    ja: "運命のハーモニー：あなたのアイデンティティ",
    ko: "운명의 하모니: 당신의 정체성",
  },
};
