import html2canvas from "html2canvas";
import { jsPDF } from "jspdf";

import { Locale } from "@/schemas/foundation";

import { getLocalizedContent } from "../i18n/locale-utils";

export interface PDFGenerationOptions {
  filename?: string;
  format?: "a4" | "letter";
  includeBranding?: boolean;
  includePageNumbers?: boolean;
  orientation?: "landscape" | "portrait";
  quality?: number;
}

export interface PremiumReportData {
  chartDataUrl?: string;
  date: string;
  insights: string[];
  locale: Locale;
  recommendations: string[];
  resultType: string;
  score: number;
  sections: ReportSection[];
  strengths: string[];
  testName: string;
  userName: string;
  weaknesses: string[];
}

export interface ReportSection {
  content: string;
  order: number;
  title: string;
  type: "chart" | "list" | "table" | "text";
}

/**
 * Download PDF blob
 */
export function downloadPDF(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Generate PDF from HTML element
 */
export async function generatePDFFromElement(
  element: HTMLElement,
  options: PDFGenerationOptions = {},
): Promise<Blob> {
  const {
    format = "a4",
    includeBranding = true,
    includePageNumbers = true,
    orientation = "portrait",
    quality = 0.95,
  } = options;

  // Capture the HTML element as canvas
  const canvas = await html2canvas(element, {
    logging: false,
    useCORS: true,
  });

  // Create PDF
  const pdf = new jsPDF({
    format,
    orientation,
    unit: "mm",
  });

  const imgWidth = orientation === "portrait" ? 210 : 297;
  const imgHeight = (canvas.height * imgWidth) / canvas.width;
  const pageHeight = orientation === "portrait" ? 297 : 210;

  let heightLeft = imgHeight;
  let position = 0;

  const imgData = canvas.toDataURL("image/jpeg", quality);

  // Add first page
  pdf.addImage(imgData, "JPEG", 0, position, imgWidth, imgHeight);
  heightLeft -= pageHeight;

  // Add additional pages if content is longer than one page
  while (heightLeft > 0) {
    position = heightLeft - imgHeight;
    pdf.addPage();
    pdf.addImage(imgData, "JPEG", 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;
  }

  // Add page numbers if requested
  if (includePageNumbers) {
    const totalPages = pdf.internal.pages.length - 1;
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i);
      pdf.setFontSize(10);
      pdf.setTextColor(150);
      pdf.text(`${i} / ${totalPages}`, imgWidth / 2, pageHeight - 10, {
        align: "center",
      });
    }
  }

  // Add branding footer
  if (includeBranding) {
    const totalPages = pdf.internal.pages.length - 1;
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i);
      pdf.setFontSize(8);
      pdf.setTextColor(180);
      pdf.text(
        "Generated by OIYO - Personality Test Platform",
        imgWidth / 2,
        pageHeight - 5,
        { align: "center" },
      );
    }
  }

  return pdf.output("blob");
}

/**
 * Generate structured premium report PDF
 */
export async function generatePremiumReportPDF(
  data: PremiumReportData,
  options: PDFGenerationOptions = {},
): Promise<Blob> {
  const { format = "a4", orientation = "portrait" } = options;

  const pdf = new jsPDF({
    format,
    orientation,
    unit: "mm",
  });

  const pageWidth = orientation === "portrait" ? 210 : 297;
  const pageHeight = orientation === "portrait" ? 297 : 210;
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;

  let yPosition = margin;

  // Helper: Add new page if needed
  const checkNewPage = (requiredHeight: number) => {
    if (yPosition + requiredHeight > pageHeight - margin) {
      pdf.addPage();
      yPosition = margin;
      return true;
    }
    return false;
  };

  // Helper: Add text with word wrap
  const addText = (text: string, fontSize: number, isBold: boolean = false) => {
    pdf.setFontSize(fontSize);
    if (isBold) {
      pdf.setFont("helvetica", "bold");
    } else {
      pdf.setFont("helvetica", "normal");
    }

    const lines = pdf.splitTextToSize(text, contentWidth);
    const lineHeight = fontSize * 0.5;

    checkNewPage(lines.length * lineHeight + 5);

    lines.forEach((line: string) => {
      pdf.text(line, margin, yPosition);
      yPosition += lineHeight;
    });

    yPosition += 5;
  };

  // === COVER PAGE ===
  // Background gradient effect (simulated with rectangles)
  pdf.setFillColor(255, 248, 240);
  pdf.rect(0, 0, pageWidth, pageHeight, "F");

  pdf.setFillColor(255, 140, 60);
  pdf.rect(0, 0, pageWidth, 60, "F");

  // Title
  pdf.setFontSize(32);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(255, 255, 255);
  pdf.text("Premium Report", pageWidth / 2, 30, { align: "center" });

  // Test name
  pdf.setFontSize(18);
  pdf.setFont("helvetica", "normal");
  pdf.text(data.testName, pageWidth / 2, 45, { align: "center" });

  // Reset color
  pdf.setTextColor(0, 0, 0);
  yPosition = 80;

  // User info box
  pdf.setFillColor(255, 255, 255);
  pdf.setDrawColor(255, 140, 60);
  pdf.roundedRect(margin, yPosition, contentWidth, 40, 5, 5, "FD");

  pdf.setFontSize(14);
  pdf.setFont("helvetica", "bold");
  pdf.text(
    getLocalizedContent(data.locale, {
      cn: "分析对象",
      en: "Analyzed For",
      es: "Analizado para",
      fr: "Analysé pour",
      ja: "分析対象",
      ko: "분석 대상",
    })!,
    margin + 10,
    yPosition + 15,
  );

  pdf.setFontSize(12);
  pdf.setFont("helvetica", "normal");
  pdf.text(data.userName, margin + 10, yPosition + 25);
  pdf.text(
    `${getLocalizedContent(data.locale, {
      cn: "日期",
      en: "Date",
      es: "Fecha",
      fr: "Date",
      ja: "日付",
      ko: "날짜",
    })}: ${data.date}`,
    margin + 10,
    yPosition + 35,
  );

  yPosition += 50;

  // Result type badge
  pdf.setFillColor(255, 140, 60);
  pdf.roundedRect(margin, yPosition, contentWidth, 30, 5, 5, "F");

  pdf.setFontSize(20);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(255, 255, 255);
  pdf.text(data.resultType, pageWidth / 2, yPosition + 20, { align: "center" });

  pdf.setTextColor(0, 0, 0);
  yPosition += 45;

  // Score
  pdf.setFontSize(16);
  pdf.setFont("helvetica", "bold");
  pdf.text(
    `${getLocalizedContent(data.locale, {
      cn: "分数",
      en: "Score",
      es: "Puntuación",
      fr: "Score",
      ja: "スコア",
      ko: "점수",
    })}: ${data.score}/100`,
    margin,
    yPosition,
  );
  yPosition += 15;

  // Add new page for content
  pdf.addPage();
  yPosition = margin;

  // === TABLE OF CONTENTS ===
  pdf.setFontSize(24);
  pdf.setFont("helvetica", "bold");
  pdf.text(
    getLocalizedContent(data.locale, {
      cn: "目录",
      en: "Table of Contents",
      es: "Índice",
      fr: "Table des matières",
      ja: "目次",
      ko: "목차",
    })!,
    margin,
    yPosition,
  );
  yPosition += 15;

  pdf.setFontSize(12);
  pdf.setFont("helvetica", "normal");

  const tocItems = [
    getLocalizedContent(data.locale, {
      cn: "1. 概览",
      en: "1. Overview",
      es: "1. Resumen",
      fr: "1. Aperçu",
      ja: "1. 概要",
      ko: "1. 개요",
    })!,
    getLocalizedContent(data.locale, {
      cn: "2. 详细分析",
      en: "2. Detailed Analysis",
      es: "2. Análisis detallado",
      fr: "2. Analyse détaillée",
      ja: "2. 詳細分析",
      ko: "2. 세부 분석",
    })!,
    getLocalizedContent(data.locale, {
      cn: "3. 优势",
      en: "3. Strengths",
      es: "3. Fortalezas",
      fr: "3. Forces",
      ja: "3. 強み",
      ko: "3. 강점",
    })!,
    getLocalizedContent(data.locale, {
      cn: "4. 待改进领域",
      en: "4. Areas for Improvement",
      es: "4. Áreas de mejora",
      fr: "4. Points à améliorer",
      ja: "4. 改善領域",
      ko: "4. 개선 영역",
    })!,
    getLocalizedContent(data.locale, {
      cn: "5. 洞察",
      en: "5. Insights",
      es: "5. Informes",
      fr: "5. Insights",
      ja: "5. インサイト",
      ko: "5. 통찰",
    })!,
    getLocalizedContent(data.locale, {
      cn: "6. 建议",
      en: "6. Recommendations",
      es: "6. Recomendaciones",
      fr: "6. Recommandations",
      ja: "6. 推奨事項",
      ko: "6. 권장 사항",
    })!,
  ];

  tocItems.forEach((item) => {
    pdf.text(item, margin + 10, yPosition);
    yPosition += 10;
  });

  yPosition += 20;

  // === OVERVIEW SECTION ===
  pdf.addPage();
  yPosition = margin;

  pdf.setFontSize(20);
  pdf.setFont("helvetica", "bold");
  pdf.setFillColor(255, 140, 60);
  pdf.rect(margin, yPosition - 5, 5, 10, "F");
  pdf.text(
    getLocalizedContent(data.locale, {
      cn: "1. 概览",
      en: "1. Overview",
      es: "1. Resumen",
      fr: "1. Aperçu",
      ja: "1. 概要",
      ko: "1. 개요",
    })!,
    margin + 10,
    yPosition + 5,
  );
  yPosition += 20;

  pdf.setFontSize(12);
  pdf.setFont("helvetica", "normal");
  addText(
    getLocalizedContent(data.locale, {
      cn: `本报告基于${data.testName}测试的结果。您的性格类型被分析为“${data.resultType}”，基于${data.score}分的总分。`,
      en: `This report is based on the results of the ${data.testName} test. Your personality type has been analyzed as "${data.resultType}", based on an overall score of ${data.score} points.`,
      es: `Este informe se basa en los resultados de la prueba ${data.testName}. Tu tipo de personalidad se ha analizado como "${data.resultType}", basándose en una puntuación total de ${data.score} puntos.`,
      fr: `Ce rapport est basé sur les résultats du test ${data.testName}. Votre type de personnalité a été analysé comme "${data.resultType}", sur la base d'un score global de ${data.score} points.`,
      ja: `このレポートは${data.testName}テストの結果に基づいています。あなたの性格タイプは「${data.resultType}」と分析され、総合スコア${data.score}点に基づいています。`,
      ko: `이 보고서는 ${data.testName} 테스트의 결과를 바탕으로 작성되었습니다. 귀하의 성격 유형은 "${data.resultType}"로 분석되었으며, 이는 전체 점수 ${data.score}점을 기반으로 합니다.`,
    })!,
    12,
    false,
  );

  // === DETAILED ANALYSIS ===
  pdf.setFontSize(20);
  pdf.setFont("helvetica", "bold");
  pdf.setFillColor(255, 140, 60);
  pdf.rect(margin, yPosition - 5, 5, 10, "F");
  pdf.text(
    getLocalizedContent(data.locale, {
      cn: "2. 详细分析",
      en: "2. Detailed Analysis",
      es: "2. Análisis detallado",
      fr: "2. Analyse détaillée",
      ja: "2. 詳細分析",
      ko: "2. 세부 분석",
    })!,
    margin + 10,
    yPosition + 5,
  );
  yPosition += 20;

  // Add sections
  data.sections
    .sort((a, b) => a.order - b.order)
    .forEach((_section) => {
      pdf.setFontSize(14);
      pdf.setFont("helvetica", "bold");
      checkNewPage(20);
      pdf.text(_section.title, margin, yPosition);
      yPosition += 10;

      pdf.setFontSize(11);
      pdf.setFont("helvetica", "normal");
      addText(_section.content, 11, false);
    });

  // === STRENGTHS ===
  checkNewPage(60);
  pdf.setFontSize(20);
  pdf.setFont("helvetica", "bold");
  pdf.setFillColor(76, 175, 80);
  pdf.rect(margin, yPosition - 5, 5, 10, "F");
  pdf.text(
    getLocalizedContent(data.locale, {
      cn: "3. 优势",
      en: "3. Strengths",
      es: "3. Fortalezas",
      fr: "3. Forces",
      ja: "3. 強み",
      ko: "3. 강점",
    })!,
    margin + 10,
    yPosition + 5,
  );
  yPosition += 20;

  data.strengths.forEach((strength) => {
    checkNewPage(15);
    pdf.setFontSize(12);
    pdf.setFont("helvetica", "normal");
    pdf.text(`✓ ${strength}`, margin + 5, yPosition);
    yPosition += 10;
  });

  yPosition += 10;

  // === AREAS FOR IMPROVEMENT ===
  checkNewPage(60);
  pdf.setFontSize(20);
  pdf.setFont("helvetica", "bold");
  pdf.setFillColor(255, 152, 0);
  pdf.rect(margin, yPosition - 5, 5, 10, "F");
  pdf.text(
    getLocalizedContent(data.locale, {
      cn: "4. 待改进领域",
      en: "4. Areas for Improvement",
      es: "4. Áreas de mejora",
      fr: "4. Points à améliorer",
      ja: "4. 改善領域",
      ko: "4. 개선 영역",
    })!,
    margin + 10,
    yPosition + 5,
  );
  yPosition += 20;

  data.weaknesses.forEach((weakness) => {
    checkNewPage(15);
    pdf.setFontSize(12);
    pdf.setFont("helvetica", "normal");
    pdf.text(`• ${weakness}`, margin + 5, yPosition);
    yPosition += 10;
  });

  yPosition += 10;

  // === INSIGHTS ===
  checkNewPage(60);
  pdf.setFontSize(20);
  pdf.setFont("helvetica", "bold");
  pdf.setFillColor(33, 150, 243);
  pdf.rect(margin, yPosition - 5, 5, 10, "F");
  pdf.text(
    getLocalizedContent(data.locale, {
      cn: "5. 洞察",
      en: "5. Insights",
      es: "5. Informes",
      fr: "5. Insights",
      ja: "5. インサイト",
      ko: "5. 통찰",
    })!,
    margin + 10,
    yPosition + 5,
  );
  yPosition += 20;

  data.insights.forEach((insight, _index) => {
    checkNewPage(20);
    pdf.setFontSize(12);
    pdf.setFont("helvetica", "bold");
    pdf.text(
      `💡 ${getLocalizedContent(data.locale, { cn: "洞察", en: "Insight", es: "Informe", fr: "Insight", ja: "インサイト", ko: "통찰" })} ${_index + 1}`,
      margin,
      yPosition,
    );
    yPosition += 8;

    pdf.setFont("helvetica", "normal");
    addText(insight, 11, false);
  });

  // === RECOMMENDATIONS ===
  checkNewPage(60);
  pdf.setFontSize(20);
  pdf.setFont("helvetica", "bold");
  pdf.setFillColor(156, 39, 176);
  pdf.rect(margin, yPosition - 5, 5, 10, "F");
  pdf.text(
    getLocalizedContent(data.locale, {
      cn: "6. 建议",
      en: "6. Recommendations",
      es: "6. Recomendaciones",
      fr: "6. Recommandations",
      ja: "6. 推奨事項",
      ko: "6. 권장 사항",
    })!,
    margin + 10,
    yPosition + 5,
  );
  yPosition += 20;

  data.recommendations.forEach((recommendation, _index) => {
    checkNewPage(20);
    pdf.setFontSize(12);
    pdf.setFont("helvetica", "bold");
    pdf.text(
      `📌 ${getLocalizedContent(data.locale, { cn: "建议", en: "Recommendation", es: "Recomendación", fr: "Recommandation", ja: "推奨事項", ko: "권장" })} ${_index + 1}`,
      margin,
      yPosition,
    );
    yPosition += 8;

    pdf.setFont("helvetica", "normal");
    addText(recommendation, 11, false);
  });

  // === FOOTER ===
  const totalPages = pdf.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);

    // Page number
    pdf.setFontSize(10);
    pdf.setTextColor(150);
    pdf.text(`${i} / ${totalPages}`, pageWidth / 2, pageHeight - 10, {
      align: "center",
    });

    // Branding
    pdf.setFontSize(8);
    pdf.setTextColor(180);
    pdf.text("Generated by OIYO - oiyo.me", pageWidth / 2, pageHeight - 5, {
      align: "center",
    });
  }

  return pdf.output("blob");
}
