// The five branches and their leaves for "실제 나의 것" (ProfileMindmap), in six languages.
// Leaf order is part of the contract: recommendations (mindmap-recommend.ts) address a leaf by
// its position, and the profile store matches labels across languages by position.
export type MindmapLang = "ko" | "en" | "ja" | "zh" | "fr" | "es";
export const MINDMAP_STORAGE_KEY = "oiyo:profile:v1";

// twigs: the items under each leaf, in leaf order (2026-10-10, CHOSEUN chose to ship the
// proposed list as it stands). Relationships and goals end at the leaf: they do not split into
// kinds the way a hobby does, and the proposed "when / with whom" items read as forced.
// Item order is a contract too: chosenSub stores items by position.
export type MindmapCat = { id: string; label: Record<MindmapLang, string>; chips: Record<MindmapLang, string[]>; twigs?: Record<MindmapLang, string[][]> };

export const MINDMAP_CATS: MindmapCat[] = [
  { id: "interest", label: { ko: "관심", en: "Interests", ja: "関心", zh: "兴趣", fr: "Intérêts", es: "Intereses" },
    chips: { ko: ["글쓰기", "정리", "탐험", "분석", "창작", "배움", "수집"], en: ["Writing", "Organizing", "Exploring", "Analyzing", "Creating", "Learning", "Collecting"], ja: ["書く", "整理", "探検", "分析", "創作", "学び", "収集"], zh: ["写作", "整理", "探索", "分析", "创作", "学习", "收藏"], fr: ["Écrire", "Organiser", "Explorer", "Analyser", "Créer", "Apprendre", "Collectionner"], es: ["Escribir", "Organizar", "Explorar", "Analizar", "Crear", "Aprender", "Coleccionar"] },
    twigs: { ko: [["일기", "에세이", "소설", "시"], ["공간", "일정", "자료", "돈"], ["낯선 동네", "새 분야", "새 음식", "새 사람"], ["숫자", "사람", "시스템", "글"], ["그림", "영상", "음악", "공예"], ["언어", "기술", "역사", "과학"], ["책", "음반", "문구", "식물"]], en: [["Journal", "Essays", "Fiction", "Poetry"], ["Spaces", "Schedules", "Files", "Money"], ["New places", "New fields", "New food", "New people"], ["Numbers", "People", "Systems", "Texts"], ["Drawing", "Video", "Music", "Crafts"], ["Languages", "Tech", "History", "Science"], ["Books", "Records", "Stationery", "Plants"]], ja: [["日記", "エッセイ", "小説", "詩"], ["空間", "予定", "資料", "お金"], ["知らない街", "新しい分野", "新しい味", "新しい人"], ["数字", "人", "仕組み", "文章"], ["絵", "映像", "音楽", "工芸"], ["語学", "技術", "歴史", "科学"], ["本", "レコード", "文房具", "植物"]], zh: [["日记", "随笔", "小说", "诗"], ["空间", "日程", "资料", "金钱"], ["陌生街区", "新领域", "新食物", "新朋友"], ["数字", "人", "系统", "文字"], ["绘画", "视频", "音乐", "手工艺"], ["语言", "技术", "历史", "科学"], ["书", "唱片", "文具", "植物"]], fr: [["Journal", "Essais", "Fiction", "Poésie"], ["Espaces", "Agenda", "Documents", "Argent"], ["Nouveaux lieux", "Nouveaux sujets", "Nouveaux plats", "Nouvelles têtes"], ["Chiffres", "Personnes", "Systèmes", "Textes"], ["Dessin", "Vidéo", "Musique", "Artisanat"], ["Langues", "Technique", "Histoire", "Sciences"], ["Livres", "Disques", "Papeterie", "Plantes"]], es: [["Diario", "Ensayo", "Ficción", "Poesía"], ["Espacios", "Agenda", "Documentos", "Dinero"], ["Lugares nuevos", "Campos nuevos", "Comida nueva", "Gente nueva"], ["Números", "Personas", "Sistemas", "Textos"], ["Dibujo", "Vídeo", "Música", "Artesanía"], ["Idiomas", "Tecnología", "Historia", "Ciencia"], ["Libros", "Discos", "Papelería", "Plantas"]] } },
  { id: "activity", label: { ko: "활동", en: "Activities", ja: "活動", zh: "活动", fr: "Activités", es: "Actividades" },
    chips: { ko: ["운동", "여행", "요리", "독서", "음악", "게임", "명상"], en: ["Exercise", "Travel", "Cooking", "Reading", "Music", "Gaming", "Meditation"], ja: ["運動", "旅行", "料理", "読書", "音楽", "ゲーム", "瞑想"], zh: ["运动", "旅行", "烹饪", "阅读", "音乐", "游戏", "冥想"], fr: ["Sport", "Voyage", "Cuisine", "Lecture", "Musique", "Jeux", "Méditation"], es: ["Ejercicio", "Viajar", "Cocinar", "Leer", "Música", "Juegos", "Meditación"] },
    twigs: { ko: [["달리기", "근력", "수영", "요가"], ["국내", "해외", "혼자", "캠핑"], ["집밥", "베이킹", "커피", "도시락"], ["소설", "인문", "과학", "에세이"], ["듣기", "연주", "노래", "공연"], ["퍼즐", "전략", "보드게임", "액션"], ["호흡", "걷기", "기록", "차"]], en: [["Running", "Strength", "Swimming", "Yoga"], ["Domestic", "Abroad", "Solo trips", "Camping"], ["Home meals", "Baking", "Coffee", "Lunchboxes"], ["Novels", "Humanities", "Science", "Essays"], ["Listening", "Playing", "Singing", "Live shows"], ["Puzzles", "Strategy", "Board games", "Action"], ["Breathing", "Walking", "Journaling", "Tea"]], ja: [["ランニング", "筋トレ", "水泳", "ヨガ"], ["国内", "海外", "一人旅", "キャンプ"], ["家ごはん", "お菓子作り", "コーヒー", "お弁当"], ["小説", "人文", "科学", "エッセイ"], ["聴く", "演奏", "歌う", "ライブ"], ["パズル", "戦略", "ボードゲーム", "アクション"], ["呼吸", "歩く", "記録", "お茶"]], zh: [["跑步", "力量训练", "游泳", "瑜伽"], ["国内", "海外", "独自旅行", "露营"], ["家常菜", "烘焙", "咖啡", "便当"], ["小说", "人文", "科学", "随笔"], ["聆听", "演奏", "唱歌", "现场演出"], ["解谜", "策略", "桌游", "动作"], ["呼吸", "行走", "记录", "茶"]], fr: [["Course", "Musculation", "Natation", "Yoga"], ["Dans le pays", "À l’étranger", "En solo", "Camping"], ["Cuisine maison", "Pâtisserie", "Café", "Gamelles"], ["Romans", "Humanités", "Sciences", "Essais"], ["Écouter", "Jouer", "Chanter", "Concerts"], ["Puzzles", "Stratégie", "Jeux de société", "Action"], ["Respiration", "Marche", "Écriture", "Thé"]], es: [["Correr", "Fuerza", "Natación", "Yoga"], ["Nacional", "Extranjero", "En solitario", "Camping"], ["Comida casera", "Repostería", "Café", "Táper"], ["Novela", "Humanidades", "Ciencia", "Ensayo"], ["Escuchar", "Tocar", "Cantar", "Conciertos"], ["Puzles", "Estrategia", "Juegos de mesa", "Acción"], ["Respiración", "Caminar", "Escritura", "Té"]] } },
  { id: "environment", label: { ko: "환경", en: "Environment", ja: "環境", zh: "环境", fr: "Environnement", es: "Entorno" },
    chips: { ko: ["자연", "도시", "바다", "산", "카페", "집", "야외"], en: ["Nature", "City", "Sea", "Mountains", "Café", "Home", "Outdoors"], ja: ["自然", "都市", "海", "山", "カフェ", "家", "屋外"], zh: ["自然", "城市", "海", "山", "咖啡馆", "家", "户外"], fr: ["Nature", "Ville", "Mer", "Montagne", "Café", "Maison", "Plein air"], es: ["Naturaleza", "Ciudad", "Mar", "Montaña", "Café", "Casa", "Aire libre"] },
    twigs: { ko: [["숲", "강", "들판", "정원"], ["골목", "시장", "야경", "서점"], ["해변", "항구", "섬", "파도"], ["능선", "계곡", "숲길", "정상"], ["조용한 곳", "창가", "동네 단골", "넓은 곳"], ["내 방", "부엌", "책상", "침대"], ["공원", "캠핑장", "운동장", "옥상"]], en: [["Forest", "Rivers", "Fields", "Gardens"], ["Alleys", "Markets", "Night views", "Bookshops"], ["Beach", "Harbor", "Islands", "Waves"], ["Ridges", "Valleys", "Forest trails", "Summits"], ["Quiet ones", "Window seat", "Local regular", "Spacious"], ["My room", "Kitchen", "Desk", "Bed"], ["Parks", "Campsites", "Sports fields", "Rooftops"]], ja: [["森", "川", "野原", "庭"], ["路地", "市場", "夜景", "本屋"], ["浜辺", "港", "島", "波"], ["尾根", "渓谷", "森の道", "山頂"], ["静かな店", "窓際", "行きつけ", "広い店"], ["自分の部屋", "台所", "机", "ベッド"], ["公園", "キャンプ場", "運動場", "屋上"]], zh: [["森林", "河流", "原野", "花园"], ["小巷", "市场", "夜景", "书店"], ["海滩", "港口", "岛屿", "海浪"], ["山脊", "山谷", "林间小道", "山顶"], ["安静的", "靠窗", "常去的店", "宽敞的"], ["我的房间", "厨房", "书桌", "床"], ["公园", "露营地", "运动场", "屋顶"]], fr: [["Forêt", "Rivière", "Prairie", "Jardin"], ["Ruelles", "Marchés", "Ville la nuit", "Librairies"], ["Plage", "Port", "Îles", "Vagues"], ["Crêtes", "Vallées", "Sentiers", "Sommets"], ["Calme", "Côté fenêtre", "Café du coin", "Spacieux"], ["Ma chambre", "Cuisine", "Bureau", "Lit"], ["Parcs", "Campings", "Terrains de sport", "Toits"]], es: [["Bosque", "Río", "Campo", "Jardín"], ["Callejones", "Mercados", "Vistas nocturnas", "Librerías"], ["Playa", "Puerto", "Islas", "Olas"], ["Crestas", "Valles", "Senderos", "Cumbres"], ["Tranquilo", "Junto a la ventana", "De barrio", "Amplio"], ["Mi cuarto", "Cocina", "Escritorio", "Cama"], ["Parques", "Campings", "Campos deportivos", "Azoteas"]] } },
  { id: "relation", label: { ko: "관계", en: "Relationships", ja: "関係", zh: "关系", fr: "Relations", es: "Relaciones" },
    chips: { ko: ["혼자", "팀", "가족", "소수 친구", "커뮤니티", "멘토"], en: ["Solo", "Team", "Family", "Few friends", "Community", "Mentor"], ja: ["一人", "チーム", "家族", "少数の友人", "コミュニティ", "メンター"], zh: ["独处", "团队", "家庭", "少数朋友", "社群", "导师"], fr: ["Seul", "Équipe", "Famille", "Quelques amis", "Communauté", "Mentor"], es: ["Solo", "Equipo", "Familia", "Pocos amigos", "Comunidad", "Mentor"] } },
  { id: "goal", label: { ko: "목표", en: "Goals", ja: "目標", zh: "目标", fr: "Objectifs", es: "Metas" },
    chips: { ko: ["성장", "안정", "자유", "영향력", "숙련", "연결", "의미"], en: ["Growth", "Stability", "Freedom", "Impact", "Mastery", "Connection", "Meaning"], ja: ["成長", "安定", "自由", "影響力", "熟達", "つながり", "意味"], zh: ["成长", "稳定", "自由", "影响力", "精通", "连接", "意义"], fr: ["Croissance", "Stabilité", "Liberté", "Impact", "Maîtrise", "Connexion", "Sens"], es: ["Crecimiento", "Estabilidad", "Libertad", "Impacto", "Maestría", "Conexión", "Sentido"] } },
];
