"use client";

import { useMemo } from "react";
import { calculateCelticTree } from "@/lib/ontology/celtic/calculator";
import { calculateMayanKin } from "@/lib/ontology/mayan/calculator";
import { calculateZiWeiCoordinates } from "@/lib/ontology/ziwei/calculator";
import { CITIES } from "@/lib/ontology/natal/signs";
import { useProfilePrefill } from "@/lib/user/useProfilePrefill";

type Lang = "ko" | "en" | "ja" | "zh" | "fr" | "es";
const COPY: Record<Lang, { title: string; sub: string; needDate: string; needTime: string; ziwei: string; mayan: string; celtic: string; bureau: string; life: string; kin: string; tone: string; tree: string; note: string; learnMore: string; whatIs: string; ziweiDef: string; mayanDef: string; celticDef: string }> = {
  ko: { title: "세 전통으로 읽는 나의 좌표", sub: "온톨로지에 저장한 출생 정보를 자미두수·마야 촐킨·켈트 나무 달력으로 함께 읽습니다.", needDate: "생년월일을 저장하면 결과가 열립니다.", needTime: "자미두수는 태어난 시각까지 있어야 정확히 계산됩니다.", ziwei: "자미두수", mayan: "마야 촐킨", celtic: "켈트 나무", bureau: "오행국", life: "명궁", kin: "킨", tone: "은하의 톤", tree: "수호 나무", note: "세 체계는 서로 다른 문화의 상징 언어입니다. 성격을 단정하기보다 자기 성찰의 관점으로 활용하세요.",  whatIs: "설명 보기", ziweiDef: "자미두수는 중국 점성술의 한 갈래로, 태어난 시각을 기준으로 12개의 \'궁\'(인생 영역)에 별을 배치해 읽습니다. 명궁은 그중 나의 성향을 보여주는 중심 궁이고, 오행국은 별이 움직이는 속도와 리듬을 정합니다.", mayanDef: "촐킨은 260일 주기의 마야 신성 달력으로, 13개의 은하의 톤(리듬)과 20개의 인장(원형적 에너지)이 조합되어 260개의 고유한 \'킨\'을 만듭니다. 태어난 날의 킨은 그 톤과 인장이 섞인 나만의 에너지 서명입니다.", celticDef: "켈트 나무 달력은 고대 오검(Ogham) 문자를 바탕으로 태어난 날짜 구간마다 수호 나무를 배정합니다. 각 나무는 고유한 성질을 상징하는데, 예를 들어 버드나무는 직관과 유연함을 뜻합니다." },
  en: { title: "Your coordinates in three traditions", sub: "Read your saved birth profile through Zi Wei Dou Shu, Mayan Tzolkin, and the Celtic tree calendar.", needDate: "Save your birth date to unlock these results.", needTime: "Zi Wei Dou Shu also needs your birth time for a precise chart.", ziwei: "Zi Wei Dou Shu", mayan: "Mayan Tzolkin", celtic: "Celtic tree", bureau: "Five-element bureau", life: "Life palace", kin: "Kin", tone: "Galactic tone", tree: "Guardian tree", note: "These are symbolic languages from different traditions. Use them as prompts for reflection, not fixed labels.",  whatIs: "Show explanation", ziweiDef: "Zi Wei Dou Shu is a branch of Chinese astrology that places stars into 12 \'palaces\' (life areas) based on your exact birth time. The life palace is the central palace reflecting your core temperament, while the five-element bureau sets the pace at which the stars move.", mayanDef: "The Tzolkin is a 260-day sacred Mayan calendar made of 13 galactic tones (rhythms) combined with 20 seals (archetypal energies), producing 260 unique \'Kin.\' Your birth Kin is the blend of a tone and a seal — a personal energy signature.", celticDef: "The Celtic tree calendar assigns a guardian tree to each birth-date range, based on the ancient Ogham alphabet. Each tree symbolizes distinct qualities — the willow, for example, represents intuition and adaptability." },
  ja: { title: "三つの伝統で読む座標", sub: "保存した出生情報を紫微斗数・マヤ暦・ケルト樹木暦で読みます。", needDate: "生年月日を保存すると結果が開きます。", needTime: "紫微斗数の精密計算には出生時刻も必要です。", ziwei: "紫微斗数", mayan: "マヤ・ツォルキン", celtic: "ケルト樹木", bureau: "五行局", life: "命宮", kin: "KIN", tone: "銀河の音", tree: "守護樹", note: "異なる文化の象徴言語です。固定的な性格分類ではなく内省にご利用ください。",  whatIs: "説明を見る", ziweiDef: "紫微斗数は出生時刻をもとに、人生の12の領域（宮）に星を配置して読む中国占星術の一派です。命宮は自分の気質を映す中心の宮で、五行局は星が動く速度とリズムを決めます。", mayanDef: "ツォルキンは260日周期のマヤの神聖暦で、13の銀河の音（リズム）と20の紋章（元型的エネルギー）が組み合わさって260通りの「KIN」を作ります。誕生日のKINは、その音と紋章が混ざったあなただけのエネルギーの署名です。", celticDef: "ケルト樹木暦は古代オガム文字にもとづき、誕生日の期間ごとに守護樹を割り当てます。それぞれの木は固有の性質を象徴し、例えば柳は直感と柔軟性を意味します。" },
  zh: { title: "三种传统中的你的坐标", sub: "用紫微斗数、玛雅卓尔金历与凯尔特树历读取已保存的出生信息。", needDate: "保存出生日期后即可查看结果。", needTime: "紫微斗数的精确计算还需要出生时间。", ziwei: "紫微斗数", mayan: "玛雅卓尔金", celtic: "凯尔特树历", bureau: "五行局", life: "命宫", kin: "KIN", tone: "银河音调", tree: "守护树", note: "它们是不同文化的象征语言，请用于自我反思而非固定定性。",  whatIs: "查看说明", ziweiDef: "紫微斗数是中国占星术的一支，根据精确的出生时间，将星曜安放到人生的12个宫位中来解读。命宫是反映你核心性格的中心宫位，五行局则决定星曜运行的节奏。", mayanDef: "卓尔金历是260天周期的玛雅神圣历法，由13个银河音调（节奏）与20个印记（原型能量）组合而成，共产生260个独特的「KIN」。你出生那天的KIN，是音调与印记交融而成的专属能量签名。", celticDef: "凯尔特树历以古老的欧甘字母为基础，为每个出生日期区间分配一棵守护树。每棵树象征不同的特质——例如柳树代表直觉与灵活。" },
  fr: { title: "Vos coordonnées selon trois traditions", sub: "Lisez votre naissance via Zi Wei Dou Shu, le Tzolkin maya et le calendrier celtique des arbres.", needDate: "Enregistrez votre date de naissance pour voir les résultats.", needTime: "Zi Wei Dou Shu exige aussi l’heure de naissance pour un calcul précis.", ziwei: "Zi Wei Dou Shu", mayan: "Tzolkin maya", celtic: "Arbre celtique", bureau: "Bureau des cinq éléments", life: "Palais de vie", kin: "Kin", tone: "Ton galactique", tree: "Arbre gardien", note: "Ces traditions sont des langages symboliques, à utiliser comme pistes de réflexion.",  whatIs: "Voir l’explication", ziweiDef: "Le Zi Wei Dou Shu est une branche de l\'astrologie chinoise qui place des étoiles dans 12 « palais » (domaines de vie) selon votre heure de naissance exacte. Le palais de vie est le palais central reflétant votre tempérament, tandis que le bureau des cinq éléments règle le rythme du mouvement des étoiles.", mayanDef: "Le Tzolkin est un calendrier sacré maya de 260 jours, composé de 13 tons galactiques (rythmes) combinés à 20 sceaux (énergies archétypales), produisant 260 « Kin » uniques. Votre Kin de naissance est le mélange d\'un ton et d\'un sceau — une signature énergétique personnelle.", celticDef: "Le calendrier celtique des arbres attribue un arbre gardien à chaque période de naissance, selon l\'ancien alphabet ogham. Chaque arbre symbolise des qualités distinctes — le saule, par exemple, représente l\'intuition et l\'adaptabilité." },
  es: { title: "Tus coordenadas en tres tradiciones", sub: "Lee tu nacimiento con Zi Wei Dou Shu, Tzolkin maya y el calendario celta de árboles.", needDate: "Guarda tu fecha de nacimiento para ver los resultados.", needTime: "Zi Wei Dou Shu también requiere la hora para un cálculo preciso.", ziwei: "Zi Wei Dou Shu", mayan: "Tzolkin maya", celtic: "Árbol celta", bureau: "Oficina de cinco elementos", life: "Palacio de vida", kin: "Kin", tone: "Tono galáctico", tree: "Árbol guardián", note: "Son lenguajes simbólicos de distintas culturas; úsalos para reflexionar, no como etiquetas fijas.",  whatIs: "Ver explicación", ziweiDef: "Zi Wei Dou Shu es una rama de la astrología china que coloca estrellas en 12 «palacios» (áreas de la vida) según tu hora de nacimiento exacta. El palacio de vida es el palacio central que refleja tu temperamento, mientras que la oficina de cinco elementos marca el ritmo del movimiento de las estrellas.", mayanDef: "El Tzolkin es un calendario sagrado maya de 260 días, formado por 13 tonos galácticos (ritmos) combinados con 20 sellos (energías arquetípicas), que produce 260 «Kin» únicos. Tu Kin de nacimiento es la mezcla de un tono y un sello — una firma energética personal.", celticDef: "El calendario celta de árboles asigna un árbol guardián a cada rango de fecha de nacimiento, según el antiguo alfabeto ogham. Cada árbol simboliza cualidades distintas — el sauce, por ejemplo, representa la intuición y la adaptabilidad." },
};

export function HeritageCoordinates({ locale }: { locale: string }) {
  const lang = (["ko", "en", "ja", "zh", "fr", "es"].includes(locale) ? locale : "en") as Lang;
  const t = COPY[lang];
  const { parsed, profile } = useProfilePrefill();
  const result = useMemo(() => {
    if (!parsed) return null;
    const local = new Date(parsed.year, parsed.month - 1, parsed.day, parsed.hour ?? 12, parsed.minute ?? 0);
    const mayan = calculateMayanKin(local);
    const celtic = calculateCelticTree(local);
    const city = CITIES.find((item) => item.id === profile.birthCityId);
    const ziwei = parsed.hour === null ? null : calculateZiWeiCoordinates(local, city?.lon ?? 135);
    return { celtic, mayan, ziwei };
  }, [parsed, profile.birthCityId]);

  return (
    <section id="heritage-coordinates" className="mt-8 rounded-[28px] border border-green-100 bg-white p-4 shadow-sm sm:p-5">
      <h2 className="text-lg font-black text-green-950">🧿 {t.title}</h2>
      <p className="mt-1 text-xs leading-5 text-green-600">{t.sub}</p>
      {!result ? <p className="mt-4 rounded-2xl bg-amber-50 p-4 text-sm font-bold text-amber-800">{t.needDate}</p> : (
        <div className="mt-4 grid gap-3 sm:grid-cols-3">
          <article className="rounded-2xl bg-violet-50 p-4"><p className="text-xs font-black text-violet-600">⭐ {t.ziwei}</p>{result.ziwei ? <><p className="mt-2 text-sm font-black text-violet-950">{t.bureau} · {result.ziwei.bureau.name}</p><p className="mt-1 text-xs text-violet-800">{t.life} · {result.ziwei.lifePalace.earthlyBranch}{(() => { const named = result.ziwei.lifePalace.stars.find((star) => star.name); return named ? ` · ${named.name}` : ""; })()}</p></> : <p className="mt-2 text-xs leading-5 text-amber-700">{t.needTime}</p>}<details className="mt-2"><summary className="cursor-pointer text-[11px] font-bold text-violet-600">{t.whatIs}</summary><p className="mt-1.5 text-[11px] leading-5 text-violet-800">{t.ziweiDef}</p></details></article>
          <article className="rounded-2xl bg-amber-50 p-4"><p className="text-xs font-black text-amber-700">🗿 {t.mayan}</p><p className="mt-2 text-sm font-black text-amber-950">{t.kin} {result.mayan?.kinNumber ?? 0} · {result.mayan?.kinName[lang === "ko" ? "ko" : "en"]}</p><p className="mt-1 text-xs text-amber-800">{t.tone} {result.mayan?.tone.number} · {result.mayan?.seal.mayanName}</p><details className="mt-2"><summary className="cursor-pointer text-[11px] font-bold text-amber-700">{t.whatIs}</summary><p className="mt-1.5 text-[11px] leading-5 text-amber-800">{t.mayanDef}</p></details></article>
          <article className="rounded-2xl bg-emerald-50 p-4"><p className="text-xs font-black text-emerald-700">🌲 {t.celtic}</p><p className="mt-2 text-sm font-black text-emerald-950">{t.tree} · {result.celtic.name}</p><p className="mt-1 text-xs text-emerald-800">{result.celtic.ogham} · {result.celtic.celticName}</p><details className="mt-2"><summary className="cursor-pointer text-[11px] font-bold text-emerald-700">{t.whatIs}</summary><p className="mt-1.5 text-[11px] leading-5 text-emerald-800">{t.celticDef}</p></details></article>
        </div>
      )}
      <p className="mt-3 text-[11px] leading-5 text-slate-400">{t.note}</p>
    </section>
  );
}
