import { ResilienceFactor, ResilienceQuestion } from "./types";

export const RESILIENCE_QUESTIONS: ResilienceQuestion[] = [
  {
    factor: "adaptability",
    id: "res_1",
    options: [
      {
        id: "opt_1",
        score: 4,
        text: {
          cn: "Strongly agree",
          en: "Strongly agree",
          es: "Strongly agree",
          fr: "Strongly agree",
          ja: "Strongly agree",
          ko: "매우 그렇다",
        },
      },
      {
        id: "opt_2",
        score: 3,
        text: {
          cn: "Agree",
          en: "Agree",
          es: "Agree",
          fr: "Agree",
          ja: "Agree",
          ko: "그렇다",
        },
      },
      {
        id: "opt_3",
        score: 2,
        text: {
          cn: "Neutral",
          en: "Neutral",
          es: "Neutral",
          fr: "Neutral",
          ja: "Neutral",
          ko: "보통이다",
        },
      },
      {
        id: "opt_4",
        score: 1,
        text: {
          cn: "Disagree",
          en: "Disagree",
          es: "Disagree",
          fr: "Disagree",
          ja: "Disagree",
          ko: "그렇지 않다",
        },
      },
      {
        id: "opt_5",
        score: 0,
        text: {
          cn: "Strongly disagree",
          en: "Strongly disagree",
          es: "Strongly disagree",
          fr: "Strongly disagree",
          ja: "Strongly disagree",
          ko: "전혀 그렇지 않다",
        },
      },
    ],
    text: {
      cn: "I tend to recover my composure quickly even after under severe stress.",
      en: "I tend to recover my composure quickly even after under severe stress.",
      es: "I tend to recover my composure quickly even after under severe stress.",
      fr: "I tend to recover my composure quickly even after under severe stress.",
      ja: "I tend to recover my composure quickly even after under severe stress.",
      ko: "심한 스트레스를 받아도 평정심을 빨리 되찾는 편이다.",
    },
  },
  {
    factor: "hardiness",
    id: "res_2",
    options: [
      {
        id: "opt_1",
        score: 4,
        text: {
          cn: "Strongly agree",
          en: "Strongly agree",
          es: "Strongly agree",
          fr: "Strongly agree",
          ja: "Strongly agree",
          ko: "매우 그렇다",
        },
      },
      {
        id: "opt_2",
        score: 3,
        text: {
          cn: "Agree",
          en: "Agree",
          es: "Agree",
          fr: "Agree",
          ja: "Agree",
          ko: "그렇다",
        },
      },
      {
        id: "opt_3",
        score: 2,
        text: {
          cn: "Neutral",
          en: "Neutral",
          es: "Neutral",
          fr: "Neutral",
          ja: "Neutral",
          ko: "보통이다",
        },
      },
      {
        id: "opt_4",
        score: 1,
        text: {
          cn: "Disagree",
          en: "Disagree",
          es: "Disagree",
          fr: "Disagree",
          ja: "Disagree",
          ko: "그렇지 않다",
        },
      },
      {
        id: "opt_5",
        score: 0,
        text: {
          cn: "Strongly disagree",
          en: "Strongly disagree",
          es: "Strongly disagree",
          fr: "Strongly disagree",
          ja: "Strongly disagree",
          ko: "전혀 그렇지 않다",
        },
      },
    ],
    text: {
      cn: "I believe I can handle whatever comes my way.",
      en: "I believe I can handle whatever comes my way.",
      es: "I believe I can handle whatever comes my way.",
      fr: "I believe I can handle whatever comes my way.",
      ja: "I believe I can handle whatever comes my way.",
      ko: "어떤 일이 일어나든 내가 다룰 수 있다는 믿음이 있다.",
    },
  },
  {
    factor: "persistence",
    id: "res_3",
    options: [
      {
        id: "opt_1",
        score: 4,
        text: {
          cn: "Strongly agree",
          en: "Strongly agree",
          es: "Strongly agree",
          fr: "Strongly agree",
          ja: "Strongly agree",
          ko: "매우 그렇다",
        },
      },
      {
        id: "opt_2",
        score: 3,
        text: {
          cn: "Agree",
          en: "Agree",
          es: "Agree",
          fr: "Agree",
          ja: "Agree",
          ko: "그렇다",
        },
      },
      {
        id: "opt_3",
        score: 2,
        text: {
          cn: "Neutral",
          en: "Neutral",
          es: "Neutral",
          fr: "Neutral",
          ja: "Neutral",
          ko: "보통이다",
        },
      },
      {
        id: "opt_4",
        score: 1,
        text: {
          cn: "Disagree",
          en: "Disagree",
          es: "Disagree",
          fr: "Disagree",
          ja: "Disagree",
          ko: "그렇지 않다",
        },
      },
      {
        id: "opt_5",
        score: 0,
        text: {
          cn: "Strongly disagree",
          en: "Strongly disagree",
          es: "Strongly disagree",
          fr: "Strongly disagree",
          ja: "Strongly disagree",
          ko: "전혀 그렇지 않다",
        },
      },
    ],
    text: {
      cn: "Past successes give me confidence for new challenges.",
      en: "Past successes give me confidence for new challenges.",
      es: "Past successes give me confidence for new challenges.",
      fr: "Past successes give me confidence for new challenges.",
      ja: "Past successes give me confidence for new challenges.",
      ko: "과거의 성취를 생각하면 고난을 이겨낼 힘이 생긴다.",
    },
  },
  {
    factor: "purpose",
    id: "res_4",
    options: [
      {
        id: "opt_1",
        score: 4,
        text: {
          cn: "Strongly agree",
          en: "Strongly agree",
          es: "Strongly agree",
          fr: "Strongly agree",
          ja: "Strongly agree",
          ko: "매우 그렇다",
        },
      },
      {
        id: "opt_2",
        score: 3,
        text: {
          cn: "Agree",
          en: "Agree",
          es: "Agree",
          fr: "Agree",
          ja: "Agree",
          ko: "그렇다",
        },
      },
      {
        id: "opt_3",
        score: 2,
        text: {
          cn: "Neutral",
          en: "Neutral",
          es: "Neutral",
          fr: "Neutral",
          ja: "Neutral",
          ko: "보통이다",
        },
      },
      {
        id: "opt_4",
        score: 1,
        text: {
          cn: "Disagree",
          en: "Disagree",
          es: "Disagree",
          fr: "Disagree",
          ja: "Disagree",
          ko: "그렇지 않다",
        },
      },
      {
        id: "opt_5",
        score: 0,
        text: {
          cn: "Strongly disagree",
          en: "Strongly disagree",
          es: "Strongly disagree",
          fr: "Strongly disagree",
          ja: "Strongly disagree",
          ko: "전혀 그렇지 않다",
        },
      },
    ],
    text: {
      cn: "I believe that difficulties in life make me stronger.",
      en: "I believe that difficulties in life make me stronger.",
      es: "I believe that difficulties in life make me stronger.",
      fr: "I believe that difficulties in life make me stronger.",
      ja: "I believe that difficulties in life make me stronger.",
      ko: "인생의 고난은 나를 더 강하게 만든다고 믿는다.",
    },
  },
  {
    factor: "trust",
    id: "res_5",
    options: [
      {
        id: "opt_1",
        score: 4,
        text: {
          cn: "Strongly agree",
          en: "Strongly agree",
          es: "Strongly agree",
          fr: "Strongly agree",
          ja: "Strongly agree",
          ko: "매우 그렇다",
        },
      },
      {
        id: "opt_2",
        score: 3,
        text: {
          cn: "Agree",
          en: "Agree",
          es: "Agree",
          fr: "Agree",
          ja: "Agree",
          ko: "그렇다",
        },
      },
      {
        id: "opt_3",
        score: 2,
        text: {
          cn: "Neutral",
          en: "Neutral",
          es: "Neutral",
          fr: "Neutral",
          ja: "Neutral",
          ko: "보통이다",
        },
      },
      {
        id: "opt_4",
        score: 1,
        text: {
          cn: "Disagree",
          en: "Disagree",
          es: "Disagree",
          fr: "Disagree",
          ja: "Disagree",
          ko: "그렇지 않다",
        },
      },
      {
        id: "opt_5",
        score: 0,
        text: {
          cn: "Strongly disagree",
          en: "Strongly disagree",
          es: "Strongly disagree",
          fr: "Strongly disagree",
          ja: "Strongly disagree",
          ko: "전혀 그렇지 않다",
        },
      },
    ],
    text: {
      cn: "I trust myself and my instincts in difficult times.",
      en: "I trust myself and my instincts in difficult times.",
      es: "I trust myself and my instincts in difficult times.",
      fr: "I trust myself and my instincts in difficult times.",
      ja: "I trust myself and my instincts in difficult times.",
      ko: "어려울 때 나 자신과 내 직관을 깊이 신뢰한다.",
    },
  },
  {
    factor: "adaptability",
    id: "res_6",
    options: [
      {
        id: "opt_1",
        score: 4,
        text: {
          cn: "Strongly agree",
          en: "Strongly agree",
          es: "Strongly agree",
          fr: "Strongly agree",
          ja: "Strongly agree",
          ko: "매우 그렇다",
        },
      },
      {
        id: "opt_2",
        score: 3,
        text: {
          cn: "Agree",
          en: "Agree",
          es: "Agree",
          fr: "Agree",
          ja: "Agree",
          ko: "그렇다",
        },
      },
      {
        id: "opt_3",
        score: 2,
        text: {
          cn: "Neutral",
          en: "Neutral",
          es: "Neutral",
          fr: "Neutral",
          ja: "Neutral",
          ko: "보통이다",
        },
      },
      {
        id: "opt_4",
        score: 1,
        text: {
          cn: "Disagree",
          en: "Disagree",
          es: "Disagree",
          fr: "Disagree",
          ja: "Disagree",
          ko: "그렇지 않다",
        },
      },
      {
        id: "opt_5",
        score: 0,
        text: {
          cn: "Strongly disagree",
          en: "Strongly disagree",
          es: "Strongly disagree",
          fr: "Strongly disagree",
          ja: "Strongly disagree",
          ko: "전혀 그렇지 않다",
        },
      },
    ],
    text: {
      cn: "I tend to bounce back quickly after illness, injury, or other hardships.",
      en: "I tend to bounce back quickly after illness, injury, or other hardships.",
      es: "I tend to bounce back quickly after illness, injury, or other hardships.",
      fr: "I tend to bounce back quickly after illness, injury, or other hardships.",
      ja: "I tend to bounce back quickly after illness, injury, or other hardships.",
      ko: "나는 질병, 부상 또는 다른 어려움을 겪은 후 빨리 회복하는 편이다.",
    },
  },
  {
    factor: "hardiness",
    id: "res_7",
    options: [
      {
        id: "opt_1",
        score: 4,
        text: {
          cn: "Strongly agree",
          en: "Strongly agree",
          es: "Strongly agree",
          fr: "Strongly agree",
          ja: "Strongly agree",
          ko: "매우 그렇다",
        },
      },
      {
        id: "opt_2",
        score: 3,
        text: {
          cn: "Agree",
          en: "Agree",
          es: "Agree",
          fr: "Agree",
          ja: "Agree",
          ko: "그렇다",
        },
      },
      {
        id: "opt_3",
        score: 2,
        text: {
          cn: "Neutral",
          en: "Neutral",
          es: "Neutral",
          fr: "Neutral",
          ja: "Neutral",
          ko: "보통이다",
        },
      },
      {
        id: "opt_4",
        score: 1,
        text: {
          cn: "Disagree",
          en: "Disagree",
          es: "Disagree",
          fr: "Disagree",
          ja: "Disagree",
          ko: "그렇지 않다",
        },
      },
      {
        id: "opt_5",
        score: 0,
        text: {
          cn: "Strongly disagree",
          en: "Strongly disagree",
          es: "Strongly disagree",
          fr: "Strongly disagree",
          ja: "Strongly disagree",
          ko: "전혀 그렇지 않다",
        },
      },
    ],
    text: {
      cn: "Under pressure, I focus and think clearly.",
      en: "Under pressure, I focus and think clearly.",
      es: "Under pressure, I focus and think clearly.",
      fr: "Under pressure, I focus and think clearly.",
      ja: "Under pressure, I focus and think clearly.",
      ko: "나는 압박감을 느낄 때도 집중력을 유지한다.",
    },
  },
  {
    factor: "persistence",
    id: "res_8",
    options: [
      {
        id: "opt_1",
        score: 4,
        text: {
          cn: "Strongly agree",
          en: "Strongly agree",
          es: "Strongly agree",
          fr: "Strongly agree",
          ja: "Strongly agree",
          ko: "매우 그렇다",
        },
      },
      {
        id: "opt_2",
        score: 3,
        text: {
          cn: "Agree",
          en: "Agree",
          es: "Agree",
          fr: "Agree",
          ja: "Agree",
          ko: "그렇다",
        },
      },
      {
        id: "opt_3",
        score: 2,
        text: {
          cn: "Neutral",
          en: "Neutral",
          es: "Neutral",
          fr: "Neutral",
          ja: "Neutral",
          ko: "보통이다",
        },
      },
      {
        id: "opt_4",
        score: 1,
        text: {
          cn: "Disagree",
          en: "Disagree",
          es: "Disagree",
          fr: "Disagree",
          ja: "Disagree",
          ko: "그렇지 않다",
        },
      },
      {
        id: "opt_5",
        score: 0,
        text: {
          cn: "Strongly disagree",
          en: "Strongly disagree",
          es: "Strongly disagree",
          fr: "Strongly disagree",
          ja: "Strongly disagree",
          ko: "전혀 그렇지 않다",
        },
      },
    ],
    text: {
      cn: "I work to attain my goals no matter what roadblocks I encounter.",
      en: "I work to attain my goals no matter what roadblocks I encounter.",
      es: "I work to attain my goals no matter what roadblocks I encounter.",
      fr: "I work to attain my goals no matter what roadblocks I encounter.",
      ja: "I work to attain my goals no matter what roadblocks I encounter.",
      ko: "어떤 난관에 부딪혀도 목표를 달성하기 위해 노력한다.",
    },
  },
  {
    factor: "purpose",
    id: "res_9",
    options: [
      {
        id: "opt_1",
        score: 4,
        text: {
          cn: "Strongly agree",
          en: "Strongly agree",
          es: "Strongly agree",
          fr: "Strongly agree",
          ja: "Strongly agree",
          ko: "매우 그렇다",
        },
      },
      {
        id: "opt_2",
        score: 3,
        text: {
          cn: "Agree",
          en: "Agree",
          es: "Agree",
          fr: "Agree",
          ja: "Agree",
          ko: "그렇다",
        },
      },
      {
        id: "opt_3",
        score: 2,
        text: {
          cn: "Neutral",
          en: "Neutral",
          es: "Neutral",
          fr: "Neutral",
          ja: "Neutral",
          ko: "보통이다",
        },
      },
      {
        id: "opt_4",
        score: 1,
        text: {
          cn: "Disagree",
          en: "Disagree",
          es: "Disagree",
          fr: "Disagree",
          ja: "Disagree",
          ko: "그렇지 않다",
        },
      },
      {
        id: "opt_5",
        score: 0,
        text: {
          cn: "Strongly disagree",
          en: "Strongly disagree",
          es: "Strongly disagree",
          fr: "Strongly disagree",
          ja: "Strongly disagree",
          ko: "전혀 그렇지 않다",
        },
      },
    ],
    text: {
      cn: "I feel that my life has meaning.",
      en: "I feel that my life has meaning.",
      es: "I feel that my life has meaning.",
      fr: "I feel that my life has meaning.",
      ja: "I feel that my life has meaning.",
      ko: "나는 내 삶이 의미가 있다고 느낀다.",
    },
  },
  {
    factor: "trust",
    id: "res_10",
    options: [
      {
        id: "opt_1",
        score: 4,
        text: {
          cn: "Strongly agree",
          en: "Strongly agree",
          es: "Strongly agree",
          fr: "Strongly agree",
          ja: "Strongly agree",
          ko: "매우 그렇다",
        },
      },
      {
        id: "opt_2",
        score: 3,
        text: {
          cn: "Agree",
          en: "Agree",
          es: "Agree",
          fr: "Agree",
          ja: "Agree",
          ko: "그렇다",
        },
      },
      {
        id: "opt_3",
        score: 2,
        text: {
          cn: "Neutral",
          en: "Neutral",
          es: "Neutral",
          fr: "Neutral",
          ja: "Neutral",
          ko: "보통이다",
        },
      },
      {
        id: "opt_4",
        score: 1,
        text: {
          cn: "Disagree",
          en: "Disagree",
          es: "Disagree",
          fr: "Disagree",
          ja: "Disagree",
          ko: "그렇지 않다",
        },
      },
      {
        id: "opt_5",
        score: 0,
        text: {
          cn: "Strongly disagree",
          en: "Strongly disagree",
          es: "Strongly disagree",
          fr: "Strongly disagree",
          ja: "Strongly disagree",
          ko: "전혀 그렇지 않다",
        },
      },
    ],
    text: {
      cn: "I can find help when I need it.",
      en: "I can find help when I need it.",
      es: "I can find help when I need it.",
      fr: "I can find help when I need it.",
      ja: "I can find help when I need it.",
      ko: "나는 필요할 때 도움을 요청할 수 있다.",
    },
  },
  {
    factor: "adaptability",
    id: "res_11",
    options: [
      {
        id: "opt_1",
        score: 4,
        text: {
          cn: "Strongly agree",
          en: "Strongly agree",
          es: "Strongly agree",
          fr: "Strongly agree",
          ja: "Strongly agree",
          ko: "매우 그렇다",
        },
      },
      {
        id: "opt_2",
        score: 3,
        text: {
          cn: "Agree",
          en: "Agree",
          es: "Agree",
          fr: "Agree",
          ja: "Agree",
          ko: "그렇다",
        },
      },
      {
        id: "opt_3",
        score: 2,
        text: {
          cn: "Neutral",
          en: "Neutral",
          es: "Neutral",
          fr: "Neutral",
          ja: "Neutral",
          ko: "보통이다",
        },
      },
      {
        id: "opt_4",
        score: 1,
        text: {
          cn: "Disagree",
          en: "Disagree",
          es: "Disagree",
          fr: "Disagree",
          ja: "Disagree",
          ko: "그렇지 않다",
        },
      },
      {
        id: "opt_5",
        score: 0,
        text: {
          cn: "Strongly disagree",
          en: "Strongly disagree",
          es: "Strongly disagree",
          fr: "Strongly disagree",
          ja: "Strongly disagree",
          ko: "전혀 그렇지 않다",
        },
      },
    ],
    text: {
      cn: "I can adapt to change easily.",
      en: "I can adapt to change easily.",
      es: "I can adapt to change easily.",
      fr: "I can adapt to change easily.",
      ja: "I can adapt to change easily.",
      ko: "나는 변화에 쉽게 적응하는 편이다.",
    },
  },
  {
    factor: "hardiness",
    id: "res_12",
    options: [
      {
        id: "opt_1",
        score: 4,
        text: {
          cn: "Strongly agree",
          en: "Strongly agree",
          es: "Strongly agree",
          fr: "Strongly agree",
          ja: "Strongly agree",
          ko: "매우 그렇다",
        },
      },
      {
        id: "opt_2",
        score: 3,
        text: {
          cn: "Agree",
          en: "Agree",
          es: "Agree",
          fr: "Agree",
          ja: "Agree",
          ko: "그렇다",
        },
      },
      {
        id: "opt_3",
        score: 2,
        text: {
          cn: "Neutral",
          en: "Neutral",
          es: "Neutral",
          fr: "Neutral",
          ja: "Neutral",
          ko: "보통이다",
        },
      },
      {
        id: "opt_4",
        score: 1,
        text: {
          cn: "Disagree",
          en: "Disagree",
          es: "Disagree",
          fr: "Disagree",
          ja: "Disagree",
          ko: "그렇지 않다",
        },
      },
      {
        id: "opt_5",
        score: 0,
        text: {
          cn: "Strongly disagree",
          en: "Strongly disagree",
          es: "Strongly disagree",
          fr: "Strongly disagree",
          ja: "Strongly disagree",
          ko: "전혀 그렇지 않다",
        },
      },
    ],
    text: {
      cn: "I see challenges as opportunities for growth.",
      en: "I see challenges as opportunities for growth.",
      es: "I see challenges as opportunities for growth.",
      fr: "I see challenges as opportunities for growth.",
      ja: "I see challenges as opportunities for growth.",
      ko: "나는 도전을 성장의 기회로 본다.",
    },
  },
];

export const RESILIENCE_RESULTS = {
  high: {
    advice: {
      cn: "Strength comes from flexibility. Be kinder to yourself sometimes.",
      en: "Strength comes from flexibility. Be kinder to yourself sometimes.",
      es: "Strength comes from flexibility. Be kinder to yourself sometimes.",
      fr: "Strength comes from flexibility. Be kinder to yourself sometimes.",
      ja: "Strength comes from flexibility. Be kinder to yourself sometimes.",
      ko: "강함은 유연함에서 나옵니다. 때로는 자신에게 더 너그러워지세요.",
    },
    description: {
      cn: "You are like a giant tree deeply rooted even in a storm.",
      en: "You are like a giant tree deeply rooted even in a storm.",
      es: "You are like a giant tree deeply rooted even in a storm.",
      fr: "You are like a giant tree deeply rooted even in a storm.",
      ja: "You are like a giant tree deeply rooted even in a storm.",
      ko: "당신은 폭풍우 속에서도 뿌리를 깊이 내린 거목과 같습니다.",
    },
    oracleInsight: {
      cn: "Destiny opens paths for those who endure. Your patience will become victory.",
      en: "Destiny opens paths for those who endure. Your patience will become victory.",
      es: "Destiny opens paths for those who endure. Your patience will become victory.",
      fr: "Destiny opens paths for those who endure. Your patience will become victory.",
      ja: "Destiny opens paths for those who endure. Your patience will become victory.",
      ko: "천명은 견디는 자에게 길을 열어줍니다. 당신의 인내는 곧 승리가 될 것입니다.",
    },
    title: {
      cn: "Unbreakable Steel Spirit",
      en: "Unbreakable Steel Spirit",
      es: "Unbreakable Steel Spirit",
      fr: "Unbreakable Steel Spirit",
      ja: "Unbreakable Steel Spirit",
      ko: "불굴의 강철 정신",
    },
  },
  low: {
    advice: {
      cn: "Resilience is a muscle. Start with small acts of courage.",
      en: "Resilience is a muscle. Start with small acts of courage.",
      es: "Resilience is a muscle. Start with small acts of courage.",
      fr: "Resilience is a muscle. Start with small acts of courage.",
      ja: "Resilience is a muscle. Start with small acts of courage.",
      ko: "회복탄력성은 근육과 같습니다. 작은 용기로부터 시작하세요.",
    },
    description: {
      cn: "You feel things deeply and may take longer to recover from setbacks.",
      en: "You feel things deeply and may take longer to recover from setbacks.",
      es: "You feel things deeply and may take longer to recover from setbacks.",
      fr: "You feel things deeply and may take longer to recover from setbacks.",
      ja: "You feel things deeply and may take longer to recover from setbacks.",
      ko: "당신은 감정을 깊게 느끼며, 시련에서 회복하는 데 시간이 조금 더 걸릴 수 있습니다.",
    },
    oracleInsight: {
      cn: "Even the mightiest oak began as a fragile seed. Your vulnerability is the soil of your growth.",
      en: "Even the mightiest oak began as a fragile seed. Your vulnerability is the soil of your growth.",
      es: "Even the mightiest oak began as a fragile seed. Your vulnerability is the soil of your growth.",
      fr: "Even the mightiest oak began as a fragile seed. Your vulnerability is the soil of your growth.",
      ja: "Even the mightiest oak began as a fragile seed. Your vulnerability is the soil of your growth.",
      ko: "가장 거대한 참나무도 연약한 씨앗에서 시작했습니다. 당신의 여림은 성장의 토양입니다.",
    },
    title: {
      cn: "The Gentle Sprout",
      en: "The Gentle Sprout",
      es: "The Gentle Sprout",
      fr: "The Gentle Sprout",
      ja: "The Gentle Sprout",
      ko: "여린 새싹",
    },
  },
  moderate: {
    advice: {
      cn: "Develop the habit of building confidence by recording small achievements.",
      en: "Develop the habit of building confidence by recording small achievements.",
      es: "Develop the habit of building confidence by recording small achievements.",
      fr: "Develop the habit of building confidence by recording small achievements.",
      ja: "Develop the habit of building confidence by recording small achievements.",
      ko: "작은 성취를 기록하며 자신감을 쌓는 습관을 들여보세요.",
    },
    description: {
      cn: "You possess a flexible resilience that bends in the wind but does not break.",
      en: "You possess a flexible resilience that bends in the wind but does not break.",
      es: "You possess a flexible resilience that bends in the wind but does not break.",
      fr: "You possess a flexible resilience that bends in the wind but does not break.",
      ja: "You possess a flexible resilience that bends in the wind but does not break.",
      ko: "바람에 휘어지지만 꺾이지 않는 유연한 회복력을 지니고 있습니다.",
    },
    oracleInsight: {
      cn: "Water flows and avoids obstacles. Flexibility is your greatest weapon.",
      en: "Water flows and avoids obstacles. Flexibility is your greatest weapon.",
      es: "Water flows and avoids obstacles. Flexibility is your greatest weapon.",
      fr: "Water flows and avoids obstacles. Flexibility is your greatest weapon.",
      ja: "Water flows and avoids obstacles. Flexibility is your greatest weapon.",
      ko: "물은 흐르며 장애물을 피합니다. 유연함이 당신의 가장 큰 무기입니다.",
    },
    title: {
      cn: "The Adaptive Reed",
      en: "The Adaptive Reed",
      es: "The Adaptive Reed",
      fr: "The Adaptive Reed",
      ja: "The Adaptive Reed",
      ko: "적응하는 갈대",
    },
  },
};
