/**
 * Prosperity & Consumption Style Questions
 * Purified to Emerald Sanctuary Standard - 6 Locale Support
 */

const SCORES = {
  balanced: (s: number) => ({ balanced: s }),
  experience: (s: number) => ({ experience: s }),
  flexer: (s: number) => ({ flexer: s }),
  impulse: (s: number) => ({ impulse: s }),
  investor: (s: number) => ({ investor: s }),
  saver: (s: number) => ({ saver: s }),
};

export const CONSUMPTION_STYLE_QUESTIONS = {
  zh: [
    {
      emoji: "💰",
      id: "1",
      options: [
        {
          emoji: "👜",
          id: "a",
          scores: { flexer: 3, impulse: 2 },
          text: "立即获取心仪已久的匠心之作（名牌）。",
        },
        {
          emoji: "🏦",
          id: "b",
          scores: { investor: 2, saver: 3 },
          text: "将一部分封存于宏大的金库（储蓄）。",
        },
        {
          emoji: "⚖️",
          id: "c",
          scores: { balanced: 3 },
          text: "维持神圣的平衡，仅换取生活必需。",
        },
        {
          emoji: "🛍️",
          id: "d",
          scores: { impulse: 3 },
          text: "顺应当下的心境，让资财随性流动。",
        },
        {
          emoji: "📈",
          id: "e",
          scores: { investor: 3 },
          text: "寻找未来成长的种子（投资机会）。",
        },
        {
          emoji: "✈️",
          id: "f",
          scores: { experience: 3 },
          text: "投资于回忆的图谱（旅行与体验）。",
        },
      ],
      text: "当丰富之潮（薪酬）归来时，您的首个仪式为何？",
    },
    {
      emoji: "📱",
      id: "2",
      options: [
        {
          emoji: "🏃",
          id: "a",
          scores: { flexer: 3, impulse: 2 },
          text: "我必须立即获取同样的圣光。",
        },
        {
          emoji: "🤔",
          id: "b",
          scores: { balanced: 2, saver: 3 },
          text: "我现有的器皿尚能承载其用。",
        },
        {
          emoji: "📅",
          id: "c",
          scores: { balanced: 3 },
          text: "我将等待下一场星象的对齐。",
        },
        {
          emoji: "😫",
          id: "d",
          scores: { flexer: 1, impulse: 3 },
          text: "我的镜子突然显得黯淡过时。",
        },
        {
          emoji: "💹",
          id: "e",
          scores: { investor: 3 },
          text: "那笔财富可以育出无数成长的种子。",
        },
        {
          emoji: "🌍",
          id: "f",
          scores: { experience: 3 },
          text: "那笔财富足以开启一场跨越世界的远征。",
        },
      ],
      text: "当同伴展示新的「黑曜石之镜」（最新手机）时……",
    },
    {
      emoji: "🛒",
      id: "3",
      options: [
        {
          emoji: "⬆️",
          id: "a",
          scores: { flexer: 3 },
          text: "将其升华至更为尊贵的阶层。",
        },
        {
          emoji: "🤨",
          id: "b",
          scores: { saver: 3 },
          text: "冥想其存在是否确为神圣所需。",
        },
        {
          emoji: "👍",
          id: "c",
          scores: { balanced: 3 },
          text: "若价与值和谐统一，我便接纳。",
        },
        {
          emoji: "⚡",
          id: "d",
          scores: { impulse: 3 },
          text: "良机即在当下，断然出击。",
        },
        {
          emoji: "📊",
          id: "e",
          scores: { investor: 3 },
          text: "计算这些铜币在未来的成长潜力。",
        },
        {
          emoji: "🎭",
          id: "f",
          scores: { experience: 3 },
          text: "生存的回忆重于物质的空壳。",
        },
      ],
      text: "当心仪之物进入「镀金窗口」（促销）时……",
    },
    {
      emoji: "☕",
      id: "4",
      options: [
        {
          emoji: "⭐",
          id: "a",
          scores: { flexer: 3 },
          text: "唯有最为优雅的氛围方能满足。",
        },
        {
          emoji: "🏠",
          id: "b",
          scores: { saver: 3 },
          text: "我在自家的圣域中亲手煎制。",
        },
        {
          emoji: "☕",
          id: "c",
          scores: { balanced: 3 },
          text: "一处质朴、可靠的坊间火炉便好。",
        },
        {
          emoji: "🎲",
          id: "d",
          scores: { impulse: 3 },
          text: "我追随心念中多变的微风。",
        },
        {
          emoji: "🪙",
          id: "e",
          scores: { investor: 3 },
          text: "今日省下的微毫将筑就明日的帝国。",
        },
        {
          emoji: "🌟",
          id: "f",
          scores: { experience: 3 },
          text: "我探寻稀有的起源与独特的叙事。",
        },
      ],
      text: "当参与「醇豆之仪」（咖啡）时……",
    },
    {
      emoji: "💵",
      id: "5",
      options: [
        {
          emoji: "⌚",
          id: "a",
          scores: { flexer: 3 },
          text: "以象征地位的配饰装点自身。",
        },
        {
          emoji: "💰",
          id: "b",
          scores: { saver: 3 },
          text: "将其悉数交付金库的庇护。",
        },
        {
          emoji: "➗",
          id: "c",
          scores: { balanced: 3 },
          text: "拆分溪流：一半归于成长，一半归于生活。",
        },
        {
          emoji: "🎁",
          id: "d",
          scores: { impulse: 3 },
          text: "瞬间满足过往所有的渴望！",
        },
        {
          emoji: "📈",
          id: "e",
          scores: { investor: 3 },
          text: "将涓涓细流导向资本的大河。",
        },
        {
          emoji: "🎫",
          id: "f",
          scores: { experience: 3 },
          text: "开启一段通往未知地平线的航程。",
        },
      ],
      text: "若突获三百万金（奖金）的恩赐？",
    },
    {
      emoji: "👕",
      id: "6",
      options: [
        {
          emoji: "🏷️",
          id: "a",
          scores: { flexer: 3 },
          text: "品牌与匠人的印记承载着灵魂。",
        },
        {
          emoji: "💸",
          id: "b",
          scores: { saver: 3 },
          text: "代价是智慧最为显著的向导。",
        },
        {
          emoji: "⚖️",
          id: "c",
          scores: { balanced: 3 },
          text: "我寻求德行与价值的平衡点。",
        },
        {
          emoji: "😍",
          id: "d",
          scores: { impulse: 3 },
          text: "我选择与当下精神共鸣之物。",
        },
        {
          emoji: "👔",
          id: "e",
          scores: { investor: 3 },
          text: "简约的皮毛，我的本质在他处。",
        },
        {
          emoji: "✨",
          id: "f",
          scores: { experience: 3 },
          text: "我披挂带有独特故事的物件。",
        },
      ],
      text: "选择覆盖身躯的「丝绸」（衣物）时最重何者？",
    },
    {
      emoji: "🎁",
      id: "7",
      options: [
        {
          emoji: "💝",
          id: "a",
          scores: { flexer: 3 },
          text: "一件能赢得尊重的名贵遗赠。",
        },
        {
          emoji: "🎀",
          id: "b",
          scores: { saver: 3 },
          text: "某种实用且含蓄的微末之物。",
        },
        {
          emoji: "🎈",
          id: "c",
          scores: { balanced: 3 },
          text: "与其真实性格契合的周全之选。",
        },
        {
          emoji: "🏬",
          id: "d",
          scores: { impulse: 3 },
          text: "凭直觉选中第一道出现的灵光。",
        },
        {
          emoji: "💳",
          id: "e",
          scores: { investor: 3 },
          text: "富足的平等或金融智慧的种子。",
        },
        {
          emoji: "🎭",
          id: "f",
          scores: { experience: 3 },
          text: "一份共度余下时光的邀约。",
        },
      ],
      text: "挑选一份庆贺同伴「岁星归位」（生日）的礼品时……",
    },
    {
      emoji: "🏦",
      id: "8",
      options: [
        {
          emoji: "😊",
          id: "a",
          scores: { flexer: 2, impulse: 2 },
          text: "我为未来渴望的燃料而感到欣喜。",
        },
        {
          emoji: "📊",
          id: "b",
          scores: { investor: 2, saver: 3 },
          text: "我衡量通往宏大目标的路途。",
        },
        {
          emoji: "👌",
          id: "c",
          scores: { balanced: 3 },
          text: "我在川流的稳定中寻得静谧。",
        },
        {
          emoji: "😅",
          id: "d",
          scores: { impulse: 3 },
          text: "周而复始。我必须策划下一场涌动。",
        },
        {
          emoji: "🧮",
          id: "e",
          scores: { investor: 3 },
          text: "我开始计算成长与产出的律动。",
        },
        {
          emoji: "🎯",
          id: "f",
          scores: { experience: 3 },
          text: "我衡量下一次探求的行囊。",
        },
      ],
      text: "审视金库当前的律动时，心中作何感想？",
    },
  ],
  en: [
    {
      emoji: "💰",
      id: "1",
      options: [
        {
          emoji: "👜",
          id: "a",
          scores: { flexer: 3, impulse: 2 },
          text: "Obtain a sacred relic of craftsmanship (luxury).",
        },
        {
          emoji: "🏦",
          id: "b",
          scores: { investor: 2, saver: 3 },
          text: "Seal a portion in the grand vault (savings).",
        },
        {
          emoji: "⚖️",
          id: "c",
          scores: { balanced: 3 },
          text: "Maintain sacred balance, securing only necessities.",
        },
        {
          emoji: "🛍️",
          id: "d",
          scores: { impulse: 3 },
          text: "Allow the energy to flow as the moment dictates.",
        },
        {
          emoji: "📈",
          id: "e",
          scores: { investor: 3 },
          text: "Seek out seeds of future growth (investments).",
        },
        {
          emoji: "✈️",
          id: "f",
          scores: { experience: 3 },
          text: "Invest in the map of memories (experiences).",
        },
      ],
      text: "What is your first ritual when the tides of abundance (salary) arrive?",
    },
    {
      emoji: "📱",
      id: "2",
      options: [
        {
          emoji: "🏃",
          id: "a",
          scores: { flexer: 3, impulse: 2 },
          text: "I must instantly acquire the same light.",
        },
        {
          emoji: "🤔",
          id: "b",
          scores: { balanced: 2, saver: 3 },
          text: "My current vessel still serves its purpose.",
        },
        {
          emoji: "📅",
          id: "c",
          scores: { balanced: 3 },
          text: "I wait for the next alignment of stars.",
        },
        {
          emoji: "😫",
          id: "d",
          scores: { flexer: 1, impulse: 3 },
          text: "My own mirror suddenly feels dim and aged.",
        },
        {
          emoji: "💹",
          id: "e",
          scores: { investor: 3 },
          text: "That wealth could sprout many seeds of growth.",
        },
        {
          emoji: "🌍",
          id: "f",
          scores: { experience: 3 },
          text: "That wealth could fund an odyssey across worlds.",
        },
      ],
      text: "When a companion unveils a new obsidian mirror (smartphone)...",
    },
    {
      emoji: "🛒",
      id: "3",
      options: [
        {
          emoji: "⬆️",
          id: "a",
          scores: { flexer: 3 },
          text: "Elevate to the most premium tier.",
        },
        {
          emoji: "🤨",
          id: "b",
          scores: { saver: 3 },
          text: "Meditate on whether its presence is truly required.",
        },
        {
          emoji: "👍",
          id: "c",
          scores: { balanced: 3 },
          text: "If the value and price harmonize, I accept it.",
        },
        {
          emoji: "⚡",
          id: "d",
          scores: { impulse: 3 },
          text: "The moment is now; seize it instantly.",
        },
        {
          emoji: "📊",
          id: "e",
          scores: { investor: 3 },
          text: "Calculate the future growth of those same coins.",
        },
        {
          emoji: "🎭",
          id: "f",
          scores: { experience: 3 },
          text: "Memories of existence outweigh material shells.",
        },
      ],
      text: 'When a desired item enters the "Gilded Window" (sale)...',
    },
    {
      emoji: "☕",
      id: "4",
      options: [
        {
          emoji: "⭐",
          id: "a",
          scores: { flexer: 3 },
          text: "Only the most refined atmosphere will suffice.",
        },
        {
          emoji: "🏠",
          id: "b",
          scores: { saver: 3 },
          text: "I brew my own elixir within my sanctuary.",
        },
        {
          emoji: "☕",
          id: "c",
          scores: { balanced: 3 },
          text: "A humble, reliable local hearth serves well.",
        },
        {
          emoji: "🎲",
          id: "d",
          scores: { impulse: 3 },
          text: "I follow the whim of the shifting winds.",
        },
        {
          emoji: "🪙",
          id: "e",
          scores: { investor: 3 },
          text: "Small coins saved today build empires tomorrow.",
        },
        {
          emoji: "🌟",
          id: "f",
          scores: { experience: 3 },
          text: "I seek out rare origins and unique narratives.",
        },
      ],
      text: "When partaking in the ritual of the brewed bean (coffee)...",
    },
    {
      emoji: "💵",
      id: "5",
      options: [
        {
          emoji: "⌚",
          id: "a",
          scores: { flexer: 3 },
          text: "Adorn myself with a symbol of status.",
        },
        {
          emoji: "💰",
          id: "b",
          scores: { saver: 3 },
          text: "Entrust it all to the safety of the vault.",
        },
        {
          emoji: "➗",
          id: "c",
          scores: { balanced: 3 },
          text: "Split the stream: half for growth, half for life.",
        },
        {
          emoji: "🎁",
          id: "d",
          scores: { impulse: 3 },
          text: "Fulfill all suppressed desires at once!",
        },
        {
          emoji: "📈",
          id: "e",
          scores: { investor: 3 },
          text: "Direct the flow into the rivers of capital.",
        },
        {
          emoji: "🎫",
          id: "f",
          scores: { experience: 3 },
          text: "Embark on a voyage to uncharted horizons.",
        },
      ],
      text: "Upon receiving a sudden gift of 3,000,000 coins (bonus)...",
    },
    {
      emoji: "👕",
      id: "6",
      options: [
        {
          emoji: "🏷️",
          id: "a",
          scores: { flexer: 3 },
          text: "The lineage and label carry the soul.",
        },
        {
          emoji: "💸",
          id: "b",
          scores: { saver: 3 },
          text: "Price is the primary beacon of wisdom.",
        },
        {
          emoji: "⚖️",
          id: "c",
          scores: { balanced: 3 },
          text: "I seek the balance of virtue and value.",
        },
        {
          emoji: "😍",
          id: "d",
          scores: { impulse: 3 },
          text: "I choose what resonates with my current spirit.",
        },
        {
          emoji: "👔",
          id: "e",
          scores: { investor: 3 },
          text: "Minimalist shells; my essence lies elsewhere.",
        },
        {
          emoji: "✨",
          id: "f",
          scores: { experience: 3 },
          text: "I wear pieces that whisper a unique story.",
        },
      ],
      text: "When choosing the silk that covers your form (clothing)...",
    },
    {
      emoji: "🎁",
      id: "7",
      options: [
        {
          emoji: "💝",
          id: "a",
          scores: { flexer: 3 },
          text: "A premium relic that commands respect.",
        },
        {
          emoji: "🎀",
          id: "b",
          scores: { saver: 3 },
          text: "Something utilitarian and modest.",
        },
        {
          emoji: "🎈",
          id: "c",
          scores: { balanced: 3 },
          text: "A thoughtful match for their true character.",
        },
        {
          emoji: "🏬",
          id: "d",
          scores: { impulse: 3 },
          text: "The first beam of inspiration I encounter.",
        },
        {
          emoji: "💳",
          id: "e",
          scores: { investor: 3 },
          text: "A seed of equity or financial wisdom.",
        },
        {
          emoji: "🎭",
          id: "f",
          scores: { experience: 3 },
          text: "An invitation to a shared moment in time.",
        },
      ],
      text: "When selecting a token for a companion's solar return (birthday)...",
    },
    {
      emoji: "🏦",
      id: "8",
      options: [
        {
          emoji: "😊",
          id: "a",
          scores: { flexer: 2, impulse: 2 },
          text: "I rejoice in the fuel for my future desires.",
        },
        {
          emoji: "📊",
          id: "b",
          scores: { investor: 2, saver: 3 },
          text: "I measure the progress toward my great goal.",
        },
        {
          emoji: "👌",
          id: "c",
          scores: { balanced: 3 },
          text: "I feel peace in the stability of the stream.",
        },
        {
          emoji: "😅",
          id: "d",
          scores: { impulse: 3 },
          text: "The cycle continues... I must plan for the next surge.",
        },
        {
          emoji: "🧮",
          id: "e",
          scores: { investor: 3 },
          text: "I begin the calculations of growth and yield.",
        },
        {
          emoji: "🎯",
          id: "f",
          scores: { experience: 3 },
          text: "I calculate the budget for my next adventure.",
        },
      ],
      text: "When gazing upon the current state of your vault...",
    },
  ],
  es: [
    {
      emoji: "💰",
      id: "1",
      options: [
        {
          emoji: "👜",
          id: "a",
          scores: { flexer: 3, impulse: 2 },
          text: "Obtener una reliquia sagrada de artesanía (lujo).",
        },
        {
          emoji: "🏦",
          id: "b",
          scores: { investor: 2, saver: 3 },
          text: "Sellar una parte en la gran bóveda (ahorro).",
        },
        {
          emoji: "⚖️",
          id: "c",
          scores: { balanced: 3 },
          text: "Mantener el equilibrio sagrado, asegurando lo esencial.",
        },
        {
          emoji: "🛍️",
          id: "d",
          scores: { impulse: 3 },
          text: "Permitir que la energía fluya según dicte el momento.",
        },
        {
          emoji: "📈",
          id: "e",
          scores: { investor: 3 },
          text: "Buscar semillas para el crecimiento futuro (inversión).",
        },
        {
          emoji: "✈️",
          id: "f",
          scores: { experience: 3 },
          text: "Invertir en el mapa de los recuerdos (experiencias).",
        },
      ],
      text: "¿Cuál es su primer ritual cuando llega la marea de la abundancia (salario)?",
    },
    {
      emoji: "📱",
      id: "2",
      options: [
        {
          emoji: "🏃",
          id: "a",
          scores: { flexer: 3, impulse: 2 },
          text: "Debo adquirir instantáneamente la misma luz.",
        },
        {
          emoji: "🤔",
          id: "b",
          scores: { balanced: 2, saver: 3 },
          text: "Mi vasija actual todavía cumple su propósito.",
        },
        {
          emoji: "📅",
          id: "c",
          scores: { balanced: 3 },
          text: "Espero la próxima alineación de estrellas.",
        },
        {
          emoji: "😫",
          id: "d",
          scores: { flexer: 1, impulse: 3 },
          text: "Mi propio espejo de repente parece opaco y viejo.",
        },
        {
          emoji: "💹",
          id: "e",
          scores: { investor: 3 },
          text: "Esa riqueza podría brotar muchas semillas de crecimiento.",
        },
        {
          emoji: "🌍",
          id: "f",
          scores: { experience: 3 },
          text: "Esa riqueza podría financiar una odisea por mundos lejanos.",
        },
      ],
      text: 'Cuando un compañero revela un nuevo "espejo de obsidiana" (smartphone)...',
    },
    {
      emoji: "🛒",
      id: "3",
      options: [
        {
          emoji: "⬆️",
          id: "a",
          scores: { flexer: 3 },
          text: "Elevarlo al nivel más premium.",
        },
        {
          emoji: "🤨",
          id: "b",
          scores: { saver: 3 },
          text: "Meditar sobre si su presencia es realmente requerida.",
        },
        {
          emoji: "👍",
          id: "c",
          scores: { balanced: 3 },
          text: "Si el valor y el precio armonizan, lo acepto.",
        },
        {
          emoji: "⚡",
          id: "d",
          scores: { impulse: 3 },
          text: "El momento es ahora; capturarlo instantáneamente.",
        },
        {
          emoji: "📊",
          id: "e",
          scores: { investor: 3 },
          text: "Calcular el crecimiento futuro de esas mismas monedas.",
        },
        {
          emoji: "🎭",
          id: "f",
          scores: { experience: 3 },
          text: "Los recuerdos de existencia pesan más que las cáscaras materiales.",
        },
      ],
      text: 'Cuando un objeto deseado entra en la "Ventana Dorada" (oferta)...',
    },
    {
      emoji: "☕",
      id: "4",
      options: [
        {
          emoji: "⭐",
          id: "a",
          scores: { flexer: 3 },
          text: "Solo la atmósfera más refinada será suficiente.",
        },
        {
          emoji: "🏠",
          id: "b",
          scores: { saver: 3 },
          text: "Yo mismo preparo mi elixir dentro de mi santuario.",
        },
        {
          emoji: "☕",
          id: "c",
          scores: { balanced: 3 },
          text: "Un hogar local humilde y confiable sirve bien.",
        },
        {
          emoji: "🎲",
          id: "d",
          scores: { impulse: 3 },
          text: "Sigo el capricho de los vientos cambiantes.",
        },
        {
          emoji: "🪙",
          id: "e",
          scores: { investor: 3 },
          text: "Pequeñas monedas ahorradas hoy construyen imperios mañana.",
        },
        {
          emoji: "🌟",
          id: "f",
          scores: { experience: 3 },
          text: "Busco orígenes raros y narrativas únicas.",
        },
      ],
      text: "Al participar en el ritual del grano tostado (café)...",
    },
    {
      emoji: "💵",
      id: "5",
      options: [
        {
          emoji: "⌚",
          id: "a",
          scores: { flexer: 3 },
          text: "Adornarme con un símbolo de estatus.",
        },
        {
          emoji: "💰",
          id: "b",
          scores: { saver: 3 },
          text: "Confiarlo todo a la seguridad de la bóveda.",
        },
        {
          emoji: "➗",
          id: "c",
          scores: { balanced: 3 },
          text: "Dividir el flujo: mitad para el crecimiento, mitad para la vida.",
        },
        {
          emoji: "🎁",
          id: "d",
          scores: { impulse: 3 },
          text: "¡Cumplir todos los deseos reprimidos a la vez!",
        },
        {
          emoji: "📈",
          id: "e",
          scores: { investor: 3 },
          text: "Dirigir el flujo hacia los ríos del capital.",
        },
        {
          emoji: "🎫",
          id: "f",
          scores: { experience: 3 },
          text: "Embarcarse en un viaje hacia horizontes inexplorados.",
        },
      ],
      text: "¿Al recibir un regalo repentino de 3.000.000 de monedas (bono)?",
    },
    {
      emoji: "👕",
      id: "6",
      options: [
        {
          emoji: "🏷️",
          id: "a",
          scores: { flexer: 3 },
          text: "El linaje y la marca llevan el alma.",
        },
        {
          emoji: "💸",
          id: "b",
          scores: { saver: 3 },
          text: "El precio es el faro principal de la sabiduría.",
        },
        {
          emoji: "⚖️",
          id: "c",
          scores: { balanced: 3 },
          text: "Busco el equilibrio entre la virtud y el valor.",
        },
        {
          emoji: "😍",
          id: "d",
          scores: { impulse: 3 },
          text: "Elijo lo que resuena con mi espíritu actual.",
        },
        {
          emoji: "👔",
          id: "e",
          scores: { investor: 3 },
          text: "Envolturas minimalistas; mi esencia reside en otro lugar.",
        },
        {
          emoji: "✨",
          id: "f",
          scores: { experience: 3 },
          text: "Visto piezas que susurran una historia única.",
        },
      ],
      text: "Al elegir la seda que cubre su forma (ropa)...",
    },
    {
      emoji: "🎁",
      id: "7",
      options: [
        {
          emoji: "💝",
          id: "a",
          scores: { flexer: 3 },
          text: "Una reliquia premium que inspira respeto.",
        },
        {
          emoji: "🎀",
          id: "b",
          scores: { saver: 3 },
          text: "Algo utilitario y modesto.",
        },
        {
          emoji: "🎈",
          id: "c",
          scores: { balanced: 3 },
          text: "Una combinación perfecta para su verdadero carácter.",
        },
        {
          emoji: "🏬",
          id: "d",
          scores: { impulse: 3 },
          text: "El primer rayo de inspiración que encuentro.",
        },
        {
          emoji: "💳",
          id: "e",
          scores: { investor: 3 },
          text: "Una semilla de equidad o sabiduría financiera.",
        },
        {
          emoji: "🎭",
          id: "f",
          scores: { experience: 3 },
          text: "Una invitación a un momento compartido en el tiempo.",
        },
      ],
      text: "Al seleccionar un obsequio para el regreso solar de un compañero (cumpleaños)...",
    },
    {
      emoji: "🏦",
      id: "8",
      options: [
        {
          emoji: "😊",
          id: "a",
          scores: { flexer: 2, impulse: 2 },
          text: "Me regocijo en el combustible para mis deseos futuros.",
        },
        {
          emoji: "📊",
          id: "b",
          scores: { investor: 2, saver: 3 },
          text: "Mido el progreso hacia mi gran meta.",
        },
        {
          emoji: "👌",
          id: "c",
          scores: { balanced: 3 },
          text: "Siento paz en la estabilidad del flujo.",
        },
        {
          emoji: "😅",
          id: "d",
          scores: { impulse: 3 },
          text: "El ciclo continúa... debo planear para el próximo aumento.",
        },
        {
          emoji: "🧮",
          id: "e",
          scores: { investor: 3 },
          text: "Comienzo los cálculos de crecimiento y rendimiento.",
        },
        {
          emoji: "🎯",
          id: "f",
          scores: { experience: 3 },
          text: "Calculo el presupuesto para mi próxima aventura.",
        },
      ],
      text: "Al contemplar el estado actual de su bóveda...",
    },
  ],
  fr: [
    {
      emoji: "💰",
      id: "1",
      options: [
        {
          emoji: "👜",
          id: "a",
          scores: { flexer: 3, impulse: 2 },
          text: "Obtenir une relique sacrée d'artisanat (luxe).",
        },
        {
          emoji: "🏦",
          id: "b",
          scores: { investor: 2, saver: 3 },
          text: "Sceller une partie dans la grande crypte (épargne).",
        },
        {
          emoji: "⚖️",
          id: "c",
          scores: { balanced: 3 },
          text: "Maintenir l'équilibre sacré, en ne prenant que l'essentiel.",
        },
        {
          emoji: "🛍️",
          id: "d",
          scores: { impulse: 3 },
          text: "Laisser l'énergie circuler au gré du moment présent.",
        },
        {
          emoji: "📈",
          id: "e",
          scores: { investor: 3 },
          text: "Chercher les graines d'une croissance future (investissement).",
        },
        {
          emoji: "✈️",
          id: "f",
          scores: { experience: 3 },
          text: "Investir dans la cartographie des souvenirs (voyages).",
        },
      ],
      text: "Quel est votre premier rituel lorsque les marées de l'abondance (salaire) arrivent ?",
    },
    {
      emoji: "📱",
      id: "2",
      options: [
        {
          emoji: "🏃",
          id: "a",
          scores: { flexer: 3, impulse: 2 },
          text: "Je dois instantanément acquérir la même lumière.",
        },
        {
          emoji: "🤔",
          id: "b",
          scores: { balanced: 2, saver: 3 },
          text: "Mon vaisseau actuel remplit encore son office.",
        },
        {
          emoji: "📅",
          id: "c",
          scores: { balanced: 3 },
          text: "J'attends le prochain alignement des astres.",
        },
        {
          emoji: "😫",
          id: "d",
          scores: { flexer: 1, impulse: 3 },
          text: "Mon propre miroir semble soudainement terne et âgé.",
        },
        {
          emoji: "💹",
          id: "e",
          scores: { investor: 3 },
          text: "Cette richesse pourrait faire germer bien des graines.",
        },
        {
          emoji: "🌍",
          id: "f",
          scores: { experience: 3 },
          text: "Cette richesse pourrait financer une épopée lointaine.",
        },
      ],
      text: "Lorsqu'un compagnon dévoile un nouveau \"miroir d'obsidienne\" (smartphone)...",
    },
    {
      emoji: "🛒",
      id: "3",
      options: [
        {
          emoji: "⬆️",
          id: "a",
          scores: { flexer: 3 },
          text: "L'élever au rang le plus prestigieux.",
        },
        {
          emoji: "🤨",
          id: "b",
          scores: { saver: 3 },
          text: "Méditer sur la nécessité réelle de sa présence.",
        },
        {
          emoji: "👍",
          id: "c",
          scores: { balanced: 3 },
          text: "Si la valeur et le prix s'harmonisent, j'accepte.",
        },
        {
          emoji: "⚡",
          id: "d",
          scores: { impulse: 3 },
          text: "C'est l'instant propice ; le saisir sans tarder.",
        },
        {
          emoji: "📊",
          id: "e",
          scores: { investor: 3 },
          text: "Calculer la croissance future de ces mêmes deniers.",
        },
        {
          emoji: "🎭",
          id: "f",
          scores: { experience: 3 },
          text: "Les souvenirs d'existence priment sur les coques matérielles.",
        },
      ],
      text: 'Lorsqu\'un objet désiré entre dans la "Fenêtre Dorée" (soldes)...',
    },
    {
      emoji: "☕",
      id: "4",
      options: [
        {
          emoji: "⭐",
          id: "a",
          scores: { flexer: 3 },
          text: "Seule l'atmosphère la plus raffinée saura me satisfaire.",
        },
        {
          emoji: "🏠",
          id: "b",
          scores: { saver: 3 },
          text: "Je distille mon propre élixir dans mon sanctuaire.",
        },
        {
          emoji: "☕",
          id: "c",
          scores: { balanced: 3 },
          text: "Un humble et fiable foyer local me suffit.",
        },
        {
          emoji: "🎲",
          id: "d",
          scores: { impulse: 3 },
          text: "Je suis le caprice des vents changeants.",
        },
        {
          emoji: "🪙",
          id: "e",
          scores: { investor: 3 },
          text: "Les petits deniers d'aujourd'hui bâtissent les empires demain.",
        },
        {
          emoji: "🌟",
          id: "f",
          scores: { experience: 3 },
          text: "Je quête des origines rares et des récits uniques.",
        },
      ],
      text: "En participant au rituel du grain torréfié (café)...",
    },
    {
      emoji: "💵",
      id: "5",
      options: [
        {
          emoji: "⌚",
          id: "a",
          scores: { flexer: 3 },
          text: "M'orner d'un symbole de mon rang.",
        },
        {
          emoji: "💰",
          id: "b",
          scores: { saver: 3 },
          text: "Confier le tout à la sûreté de la crypte.",
        },
        {
          emoji: "➗",
          id: "c",
          scores: { balanced: 3 },
          text: "Diviser le flux : moitié pour la croissance, moitié pour la vie.",
        },
        {
          emoji: "🎁",
          id: "d",
          scores: { impulse: 3 },
          text: "Combler tous les désirs réprimés d'un seul coup !",
        },
        {
          emoji: "📈",
          id: "e",
          scores: { investor: 3 },
          text: "Diriger le courant vers les rivières du capital.",
        },
        {
          emoji: "🎫",
          id: "f",
          scores: { experience: 3 },
          text: "M'embarquer pour un voyage vers des horizons inexplorés.",
        },
      ],
      text: "Si vous recevez un don soudain de 3 000 000 de pièces (bonus) ?",
    },
    {
      emoji: "👕",
      id: "6",
      options: [
        {
          emoji: "🏷️",
          id: "a",
          scores: { flexer: 3 },
          text: "Le lignage et le blason portent l'âme.",
        },
        {
          emoji: "💸",
          id: "b",
          scores: { saver: 3 },
          text: "Le prix est le principal phare de la sagesse.",
        },
        {
          emoji: "⚖️",
          id: "c",
          scores: { balanced: 3 },
          text: "Je quête l'équilibre entre la vertu et la valeur.",
        },
        {
          emoji: "😍",
          id: "d",
          scores: { impulse: 3 },
          text: "Je choisis ce qui résonne avec mon esprit du moment.",
        },
        {
          emoji: "👔",
          id: "e",
          scores: { investor: 3 },
          text: "Enveloppes minimalistes ; mon essence est ailleurs.",
        },
        {
          emoji: "✨",
          id: "f",
          scores: { experience: 3 },
          text: "Je porte des pièces qui murmurent une histoire unique.",
        },
      ],
      text: "En choisissant la soie qui couvre votre forme (vêtements)...",
    },
    {
      emoji: "🎁",
      id: "7",
      options: [
        {
          emoji: "💝",
          id: "a",
          scores: { flexer: 3 },
          text: "Une relique précieuse qui force le respect.",
        },
        {
          emoji: "🎀",
          id: "b",
          scores: { saver: 3 },
          text: "Quelque chose d'utilitaire et de modeste.",
        },
        {
          emoji: "🎈",
          id: "c",
          scores: { balanced: 3 },
          text: "Une attention choisie pour sa véritable nature.",
        },
        {
          emoji: "🏬",
          id: "d",
          scores: { impulse: 3 },
          text: "La première lueur d'inspiration qui s'offre à moi.",
        },
        {
          emoji: "💳",
          id: "e",
          scores: { investor: 3 },
          text: "Une graine d'équité ou de sagesse financière.",
        },
        {
          emoji: "🎭",
          id: "f",
          scores: { experience: 3 },
          text: "Une invitation à un moment partagé dans le temps.",
        },
      ],
      text: "En choisissant une offrande pour le retour solaire d'un compagnon (anniversaire)...",
    },
    {
      emoji: "🏦",
      id: "8",
      options: [
        {
          emoji: "😊",
          id: "a",
          scores: { flexer: 2, impulse: 2 },
          text: "Je me réjouis du carburant pour mes désirs futurs.",
        },
        {
          emoji: "📊",
          id: "b",
          scores: { investor: 2, saver: 3 },
          text: "Je mesure le chemin vers mon grand dessein.",
        },
        {
          emoji: "👌",
          id: "c",
          scores: { balanced: 3 },
          text: "Je trouve la paix dans la stabilité du flux.",
        },
        {
          emoji: "😅",
          id: "d",
          scores: { impulse: 3 },
          text: "Le cycle continue... je dois prévoir la prochaine crue.",
        },
        {
          emoji: "🧮",
          id: "e",
          scores: { investor: 3 },
          text: "J'entame les calculs de croissance et de rendement.",
        },
        {
          emoji: "🎯",
          id: "f",
          scores: { experience: 3 },
          text: "Je mesure les ressources pour ma prochaine aventure.",
        },
      ],
      text: "En contemplant l'état actuel de votre crypte...",
    },
  ],
  ja: [
    {
      emoji: "💰",
      id: "1",
      options: [
        {
          emoji: "👜",
          id: "a",
          scores: { flexer: 3, impulse: 2 },
          text: "欲しかった職人の至宝（高級品）を即座に手に入れる。",
        },
        {
          emoji: "🏦",
          id: "b",
          scores: { investor: 2, saver: 3 },
          text: "大いなる蔵（貯蓄・投資）に一部を封じる。",
        },
        {
          emoji: "⚖️",
          id: "c",
          scores: { balanced: 3 },
          text: "聖なる調和を保ち、必需品のみを確保する。",
        },
        {
          emoji: "🛍️",
          id: "d",
          scores: { impulse: 3 },
          text: "その瞬間の心のままに、エネルギーを流す。",
        },
        {
          emoji: "📈",
          id: "e",
          scores: { investor: 3 },
          text: "未来の成長の種（株式・資産）を探す。",
        },
        {
          emoji: "✈️",
          id: "f",
          scores: { experience: 3 },
          text: "記憶の地図（旅行・体験）に投資する。",
        },
      ],
      text: "給与という豊穣の波が届いた時、最初の儀式は何ですか？",
    },
    {
      emoji: "📱",
      id: "2",
      options: [
        {
          emoji: "🏃",
          id: "a",
          scores: { flexer: 3, impulse: 2 },
          text: "自分も直ちに同じ光を手に入れる。",
        },
        {
          emoji: "🤔",
          id: "b",
          scores: { balanced: 2, saver: 3 },
          text: "今の器でまだ十分に役目は果たせる。",
        },
        {
          emoji: "📅",
          id: "c",
          scores: { balanced: 3 },
          text: "星々の巡り（次世代機）を待つ。",
        },
        {
          emoji: "😫",
          id: "d",
          scores: { flexer: 1, impulse: 3 },
          text: "自分の鏡が急に古ぼけて見え、欲しくなる。",
        },
        {
          emoji: "💹",
          id: "e",
          scores: { investor: 3 },
          text: "その富があれば、多くの成長の種が蒔ける。",
        },
        {
          emoji: "🌍",
          id: "f",
          scores: { experience: 3 },
          text: "その富があれば、異国への旅路が開ける。",
        },
      ],
      text: "友人が新しい「黒曜石の鏡」（最新スマホ）を披露した時……",
    },
    {
      emoji: "🛒",
      id: "3",
      options: [
        {
          emoji: "⬆️",
          id: "a",
          scores: { flexer: 3 },
          text: "さらに上位の至高の階層へ昇格させる。",
        },
        {
          emoji: "🤨",
          id: "b",
          scores: { saver: 3 },
          text: "それが本当に必要か、深く瞑想する。",
        },
        {
          emoji: "👍",
          id: "c",
          scores: { balanced: 3 },
          text: "価値と対価が調和しているならば、受け入れる。",
        },
        {
          emoji: "⚡",
          id: "d",
          scores: { impulse: 3 },
          text: "好機は今、迷わずその手に掴む。",
        },
        {
          emoji: "📊",
          id: "e",
          scores: { investor: 3 },
          text: "その硬貨が未来にもたらす成長を計算する。",
        },
        {
          emoji: "🎭",
          id: "f",
          scores: { experience: 3 },
          text: "存在の記憶は、物質の殻よりも重い。",
        },
      ],
      text: "熱望していた品が「黄金の窓」（セール）に現れた時……",
    },
    {
      emoji: "☕",
      id: "4",
      options: [
        {
          emoji: "⭐",
          id: "a",
          scores: { flexer: 3 },
          text: "最高級の雰囲気のみが満足をもたらす。",
        },
        {
          emoji: "🏠",
          id: "b",
          scores: { saver: 3 },
          text: "自らの聖域で秘薬を自ら煎じる。",
        },
        {
          emoji: "☕",
          id: "c",
          scores: { balanced: 3 },
          text: "信頼のおける地元の炉端で十分である。",
        },
        {
          emoji: "🎲",
          id: "d",
          scores: { impulse: 3 },
          text: "気まぐれな風に吹かれるままに選ぶ。",
        },
        {
          emoji: "🪙",
          id: "e",
          scores: { investor: 3 },
          text: "今日の小銭が明日の帝国を築く。",
        },
        {
          emoji: "🌟",
          id: "f",
          scores: { experience: 3 },
          text: "希少な起源と独自の物語を求める。",
        },
      ],
      text: "「芳醇な豆の儀式」（コーヒー）を嗜む時……",
    },
    {
      emoji: "💵",
      id: "5",
      options: [
        {
          emoji: "⌚",
          id: "a",
          scores: { flexer: 3 },
          text: "地位の象徴となる装飾品を身に纏う。",
        },
        {
          emoji: "💰",
          id: "b",
          scores: { saver: 3 },
          text: "全てを大いなる蔵の安全に委ねる。",
        },
        {
          emoji: "➗",
          id: "c",
          scores: { balanced: 3 },
          text: "流れを分け、半分は成長へ、半分は生活へ。",
        },
        {
          emoji: "🎁",
          id: "d",
          scores: { impulse: 3 },
          text: "抑えていた渇望を一気に解放する！",
        },
        {
          emoji: "📈",
          id: "e",
          scores: { investor: 3 },
          text: "資本の河へと、その流れを導く。",
        },
        {
          emoji: "🎫",
          id: "f",
          scores: { experience: 3 },
          text: "未踏の地平を求める航海に出る。",
        },
      ],
      text: "突如として三百万の硬貨（ボーナス）を授かったら？",
    },
    {
      emoji: "👕",
      id: "6",
      options: [
        {
          emoji: "🏷️",
          id: "a",
          scores: { flexer: 3 },
          text: "系譜（ブランド）と紋章が魂を語る。",
        },
        {
          emoji: "💸",
          id: "b",
          scores: { saver: 3 },
          text: "対価こそが知恵の第一の指針である。",
        },
        {
          emoji: "⚖️",
          id: "c",
          scores: { balanced: 3 },
          text: "徳と価値の調和を追求する。",
        },
        {
          emoji: "😍",
          id: "d",
          scores: { impulse: 3 },
          text: "今の精神に共鳴するものを選ぶ。",
        },
        {
          emoji: "👔",
          id: "e",
          scores: { investor: 3 },
          text: "最小限の殻。本質は他にある。",
        },
        {
          emoji: "✨",
          id: "f",
          scores: { experience: 3 },
          text: "独自の物語を囁く一着を纏う。",
        },
      ],
      text: "身を包む「絹」（衣服）を選ぶ際に重視することは？",
    },
    {
      emoji: "🎁",
      id: "7",
      options: [
        {
          emoji: "💝",
          id: "a",
          scores: { flexer: 3 },
          text: "尊敬を勝ち取る至高の品。",
        },
        {
          emoji: "🎀",
          id: "b",
          scores: { saver: 3 },
          text: "実用的で控えめなもの。",
        },
        {
          emoji: "🎈",
          id: "c",
          scores: { balanced: 3 },
          text: "相手の本質に最も適ったもの。",
        },
        {
          emoji: "🏬",
          id: "d",
          scores: { impulse: 3 },
          text: "最初に降りてきた輝きを直感で選ぶ。",
        },
        {
          emoji: "💳",
          id: "e",
          scores: { investor: 3 },
          text: "富の平等や金融の知恵の種。",
        },
        {
          emoji: "🎭",
          id: "f",
          scores: { experience: 3 },
          text: "時を共有するための招待状。",
        },
      ],
      text: "仲間の「太陽の回帰」（誕生日）を祝う贈り物を選ぶ時……",
    },
    {
      emoji: "🏦",
      id: "8",
      options: [
        {
          emoji: "😊",
          id: "a",
          scores: { flexer: 2, impulse: 2 },
          text: "未来の渇望を満たす糧があることを悦ぶ。",
        },
        {
          emoji: "📊",
          id: "b",
          scores: { investor: 2, saver: 3 },
          text: "大いなる目標への道程を測る。",
        },
        {
          emoji: "👌",
          id: "c",
          scores: { balanced: 3 },
          text: "流れの安定の中に、安らぎを見出す。",
        },
        {
          emoji: "😅",
          id: "d",
          scores: { impulse: 3 },
          text: "巡りは続く。次なる潮流に備える。",
        },
        {
          emoji: "🧮",
          id: "e",
          scores: { investor: 3 },
          text: "成長と収穫の計算を始める。",
        },
        {
          emoji: "🎯",
          id: "f",
          scores: { experience: 3 },
          text: "次なる冒険のための予算を確認する。",
        },
      ],
      text: "自らの蔵の現状を眺めた時の心持ちは？",
    },
  ],
  ko: [
    {
      emoji: "💰",
      id: "1",
      options: [
        {
          emoji: "👜",
          id: "a",
          scores: { flexer: 3, impulse: 2 },
          text: "갖고 싶던 명품을 바로 구매",
        },
        {
          emoji: "🏦",
          id: "b",
          scores: { investor: 2, saver: 3 },
          text: "정기 적금과 투자 계좌에 자동 이체",
        },
        {
          emoji: "⚖️",
          id: "c",
          scores: { balanced: 3 },
          text: "필요한 것만 구매하고 나머지는 저축",
        },
        {
          emoji: "🛍️",
          id: "d",
          scores: { impulse: 3 },
          text: "그때그때 생각나는 대로 소비",
        },
        {
          emoji: "📈",
          id: "e",
          scores: { investor: 3 },
          text: "주식이나 부동산 투자 기회 찾기",
        },
        {
          emoji: "✈️",
          id: "f",
          scores: { experience: 3 },
          text: "여행이나 새로운 경험 예약",
        },
      ],
      text: "월급이 들어왔을 때 가장 먼저 하는 일은?",
    },
    {
      emoji: "📱",
      id: "2",
      options: [
        {
          emoji: "🏃",
          id: "a",
          scores: { flexer: 3, impulse: 2 },
          text: "나도 바로 사러 간다!",
        },
        {
          emoji: "🤔",
          id: "b",
          scores: { balanced: 2, saver: 3 },
          text: "내 폰 아직 쓸만한데 왜 바꿔?",
        },
        {
          emoji: "📅",
          id: "c",
          scores: { balanced: 3 },
          text: "다음 세대 나오면 그때 고려해볼게",
        },
        {
          emoji: "😫",
          id: "d",
          scores: { flexer: 1, impulse: 3 },
          text: "갑자기 내 폰이 구형으로 보임... 사야겠다",
        },
        {
          emoji: "💹",
          id: "e",
          scores: { investor: 3 },
          text: "그 돈이면 주식 몇 주 살 수 있는데",
        },
        {
          emoji: "🌍",
          id: "f",
          scores: { experience: 3 },
          text: "그 돈이면 해외여행 갈 수 있겠네",
        },
      ],
      text: "친구가 최신 아이폰을 샀다고 자랑할 때?",
    },
    {
      emoji: "🛒",
      id: "3",
      options: [
        {
          emoji: "⬆️",
          id: "a",
          scores: { flexer: 3 },
          text: "프리미엄 라인으로 업그레이드해서 구매",
        },
        {
          emoji: "🤨",
          id: "b",
          scores: { saver: 3 },
          text: "세일이래도 정말 필요한지 다시 생각",
        },
        {
          emoji: "👍",
          id: "c",
          scores: { balanced: 3 },
          text: "할인된 가격이 적정하면 구매",
        },
        {
          emoji: "⚡",
          id: "d",
          scores: { impulse: 3 },
          text: "지금 아니면 못 사! 즉시 결제",
        },
        {
          emoji: "📊",
          id: "e",
          scores: { investor: 3 },
          text: "그 돈을 투자하면 수익률이...",
        },
        {
          emoji: "🎭",
          id: "f",
          scores: { experience: 3 },
          text: "물건보다는 경험이 더 가치있어",
        },
      ],
      text: "온라인 쇼핑몰에서 장바구니에 담은 물건이 세일할 때?",
    },
    {
      emoji: "☕",
      id: "4",
      options: [
        {
          emoji: "⭐",
          id: "a",
          scores: { flexer: 3 },
          text: "스타벅스 리저브만! 분위기가 중요해",
        },
        {
          emoji: "🏠",
          id: "b",
          scores: { saver: 3 },
          text: "집에서 직접 내려 마심. 훨씬 저렴",
        },
        {
          emoji: "☕",
          id: "c",
          scores: { balanced: 3 },
          text: "가성비 좋은 동네 카페 단골",
        },
        {
          emoji: "🎲",
          id: "d",
          scores: { impulse: 3 },
          text: "그날 기분에 따라 다름",
        },
        {
          emoji: "🪙",
          id: "e",
          scores: { investor: 3 },
          text: "커피값도 모으면 투자 자금이 돼",
        },
        {
          emoji: "🌟",
          id: "f",
          scores: { experience: 3 },
          text: "특별한 원두나 경험이 있는 곳 찾아감",
        },
      ],
      text: "카페에서 커피를 주문할 때?",
    },
    {
      emoji: "💵",
      id: "5",
      options: [
        {
          emoji: "⌚",
          id: "a",
          scores: { flexer: 3 },
          text: "명품 가방이나 시계 구매",
        },
        {
          emoji: "💰",
          id: "b",
          scores: { saver: 3 },
          text: "전액 저축 또는 비상금으로",
        },
        {
          emoji: "➗",
          id: "c",
          scores: { balanced: 3 },
          text: "절반은 저축, 절반은 필요한 것 구매",
        },
        {
          emoji: "🎁",
          id: "d",
          scores: { impulse: 3 },
          text: "평소 못 쓴 거 다 사버리기!",
        },
        {
          emoji: "📈",
          id: "e",
          scores: { investor: 3 },
          text: "주식, ETF, 코인 등에 투자",
        },
        {
          emoji: "🎫",
          id: "f",
          scores: { experience: 3 },
          text: "해외여행이나 특별한 경험 계획",
        },
      ],
      text: "예상치 못한 보너스 300만원을 받았다면?",
    },
    {
      emoji: "👕",
      id: "6",
      options: [
        {
          emoji: "🏷️",
          id: "a",
          scores: { flexer: 3 },
          text: "브랜드와 디자이너 라벨",
        },
        {
          emoji: "💸",
          id: "b",
          scores: { saver: 3 },
          text: "가격! 세일 제품 위주로",
        },
        {
          emoji: "⚖️",
          id: "c",
          scores: { balanced: 3 },
          text: "품질과 가격의 균형",
        },
        {
          emoji: "😍",
          id: "d",
          scores: { impulse: 3 },
          text: "그 순간 끌리는 거!",
        },
        {
          emoji: "👔",
          id: "e",
          scores: { investor: 3 },
          text: "기본템 몇 벌만. 옷에 투자할 돈이 아깝",
        },
        {
          emoji: "✨",
          id: "f",
          scores: { experience: 3 },
          text: "특별한 스토리가 있는 옷",
        },
      ],
      text: "옷을 살 때 가장 중요하게 생각하는 것은?",
    },
    {
      emoji: "🎁",
      id: "7",
      options: [
        {
          emoji: "💝",
          id: "a",
          scores: { flexer: 3 },
          text: "명품 브랜드 소품으로 확실하게",
        },
        {
          emoji: "🎀",
          id: "b",
          scores: { saver: 3 },
          text: "실용적이면서 저렴한 것",
        },
        {
          emoji: "🎈",
          id: "c",
          scores: { balanced: 3 },
          text: "친구 취향에 맞는 적당한 가격대",
        },
        {
          emoji: "🏬",
          id: "d",
          scores: { impulse: 3 },
          text: "백화점 가서 눈에 띄는 거 바로 구매",
        },
        {
          emoji: "💳",
          id: "e",
          scores: { investor: 3 },
          text: "주식 선물이나 금융상품 추천",
        },
        {
          emoji: "🎭",
          id: "f",
          scores: { experience: 3 },
          text: "함께 할 수 있는 경험 선물 (공연, 여행)",
        },
      ],
      text: "친구 생일 선물을 고를 때?",
    },
    {
      emoji: "🏦",
      id: "8",
      options: [
        {
          emoji: "😊",
          id: "a",
          scores: { flexer: 2, impulse: 2 },
          text: "쓸 돈이 있다는 게 행복해!",
        },
        {
          emoji: "📊",
          id: "b",
          scores: { investor: 2, saver: 3 },
          text: "목표 금액 달성 여부 체크",
        },
        {
          emoji: "👌",
          id: "c",
          scores: { balanced: 3 },
          text: "적절히 관리되고 있다면 만족",
        },
        {
          emoji: "😅",
          id: "d",
          scores: { impulse: 3 },
          text: "이달도 또 다 써버렸네... 다음 달에는!",
        },
        {
          emoji: "🧮",
          id: "e",
          scores: { investor: 3 },
          text: "투자 수익률 계산 시작",
        },
        {
          emoji: "🎯",
          id: "f",
          scores: { experience: 3 },
          text: "다음 경험을 위한 예산 확인",
        },
      ],
      text: "통장 잔고를 확인했을 때의 기분은?",
    },
  ],
};
