// ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// This file is generated by scripts/generate-i18n-registry.mjs
// It allows for Edge Runtime compatible dynamic loading of i18n messages.

export const i18nRegistry: any = {
  "500": (locale: string) => import(`../../messages/${locale}/500.json`),
  about: (locale: string) => import(`../../messages/${locale}/about.json`),
  AccessGuard: (locale: string) =>
    import(`../../messages/${locale}/AccessGuard.json`),
  account: (locale: string) => import(`../../messages/${locale}/account.json`),
  accuracy: (locale: string) =>
    import(`../../messages/${locale}/accuracy.json`),
  achievements: (locale: string) =>
    import(`../../messages/${locale}/achievements.json`),
  action: (locale: string) => import(`../../messages/${locale}/action.json`),
  actions: (locale: string) => import(`../../messages/${locale}/actions.json`),
  addSubscription: (locale: string) =>
    import(`../../messages/${locale}/addSubscription.json`),
  advisor: (locale: string) => import(`../../messages/${locale}/advisor.json`),
  affirmations: (locale: string) =>
    import(`../../messages/${locale}/affirmations.json`),
  ai: (locale: string) => import(`../../messages/${locale}/ai.json`),
  aiHoroscopeGenerator: (locale: string) =>
    import(`../../messages/${locale}/aiHoroscopeGenerator.json`),
  akashic: (locale: string) => import(`../../messages/${locale}/akashic.json`),
  AncientCoordinateCard: (locale: string) =>
    import(`../../messages/${locale}/AncientCoordinateCard.json`),
  anxietyRelief: (locale: string) =>
    import(`../../messages/${locale}/anxietyRelief.json`),
  april: (locale: string) => import(`../../messages/${locale}/april.json`),
  archives: (locale: string) =>
    import(`../../messages/${locale}/archives.json`),
  assessment: (locale: string) =>
    import(`../../messages/${locale}/assessment.json`),
  assetMap: (locale: string) =>
    import(`../../messages/${locale}/assetMap.json`),
  attachment: (locale: string) =>
    import(`../../messages/${locale}/attachment.json`),
  august: (locale: string) => import(`../../messages/${locale}/august.json`),
  benefits: (locale: string) =>
    import(`../../messages/${locale}/benefits.json`),
  big5: (locale: string) => import(`../../messages/${locale}/big5.json`),
  billing: (locale: string) => import(`../../messages/${locale}/billing.json`),
  biology: (locale: string) => import(`../../messages/${locale}/biology.json`),
  biorhythm: (locale: string) =>
    import(`../../messages/${locale}/biorhythm.json`),
  birthflower: (locale: string) =>
    import(`../../messages/${locale}/birthflower.json`),
  BlogIdeaGenerator: (locale: string) =>
    import(`../../messages/${locale}/BlogIdeaGenerator.json`),
  bloodType: (locale: string) =>
    import(`../../messages/${locale}/bloodType.json`),
  branches: (locale: string) =>
    import(`../../messages/${locale}/branches.json`),
  bridge: (locale: string) => import(`../../messages/${locale}/bridge.json`),
  budgetPlanner: (locale: string) =>
    import(`../../messages/${locale}/budgetPlanner.json`),
  byArea: (locale: string) => import(`../../messages/${locale}/byArea.json`),
  byEmotion: (locale: string) =>
    import(`../../messages/${locale}/byEmotion.json`),
  calculator: (locale: string) =>
    import(`../../messages/${locale}/calculator.json`),
  career: (locale: string) => import(`../../messages/${locale}/career.json`),
  catalog: (locale: string) => import(`../../messages/${locale}/catalog.json`),
  categories: (locale: string) =>
    import(`../../messages/${locale}/categories.json`),
  category: (locale: string) =>
    import(`../../messages/${locale}/category.json`),
  celestial: (locale: string) =>
    import(`../../messages/${locale}/celestial.json`),
  celtic: (locale: string) => import(`../../messages/${locale}/celtic.json`),
  characters: (locale: string) =>
    import(`../../messages/${locale}/characters.json`),
  chart: (locale: string) => import(`../../messages/${locale}/chart.json`),
  chosun: (locale: string) => import(`../../messages/${locale}/chosun.json`),
  cognitiveBias: (locale: string) =>
    import(`../../messages/${locale}/cognitiveBias.json`),
  color: (locale: string) => import(`../../messages/${locale}/color.json`),
  colorPersonality: (locale: string) =>
    import(`../../messages/${locale}/colorPersonality.json`),
  columns: (locale: string) => import(`../../messages/${locale}/columns.json`),
  commerce: (locale: string) =>
    import(`../../messages/${locale}/commerce.json`),
  common: (locale: string) => import(`../../messages/${locale}/common.json`),
  communicationStyle: (locale: string) =>
    import(`../../messages/${locale}/communicationStyle.json`),
  community: (locale: string) =>
    import(`../../messages/${locale}/community.json`),
  company: (locale: string) => import(`../../messages/${locale}/company.json`),
  comparison: (locale: string) =>
    import(`../../messages/${locale}/comparison.json`),
  compatibility: (locale: string) =>
    import(`../../messages/${locale}/compatibility.json`),
  complete: (locale: string) =>
    import(`../../messages/${locale}/complete.json`),
  compoundInterest: (locale: string) =>
    import(`../../messages/${locale}/compoundInterest.json`),
  comprehensiveReport: (locale: string) =>
    import(`../../messages/${locale}/comprehensiveReport.json`),
  conflict: (locale: string) =>
    import(`../../messages/${locale}/conflict.json`),
  "conflict-response": (locale: string) =>
    import(`../../messages/${locale}/conflict-response.json`),
  conflictSolver: (locale: string) =>
    import(`../../messages/${locale}/conflictSolver.json`),
  connector: (locale: string) =>
    import(`../../messages/${locale}/connector.json`),
  consumption: (locale: string) =>
    import(`../../messages/${locale}/consumption.json`),
  contact: (locale: string) => import(`../../messages/${locale}/contact.json`),
  content: (locale: string) => import(`../../messages/${locale}/content.json`),
  coordinator: (locale: string) =>
    import(`../../messages/${locale}/coordinator.json`),
  copingStrategies: (locale: string) =>
    import(`../../messages/${locale}/copingStrategies.json`),
  core: (locale: string) => import(`../../messages/${locale}/core.json`),
  correlation: (locale: string) =>
    import(`../../messages/${locale}/correlation.json`),
  cosmic: (locale: string) => import(`../../messages/${locale}/cosmic.json`),
  country: (locale: string) => import(`../../messages/${locale}/country.json`),
  create: (locale: string) => import(`../../messages/${locale}/create.json`),
  cta: (locale: string) => import(`../../messages/${locale}/cta.json`),
  daily: (locale: string) => import(`../../messages/${locale}/daily.json`),
  dailyLucky: (locale: string) =>
    import(`../../messages/${locale}/dailyLucky.json`),
  dailyOracle: (locale: string) =>
    import(`../../messages/${locale}/dailyOracle.json`),
  dashboard: (locale: string) =>
    import(`../../messages/${locale}/dashboard.json`),
  dating: (locale: string) => import(`../../messages/${locale}/dating.json`),
  december: (locale: string) =>
    import(`../../messages/${locale}/december.json`),
  deepWork: (locale: string) =>
    import(`../../messages/${locale}/deepWork.json`),
  demo: (locale: string) => import(`../../messages/${locale}/demo.json`),
  demographics: (locale: string) =>
    import(`../../messages/${locale}/demographics.json`),
  destiny: (locale: string) => import(`../../messages/${locale}/destiny.json`),
  dimensions: (locale: string) =>
    import(`../../messages/${locale}/dimensions.json`),
  discovery: (locale: string) =>
    import(`../../messages/${locale}/discovery.json`),
  displays: (locale: string) =>
    import(`../../messages/${locale}/displays.json`),
  dominant: (locale: string) =>
    import(`../../messages/${locale}/dominant.json`),
  dream: (locale: string) => import(`../../messages/${locale}/dream.json`),
  duration: (locale: string) =>
    import(`../../messages/${locale}/duration.json`),
  economicPersonality: (locale: string) =>
    import(`../../messages/${locale}/economicPersonality.json`),
  egenteto: (locale: string) =>
    import(`../../messages/${locale}/egenteto.json`),
  egyptian: (locale: string) =>
    import(`../../messages/${locale}/egyptian.json`),
  elements: (locale: string) =>
    import(`../../messages/${locale}/elements.json`),
  eligibility: (locale: string) =>
    import(`../../messages/${locale}/eligibility.json`),
  email: (locale: string) => import(`../../messages/${locale}/email.json`),
  EmotionalExpression: (locale: string) =>
    import(`../../messages/${locale}/EmotionalExpression.json`),
  emotionSummary: (locale: string) =>
    import(`../../messages/${locale}/emotionSummary.json`),
  empty: (locale: string) => import(`../../messages/${locale}/empty.json`),
  emptyState: (locale: string) =>
    import(`../../messages/${locale}/emptyState.json`),
  encyclopedia: (locale: string) =>
    import(`../../messages/${locale}/encyclopedia.json`),
  enneagram: (locale: string) =>
    import(`../../messages/${locale}/enneagram.json`),
  error: (locale: string) => import(`../../messages/${locale}/error.json`),
  errorPage: (locale: string) =>
    import(`../../messages/${locale}/errorPage.json`),
  essence: (locale: string) => import(`../../messages/${locale}/essence.json`),
  familyDynamics: (locale: string) =>
    import(`../../messages/${locale}/familyDynamics.json`),
  faq: (locale: string) => import(`../../messages/${locale}/faq.json`),
  features: (locale: string) =>
    import(`../../messages/${locale}/features.json`),
  february: (locale: string) =>
    import(`../../messages/${locale}/february.json`),
  filter: (locale: string) => import(`../../messages/${locale}/filter.json`),
  filters: (locale: string) => import(`../../messages/${locale}/filters.json`),
  final: (locale: string) => import(`../../messages/${locale}/final.json`),
  finance: (locale: string) => import(`../../messages/${locale}/finance.json`),
  form: (locale: string) => import(`../../messages/${locale}/form.json`),
  fortune: (locale: string) => import(`../../messages/${locale}/fortune.json`),
  friendship: (locale: string) =>
    import(`../../messages/${locale}/friendship.json`),
  friendshipStyle: (locale: string) =>
    import(`../../messages/${locale}/friendshipStyle.json`),
  gamification: (locale: string) =>
    import(`../../messages/${locale}/gamification.json`),
  generic: (locale: string) => import(`../../messages/${locale}/generic.json`),
  gift: (locale: string) => import(`../../messages/${locale}/gift.json`),
  GiftRecommendation: (locale: string) =>
    import(`../../messages/${locale}/GiftRecommendation.json`),
  giftTax: (locale: string) => import(`../../messages/${locale}/giftTax.json`),
  globalComparison: (locale: string) =>
    import(`../../messages/${locale}/globalComparison.json`),
  goals: (locale: string) => import(`../../messages/${locale}/goals.json`),
  grid: (locale: string) => import(`../../messages/${locale}/grid.json`),
  growth: (locale: string) => import(`../../messages/${locale}/growth.json`),
  habitAssistant: (locale: string) =>
    import(`../../messages/${locale}/habitAssistant.json`),
  habitQuest: (locale: string) =>
    import(`../../messages/${locale}/habitQuest.json`),
  habits: (locale: string) => import(`../../messages/${locale}/habits.json`),
  header: (locale: string) => import(`../../messages/${locale}/header.json`),
  health: (locale: string) => import(`../../messages/${locale}/health.json`),
  hellenistic: (locale: string) =>
    import(`../../messages/${locale}/hellenistic.json`),
  hero: (locale: string) => import(`../../messages/${locale}/hero.json`),
  hexaco: (locale: string) => import(`../../messages/${locale}/hexaco.json`),
  highlights: (locale: string) =>
    import(`../../messages/${locale}/highlights.json`),
  hobbies: (locale: string) => import(`../../messages/${locale}/hobbies.json`),
  hobby: (locale: string) => import(`../../messages/${locale}/hobby.json`),
  horoscope: (locale: string) =>
    import(`../../messages/${locale}/horoscope.json`),
  hsp: (locale: string) => import(`../../messages/${locale}/hsp.json`),
  hub: (locale: string) => import(`../../messages/${locale}/hub.json`),
  includes: (locale: string) =>
    import(`../../messages/${locale}/includes.json`),
  info: (locale: string) => import(`../../messages/${locale}/info.json`),
  input: (locale: string) => import(`../../messages/${locale}/input.json`),
  inputs: (locale: string) => import(`../../messages/${locale}/inputs.json`),
  insight: (locale: string) => import(`../../messages/${locale}/insight.json`),
  insights: (locale: string) =>
    import(`../../messages/${locale}/insights.json`),
  integrationFlow: (locale: string) =>
    import(`../../messages/${locale}/integrationFlow.json`),
  interactions: (locale: string) =>
    import(`../../messages/${locale}/interactions.json`),
  interests: (locale: string) =>
    import(`../../messages/${locale}/interests.json`),
  interpretations: (locale: string) =>
    import(`../../messages/${locale}/interpretations.json`),
  interviewScorer: (locale: string) =>
    import(`../../messages/${locale}/interviewScorer.json`),
  investment: (locale: string) =>
    import(`../../messages/${locale}/investment.json`),
  january: (locale: string) => import(`../../messages/${locale}/january.json`),
  jeonseGuard: (locale: string) =>
    import(`../../messages/${locale}/jeonseGuard.json`),
  jobMatch: (locale: string) =>
    import(`../../messages/${locale}/jobMatch.json`),
  journal: (locale: string) => import(`../../messages/${locale}/journal.json`),
  july: (locale: string) => import(`../../messages/${locale}/july.json`),
  june: (locale: string) => import(`../../messages/${locale}/june.json`),
  kabbalah: (locale: string) =>
    import(`../../messages/${locale}/kabbalah.json`),
  keywords: (locale: string) =>
    import(`../../messages/${locale}/keywords.json`),
  labels: (locale: string) => import(`../../messages/${locale}/labels.json`),
  labor: (locale: string) => import(`../../messages/${locale}/labor.json`),
  lacking: (locale: string) => import(`../../messages/${locale}/lacking.json`),
  landing: (locale: string) => import(`../../messages/${locale}/landing.json`),
  leaderboard: (locale: string) =>
    import(`../../messages/${locale}/leaderboard.json`),
  leadership: (locale: string) =>
    import(`../../messages/${locale}/leadership.json`),
  learning: (locale: string) =>
    import(`../../messages/${locale}/learning.json`),
  learningStyle: (locale: string) =>
    import(`../../messages/${locale}/learningStyle.json`),
  legal: (locale: string) => import(`../../messages/${locale}/legal.json`),
  level: (locale: string) => import(`../../messages/${locale}/level.json`),
  levelCard: (locale: string) =>
    import(`../../messages/${locale}/levelCard.json`),
  levels: (locale: string) => import(`../../messages/${locale}/levels.json`),
  library: (locale: string) => import(`../../messages/${locale}/library.json`),
  lifeBlueprint: (locale: string) =>
    import(`../../messages/${locale}/lifeBlueprint.json`),
  lifeFocus: (locale: string) =>
    import(`../../messages/${locale}/lifeFocus.json`),
  lifepath: (locale: string) =>
    import(`../../messages/${locale}/lifepath.json`),
  lifeSimulator: (locale: string) =>
    import(`../../messages/${locale}/lifeSimulator.json`),
  lifestyle: (locale: string) =>
    import(`../../messages/${locale}/lifestyle.json`),
  list: (locale: string) => import(`../../messages/${locale}/list.json`),
  loading: (locale: string) => import(`../../messages/${locale}/loading.json`),
  loading_legacy: (locale: string) =>
    import(`../../messages/${locale}/loading_legacy.json`),
  "love-language": (locale: string) =>
    import(`../../messages/${locale}/love-language.json`),
  loveAdvisor: (locale: string) =>
    import(`../../messages/${locale}/loveAdvisor.json`),
  loveCommunication: (locale: string) =>
    import(`../../messages/${locale}/loveCommunication.json`),
  luck: (locale: string) => import(`../../messages/${locale}/luck.json`),
  mandalart: (locale: string) =>
    import(`../../messages/${locale}/mandalart.json`),
  manifest: (locale: string) =>
    import(`../../messages/${locale}/manifest.json`),
  march: (locale: string) => import(`../../messages/${locale}/march.json`),
  marketing: (locale: string) =>
    import(`../../messages/${locale}/marketing.json`),
  master: (locale: string) => import(`../../messages/${locale}/master.json`),
  may: (locale: string) => import(`../../messages/${locale}/may.json`),
  mayan: (locale: string) => import(`../../messages/${locale}/mayan.json`),
  mbti: (locale: string) => import(`../../messages/${locale}/mbti.json`),
  mbtiSalary: (locale: string) =>
    import(`../../messages/${locale}/mbtiSalary.json`),
  mental: (locale: string) => import(`../../messages/${locale}/mental.json`),
  meta: (locale: string) => import(`../../messages/${locale}/meta.json`),
  metrics: (locale: string) => import(`../../messages/${locale}/metrics.json`),
  mission: (locale: string) => import(`../../messages/${locale}/mission.json`),
  modes: (locale: string) => import(`../../messages/${locale}/modes.json`),
  moneyHabits: (locale: string) =>
    import(`../../messages/${locale}/moneyHabits.json`),
  moods: (locale: string) => import(`../../messages/${locale}/moods.json`),
  myTickets: (locale: string) =>
    import(`../../messages/${locale}/myTickets.json`),
  nav: (locale: string) => import(`../../messages/${locale}/nav.json`),
  navigation: (locale: string) =>
    import(`../../messages/${locale}/navigation.json`),
  nextActions: (locale: string) =>
    import(`../../messages/${locale}/nextActions.json`),
  nJobler: (locale: string) => import(`../../messages/${locale}/nJobler.json`),
  "noble-persons": (locale: string) =>
    import(`../../messages/${locale}/noble-persons.json`),
  nonRefundable: (locale: string) =>
    import(`../../messages/${locale}/nonRefundable.json`),
  nordic: (locale: string) => import(`../../messages/${locale}/nordic.json`),
  notFound: (locale: string) =>
    import(`../../messages/${locale}/notFound.json`),
  notifications: (locale: string) =>
    import(`../../messages/${locale}/notifications.json`),
  notificationsPanel: (locale: string) =>
    import(`../../messages/${locale}/notificationsPanel.json`),
  november: (locale: string) =>
    import(`../../messages/${locale}/november.json`),
  numerology: (locale: string) =>
    import(`../../messages/${locale}/numerology.json`),
  october: (locale: string) => import(`../../messages/${locale}/october.json`),
  onboarding: (locale: string) =>
    import(`../../messages/${locale}/onboarding.json`),
  onomancy: (locale: string) =>
    import(`../../messages/${locale}/onomancy.json`),
  ontology: (locale: string) =>
    import(`../../messages/${locale}/ontology.json`),
  operations: (locale: string) =>
    import(`../../messages/${locale}/operations.json`),
  oracle: (locale: string) => import(`../../messages/${locale}/oracle.json`),
  origin: (locale: string) => import(`../../messages/${locale}/origin.json`),
  overview: (locale: string) =>
    import(`../../messages/${locale}/overview.json`),
  page: (locale: string) => import(`../../messages/${locale}/page.json`),
  pantheon: (locale: string) =>
    import(`../../messages/${locale}/pantheon.json`),
  payment: (locale: string) => import(`../../messages/${locale}/payment.json`),
  paymentFaq: (locale: string) =>
    import(`../../messages/${locale}/paymentFaq.json`),
  paymentMethods: (locale: string) =>
    import(`../../messages/${locale}/paymentMethods.json`),
  payments: (locale: string) =>
    import(`../../messages/${locale}/payments.json`),
  perfectionism: (locale: string) =>
    import(`../../messages/${locale}/perfectionism.json`),
  performance: (locale: string) =>
    import(`../../messages/${locale}/performance.json`),
  personality: (locale: string) =>
    import(`../../messages/${locale}/personality.json`),
  phases: (locale: string) => import(`../../messages/${locale}/phases.json`),
  pillars: (locale: string) => import(`../../messages/${locale}/pillars.json`),
  plans: (locale: string) => import(`../../messages/${locale}/plans.json`),
  preferences: (locale: string) =>
    import(`../../messages/${locale}/preferences.json`),
  premium: (locale: string) => import(`../../messages/${locale}/premium.json`),
  PremiumLock: (locale: string) =>
    import(`../../messages/${locale}/PremiumLock.json`),
  PremiumReport: (locale: string) =>
    import(`../../messages/${locale}/PremiumReport.json`),
  presets: (locale: string) => import(`../../messages/${locale}/presets.json`),
  pricing: (locale: string) => import(`../../messages/${locale}/pricing.json`),
  priority: (locale: string) =>
    import(`../../messages/${locale}/priority.json`),
  process: (locale: string) => import(`../../messages/${locale}/process.json`),
  processingTime: (locale: string) =>
    import(`../../messages/${locale}/processingTime.json`),
  professionalGuidance: (locale: string) =>
    import(`../../messages/${locale}/professionalGuidance.json`),
  profile: (locale: string) => import(`../../messages/${locale}/profile.json`),
  progress: (locale: string) =>
    import(`../../messages/${locale}/progress.json`),
  prompts: (locale: string) => import(`../../messages/${locale}/prompts.json`),
  prosperity: (locale: string) =>
    import(`../../messages/${locale}/prosperity.json`),
  pwa: (locale: string) => import(`../../messages/${locale}/pwa.json`),
  questions: (locale: string) =>
    import(`../../messages/${locale}/questions.json`),
  quickActions: (locale: string) =>
    import(`../../messages/${locale}/quickActions.json`),
  randomPrompts: (locale: string) =>
    import(`../../messages/${locale}/randomPrompts.json`),
  recent: (locale: string) => import(`../../messages/${locale}/recent.json`),
  recentTests: (locale: string) =>
    import(`../../messages/${locale}/recentTests.json`),
  recommendations: (locale: string) =>
    import(`../../messages/${locale}/recommendations.json`),
  rel: (locale: string) => import(`../../messages/${locale}/rel.json`),
  "relationship-mbti": (locale: string) =>
    import(`../../messages/${locale}/relationship-mbti.json`),
  relationshipHub: (locale: string) =>
    import(`../../messages/${locale}/relationshipHub.json`),
  resilience: (locale: string) =>
    import(`../../messages/${locale}/resilience.json`),
  resonance: (locale: string) =>
    import(`../../messages/${locale}/resonance.json`),
  "resonance-tags": (locale: string) =>
    import(`../../messages/${locale}/resonance-tags.json`),
  response: (locale: string) =>
    import(`../../messages/${locale}/response.json`),
  result: (locale: string) => import(`../../messages/${locale}/result.json`),
  results: (locale: string) => import(`../../messages/${locale}/results.json`),
  riasec: (locale: string) => import(`../../messages/${locale}/riasec.json`),
  routineGenerator: (locale: string) =>
    import(`../../messages/${locale}/routineGenerator.json`),
  saju: (locale: string) => import(`../../messages/${locale}/saju.json`),
  "saju-daymaster": (locale: string) =>
    import(`../../messages/${locale}/saju-daymaster.json`),
  "saju-gods": (locale: string) =>
    import(`../../messages/${locale}/saju-gods.json`),
  salaryCalculator: (locale: string) =>
    import(`../../messages/${locale}/salaryCalculator.json`),
  scenario: (locale: string) =>
    import(`../../messages/${locale}/scenario.json`),
  scopes: (locale: string) => import(`../../messages/${locale}/scopes.json`),
  search: (locale: string) => import(`../../messages/${locale}/search.json`),
  sections: (locale: string) =>
    import(`../../messages/${locale}/sections.json`),
  selfDiscovery: (locale: string) =>
    import(`../../messages/${locale}/selfDiscovery.json`),
  selfSaju: (locale: string) =>
    import(`../../messages/${locale}/selfSaju.json`),
  seo: (locale: string) => import(`../../messages/${locale}/seo.json`),
  september: (locale: string) =>
    import(`../../messages/${locale}/september.json`),
  session: (locale: string) => import(`../../messages/${locale}/session.json`),
  settings: (locale: string) =>
    import(`../../messages/${locale}/settings.json`),
  severancePay: (locale: string) =>
    import(`../../messages/${locale}/severancePay.json`),
  signIn: (locale: string) => import(`../../messages/${locale}/signIn.json`),
  signUp: (locale: string) => import(`../../messages/${locale}/signUp.json`),
  sleepPattern: (locale: string) =>
    import(`../../messages/${locale}/sleepPattern.json`),
  snsPersonality: (locale: string) =>
    import(`../../messages/${locale}/snsPersonality.json`),
  social: (locale: string) => import(`../../messages/${locale}/social.json`),
  "social-logic": (locale: string) =>
    import(`../../messages/${locale}/social-logic.json`),
  sohn: (locale: string) => import(`../../messages/${locale}/sohn.json`),
  solutions: (locale: string) =>
    import(`../../messages/${locale}/solutions.json`),
  sovereign: (locale: string) =>
    import(`../../messages/${locale}/sovereign.json`),
  spendingStyle: (locale: string) =>
    import(`../../messages/${locale}/spendingStyle.json`),
  stars: (locale: string) => import(`../../messages/${locale}/stars.json`),
  "static-wisdom": (locale: string) =>
    import(`../../messages/${locale}/static-wisdom.json`),
  stats: (locale: string) => import(`../../messages/${locale}/stats.json`),
  status: (locale: string) => import(`../../messages/${locale}/status.json`),
  stems: (locale: string) => import(`../../messages/${locale}/stems.json`),
  steps: (locale: string) => import(`../../messages/${locale}/steps.json`),
  story: (locale: string) => import(`../../messages/${locale}/story.json`),
  streak: (locale: string) => import(`../../messages/${locale}/streak.json`),
  styling: (locale: string) => import(`../../messages/${locale}/styling.json`),
  subscriptionManager: (locale: string) =>
    import(`../../messages/${locale}/subscriptionManager.json`),
  summary: (locale: string) => import(`../../messages/${locale}/summary.json`),
  support: (locale: string) => import(`../../messages/${locale}/support.json`),
  symbols: (locale: string) => import(`../../messages/${locale}/symbols.json`),
  synergy: (locale: string) => import(`../../messages/${locale}/synergy.json`),
  systems: (locale: string) => import(`../../messages/${locale}/systems.json`),
  systemSynergy: (locale: string) =>
    import(`../../messages/${locale}/systemSynergy.json`),
  tabs: (locale: string) => import(`../../messages/${locale}/tabs.json`),
  tarot: (locale: string) => import(`../../messages/${locale}/tarot.json`),
  tci: (locale: string) => import(`../../messages/${locale}/tci.json`),
  tenGods: (locale: string) => import(`../../messages/${locale}/tenGods.json`),
  terms: (locale: string) => import(`../../messages/${locale}/terms.json`),
  test: (locale: string) => import(`../../messages/${locale}/test.json`),
  testHistory: (locale: string) =>
    import(`../../messages/${locale}/testHistory.json`),
  tests: (locale: string) => import(`../../messages/${locale}/tests.json`),
  tier: (locale: string) => import(`../../messages/${locale}/tier.json`),
  time: (locale: string) => import(`../../messages/${locale}/time.json`),
  timeAgo: (locale: string) => import(`../../messages/${locale}/timeAgo.json`),
  timeManagement: (locale: string) =>
    import(`../../messages/${locale}/timeManagement.json`),
  tip: (locale: string) => import(`../../messages/${locale}/tip.json`),
  tips: (locale: string) => import(`../../messages/${locale}/tips.json`),
  tools: (locale: string) => import(`../../messages/${locale}/tools.json`),
  track: (locale: string) => import(`../../messages/${locale}/track.json`),
  tracking: (locale: string) =>
    import(`../../messages/${locale}/tracking.json`),
  travel: (locale: string) => import(`../../messages/${locale}/travel.json`),
  triggerFlow: (locale: string) =>
    import(`../../messages/${locale}/triggerFlow.json`),
  trust: (locale: string) => import(`../../messages/${locale}/trust.json`),
  twelveWoonsung: (locale: string) =>
    import(`../../messages/${locale}/twelveWoonsung.json`),
  types: (locale: string) => import(`../../messages/${locale}/types.json`),
  typesSection: (locale: string) =>
    import(`../../messages/${locale}/typesSection.json`),
  uce: (locale: string) => import(`../../messages/${locale}/uce.json`),
  ucl: (locale: string) => import(`../../messages/${locale}/ucl.json`),
  ui: (locale: string) => import(`../../messages/${locale}/ui.json`),
  universal: (locale: string) =>
    import(`../../messages/${locale}/universal.json`),
  upgrade: (locale: string) => import(`../../messages/${locale}/upgrade.json`),
  user: (locale: string) => import(`../../messages/${locale}/user.json`),
  values: (locale: string) => import(`../../messages/${locale}/values.json`),
  ValueScore: (locale: string) =>
    import(`../../messages/${locale}/ValueScore.json`),
  vat: (locale: string) => import(`../../messages/${locale}/vat.json`),
  vault: (locale: string) => import(`../../messages/${locale}/vault.json`),
  vedic: (locale: string) => import(`../../messages/${locale}/vedic.json`),
  viral: (locale: string) => import(`../../messages/${locale}/viral.json`),
  visualization: (locale: string) =>
    import(`../../messages/${locale}/visualization.json`),
  welcome: (locale: string) => import(`../../messages/${locale}/welcome.json`),
  wisdom: (locale: string) => import(`../../messages/${locale}/wisdom.json`),
  workStyleLab: (locale: string) =>
    import(`../../messages/${locale}/workStyleLab.json`),
  ziwei: (locale: string) => import(`../../messages/${locale}/ziwei.json`),
  zodiac: (locale: string) => import(`../../messages/${locale}/zodiac.json`),
};

export type I18nRegistry = typeof i18nRegistry;
