import { CountryProfile, CountryQuestion } from "./types";

export const COUNTRY_QUESTIONS: CountryQuestion[] = [
  {
    emoji: "🌤️",
    id: "climate",
    options: [
      {
        emoji: "❄️",
        id: "cold_crisp",
        scores: { modern: 1, mountainous: 2, nordic: 3 },
        text: {
          zh: "寒冷清爽的冬天和温和的夏天",
          en: "Cold, crisp winters with mild summers",
          es: "Inviernos fríos y frescos con veranos suaves",
          fr: "Des hivers froids et vivifiants avec des étés doux",
          ja: "寒く澄んだ冬と穏やかな夏",
          ko: "춥고 상쾌한 겨울과 온화한 여름",
        },
      },
      {
        emoji: "☀️",
        id: "warm_sunny",
        scores: { coastal: 2, mediterranean: 3, tropical: 2 },
        text: {
          zh: "一年中大部分时间温暖晴朗",
          en: "Warm, sunny weather most of the year",
          es: "Clima cálido y soleado la mayor parte del año",
          fr: "Un temps chaud et ensoleillé presque toute l'année",
          ja: "一年の大半が暖かく晴れている気候",
          ko: "일년 내내 따뜻하고 화창한 날씨",
        },
      },
      {
        emoji: "🌴",
        id: "hot_humid",
        scores: { coastal: 1, tropical: 3 },
        text: {
          zh: "炎热潮湿，绿意盎然",
          en: "Hot and humid with lush greenery",
          es: "Caluroso y húmedo, con vegetación exuberante",
          fr: "Chaud et humide, avec une végétation luxuriante",
          ja: "暑く湿度が高く、豊かな緑に囲まれている",
          ko: "덥고 습하며 푸른 녹음이 우거진 곳",
        },
      },
      {
        emoji: "🍂",
        id: "four_seasons",
        scores: { cosmopolitan: 1, cultural: 2, modern: 2 },
        text: {
          zh: "四季分明，变化丰富",
          en: "Four distinct seasons with variety",
          es: "Cuatro estaciones bien diferenciadas y variadas",
          fr: "Quatre saisons bien distinctes et variées",
          ja: "変化に富んだはっきりした四季",
          ko: "뚜렷한 사계절이 있는 곳",
        },
      },
    ],
    text: {
      zh: "哪种气候最适合你生活？",
      en: "What type of climate do you thrive in?",
      es: "¿En qué tipo de clima te sientes mejor?",
      fr: "Dans quel type de climat vous épanouissez-vous le mieux ?",
      ja: "どんな気候だといちばん心地よく過ごせますか？",
      ko: "어떤 기후에서 가장 잘 지낼 수 있나요?",
    },
  },
  {
    emoji: "⏰",
    id: "lifestyle",
    options: [
      {
        emoji: "🧘",
        id: "slow_mindful",
        scores: { mediterranean: 2, mountainous: 2, nordic: 3, tropical: 2 },
        text: {
          zh: "慢节奏、有觉察的生活，工作与生活平衡良好",
          en: "Slow, mindful living with strong work-life balance",
          es: "Vida lenta y consciente con buen equilibrio entre trabajo y vida personal",
          fr: "Une vie lente et consciente, avec un bon équilibre entre travail et vie personnelle",
          ja: "ゆったりと丁寧に暮らし、仕事と生活のバランスを大切にする",
          ko: "느리고 여유로운 삶과 확실한 워라밸",
        },
      },
      {
        emoji: "🏃",
        id: "fast_dynamic",
        scores: { cosmopolitan: 3, modern: 3 },
        text: {
          zh: "快节奏、充满活力的都市能量",
          en: "Fast-paced, dynamic urban energy",
          es: "Energía urbana rápida y dinámica",
          fr: "Une énergie urbaine rapide et dynamique",
          ja: "テンポが速く、活気のある都会のエネルギー",
          ko: "빠른 속도의 역동적인 도시 생활",
        },
      },
      {
        emoji: "👥",
        id: "community_social",
        scores: { cultural: 3, mediterranean: 3, tropical: 1 },
        text: {
          zh: "重视社区，拥有紧密的社会联系",
          en: "Community-focused with strong social bonds",
          es: "Centrado en la comunidad, con vínculos sociales fuertes",
          fr: "Axé sur la communauté, avec des liens sociaux forts",
          ja: "コミュニティを重視し、人とのつながりが強い",
          ko: "공동체 중심의 강한 사회적 유대감",
        },
      },
      {
        emoji: "🆓",
        id: "independent_flexible",
        scores: { cosmopolitan: 2, modern: 2, mountainous: 1 },
        text: {
          zh: "独立自主，日程灵活，可远程工作",
          en: "Independent with flexible routines and remote work",
          es: "Independiente, con rutinas flexibles y trabajo remoto",
          fr: "Indépendant, avec des routines flexibles et du télétravail",
          ja: "自立していて、柔軟な日課やリモートワークができる",
          ko: "독립적이고 유연한 일상과 원격 근무",
        },
      },
    ],
    text: {
      zh: "哪种生活节奏最吸引你？",
      en: "What lifestyle pace appeals to you most?",
      es: "¿Qué ritmo de vida te atrae más?",
      fr: "Quel rythme de vie vous attire le plus ?",
      ja: "どんな生活のペースにいちばん惹かれますか？",
      ko: "어떤 생활 패턴이 가장 매력적인가요?",
    },
  },
  {
    emoji: "🗺️",
    id: "geography",
    options: [
      {
        emoji: "⛰️",
        id: "mountains_forests",
        scores: { mountainous: 3, nordic: 2 },
        text: {
          zh: "壮丽的群山和原始森林",
          en: "Majestic mountains and pristine forests",
          es: "Montañas majestuosas y bosques vírgenes",
          fr: "Des montagnes majestueuses et des forêts préservées",
          ja: "雄大な山々と手つかずの森",
          ko: "장엄한 산맥과 울창한 숲",
        },
      },
      {
        emoji: "🏖️",
        id: "coastline_beaches",
        scores: { coastal: 3, mediterranean: 2, tropical: 2 },
        text: {
          zh: "美丽的海岸线和纯净海滩",
          en: "Beautiful coastlines and pristine beaches",
          es: "Hermosas costas y playas vírgenes",
          fr: "De magnifiques littoraux et des plages préservées",
          ja: "美しい海岸線と手つかずのビーチ",
          ko: "아름다운 해안선과 깨끗한 해변",
        },
      },
      {
        emoji: "🏙️",
        id: "urban_skylines",
        scores: { cosmopolitan: 3, modern: 3 },
        text: {
          zh: "令人印象深刻的天际线和城市景观",
          en: "Impressive skylines and urban landscapes",
          es: "Horizontes urbanos impresionantes y paisajes de ciudad",
          fr: "Des skylines impressionnantes et des paysages urbains",
          ja: "印象的なスカイラインと都市景観",
          ko: "인상적인 스카이라인과 도시 경관",
        },
      },
      {
        emoji: "🌾",
        id: "rolling_countryside",
        scores: { cultural: 3, mediterranean: 1 },
        text: {
          zh: "起伏的丘陵和宁静的乡村",
          en: "Rolling hills and peaceful countryside",
          es: "Colinas onduladas y campo tranquilo",
          fr: "Des collines vallonnées et une campagne paisible",
          ja: "なだらかな丘陵と穏やかな田園風景",
          ko: "완만한 언덕과 평화로운 시골",
        },
      },
    ],
    text: {
      zh: "哪种地理特征最吸引你？",
      en: "Which geographical feature draws you most?",
      es: "¿Qué rasgo geográfico te atrae más?",
      fr: "Quelle caractéristique géographique vous attire le plus ?",
      ja: "どんな地理的特徴にいちばん惹かれますか？",
      ko: "어떤 지형적 특징이 가장 매력적인가요?",
    },
  },
  {
    emoji: "🎭",
    id: "culture",
    options: [
      {
        emoji: "🚀",
        id: "innovation_progress",
        scores: { cosmopolitan: 2, modern: 3, nordic: 1 },
        text: {
          zh: "创新、科技与进步",
          en: "Innovation, technology, and progress",
          es: "Innovación, tecnología y progreso",
          fr: "Innovation, technologie et progrès",
          ja: "革新、テクノロジー、そして進歩",
          ko: "혁신, 기술, 그리고 발전",
        },
      },
      {
        emoji: "🏛️",
        id: "tradition_heritage",
        scores: { cultural: 3, mediterranean: 2 },
        text: {
          zh: "深厚的传统与文化遗产",
          en: "Rich traditions and cultural heritage",
          es: "Ricas tradiciones y patrimonio cultural",
          fr: "Des traditions riches et un patrimoine culturel fort",
          ja: "豊かな伝統と文化遺産",
          ko: "풍부한 전통과 문화 유산",
        },
      },
      {
        emoji: "⚖️",
        id: "equality_welfare",
        scores: { cosmopolitan: 1, nordic: 3 },
        text: {
          zh: "社会平等与完善的福利体系",
          en: "Social equality and strong welfare systems",
          es: "Igualdad social y sistemas de bienestar sólidos",
          fr: "Égalité sociale et systèmes de protection sociale solides",
          ja: "社会的平等と手厚い福祉制度",
          ko: "사회적 평등과 강력한 복지 시스템",
        },
      },
      {
        emoji: "🌍",
        id: "diversity_fusion",
        scores: { cosmopolitan: 3, modern: 1, tropical: 1 },
        text: {
          zh: "文化多样性与思想交融",
          en: "Cultural diversity and a melting pot of ideas",
          es: "Diversidad cultural y un crisol de ideas",
          fr: "Diversité culturelle et brassage d'idées",
          ja: "文化の多様性とアイデアが交わる環境",
          ko: "문화적 다양성과 아이디어의 용광로",
        },
      },
    ],
    text: {
      zh: "你最看重哪种文化层面？",
      en: "What cultural aspect is most important to you?",
      es: "¿Qué aspecto cultural es más importante para ti?",
      fr: "Quel aspect culturel est le plus important pour vous ?",
      ja: "文化面でいちばん大切にしたいことは何ですか？",
      ko: "가장 중요하게 생각하는 문화적 요소는 무엇인가요?",
    },
  },
  {
    emoji: "🍽️",
    id: "food_cuisine",
    options: [
      {
        emoji: "🐟",
        id: "simple_fresh",
        scores: { coastal: 2, mediterranean: 1, nordic: 2 },
        text: {
          zh: "简单、新鲜、高品质的食材",
          en: "Simple, fresh, high-quality ingredients",
          es: "Ingredientes sencillos, frescos y de alta calidad",
          fr: "Des ingrédients simples, frais et de grande qualité",
          ja: "シンプルで新鮮な高品質の食材",
          ko: "간단하고 신선한 고품질 재료",
        },
      },
      {
        emoji: "🥘",
        id: "complex_flavorful",
        scores: { cultural: 3, mediterranean: 2 },
        text: {
          zh: "复杂的风味和丰富的饮食传统",
          en: "Complex flavors and rich culinary traditions",
          es: "Sabores complejos y ricas tradiciones culinarias",
          fr: "Des saveurs complexes et de riches traditions culinaires",
          ja: "複雑な味わいと豊かな食文化",
          ko: "복잡한 맛과 풍부한 요리 전통",
        },
      },
      {
        emoji: "🌮",
        id: "fusion_international",
        scores: { cosmopolitan: 3, modern: 1, tropical: 1 },
        text: {
          zh: "国际融合料理和多样的街头小吃",
          en: "International fusion and diverse street food",
          es: "Fusión internacional y comida callejera diversa",
          fr: "Cuisine fusion internationale et street food variée",
          ja: "国際的なフュージョン料理と多彩な屋台グルメ",
          ko: "다양한 길거리 음식과 인터내셔널 퓨전",
        },
      },
      {
        emoji: "🥬",
        id: "organic_sustainable",
        scores: { mountainous: 1, nordic: 2 },
        text: {
          zh: "有机、可持续、本地采购",
          en: "Organic, sustainable, and locally sourced",
          es: "Orgánico, sostenible y de origen local",
          fr: "Bio, durable et issu de producteurs locaux",
          ja: "オーガニックで持続可能、地元産のもの",
          ko: "유기농, 지속가능한, 지역 생산 식재료",
        },
      },
    ],
    text: {
      zh: "哪种料理最让你心动？",
      en: "What type of cuisine excites you most?",
      es: "¿Qué tipo de cocina te entusiasma más?",
      fr: "Quel type de cuisine vous enthousiasme le plus ?",
      ja: "どんな料理にいちばんワクワクしますか？",
      ko: "어떤 종류의 요리가 가장 흥미로운가요?",
    },
  },
  {
    emoji: "🏛️",
    id: "social_system",
    options: [
      {
        emoji: "🏥",
        id: "universal_healthcare",
        scores: { cultural: 1, nordic: 3 },
        text: {
          zh: "全民医疗和强大的公共服务",
          en: "Universal healthcare and strong public services",
          es: "Sanidad universal y servicios públicos sólidos",
          fr: "Soins de santé universels et services publics solides",
          ja: "国民皆保険と充実した公共サービス",
          ko: "보편적 의료보험과 강력한 공공 서비스",
        },
      },
      {
        emoji: "💼",
        id: "entrepreneurial_freedom",
        scores: { cosmopolitan: 3, modern: 2 },
        text: {
          zh: "创业自由和经济机会",
          en: "Entrepreneurial freedom and economic opportunities",
          es: "Libertad emprendedora y oportunidades económicas",
          fr: "Liberté d'entreprendre et opportunités économiques",
          ja: "起業の自由と経済的なチャンス",
          ko: "기업가적 자유와 경제적 기회",
        },
      },
      {
        emoji: "👨‍👩‍👧‍👦",
        id: "family_community",
        scores: { cultural: 2, mediterranean: 3 },
        text: {
          zh: "牢固的家庭纽带和紧密的社区支持",
          en: "Strong family ties and tight-knit community support",
          es: "Fuertes lazos familiares y apoyo comunitario estrecho",
          fr: "Des liens familiaux forts et un soutien communautaire soudé",
          ja: "強い家族の絆と結束のある地域の支え",
          ko: "강한 가족 유대와 끈끈한 공동체 지원",
        },
      },
      {
        emoji: "🌱",
        id: "environmental_protection",
        scores: { mountainous: 2, nordic: 3, tropical: 1 },
        text: {
          zh: "严格的环境保护和对可持续性的重视",
          en: "Strict environmental protection and sustainability focus",
          es: "Protección ambiental estricta y enfoque en la sostenibilidad",
          fr: "Protection stricte de l'environnement et priorité à la durabilité",
          ja: "厳格な環境保護と持続可能性への重視",
          ko: "엄격한 환경 보호와 지속가능성에 대한 집중",
        },
      },
    ],
    text: {
      zh: "你最重视哪种社会制度？",
      en: "What social system do you value most?",
      es: "¿Qué sistema social valoras más?",
      fr: "Quel système social valorisez-vous le plus ?",
      ja: "どんな社会制度をいちばん重視しますか？",
      ko: "가장 중시하는 사회 제도는 무엇인가요?",
    },
  },
  {
    emoji: "🏠",
    id: "housing",
    options: [
      {
        emoji: "🏢",
        id: "minimalist_functional",
        scores: { modern: 2, nordic: 3 },
        text: {
          zh: "极简、实用且设计精良（例如：斯堪的纳维亚风格）",
          en: "Minimalist, functional, and well-designed (e.g., Scandinavian)",
          es: "Minimalista, funcional y bien diseñado (por ejemplo, escandinavo)",
          fr: "Minimaliste, fonctionnel et bien conçu (par exemple, scandinave)",
          ja: "ミニマルで機能的、洗練されたデザイン（例：スカンジナビア風）",
          ko: "미니멀하고 실용적이며 세련된 디자인 (예: 스칸디나비아)",
        },
      },
      {
        emoji: "🏘️",
        id: "charming_historical",
        scores: { cultural: 3, mediterranean: 2 },
        text: {
          zh: "富有个性的迷人历史建筑",
          en: "Charming historical buildings with character",
          es: "Edificios históricos con encanto y personalidad",
          fr: "Des bâtiments historiques charmants et pleins de caractère",
          ja: "個性と魅力のある歴史的な建物",
          ko: "매력적인 역사적 건물과 특별한 분위기",
        },
      },
      {
        emoji: "🌲",
        id: "nature_integrated",
        scores: { coastal: 2, mountainous: 3, tropical: 2 },
        text: {
          zh: "与自然环境融为一体（例如：小木屋、海滨住宅）",
          en: "Integrated with natural surroundings (e.g., cabin, beach house)",
          es: "Integrado con el entorno natural (por ejemplo, cabaña o casa de playa)",
          fr: "Intégré à l'environnement naturel (par exemple, chalet ou maison de plage)",
          ja: "自然環境と調和している住まい（例：キャビン、ビーチハウス）",
          ko: "자연과 조화된 환경 (예: 통나무집, 해변의 집)",
        },
      },
      {
        emoji: "🏗️",
        id: "high_tech_modern",
        scores: { cosmopolitan: 2, modern: 3 },
        text: {
          zh: "配备超现代设施的高科技智能住宅",
          en: "High-tech smart homes with ultra-modern amenities",
          es: "Casas inteligentes de alta tecnología con comodidades ultramodernas",
          fr: "Maisons intelligentes high-tech avec équipements ultramodernes",
          ja: "最先端の設備を備えたハイテクなスマートホーム",
          ko: "최첨단 스마트홈과 초현대적 편의시설",
        },
      },
    ],
    text: {
      zh: "哪种居住环境最吸引你？",
      en: "What type of living environment appeals to you?",
      es: "¿Qué tipo de entorno de vivienda te atrae más?",
      fr: "Quel type d'environnement de vie vous attire le plus ?",
      ja: "どんな住環境にいちばん惹かれますか？",
      ko: "어떤 주거 환경이 가장 매력적인가요?",
    },
  },
  {
    emoji: "🚲",
    id: "transportation",
    options: [
      {
        emoji: "🚴",
        id: "cycling_walking",
        scores: { coastal: 1, nordic: 3 },
        text: {
          zh: "在自行车友好型城市骑行和步行",
          en: "Cycling and walking in bike-friendly cities",
          es: "Moverse en bicicleta y caminar en ciudades aptas para ciclistas",
          fr: "Faire du vélo et marcher dans des villes adaptées aux cyclistes",
          ja: "自転車にやさしい街でサイクリングや徒歩移動をする",
          ko: "자전거 친화적인 도시에서 사이클링과 걷기",
        },
      },
      {
        emoji: "🚇",
        id: "public_transport",
        scores: { cosmopolitan: 2, cultural: 1, modern: 3 },
        text: {
          zh: "高效、清洁、现代化的公共交通",
          en: "Efficient, clean, and modern public transportation",
          es: "Transporte público eficiente, limpio y moderno",
          fr: "Des transports publics efficaces, propres et modernes",
          ja: "効率的で清潔、近代的な公共交通",
          ko: "효율적이고 깨끗하며 현대적인 대중교통",
        },
      },
      {
        emoji: "🚗",
        id: "car_flexibility",
        scores: { cosmopolitan: 1, mountainous: 2 },
        text: {
          zh: "用私家车获得最大灵活性并进行公路旅行",
          en: "Personal car for maximum flexibility and road trips",
          es: "Coche propio para máxima flexibilidad y viajes por carretera",
          fr: "Voiture personnelle pour un maximum de flexibilité et des road trips",
          ja: "自由度の高い移動やロードトリップのための自家用車",
          ko: "최대한의 유연성을 위한 자가용과 도로 여행",
        },
      },
      {
        emoji: "⛵",
        id: "boat_water",
        scores: { coastal: 3, mediterranean: 1, tropical: 1 },
        text: {
          zh: "船、渡轮和水上交通",
          en: "Boats, ferries, and water-based transportation",
          es: "Barcos, ferris y transporte por agua",
          fr: "Bateaux, ferries et transports sur l'eau",
          ja: "ボート、フェリーなどの水上交通",
          ko: "보트, 페리 등 수상 교통",
        },
      },
    ],
    text: {
      zh: "你更喜欢怎样出行？",
      en: "How do you prefer to get around?",
      es: "¿Cómo prefieres desplazarte?",
      fr: "Comment préférez-vous vous déplacer ?",
      ja: "移動手段は何がいちばん好みですか？",
      ko: "선호하는 이동 방법은 무엇인가요?",
    },
  },
  {
    emoji: "💸",
    id: "budget",
    options: [
      {
        emoji: "🪙",
        id: "budget_guardian",
        scores: { mediterranean: 1, tropical: 3 },
        text: {
          zh: "即使设施简单，也要把开销降到最低",
          en: "Keep expenses minimal, even if amenities are simple",
          es: "Mantener los gastos al mínimo, aunque las comodidades sean sencillas",
          fr: "Limiter les dépenses au minimum, même si les équipements sont simples",
          ja: "設備がシンプルでも、出費はできるだけ抑えたい",
          ko: "편의는 단순해도 생활비를 최소로 유지하고 싶어요",
        },
      },
      {
        emoji: "⚖️",
        id: "balanced_value",
        scores: { coastal: 1, cultural: 2 },
        text: {
          zh: "成本适中，同时有可靠的公共服务和高性价比",
          en: "Balanced costs with reliable public services and good value",
          es: "Costes equilibrados, servicios públicos fiables y buena relación calidad-precio",
          fr: "Des coûts équilibrés, des services publics fiables et un bon rapport qualité-prix",
          ja: "費用のバランスがよく、公共サービスが信頼できてコスパも高い",
          ko: "안정적인 공공서비스와 적당한 비용의 균형을 원해요",
        },
      },
      {
        emoji: "💎",
        id: "premium_quality",
        scores: { cosmopolitan: 1, modern: 2, nordic: 3 },
        text: {
          zh: "愿意为世界级基础设施和生活品质投入更多",
          en: "Invest more for world-class infrastructure and quality of life",
          es: "Invertir más en infraestructura de primer nivel y calidad de vida",
          fr: "Investir davantage pour des infrastructures de classe mondiale et une meilleure qualité de vie",
          ja: "世界水準のインフラと生活の質のためなら多めに投資したい",
          ko: "세계적인 인프라와 삶의 질을 위해서라면 더 투자할 수 있어요",
        },
      },
      {
        emoji: "📈",
        id: "growth_hub",
        scores: { cosmopolitan: 3, modern: 2 },
        text: {
          zh: "如果职业和成长机会充足，较高成本也可以接受",
          en: "Higher costs are fine if career and growth opportunities are abundant",
          es: "Los costes más altos están bien si abundan las oportunidades profesionales y de crecimiento",
          fr: "Des coûts plus élevés me conviennent si les opportunités de carrière et de croissance sont nombreuses",
          ja: "キャリアや成長の機会が豊富なら、費用が高くても構わない",
          ko: "커리어와 성장 기회가 많다면 높은 비용도 감수할 수 있어요",
        },
      },
    ],
    text: {
      zh: "哪种生活成本取舍最适合你？",
      en: "Which cost of living trade-off feels right for you?",
      es: "¿Qué equilibrio de coste de vida te parece más adecuado?",
      fr: "Quel compromis sur le coût de la vie vous semble le plus juste ?",
      ja: "生活費について、どんなバランスが自分に合っていますか？",
      ko: "생활비 면에서 어떤 선택이 가장 현실적인가요?",
    },
  },
  {
    emoji: "🗣️",
    id: "language",
    options: [
      {
        emoji: "🗽",
        id: "english_primary",
        scores: { cosmopolitan: 3, modern: 2 },
        text: {
          zh: "我需要各处都有完善的英语支持",
          en: "I need strong English support everywhere",
          es: "Necesito buen apoyo en inglés en todas partes",
          fr: "J'ai besoin d'un bon accompagnement en anglais partout",
          ja: "どこでも英語のサポートがしっかり必要",
          ko: "업무와 일상생활 전반에 영어 지원이 필요해요",
        },
      },
      {
        emoji: "🌐",
        id: "multilingual_mix",
        scores: { cosmopolitan: 2, cultural: 1 },
        text: {
          zh: "喜欢多种语言并存的全球枢纽",
          en: "Happy in global hubs with multiple languages spoken",
          es: "Me siento a gusto en centros globales donde se hablan varios idiomas",
          fr: "Je me sens bien dans des hubs mondiaux où l'on parle plusieurs langues",
          ja: "複数の言語が使われるグローバルな拠点が心地よい",
          ko: "여러 언어가 공존하는 글로벌 허브가 좋아요",
        },
      },
      {
        emoji: "📚",
        id: "local_immersion",
        scores: { cultural: 3, mediterranean: 2 },
        text: {
          zh: "我想深入学习当地语言",
          en: "I want to dive deep into the local language",
          es: "Quiero sumergirme a fondo en el idioma local",
          fr: "Je veux m'immerger profondément dans la langue locale",
          ja: "現地の言語に深く入り込みたい",
          ko: "현지 언어와 문화를 깊게 배우고 싶어요",
        },
      },
      {
        emoji: "🧠",
        id: "language_challenge",
        scores: { mountainous: 1, nordic: 1 },
        text: {
          zh: "我喜欢语言方面的挑战",
          en: "I enjoy a language challenge",
          es: "Disfruto los retos lingüísticos",
          fr: "J'aime les défis linguistiques",
          ja: "言語の難しさも楽しめる",
          ko: "매력적인 문화라면 어려운 언어도 좋아요",
        },
      },
    ],
    text: {
      zh: "你日常需要多少当地语言支持？",
      en: "How much local language support do you need day to day?",
      es: "¿Cuánto apoyo con el idioma local necesitas en el día a día?",
      fr: "De quel niveau d'aide avec la langue locale avez-vous besoin au quotidien ?",
      ja: "日常生活で、現地語のサポートはどれくらい必要ですか？",
      ko: "일상에서 어느 정도의 현지어 지원이 필요하나요?",
    },
  },
  {
    emoji: "🔮",
    id: "future",
    options: [
      {
        emoji: "🏡",
        id: "family_roots",
        scores: { cultural: 2, mediterranean: 3 },
        text: {
          zh: "在深厚的社区和家庭根基中安定下来",
          en: "Settling down with deep community and family roots",
          es: "Establecerme con raíces profundas en la comunidad y la familia",
          fr: "M'installer avec de solides racines communautaires et familiales",
          ja: "地域や家族との深いつながりの中で定住する",
          ko: "깊은 공동체 속에서 가족과 함께 정착",
        },
      },
      {
        emoji: "💼",
        id: "career_acceleration",
        scores: { cosmopolitan: 3, modern: 2 },
        text: {
          zh: "快速推进职业发展并建立全球人脉",
          en: "Fast-tracking my career and building a global network",
          es: "Acelerar mi carrera y construir una red global",
          fr: "Accélérer ma carrière et bâtir un réseau mondial",
          ja: "キャリアを加速させ、グローバルなネットワークを築く",
          ko: "커리어를 빠르게 발전시키고 글로벌 네트워크 구축",
        },
      },
      {
        emoji: "🧘‍♀️",
        id: "slow_living",
        scores: { mountainous: 2, nordic: 2, tropical: 1 },
        text: {
          zh: "设计一种更慢、更注重健康、亲近自然的生活",
          en: "Designing a slower, wellness-focused life close to nature",
          es: "Diseñar una vida más lenta, centrada en el bienestar y cerca de la naturaleza",
          fr: "Créer une vie plus lente, axée sur le bien-être et proche de la nature",
          ja: "自然の近くで、ゆったりと健康を大切にする暮らしをつくる",
          ko: "자연과 가까운 곳에서 느린 삶",
        },
      },
      {
        emoji: "✈️",
        id: "global_nomad",
        scores: { coastal: 2, modern: 1 },
        text: {
          zh: "作为数字游民保持流动生活",
          en: "Staying mobile as a digital nomad",
          es: "Mantenerme en movimiento como nómada digital",
          fr: "Rester mobile en tant que nomade numérique",
          ja: "デジタルノマドとして身軽に暮らし続ける",
          ko: "디지털 노마드로서 유연하게 생활",
        },
      },
    ],
    text: {
      zh: "你正在规划怎样的未来愿景？",
      en: "What future vision are you planning toward?",
      es: "¿Hacia qué visión de futuro estás planificando?",
      fr: "Vers quelle vision d'avenir vous projetez-vous ?",
      ja: "どんな将来像に向かって計画していますか？",
      ko: "앞으로 어떤 삶의 방향을 그리고 있나요?",
    },
  },
  {
    emoji: "🥂",
    id: "social_activity",
    options: [
      {
        emoji: "🌃",
        id: "vibrant_nightlife",
        scores: { cosmopolitan: 3, mediterranean: 1 },
        text: {
          zh: "探索充满活力的夜生活、酒吧和活动",
          en: "Exploring vibrant nightlife, bars, and events",
          es: "Explorar una vida nocturna vibrante, bares y eventos",
          fr: "Explorer une vie nocturne animée, des bars et des événements",
          ja: "活気あるナイトライフやバー、イベントを楽しむ",
          ko: "활기찬 밤문화, 바, 이벤트 탐방",
        },
      },
      {
        emoji: "🍻",
        id: "cozy_gatherings",
        scores: { cultural: 2, nordic: 3 },
        text: {
          zh: "与亲密朋友的小型温馨聚会",
          en: "Cozy gatherings with close friends",
          es: "Reuniones acogedoras con amigos cercanos",
          fr: "Des moments chaleureux avec des amis proches",
          ja: "親しい友人との居心地のよい集まり",
          ko: "가까운 친구들과 아늑한 모임",
        },
      },
      {
        emoji: "🖼️",
        id: "cultural_events",
        scores: { cultural: 3, modern: 1 },
        text: {
          zh: "参加音乐会、戏剧或画廊开幕活动",
          en: "Attending concerts, theater, or gallery openings",
          es: "Asistir a conciertos, teatro o inauguraciones de galerías",
          fr: "Assister à des concerts, au théâtre ou à des vernissages",
          ja: "コンサートや演劇、ギャラリーのオープニングに行く",
          ko: "콘서트, 연극, 갤러리 참석",
        },
      },
      {
        emoji: "🌳",
        id: "outdoor_evenings",
        scores: { coastal: 3, mountainous: 1, tropical: 2 },
        text: {
          zh: "在户外度过放松的夜晚，比如篝火或野餐",
          en: "Relaxed evenings outdoors, bonfires or picnics",
          es: "Noches relajadas al aire libre, con fogatas o picnics",
          fr: "Des soirées détendues en plein air, autour d'un feu ou d'un pique-nique",
          ja: "焚き火やピクニックなど、屋外でのんびり過ごす夜",
          ko: "해변의 모닥불이나 공원 피크닉",
        },
      },
    ],
    text: {
      zh: "你理想中的社交夜晚是什么样的？",
      en: "What is your ideal social evening?",
      es: "¿Cómo sería tu noche social ideal?",
      fr: "À quoi ressemble votre soirée sociale idéale ?",
      ja: "理想の社交的な夜はどんな過ごし方ですか？",
      ko: "이상적인 저녁 사교 활동은 무엇인가요?",
    },
  },
];

export const COUNTRIES_DATABASE: Record<string, CountryProfile> = {
  canada: {
    bestFor: [
      { en: "Families", ko: "가족" },
      { en: "Nature Lovers", ko: "자연 애호가" },
    ],
    climate: {
      zh: "寒冷的冬天",
      en: "Cold winters",
      es: "Inviernos fríos",
      fr: "Hivers froids",
      ja: "寒い冬",
      ko: "추운 겨울",
    },
    cons: [
      { en: "Cold winters", ko: "추운 겨울" },
      { en: "High housing costs", ko: "높은 주거비" },
    ],
    continent: "North America",
    currency: "CAD",
    flag: "🇨🇦",
    language: ["English", "French"],
    metrics: {
      costOfLiving: "High",
      healthcare: 8.8,
      internetSpeed: 150,
      qualityOfLife: 9.0,
      safety: 9.0,
    },
    name: {
      zh: "加拿大",
      en: "Canada",
      es: "Canadá",
      fr: "Canada",
      ja: "カナダ",
      ko: "캐나다",
    },
    population: "38m",
    pros: [
      { en: "Welcoming society", ko: "환영하는 사회" },
      { en: "Nature", ko: "대자연" },
    ],
    vibe: {
      zh: "多元文化、辽阔、礼貌",
      en: "Multicultural, vast, polite",
      es: "Multicultural, vasto y cortés",
      fr: "Multiculturel, vaste et poli",
      ja: "多文化で広大、礼儀正しい",
      ko: "다문화적이고 광대한",
    },
  },
  italy: {
    bestFor: [
      { en: "Foodies", ko: "미식가" },
      { en: "Artists", ko: "예술가" },
    ],
    climate: {
      zh: "地中海气候",
      en: "Mediterranean",
      es: "Mediterráneo",
      fr: "Méditerranéen",
      ja: "地中海性",
      ko: "지중해성",
    },
    cons: [
      { en: "Bureaucracy", ko: "관료주의" },
      { en: "Economic instability", ko: "경제적 불안정" },
    ],
    continent: "Europe",
    currency: "EUR",
    flag: "🇮🇹",
    language: ["Italian"],
    metrics: {
      costOfLiving: "Medium",
      healthcare: 8.5,
      internetSpeed: 60,
      qualityOfLife: 8.2,
      safety: 8.0,
    },
    name: {
      zh: "意大利",
      en: "Italy",
      es: "Italia",
      fr: "Italie",
      ja: "イタリア",
      ko: "이탈리아",
    },
    population: "59m",
    pros: [
      { en: "World-renowned cuisine", ko: "세계적인 요리" },
      { en: "Incomparable art & history", ko: "예술과 역사" },
    ],
    vibe: {
      zh: "历史悠久、热情、美味",
      en: "Historic, passionate, and delicious",
      es: "Histórico, apasionado y delicioso",
      fr: "Historique, passionné et délicieux",
      ja: "歴史的で情熱的、そしておいしい",
      ko: "역사적이고 열정적인",
    },
  },
  japan: {
    bestFor: [
      { en: "Foodies", ko: "미식가" },
      { en: "Tech Lovers", ko: "기술 애호가" },
    ],
    climate: {
      zh: "四季分明",
      en: "Four seasons",
      es: "Cuatro estaciones",
      fr: "Quatre saisons",
      ja: "四季",
      ko: "사계절",
    },
    cons: [
      { en: "Work culture", ko: "직장 문화" },
      { en: "Language barrier", ko: "언어 장벽" },
    ],
    continent: "Asia",
    currency: "JPY",
    flag: "🇯🇵",
    language: ["Japanese"],
    metrics: {
      costOfLiving: "High",
      healthcare: 9.3,
      internetSpeed: 180,
      qualityOfLife: 8.8,
      safety: 9.7,
    },
    name: {
      zh: "日本",
      en: "Japan",
      es: "Japón",
      fr: "Japon",
      ja: "日本",
      ko: "일본",
    },
    population: "125m",
    pros: [
      { en: "Safety", ko: "치안" },
      { en: "Food & Culture", ko: "음식과 문화" },
    ],
    vibe: {
      zh: "传统、现代、有序",
      en: "Traditional, modern, orderly",
      es: "Tradicional, moderno y ordenado",
      fr: "Traditionnel, moderne et ordonné",
      ja: "伝統的で近代的、秩序がある",
      ko: "전통과 현대의 조화",
    },
  },
  norway: {
    bestFor: [
      { en: "Nature Lovers", ko: "자연 애호가" },
      { en: "Families", ko: "가족" },
    ],
    climate: {
      zh: "寒冷的冬天，温和的夏天",
      en: "Cold winters, mild summers",
      es: "Inviernos fríos y veranos suaves",
      fr: "Hivers froids, étés doux",
      ja: "寒い冬と穏やかな夏",
      ko: "추운 겨울, 온화한 여름",
    },
    cons: [
      { en: "Extremely high cost of living", ko: "극도로 높은 생활비" },
      { en: "Cold winters", ko: "추운 겨울" },
    ],
    continent: "Europe",
    currency: "NOK",
    flag: "🇳🇴",
    language: ["Norwegian", "English"],
    metrics: {
      costOfLiving: "Very High",
      healthcare: 9.2,
      internetSpeed: 100,
      qualityOfLife: 9.5,
      safety: 9.8,
    },
    name: {
      zh: "挪威",
      en: "Norway",
      es: "Noruega",
      fr: "Norvège",
      ja: "ノルウェー",
      ko: "노르웨이",
    },
    population: "5.4m",
    pros: [
      { en: "Exceptional work-life balance", ko: "뛰어난 워라밸" },
      { en: "Stunning natural beauty", ko: "멋진 자연 경관" },
    ],
    vibe: {
      zh: "宁静、壮丽、物价高",
      en: "Peaceful, majestic, and expensive",
      es: "Pacífico, majestuoso y caro",
      fr: "Paisible, majestueux et cher",
      ja: "穏やかで雄大、物価が高い",
      ko: "평화롭고, 장엄하며, 물가가 비싼",
    },
  },
  singapore: {
    bestFor: [
      { en: "Finance Pros", ko: "금융 전문가" },
      { en: "Families", ko: "가족" },
    ],
    climate: {
      zh: "热带",
      en: "Tropical",
      es: "tropical",
      fr: "tropical",
      ja: "熱帯",
      ko: "열대",
    },
    cons: [
      { en: "Expensive", ko: "비쌈" },
      { en: "Humidity", ko: "습도" },
    ],
    continent: "Asia",
    currency: "SGD",
    flag: "🇸🇬",
    language: ["English", "Mandarin"],
    metrics: {
      costOfLiving: "Very High",
      healthcare: 8.9,
      internetSpeed: 250,
      qualityOfLife: 9.0,
      safety: 9.8,
    },
    name: {
      zh: "新加坡",
      en: "Singapore",
      es: "Singapur",
      fr: "Singapour",
      ja: "シンガポール",
      ko: "싱가포르",
    },
    population: "5.9m",
    pros: [
      { en: "Safety & Cleanliness", ko: "안전과 청결" },
      { en: "Global Hub", ko: "글로벌 허브" },
    ],
    vibe: {
      zh: "现代、高效、多元文化",
      en: "Modern, efficient, multicultural",
      es: "Moderno, eficiente y multicultural",
      fr: "Moderne, efficace et multiculturel",
      ja: "近代的で効率的、多文化",
      ko: "현대적이고 효율적인",
    },
  },
  sweden: {
    bestFor: [
      { en: "Tech Pros", ko: "기술 전문가" },
      { en: "Designers", ko: "디자이너" },
    ],
    climate: {
      zh: "寒冷的冬天，宜人的夏天",
      en: "Cold winters, pleasant summers",
      es: "Inviernos fríos y veranos agradables",
      fr: "Hivers froids, étés agréables",
      ja: "寒い冬と過ごしやすい夏",
      ko: "추운 겨울, 쾌적한 여름",
    },
    cons: [
      { en: "High taxes", ko: "높은 세금" },
      { en: "Dark winters", ko: "어두운 겨울" },
    ],
    continent: "Europe",
    currency: "SEK",
    flag: "🇸🇪",
    language: ["Swedish", "English"],
    metrics: {
      costOfLiving: "High",
      healthcare: 9.0,
      internetSpeed: 120,
      qualityOfLife: 9.2,
      safety: 9.5,
    },
    name: {
      zh: "瑞典",
      en: "Sweden",
      es: "Suecia",
      fr: "Suède",
      ja: "スウェーデン",
      ko: "스웨덴",
    },
    population: "10.4m",
    pros: [
      { en: "Tech and innovation hub", ko: "기술 혁신 허브" },
      { en: "Strong social benefits", ko: "강력한 사회 보장" },
    ],
    vibe: {
      zh: "创新、有格调、内敛",
      en: "Innovative, stylish, and reserved",
      es: "Innovador, elegante y reservado",
      fr: "Innovant, élégant et réservé",
      ja: "革新的で洗練され、控えめ",
      ko: "혁신적이고 스타일리시한",
    },
  },
  thailand: {
    bestFor: [
      { en: "Digital Nomads", ko: "디지털 노마드" },
      { en: "Budget Travelers", ko: "저예산 여행자" },
    ],
    climate: {
      zh: "热带",
      en: "Tropical",
      es: "tropical",
      fr: "tropical",
      ja: "熱帯",
      ko: "열대",
    },
    cons: [
      { en: "Hot and humid", ko: "고온 다습" },
      { en: "Traffic", ko: "교통 체증" },
    ],
    continent: "Asia",
    currency: "THB",
    flag: "🇹🇭",
    language: ["Thai"],
    metrics: {
      costOfLiving: "Low",
      healthcare: 7.8,
      internetSpeed: 200,
      qualityOfLife: 7.5,
      safety: 7.6,
    },
    name: {
      zh: "泰国",
      en: "Thailand",
      es: "Tailandia",
      fr: "Thaïlande",
      ja: "タイ",
      ko: "태국",
    },
    population: "70m",
    pros: [
      { en: "Low cost of living", ko: "저렴한 생활비" },
      { en: "Delicious food", ko: "맛있는 음식" },
    ],
    vibe: {
      zh: "充满活力、富有灵性、适合预算有限的人",
      en: "Vibrant, spiritual, budget-friendly",
      es: "Vibrante, espiritual y económica",
      fr: "Vibrante, spirituelle et abordable",
      ja: "活気があり、スピリチュアルで予算にやさしい",
      ko: "활기차고 영적인",
    },
  },
};
