import { CountryProfile, CountryQuestion } from "./types";

export const COUNTRY_QUESTIONS: CountryQuestion[] = [
  {
    emoji: "🌤️",
    id: "climate",
    options: [
      {
        emoji: "❄️",
        id: "cold_crisp",
        scores: { modern: 1, mountainous: 2, nordic: 3 },
        text: {
          cn: "Cold, crisp winters with mild summers",
          en: "Cold, crisp winters with mild summers",
          es: "Cold, crisp winters with mild summers",
          fr: "Cold, crisp winters with mild summers",
          ja: "Cold, crisp winters with mild summers",
          ko: "춥고 상쾌한 겨울과 온화한 여름",
        },
      },
      {
        emoji: "☀️",
        id: "warm_sunny",
        scores: { coastal: 2, mediterranean: 3, tropical: 2 },
        text: {
          cn: "Warm, sunny weather most of the year",
          en: "Warm, sunny weather most of the year",
          es: "Warm, sunny weather most of the year",
          fr: "Warm, sunny weather most of the year",
          ja: "Warm, sunny weather most of the year",
          ko: "일년 내내 따뜻하고 화창한 날씨",
        },
      },
      {
        emoji: "🌴",
        id: "hot_humid",
        scores: { coastal: 1, tropical: 3 },
        text: {
          cn: "Hot and humid with lush greenery",
          en: "Hot and humid with lush greenery",
          es: "Hot and humid with lush greenery",
          fr: "Hot and humid with lush greenery",
          ja: "Hot and humid with lush greenery",
          ko: "덥고 습하며 푸른 녹음이 우거진 곳",
        },
      },
      {
        emoji: "🍂",
        id: "four_seasons",
        scores: { cosmopolitan: 1, cultural: 2, modern: 2 },
        text: {
          cn: "Four distinct seasons with variety",
          en: "Four distinct seasons with variety",
          es: "Four distinct seasons with variety",
          fr: "Four distinct seasons with variety",
          ja: "Four distinct seasons with variety",
          ko: "뚜렷한 사계절이 있는 곳",
        },
      },
    ],
    text: {
      cn: "What type of climate do you thrive in?",
      en: "What type of climate do you thrive in?",
      es: "What type of climate do you thrive in?",
      fr: "What type of climate do you thrive in?",
      ja: "What type of climate do you thrive in?",
      ko: "어떤 기후에서 가장 잘 지낼 수 있나요?",
    },
  },
  {
    emoji: "⏰",
    id: "lifestyle",
    options: [
      {
        emoji: "🧘",
        id: "slow_mindful",
        scores: { mediterranean: 2, mountainous: 2, nordic: 3, tropical: 2 },
        text: {
          cn: "Slow, mindful living with strong work-life balance",
          en: "Slow, mindful living with strong work-life balance",
          es: "Slow, mindful living with strong work-life balance",
          fr: "Slow, mindful living with strong work-life balance",
          ja: "Slow, mindful living with strong work-life balance",
          ko: "느리고 여유로운 삶과 확실한 워라밸",
        },
      },
      {
        emoji: "🏃",
        id: "fast_dynamic",
        scores: { cosmopolitan: 3, modern: 3 },
        text: {
          cn: "Fast-paced, dynamic urban energy",
          en: "Fast-paced, dynamic urban energy",
          es: "Fast-paced, dynamic urban energy",
          fr: "Fast-paced, dynamic urban energy",
          ja: "Fast-paced, dynamic urban energy",
          ko: "빠른 속도의 역동적인 도시 생활",
        },
      },
      {
        emoji: "👥",
        id: "community_social",
        scores: { cultural: 3, mediterranean: 3, tropical: 1 },
        text: {
          cn: "Community-focused with strong social bonds",
          en: "Community-focused with strong social bonds",
          es: "Community-focused with strong social bonds",
          fr: "Community-focused with strong social bonds",
          ja: "Community-focused with strong social bonds",
          ko: "공동체 중심의 강한 사회적 유대감",
        },
      },
      {
        emoji: "🆓",
        id: "independent_flexible",
        scores: { cosmopolitan: 2, modern: 2, mountainous: 1 },
        text: {
          cn: "Independent with flexible routines and remote work",
          en: "Independent with flexible routines and remote work",
          es: "Independent with flexible routines and remote work",
          fr: "Independent with flexible routines and remote work",
          ja: "Independent with flexible routines and remote work",
          ko: "독립적이고 유연한 일상과 원격 근무",
        },
      },
    ],
    text: {
      cn: "What lifestyle pace appeals to you most?",
      en: "What lifestyle pace appeals to you most?",
      es: "What lifestyle pace appeals to you most?",
      fr: "What lifestyle pace appeals to you most?",
      ja: "What lifestyle pace appeals to you most?",
      ko: "어떤 생활 패턴이 가장 매력적인가요?",
    },
  },
  {
    emoji: "🗺️",
    id: "geography",
    options: [
      {
        emoji: "⛰️",
        id: "mountains_forests",
        scores: { mountainous: 3, nordic: 2 },
        text: {
          cn: "Majestic mountains and pristine forests",
          en: "Majestic mountains and pristine forests",
          es: "Majestic mountains and pristine forests",
          fr: "Majestic mountains and pristine forests",
          ja: "Majestic mountains and pristine forests",
          ko: "장엄한 산맥과 울창한 숲",
        },
      },
      {
        emoji: "🏖️",
        id: "coastline_beaches",
        scores: { coastal: 3, mediterranean: 2, tropical: 2 },
        text: {
          cn: "Beautiful coastlines and pristine beaches",
          en: "Beautiful coastlines and pristine beaches",
          es: "Beautiful coastlines and pristine beaches",
          fr: "Beautiful coastlines and pristine beaches",
          ja: "Beautiful coastlines and pristine beaches",
          ko: "아름다운 해안선과 깨끗한 해변",
        },
      },
      {
        emoji: "🏙️",
        id: "urban_skylines",
        scores: { cosmopolitan: 3, modern: 3 },
        text: {
          cn: "Impressive skylines and urban landscapes",
          en: "Impressive skylines and urban landscapes",
          es: "Impressive skylines and urban landscapes",
          fr: "Impressive skylines and urban landscapes",
          ja: "Impressive skylines and urban landscapes",
          ko: "인상적인 스카이라인과 도시 경관",
        },
      },
      {
        emoji: "🌾",
        id: "rolling_countryside",
        scores: { cultural: 3, mediterranean: 1 },
        text: {
          cn: "Rolling hills and peaceful countryside",
          en: "Rolling hills and peaceful countryside",
          es: "Rolling hills and peaceful countryside",
          fr: "Rolling hills and peaceful countryside",
          ja: "Rolling hills and peaceful countryside",
          ko: "완만한 언덕과 평화로운 시골",
        },
      },
    ],
    text: {
      cn: "Which geographical feature draws you most?",
      en: "Which geographical feature draws you most?",
      es: "Which geographical feature draws you most?",
      fr: "Which geographical feature draws you most?",
      ja: "Which geographical feature draws you most?",
      ko: "어떤 지형적 특징이 가장 매력적인가요?",
    },
  },
  {
    emoji: "🎭",
    id: "culture",
    options: [
      {
        emoji: "🚀",
        id: "innovation_progress",
        scores: { cosmopolitan: 2, modern: 3, nordic: 1 },
        text: {
          cn: "Innovation, technology, and progress",
          en: "Innovation, technology, and progress",
          es: "Innovation, technology, and progress",
          fr: "Innovation, technology, and progress",
          ja: "Innovation, technology, and progress",
          ko: "혁신, 기술, 그리고 발전",
        },
      },
      {
        emoji: "🏛️",
        id: "tradition_heritage",
        scores: { cultural: 3, mediterranean: 2 },
        text: {
          cn: "Rich traditions and cultural heritage",
          en: "Rich traditions and cultural heritage",
          es: "Rich traditions and cultural heritage",
          fr: "Rich traditions and cultural heritage",
          ja: "Rich traditions and cultural heritage",
          ko: "풍부한 전통과 문화 유산",
        },
      },
      {
        emoji: "⚖️",
        id: "equality_welfare",
        scores: { cosmopolitan: 1, nordic: 3 },
        text: {
          cn: "Social equality and strong welfare systems",
          en: "Social equality and strong welfare systems",
          es: "Social equality and strong welfare systems",
          fr: "Social equality and strong welfare systems",
          ja: "Social equality and strong welfare systems",
          ko: "사회적 평등과 강력한 복지 시스템",
        },
      },
      {
        emoji: "🌍",
        id: "diversity_fusion",
        scores: { cosmopolitan: 3, modern: 1, tropical: 1 },
        text: {
          cn: "Cultural diversity and a melting pot of ideas",
          en: "Cultural diversity and a melting pot of ideas",
          es: "Cultural diversity and a melting pot of ideas",
          fr: "Cultural diversity and a melting pot of ideas",
          ja: "Cultural diversity and a melting pot of ideas",
          ko: "문화적 다양성과 아이디어의 용광로",
        },
      },
    ],
    text: {
      cn: "What cultural aspect is most important to you?",
      en: "What cultural aspect is most important to you?",
      es: "What cultural aspect is most important to you?",
      fr: "What cultural aspect is most important to you?",
      ja: "What cultural aspect is most important to you?",
      ko: "가장 중요하게 생각하는 문화적 요소는 무엇인가요?",
    },
  },
  {
    emoji: "🍽️",
    id: "food_cuisine",
    options: [
      {
        emoji: "🐟",
        id: "simple_fresh",
        scores: { coastal: 2, mediterranean: 1, nordic: 2 },
        text: {
          cn: "Simple, fresh, high-quality ingredients",
          en: "Simple, fresh, high-quality ingredients",
          es: "Simple, fresh, high-quality ingredients",
          fr: "Simple, fresh, high-quality ingredients",
          ja: "Simple, fresh, high-quality ingredients",
          ko: "간단하고 신선한 고품질 재료",
        },
      },
      {
        emoji: "🥘",
        id: "complex_flavorful",
        scores: { cultural: 3, mediterranean: 2 },
        text: {
          cn: "Complex flavors and rich culinary traditions",
          en: "Complex flavors and rich culinary traditions",
          es: "Complex flavors and rich culinary traditions",
          fr: "Complex flavors and rich culinary traditions",
          ja: "Complex flavors and rich culinary traditions",
          ko: "복잡한 맛과 풍부한 요리 전통",
        },
      },
      {
        emoji: "🌮",
        id: "fusion_international",
        scores: { cosmopolitan: 3, modern: 1, tropical: 1 },
        text: {
          cn: "International fusion and diverse street food",
          en: "International fusion and diverse street food",
          es: "International fusion and diverse street food",
          fr: "International fusion and diverse street food",
          ja: "International fusion and diverse street food",
          ko: "다양한 길거리 음식과 인터내셔널 퓨전",
        },
      },
      {
        emoji: "🥬",
        id: "organic_sustainable",
        scores: { mountainous: 1, nordic: 2 },
        text: {
          cn: "Organic, sustainable, and locally sourced",
          en: "Organic, sustainable, and locally sourced",
          es: "Organic, sustainable, and locally sourced",
          fr: "Organic, sustainable, and locally sourced",
          ja: "Organic, sustainable, and locally sourced",
          ko: "유기농, 지속가능한, 지역 생산 식재료",
        },
      },
    ],
    text: {
      cn: "What type of cuisine excites you most?",
      en: "What type of cuisine excites you most?",
      es: "What type of cuisine excites you most?",
      fr: "What type of cuisine excites you most?",
      ja: "What type of cuisine excites you most?",
      ko: "어떤 종류의 요리가 가장 흥미로운가요?",
    },
  },
  {
    emoji: "🏛️",
    id: "social_system",
    options: [
      {
        emoji: "🏥",
        id: "universal_healthcare",
        scores: { cultural: 1, nordic: 3 },
        text: {
          cn: "Universal healthcare and strong public services",
          en: "Universal healthcare and strong public services",
          es: "Universal healthcare and strong public services",
          fr: "Universal healthcare and strong public services",
          ja: "Universal healthcare and strong public services",
          ko: "보편적 의료보험과 강력한 공공 서비스",
        },
      },
      {
        emoji: "💼",
        id: "entrepreneurial_freedom",
        scores: { cosmopolitan: 3, modern: 2 },
        text: {
          cn: "Entrepreneurial freedom and economic opportunities",
          en: "Entrepreneurial freedom and economic opportunities",
          es: "Entrepreneurial freedom and economic opportunities",
          fr: "Entrepreneurial freedom and economic opportunities",
          ja: "Entrepreneurial freedom and economic opportunities",
          ko: "기업가적 자유와 경제적 기회",
        },
      },
      {
        emoji: "👨‍👩‍👧‍👦",
        id: "family_community",
        scores: { cultural: 2, mediterranean: 3 },
        text: {
          cn: "Strong family ties and tight-knit community support",
          en: "Strong family ties and tight-knit community support",
          es: "Strong family ties and tight-knit community support",
          fr: "Strong family ties and tight-knit community support",
          ja: "Strong family ties and tight-knit community support",
          ko: "강한 가족 유대와 끈끈한 공동체 지원",
        },
      },
      {
        emoji: "🌱",
        id: "environmental_protection",
        scores: { mountainous: 2, nordic: 3, tropical: 1 },
        text: {
          cn: "Strict environmental protection and sustainability focus",
          en: "Strict environmental protection and sustainability focus",
          es: "Strict environmental protection and sustainability focus",
          fr: "Strict environmental protection and sustainability focus",
          ja: "Strict environmental protection and sustainability focus",
          ko: "엄격한 환경 보호와 지속가능성에 대한 집중",
        },
      },
    ],
    text: {
      cn: "What social system do you value most?",
      en: "What social system do you value most?",
      es: "What social system do you value most?",
      fr: "What social system do you value most?",
      ja: "What social system do you value most?",
      ko: "가장 중시하는 사회 제도는 무엇인가요?",
    },
  },
  {
    emoji: "🏠",
    id: "housing",
    options: [
      {
        emoji: "🏢",
        id: "minimalist_functional",
        scores: { modern: 2, nordic: 3 },
        text: {
          cn: "Minimalist, functional, and well-designed",
          en: "Minimalist, functional, and well-designed (e.g., Scandinavian)",
          es: "Minimalist, functional, and well-designed",
          fr: "Minimalist, functional, and well-designed",
          ja: "Minimalist, functional, and well-designed",
          ko: "미니멀하고 실용적이며 세련된 디자인 (예: 스칸디나비아)",
        },
      },
      {
        emoji: "🏘️",
        id: "charming_historical",
        scores: { cultural: 3, mediterranean: 2 },
        text: {
          cn: "Charming historical buildings with character",
          en: "Charming historical buildings with character",
          es: "Charming historical buildings with character",
          fr: "Charming historical buildings with character",
          ja: "Charming historical buildings with character",
          ko: "매력적인 역사적 건물과 특별한 분위기",
        },
      },
      {
        emoji: "🌲",
        id: "nature_integrated",
        scores: { coastal: 2, mountainous: 3, tropical: 2 },
        text: {
          cn: "Integrated with natural surroundings",
          en: "Integrated with natural surroundings (e.g., cabin, beach house)",
          es: "Integrated with natural surroundings",
          fr: "Integrated with natural surroundings",
          ja: "Integrated with natural surroundings",
          ko: "자연과 조화된 환경 (예: 통나무집, 해변의 집)",
        },
      },
      {
        emoji: "🏗️",
        id: "high_tech_modern",
        scores: { cosmopolitan: 2, modern: 3 },
        text: {
          cn: "High-tech smart homes with ultra-modern amenities",
          en: "High-tech smart homes with ultra-modern amenities",
          es: "High-tech smart homes with ultra-modern amenities",
          fr: "High-tech smart homes with ultra-modern amenities",
          ja: "High-tech smart homes with ultra-modern amenities",
          ko: "최첨단 스마트홈과 초현대적 편의시설",
        },
      },
    ],
    text: {
      cn: "What type of living environment appeals to you?",
      en: "What type of living environment appeals to you?",
      es: "What type of living environment appeals to you?",
      fr: "What type of living environment appeals to you?",
      ja: "What type of living environment appeals to you?",
      ko: "어떤 주거 환경이 가장 매력적인가요?",
    },
  },
  {
    emoji: "🚲",
    id: "transportation",
    options: [
      {
        emoji: "🚴",
        id: "cycling_walking",
        scores: { coastal: 1, nordic: 3 },
        text: {
          cn: "Cycling and walking in bike-friendly cities",
          en: "Cycling and walking in bike-friendly cities",
          es: "Cycling and walking in bike-friendly cities",
          fr: "Cycling and walking in bike-friendly cities",
          ja: "Cycling and walking in bike-friendly cities",
          ko: "자전거 친화적인 도시에서 사이클링과 걷기",
        },
      },
      {
        emoji: "🚇",
        id: "public_transport",
        scores: { cosmopolitan: 2, cultural: 1, modern: 3 },
        text: {
          cn: "Efficient, clean, and modern public transportation",
          en: "Efficient, clean, and modern public transportation",
          es: "Efficient, clean, and modern public transportation",
          fr: "Efficient, clean, and modern public transportation",
          ja: "Efficient, clean, and modern public transportation",
          ko: "효율적이고 깨끗하며 현대적인 대중교통",
        },
      },
      {
        emoji: "🚗",
        id: "car_flexibility",
        scores: { cosmopolitan: 1, mountainous: 2 },
        text: {
          cn: "Personal car for maximum flexibility",
          en: "Personal car for maximum flexibility and road trips",
          es: "Personal car for maximum flexibility",
          fr: "Personal car for maximum flexibility",
          ja: "Personal car for maximum flexibility",
          ko: "최대한의 유연성을 위한 자가용과 도로 여행",
        },
      },
      {
        emoji: "⛵",
        id: "boat_water",
        scores: { coastal: 3, mediterranean: 1, tropical: 1 },
        text: {
          cn: "Boats, ferries, and water-based transportation",
          en: "Boats, ferries, and water-based transportation",
          es: "Boats, ferries, and water-based transportation",
          fr: "Boats, ferries, and water-based transportation",
          ja: "Boats, ferries, and water-based transportation",
          ko: "보트, 페리 등 수상 교통",
        },
      },
    ],
    text: {
      cn: "How do you prefer to get around?",
      en: "How do you prefer to get around?",
      es: "How do you prefer to get around?",
      fr: "How do you prefer to get around?",
      ja: "How do you prefer to get around?",
      ko: "선호하는 이동 방법은 무엇인가요?",
    },
  },
  {
    emoji: "💸",
    id: "budget",
    options: [
      {
        emoji: "🪙",
        id: "budget_guardian",
        scores: { mediterranean: 1, tropical: 3 },
        text: {
          cn: "Keep expenses minimal, even if amenities are simple",
          en: "Keep expenses minimal, even if amenities are simple",
          es: "Keep expenses minimal, even if amenities are simple",
          fr: "Keep expenses minimal, even if amenities are simple",
          ja: "Keep expenses minimal, even if amenities are simple",
          ko: "편의는 단순해도 생활비를 최소로 유지하고 싶어요",
        },
      },
      {
        emoji: "⚖️",
        id: "balanced_value",
        scores: { coastal: 1, cultural: 2 },
        text: {
          cn: "Balanced costs with reliable public services",
          en: "Balanced costs with reliable public services and good value",
          es: "Balanced costs with reliable public services",
          fr: "Balanced costs with reliable public services",
          ja: "Balanced costs with reliable public services",
          ko: "안정적인 공공서비스와 적당한 비용의 균형을 원해요",
        },
      },
      {
        emoji: "💎",
        id: "premium_quality",
        scores: { cosmopolitan: 1, modern: 2, nordic: 3 },
        text: {
          cn: "Invest more for world-class infrastructure",
          en: "Invest more for world-class infrastructure and quality of life",
          es: "Invest more for world-class infrastructure",
          fr: "Invest more for world-class infrastructure",
          ja: "Invest more for world-class infrastructure",
          ko: "세계적인 인프라와 삶의 질을 위해서라면 더 투자할 수 있어요",
        },
      },
      {
        emoji: "📈",
        id: "growth_hub",
        scores: { cosmopolitan: 3, modern: 2 },
        text: {
          cn: "Higher costs are fine for growth opportunities",
          en: "Higher costs are fine if career and growth opportunities are abundant",
          es: "Higher costs are fine for growth opportunities",
          fr: "Higher costs are fine for growth opportunities",
          ja: "Higher costs are fine for growth opportunities",
          ko: "커리어와 성장 기회가 많다면 높은 비용도 감수할 수 있어요",
        },
      },
    ],
    text: {
      cn: "Which cost of living trade-off feels right for you?",
      en: "Which cost of living trade-off feels right for you?",
      es: "Which cost of living trade-off feels right for you?",
      fr: "Which cost of living trade-off feels right for you?",
      ja: "Which cost of living trade-off feels right for you?",
      ko: "생활비 면에서 어떤 선택이 가장 현실적인가요?",
    },
  },
  {
    emoji: "🗣️",
    id: "language",
    options: [
      {
        emoji: "🗽",
        id: "english_primary",
        scores: { cosmopolitan: 3, modern: 2 },
        text: {
          cn: "I need strong English support everywhere",
          en: "I need strong English support everywhere",
          es: "I need strong English support everywhere",
          fr: "I need strong English support everywhere",
          ja: "I need strong English support everywhere",
          ko: "업무와 일상생활 전반에 영어 지원이 필요해요",
        },
      },
      {
        emoji: "🌐",
        id: "multilingual_mix",
        scores: { cosmopolitan: 2, cultural: 1 },
        text: {
          cn: "Happy in global hubs",
          en: "Happy in global hubs with multiple languages spoken",
          es: "Happy in global hubs",
          fr: "Happy in global hubs",
          ja: "Happy in global hubs",
          ko: "여러 언어가 공존하는 글로벌 허브가 좋아요",
        },
      },
      {
        emoji: "📚",
        id: "local_immersion",
        scores: { cultural: 3, mediterranean: 2 },
        text: {
          cn: "I want to dive deep into the local language",
          en: "I want to dive deep into the local language",
          es: "I want to dive deep into the local language",
          fr: "I want to dive deep into the local language",
          ja: "I want to dive deep into the local language",
          ko: "현지 언어와 문화를 깊게 배우고 싶어요",
        },
      },
      {
        emoji: "🧠",
        id: "language_challenge",
        scores: { mountainous: 1, nordic: 1 },
        text: {
          cn: "I enjoy a language challenge",
          en: "I enjoy a language challenge",
          es: "I enjoy a language challenge",
          fr: "I enjoy a language challenge",
          ja: "I enjoy a language challenge",
          ko: "매력적인 문화라면 어려운 언어도 좋아요",
        },
      },
    ],
    text: {
      cn: "How much local language support do you need?",
      en: "How much local language support do you need day to day?",
      es: "How much local language support do you need?",
      fr: "How much local language support do you need?",
      ja: "How much local language support do you need?",
      ko: "일상에서 어느 정도의 현지어 지원이 필요하나요?",
    },
  },
  {
    emoji: "🔮",
    id: "future",
    options: [
      {
        emoji: "🏡",
        id: "family_roots",
        scores: { cultural: 2, mediterranean: 3 },
        text: {
          cn: "Settling down with community roots",
          en: "Settling down with deep community and family roots",
          es: "Settling down with community roots",
          fr: "Settling down with community roots",
          ja: "Settling down with community roots",
          ko: "깊은 공동체 속에서 가족과 함께 정착",
        },
      },
      {
        emoji: "💼",
        id: "career_acceleration",
        scores: { cosmopolitan: 3, modern: 2 },
        text: {
          cn: "Fast-tracking career",
          en: "Fast-tracking my career and building a global network",
          es: "Fast-tracking career",
          fr: "Fast-tracking career",
          ja: "Fast-tracking career",
          ko: "커리어를 빠르게 발전시키고 글로벌 네트워크 구축",
        },
      },
      {
        emoji: "🧘‍♀️",
        id: "slow_living",
        scores: { mountainous: 2, nordic: 2, tropical: 1 },
        text: {
          cn: "Designing a slower life",
          en: "Designing a slower, wellness-focused life close to nature",
          es: "Designing a slower life",
          fr: "Designing a slower life",
          ja: "Designing a slower life",
          ko: "자연과 가까운 곳에서 느린 삶",
        },
      },
      {
        emoji: "✈️",
        id: "global_nomad",
        scores: { coastal: 2, modern: 1 },
        text: {
          cn: "Staying mobile as a digital nomad",
          en: "Staying mobile as a digital nomad",
          es: "Staying mobile as a digital nomad",
          fr: "Staying mobile as a digital nomad",
          ja: "Staying mobile as a digital nomad",
          ko: "디지털 노마드로서 유연하게 생활",
        },
      },
    ],
    text: {
      cn: "What future vision are you planning toward?",
      en: "What future vision are you planning toward?",
      es: "What future vision are you planning toward?",
      fr: "What future vision are you planning toward?",
      ja: "What future vision are you planning toward?",
      ko: "앞으로 어떤 삶의 방향을 그리고 있나요?",
    },
  },
  {
    emoji: "🥂",
    id: "social_activity",
    options: [
      {
        emoji: "🌃",
        id: "vibrant_nightlife",
        scores: { cosmopolitan: 3, mediterranean: 1 },
        text: {
          cn: "Vibrant nightlife",
          en: "Exploring vibrant nightlife, bars, and events",
          es: "Vibrant nightlife",
          fr: "Vibrant nightlife",
          ja: "Vibrant nightlife",
          ko: "활기찬 밤문화, 바, 이벤트 탐방",
        },
      },
      {
        emoji: "🍻",
        id: "cozy_gatherings",
        scores: { cultural: 2, nordic: 3 },
        text: {
          cn: "Cozy gatherings",
          en: "Cozy gatherings with close friends",
          es: "Cozy gatherings",
          fr: "Cozy gatherings",
          ja: "Cozy gatherings",
          ko: "가까운 친구들과 아늑한 모임",
        },
      },
      {
        emoji: "🖼️",
        id: "cultural_events",
        scores: { cultural: 3, modern: 1 },
        text: {
          cn: "Cultural events",
          en: "Attending concerts, theater, or gallery openings",
          es: "Cultural events",
          fr: "Cultural events",
          ja: "Cultural events",
          ko: "콘서트, 연극, 갤러리 참석",
        },
      },
      {
        emoji: "🌳",
        id: "outdoor_evenings",
        scores: { coastal: 3, mountainous: 1, tropical: 2 },
        text: {
          cn: "Relaxed evenings outdoors",
          en: "Relaxed evenings outdoors, bonfires or picnics",
          es: "Relaxed evenings outdoors",
          fr: "Relaxed evenings outdoors",
          ja: "Relaxed evenings outdoors",
          ko: "해변의 모닥불이나 공원 피크닉",
        },
      },
    ],
    text: {
      cn: "What is your ideal social evening?",
      en: "What is your ideal social evening?",
      es: "What is your ideal social evening?",
      fr: "What is your ideal social evening?",
      ja: "What is your ideal social evening?",
      ko: "이상적인 저녁 사교 활동은 무엇인가요?",
    },
  },
];

export const COUNTRIES_DATABASE: Record<string, CountryProfile> = {
  canada: {
    bestFor: [
      { en: "Families", ko: "가족" },
      { en: "Nature Lovers", ko: "자연 애호가" },
    ],
    climate: {
      cn: "Cold winters",
      en: "Cold winters",
      es: "Cold winters",
      fr: "Cold winters",
      ja: "Cold winters",
      ko: "추운 겨울",
    },
    cons: [
      { en: "Cold winters", ko: "추운 겨울" },
      { en: "High housing costs", ko: "높은 주거비" },
    ],
    continent: "North America",
    currency: "CAD",
    flag: "🇨🇦",
    language: ["English", "French"],
    metrics: {
      costOfLiving: "High",
      healthcare: 8.8,
      internetSpeed: 150,
      qualityOfLife: 9.0,
      safety: 9.0,
    },
    name: {
      cn: "Canada",
      en: "Canada",
      es: "Canada",
      fr: "Canada",
      ja: "Canada",
      ko: "캐나다",
    },
    population: "38m",
    pros: [
      { en: "Welcoming society", ko: "환영하는 사회" },
      { en: "Nature", ko: "대자연" },
    ],
    vibe: {
      cn: "Multicultural",
      en: "Multicultural, vast, polite",
      es: "Multicultural",
      fr: "Multicultural",
      ja: "Multicultural",
      ko: "다문화적이고 광대한",
    },
  },
  italy: {
    bestFor: [
      { en: "Foodies", ko: "미식가" },
      { en: "Artists", ko: "예술가" },
    ],
    climate: {
      cn: "Mediterranean",
      en: "Mediterranean",
      es: "Mediterranean",
      fr: "Mediterranean",
      ja: "Mediterranean",
      ko: "지중해성",
    },
    cons: [
      { en: "Bureaucracy", ko: "관료주의" },
      { en: "Economic instability", ko: "경제적 불안정" },
    ],
    continent: "Europe",
    currency: "EUR",
    flag: "🇮🇹",
    language: ["Italian"],
    metrics: {
      costOfLiving: "Medium",
      healthcare: 8.5,
      internetSpeed: 60,
      qualityOfLife: 8.2,
      safety: 8.0,
    },
    name: {
      cn: "Italy",
      en: "Italy",
      es: "Italy",
      fr: "Italy",
      ja: "Italy",
      ko: "이탈리아",
    },
    population: "59m",
    pros: [
      { en: "World-renowned cuisine", ko: "세계적인 요리" },
      { en: "Incomparable art & history", ko: "예술과 역사" },
    ],
    vibe: {
      cn: "Historic",
      en: "Historic, passionate, and delicious",
      es: "Historic",
      fr: "Historic",
      ja: "Historic",
      ko: "역사적이고 열정적인",
    },
  },
  japan: {
    bestFor: [
      { en: "Foodies", ko: "미식가" },
      { en: "Tech Lovers", ko: "기술 애호가" },
    ],
    climate: {
      cn: "Four seasons",
      en: "Four seasons",
      es: "Four seasons",
      fr: "Four seasons",
      ja: "Four seasons",
      ko: "사계절",
    },
    cons: [
      { en: "Work culture", ko: "직장 문화" },
      { en: "Language barrier", ko: "언어 장벽" },
    ],
    continent: "Asia",
    currency: "JPY",
    flag: "🇯🇵",
    language: ["Japanese"],
    metrics: {
      costOfLiving: "High",
      healthcare: 9.3,
      internetSpeed: 180,
      qualityOfLife: 8.8,
      safety: 9.7,
    },
    name: {
      cn: "Japan",
      en: "Japan",
      es: "Japan",
      fr: "Japan",
      ja: "Japan",
      ko: "일본",
    },
    population: "125m",
    pros: [
      { en: "Safety", ko: "치안" },
      { en: "Food & Culture", ko: "음식과 문화" },
    ],
    vibe: {
      cn: "Traditional",
      en: "Traditional, modern, orderly",
      es: "Traditional",
      fr: "Traditional",
      ja: "Traditional",
      ko: "전통과 현대의 조화",
    },
  },
  norway: {
    bestFor: [
      { en: "Nature Lovers", ko: "자연 애호가" },
      { en: "Families", ko: "가족" },
    ],
    climate: {
      cn: "Cold winters",
      en: "Cold winters, mild summers",
      es: "Cold winters",
      fr: "Cold winters",
      ja: "Cold winters",
      ko: "추운 겨울, 온화한 여름",
    },
    cons: [
      { en: "Extremely high cost of living", ko: "극도로 높은 생활비" },
      { en: "Cold winters", ko: "추운 겨울" },
    ],
    continent: "Europe",
    currency: "NOK",
    flag: "🇳🇴",
    language: ["Norwegian", "English"],
    metrics: {
      costOfLiving: "Very High",
      healthcare: 9.2,
      internetSpeed: 100,
      qualityOfLife: 9.5,
      safety: 9.8,
    },
    name: {
      cn: "Norway",
      en: "Norway",
      es: "Norway",
      fr: "Norway",
      ja: "Norway",
      ko: "노르웨이",
    },
    population: "5.4m",
    pros: [
      { en: "Exceptional work-life balance", ko: "뛰어난 워라밸" },
      { en: "Stunning natural beauty", ko: "멋진 자연 경관" },
    ],
    vibe: {
      cn: "Peaceful, majestic",
      en: "Peaceful, majestic, and expensive",
      es: "Peaceful, majestic",
      fr: "Peaceful, majestic",
      ja: "Peaceful, majestic",
      ko: "평화롭고, 장엄하며, 물가가 비싼",
    },
  },
  singapore: {
    bestFor: [
      { en: "Finance Pros", ko: "금융 전문가" },
      { en: "Families", ko: "가족" },
    ],
    climate: {
      cn: "Tropical",
      en: "Tropical",
      es: "Tropical",
      fr: "Tropical",
      ja: "Tropical",
      ko: "열대",
    },
    cons: [
      { en: "Expensive", ko: "비쌈" },
      { en: "Humidity", ko: "습도" },
    ],
    continent: "Asia",
    currency: "SGD",
    flag: "🇸🇬",
    language: ["English", "Mandarin"],
    metrics: {
      costOfLiving: "Very High",
      healthcare: 8.9,
      internetSpeed: 250,
      qualityOfLife: 9.0,
      safety: 9.8,
    },
    name: {
      cn: "Singapore",
      en: "Singapore",
      es: "Singapore",
      fr: "Singapore",
      ja: "Singapore",
      ko: "싱가포르",
    },
    population: "5.9m",
    pros: [
      { en: "Safety & Cleanliness", ko: "안전과 청결" },
      { en: "Global Hub", ko: "글로벌 허브" },
    ],
    vibe: {
      cn: "Modern",
      en: "Modern, efficient, multicultural",
      es: "Modern",
      fr: "Modern",
      ja: "Modern",
      ko: "현대적이고 효율적인",
    },
  },
  sweden: {
    bestFor: [
      { en: "Tech Pros", ko: "기술 전문가" },
      { en: "Designers", ko: "디자이너" },
    ],
    climate: {
      cn: "Cold winters",
      en: "Cold winters, pleasant summers",
      es: "Cold winters",
      fr: "Cold winters",
      ja: "Cold winters",
      ko: "추운 겨울, 쾌적한 여름",
    },
    cons: [
      { en: "High taxes", ko: "높은 세금" },
      { en: "Dark winters", ko: "어두운 겨울" },
    ],
    continent: "Europe",
    currency: "SEK",
    flag: "🇸🇪",
    language: ["Swedish", "English"],
    metrics: {
      costOfLiving: "High",
      healthcare: 9.0,
      internetSpeed: 120,
      qualityOfLife: 9.2,
      safety: 9.5,
    },
    name: {
      cn: "Sweden",
      en: "Sweden",
      es: "Sweden",
      fr: "Sweden",
      ja: "Sweden",
      ko: "스웨덴",
    },
    population: "10.4m",
    pros: [
      { en: "Tech and innovation hub", ko: "기술 혁신 허브" },
      { en: "Strong social benefits", ko: "강력한 사회 보장" },
    ],
    vibe: {
      cn: "Innovative",
      en: "Innovative, stylish, and reserved",
      es: "Innovative",
      fr: "Innovative",
      ja: "Innovative",
      ko: "혁신적이고 스타일리시한",
    },
  },
  thailand: {
    bestFor: [
      { en: "Digital Nomads", ko: "디지털 노마드" },
      { en: "Budget Travelers", ko: "저예산 여행자" },
    ],
    climate: {
      cn: "Tropical",
      en: "Tropical",
      es: "Tropical",
      fr: "Tropical",
      ja: "Tropical",
      ko: "열대",
    },
    cons: [
      { en: "Hot and humid", ko: "고온 다습" },
      { en: "Traffic", ko: "교통 체증" },
    ],
    continent: "Asia",
    currency: "THB",
    flag: "🇹🇭",
    language: ["Thai"],
    metrics: {
      costOfLiving: "Low",
      healthcare: 7.8,
      internetSpeed: 200,
      qualityOfLife: 7.5,
      safety: 7.6,
    },
    name: {
      cn: "Thailand",
      en: "Thailand",
      es: "Thailand",
      fr: "Thailand",
      ja: "Thailand",
      ko: "태국",
    },
    population: "70m",
    pros: [
      { en: "Low cost of living", ko: "저렴한 생활비" },
      { en: "Delicious food", ko: "맛있는 음식" },
    ],
    vibe: {
      cn: "Vibrant",
      en: "Vibrant, spiritual, budget-friendly",
      es: "Vibrant",
      fr: "Vibrant",
      ja: "Vibrant",
      ko: "활기차고 영적인",
    },
  },
};
