export enum EarthlyBranch {
  CHUK = "CHUK",
  HAE = "HAE",
  IN = "IN",
  JA = "JA",
  JIN = "JIN",
  MI = "MI",
  MYO = "MYO",
  O = "O",
  SA = "SA",
  SIN = "SIN",
  SUL = "SUL",
  YU = "YU",
}
export enum FiveElement {
  EARTH = "EARTH",
  FIRE = "FIRE",
  METAL = "METAL",
  WATER = "WATER",
  WOOD = "WOOD",
}

export enum HeavenlyStem {
  BYEONG = "BYEONG",
  EUL = "EUL",
  GAP = "GAP",
  GI = "GI",
  GYE = "GYE",
  GYEONG = "GYEONG",
  IM = "IM",
  JEONG = "JEONG",
  MU = "MU",
  SIN = "SIN",
}

export enum YinYang {
  YANG = "YANG",
  YIN = "YIN",
}

export interface StemBranchDetail {
  characteristicsKey: string;
  element: FiveElement;
  id: string;
  meaningKey: string;
  nameKey: string;
  yinYang: YinYang;
}

export const HEAVENLY_STEMS: Record<HeavenlyStem, StemBranchDetail> = {
  [HeavenlyStem.BYEONG]: {
    characteristicsKey: "ontology.saju.stems.BYEONG.characteristics",
    element: FiveElement.FIRE,
    id: HeavenlyStem.BYEONG,
    meaningKey: "ontology.saju.stems.BYEONG.meaning",
    nameKey: "ontology.saju.stems.BYEONG.name",
    yinYang: YinYang.YANG,
  },
  [HeavenlyStem.EUL]: {
    characteristicsKey: "ontology.saju.stems.EUL.characteristics",
    element: FiveElement.WOOD,
    id: HeavenlyStem.EUL,
    meaningKey: "ontology.saju.stems.EUL.meaning",
    nameKey: "ontology.saju.stems.EUL.name",
    yinYang: YinYang.YIN,
  },
  [HeavenlyStem.GAP]: {
    characteristicsKey: "ontology.saju.stems.GAP.characteristics",
    element: FiveElement.WOOD,
    id: HeavenlyStem.GAP,
    meaningKey: "ontology.saju.stems.GAP.meaning",
    nameKey: "ontology.saju.stems.GAP.name",
    yinYang: YinYang.YANG,
  },
  [HeavenlyStem.GI]: {
    characteristicsKey: "ontology.saju.stems.GI.characteristics",
    element: FiveElement.EARTH,
    id: HeavenlyStem.GI,
    meaningKey: "ontology.saju.stems.GI.meaning",
    nameKey: "ontology.saju.stems.GI.name",
    yinYang: YinYang.YIN,
  },
  [HeavenlyStem.GYE]: {
    characteristicsKey: "ontology.saju.stems.GYE.characteristics",
    element: FiveElement.WATER,
    id: HeavenlyStem.GYE,
    meaningKey: "ontology.saju.stems.GYE.meaning",
    nameKey: "ontology.saju.stems.GYE.name",
    yinYang: YinYang.YIN,
  },
  [HeavenlyStem.GYEONG]: {
    characteristicsKey: "ontology.saju.stems.GYEONG.characteristics",
    element: FiveElement.METAL,
    id: HeavenlyStem.GYEONG,
    meaningKey: "ontology.saju.stems.GYEONG.meaning",
    nameKey: "ontology.saju.stems.GYEONG.name",
    yinYang: YinYang.YANG,
  },
  [HeavenlyStem.IM]: {
    characteristicsKey: "ontology.saju.stems.IM.characteristics",
    element: FiveElement.WATER,
    id: HeavenlyStem.IM,
    meaningKey: "ontology.saju.stems.IM.meaning",
    nameKey: "ontology.saju.stems.IM.name",
    yinYang: YinYang.YANG,
  },
  [HeavenlyStem.JEONG]: {
    characteristicsKey: "ontology.saju.stems.JEONG.characteristics",
    element: FiveElement.FIRE,
    id: HeavenlyStem.JEONG,
    meaningKey: "ontology.saju.stems.JEONG.meaning",
    nameKey: "ontology.saju.stems.JEONG.name",
    yinYang: YinYang.YIN,
  },
  [HeavenlyStem.MU]: {
    characteristicsKey: "ontology.saju.stems.MU.characteristics",
    element: FiveElement.EARTH,
    id: HeavenlyStem.MU,
    meaningKey: "ontology.saju.stems.MU.meaning",
    nameKey: "ontology.saju.stems.MU.name",
    yinYang: YinYang.YANG,
  },
  [HeavenlyStem.SIN]: {
    characteristicsKey: "ontology.saju.stems.SIN.characteristics",
    element: FiveElement.METAL,
    id: HeavenlyStem.SIN,
    meaningKey: "ontology.saju.stems.SIN.meaning",
    nameKey: "ontology.saju.stems.SIN.name",
    yinYang: YinYang.YIN,
  },
};

export const EARTHLY_BRANCHES: Record<
  EarthlyBranch,
  StemBranchDetail & { animalKey: string; seasonKey: string; timeKey: string }
> = {
  [EarthlyBranch.CHUK]: {
    animalKey: "ontology.saju.branches.CHUK.animal",
    characteristicsKey: "ontology.saju.branches.CHUK.characteristics",
    element: FiveElement.EARTH,
    id: EarthlyBranch.CHUK,
    meaningKey: "ontology.saju.branches.CHUK.meaning",
    nameKey: "ontology.saju.branches.CHUK.name",
    seasonKey: "ontology.saju.branches.CHUK.season",
    timeKey: "ontology.saju.branches.CHUK.time",
    yinYang: YinYang.YIN,
  },
  [EarthlyBranch.HAE]: {
    animalKey: "ontology.saju.branches.HAE.animal",
    characteristicsKey: "ontology.saju.branches.HAE.characteristics",
    element: FiveElement.WATER,
    id: EarthlyBranch.HAE,
    meaningKey: "ontology.saju.branches.HAE.meaning",
    nameKey: "ontology.saju.branches.HAE.name",
    seasonKey: "ontology.saju.branches.HAE.season",
    timeKey: "ontology.saju.branches.HAE.time",
    yinYang: YinYang.YIN,
  },
  [EarthlyBranch.IN]: {
    animalKey: "ontology.saju.branches.IN.animal",
    characteristicsKey: "ontology.saju.branches.IN.characteristics",
    element: FiveElement.WOOD,
    id: EarthlyBranch.IN,
    meaningKey: "ontology.saju.branches.IN.meaning",
    nameKey: "ontology.saju.branches.IN.name",
    seasonKey: "ontology.saju.branches.IN.season",
    timeKey: "ontology.saju.branches.IN.time",
    yinYang: YinYang.YANG,
  },
  [EarthlyBranch.JA]: {
    animalKey: "ontology.saju.branches.JA.animal",
    characteristicsKey: "ontology.saju.branches.JA.characteristics",
    element: FiveElement.WATER,
    id: EarthlyBranch.JA,
    meaningKey: "ontology.saju.branches.JA.meaning",
    nameKey: "ontology.saju.branches.JA.name",
    seasonKey: "ontology.saju.branches.JA.season",
    timeKey: "ontology.saju.branches.JA.time",
    yinYang: YinYang.YANG,
  },
  [EarthlyBranch.JIN]: {
    animalKey: "ontology.saju.branches.JIN.animal",
    characteristicsKey: "ontology.saju.branches.JIN.characteristics",
    element: FiveElement.EARTH,
    id: EarthlyBranch.JIN,
    meaningKey: "ontology.saju.branches.JIN.meaning",
    nameKey: "ontology.saju.branches.JIN.name",
    seasonKey: "ontology.saju.branches.JIN.season",
    timeKey: "ontology.saju.branches.JIN.time",
    yinYang: YinYang.YANG,
  },
  [EarthlyBranch.MI]: {
    animalKey: "ontology.saju.branches.MI.animal",
    characteristicsKey: "ontology.saju.branches.MI.characteristics",
    element: FiveElement.EARTH,
    id: EarthlyBranch.MI,
    meaningKey: "ontology.saju.branches.MI.meaning",
    nameKey: "ontology.saju.branches.MI.name",
    seasonKey: "ontology.saju.branches.MI.season",
    timeKey: "ontology.saju.branches.MI.time",
    yinYang: YinYang.YIN,
  },
  [EarthlyBranch.MYO]: {
    animalKey: "ontology.saju.branches.MYO.animal",
    characteristicsKey: "ontology.saju.branches.MYO.characteristics",
    element: FiveElement.WOOD,
    id: EarthlyBranch.MYO,
    meaningKey: "ontology.saju.branches.MYO.meaning",
    nameKey: "ontology.saju.branches.MYO.name",
    seasonKey: "ontology.saju.branches.MYO.season",
    timeKey: "ontology.saju.branches.MYO.time",
    yinYang: YinYang.YIN,
  },
  [EarthlyBranch.O]: {
    animalKey: "ontology.saju.branches.O.animal",
    characteristicsKey: "ontology.saju.branches.O.characteristics",
    element: FiveElement.FIRE,
    id: EarthlyBranch.O,
    meaningKey: "ontology.saju.branches.O.meaning",
    nameKey: "ontology.saju.branches.O.name",
    seasonKey: "ontology.saju.branches.O.season",
    timeKey: "ontology.saju.branches.O.time",
    yinYang: YinYang.YANG,
  },
  [EarthlyBranch.SA]: {
    animalKey: "ontology.saju.branches.SA.animal",
    characteristicsKey: "ontology.saju.branches.SA.characteristics",
    element: FiveElement.FIRE,
    id: EarthlyBranch.SA,
    meaningKey: "ontology.saju.branches.SA.meaning",
    nameKey: "ontology.saju.branches.SA.name",
    seasonKey: "ontology.saju.branches.SA.season",
    timeKey: "ontology.saju.branches.SA.time",
    yinYang: YinYang.YIN,
  },
  [EarthlyBranch.SIN]: {
    animalKey: "ontology.saju.branches.SIN.animal",
    characteristicsKey: "ontology.saju.branches.SIN.characteristics",
    element: FiveElement.METAL,
    id: EarthlyBranch.SIN,
    meaningKey: "ontology.saju.branches.SIN.meaning",
    nameKey: "ontology.saju.branches.SIN.name",
    seasonKey: "ontology.saju.branches.SIN.season",
    timeKey: "ontology.saju.branches.SIN.time",
    yinYang: YinYang.YANG,
  },
  [EarthlyBranch.SUL]: {
    animalKey: "ontology.saju.branches.SUL.animal",
    characteristicsKey: "ontology.saju.branches.SUL.characteristics",
    element: FiveElement.EARTH,
    id: EarthlyBranch.SUL,
    meaningKey: "ontology.saju.branches.SUL.meaning",
    nameKey: "ontology.saju.branches.SUL.name",
    seasonKey: "ontology.saju.branches.SUL.season",
    timeKey: "ontology.saju.branches.SUL.time",
    yinYang: YinYang.YANG,
  },
  [EarthlyBranch.YU]: {
    animalKey: "ontology.saju.branches.YU.animal",
    characteristicsKey: "ontology.saju.branches.YU.characteristics",
    element: FiveElement.METAL,
    id: EarthlyBranch.YU,
    meaningKey: "ontology.saju.branches.YU.meaning",
    nameKey: "ontology.saju.branches.YU.name",
    seasonKey: "ontology.saju.branches.YU.season",
    timeKey: "ontology.saju.branches.YU.time",
    yinYang: YinYang.YIN,
  },
};

export const SIXTY_GANZHI = [
  { branch: EarthlyBranch.JA, stem: HeavenlyStem.GAP },
  { branch: EarthlyBranch.CHUK, stem: HeavenlyStem.EUL },
  { branch: EarthlyBranch.IN, stem: HeavenlyStem.BYEONG },
  { branch: EarthlyBranch.MYO, stem: HeavenlyStem.JEONG },
  { branch: EarthlyBranch.JIN, stem: HeavenlyStem.MU },
  { branch: EarthlyBranch.SA, stem: HeavenlyStem.GI },
  { branch: EarthlyBranch.O, stem: HeavenlyStem.GYEONG },
  { branch: EarthlyBranch.MI, stem: HeavenlyStem.SIN },
  { branch: EarthlyBranch.SIN, stem: HeavenlyStem.IM },
  { branch: EarthlyBranch.YU, stem: HeavenlyStem.GYE },
  { branch: EarthlyBranch.SUL, stem: HeavenlyStem.GAP },
  { branch: EarthlyBranch.HAE, stem: HeavenlyStem.EUL },
  { branch: EarthlyBranch.JA, stem: HeavenlyStem.BYEONG },
  { branch: EarthlyBranch.CHUK, stem: HeavenlyStem.JEONG },
  { branch: EarthlyBranch.IN, stem: HeavenlyStem.MU },
  { branch: EarthlyBranch.MYO, stem: HeavenlyStem.GI },
  { branch: EarthlyBranch.JIN, stem: HeavenlyStem.GYEONG },
  { branch: EarthlyBranch.SA, stem: HeavenlyStem.SIN },
  { branch: EarthlyBranch.O, stem: HeavenlyStem.IM },
  { branch: EarthlyBranch.MI, stem: HeavenlyStem.GYE },
  { branch: EarthlyBranch.SIN, stem: HeavenlyStem.GAP },
  { branch: EarthlyBranch.YU, stem: HeavenlyStem.EUL },
  { branch: EarthlyBranch.SUL, stem: HeavenlyStem.BYEONG },
  { branch: EarthlyBranch.HAE, stem: HeavenlyStem.JEONG },
  { branch: EarthlyBranch.JA, stem: HeavenlyStem.MU },
  { branch: EarthlyBranch.CHUK, stem: HeavenlyStem.GI },
  { branch: EarthlyBranch.IN, stem: HeavenlyStem.GYEONG },
  { branch: EarthlyBranch.MYO, stem: HeavenlyStem.SIN },
  { branch: EarthlyBranch.JIN, stem: HeavenlyStem.IM },
  { branch: EarthlyBranch.SA, stem: HeavenlyStem.GYE },
  { branch: EarthlyBranch.O, stem: HeavenlyStem.GAP },
  { branch: EarthlyBranch.MI, stem: HeavenlyStem.EUL },
  { branch: EarthlyBranch.SIN, stem: HeavenlyStem.BYEONG },
  { branch: EarthlyBranch.YU, stem: HeavenlyStem.JEONG },
  { branch: EarthlyBranch.SUL, stem: HeavenlyStem.MU },
  { branch: EarthlyBranch.HAE, stem: HeavenlyStem.GI },
  { branch: EarthlyBranch.JA, stem: HeavenlyStem.GYEONG },
  { branch: EarthlyBranch.CHUK, stem: HeavenlyStem.SIN },
  { branch: EarthlyBranch.IN, stem: HeavenlyStem.IM },
  { branch: EarthlyBranch.MYO, stem: HeavenlyStem.GYE },
  { branch: EarthlyBranch.JIN, stem: HeavenlyStem.GAP },
  { branch: EarthlyBranch.SA, stem: HeavenlyStem.EUL },
  { branch: EarthlyBranch.O, stem: HeavenlyStem.BYEONG },
  { branch: EarthlyBranch.MI, stem: HeavenlyStem.JEONG },
  { branch: EarthlyBranch.SIN, stem: HeavenlyStem.MU },
  { branch: EarthlyBranch.YU, stem: HeavenlyStem.GI },
  { branch: EarthlyBranch.SUL, stem: HeavenlyStem.GYEONG },
  { branch: EarthlyBranch.HAE, stem: HeavenlyStem.SIN },
  { branch: EarthlyBranch.JA, stem: HeavenlyStem.IM },
  { branch: EarthlyBranch.CHUK, stem: HeavenlyStem.GYE },
  { branch: EarthlyBranch.IN, stem: HeavenlyStem.GAP },
  { branch: EarthlyBranch.MYO, stem: HeavenlyStem.EUL },
  { branch: EarthlyBranch.JIN, stem: HeavenlyStem.BYEONG },
  { branch: EarthlyBranch.SA, stem: HeavenlyStem.JEONG },
  { branch: EarthlyBranch.O, stem: HeavenlyStem.MU },
  { branch: EarthlyBranch.MI, stem: HeavenlyStem.GI },
  { branch: EarthlyBranch.SIN, stem: HeavenlyStem.GYEONG },
  { branch: EarthlyBranch.YU, stem: HeavenlyStem.SIN },
  { branch: EarthlyBranch.SUL, stem: HeavenlyStem.IM },
  { branch: EarthlyBranch.HAE, stem: HeavenlyStem.GYE },
];

export const ELEMENT_TRAITS = {
  [FiveElement.EARTH]: {
    keywordsKey: "ontology.saju.elements.EARTH.keywords",
    nameKey: "ontology.saju.elements.EARTH.name",
    strengthsKey: "ontology.saju.elements.EARTH.strengths",
    weaknessesKey: "ontology.saju.elements.EARTH.weaknesses",
  },
  [FiveElement.FIRE]: {
    keywordsKey: "ontology.saju.elements.FIRE.keywords",
    nameKey: "ontology.saju.elements.FIRE.name",
    strengthsKey: "ontology.saju.elements.FIRE.strengths",
    weaknessesKey: "ontology.saju.elements.FIRE.weaknesses",
  },
  [FiveElement.METAL]: {
    keywordsKey: "ontology.saju.elements.METAL.keywords",
    nameKey: "ontology.saju.elements.METAL.name",
    strengthsKey: "ontology.saju.elements.METAL.strengths",
    weaknessesKey: "ontology.saju.elements.METAL.weaknesses",
  },
  [FiveElement.WATER]: {
    keywordsKey: "ontology.saju.elements.WATER.keywords",
    nameKey: "ontology.saju.elements.WATER.name",
    strengthsKey: "ontology.saju.elements.WATER.strengths",
    weaknessesKey: "ontology.saju.elements.WATER.weaknesses",
  },
  [FiveElement.WOOD]: {
    keywordsKey: "ontology.saju.elements.WOOD.keywords",
    nameKey: "ontology.saju.elements.WOOD.name",
    strengthsKey: "ontology.saju.elements.WOOD.strengths",
    weaknessesKey: "ontology.saju.elements.WOOD.weaknesses",
  },
};

export const SAJU_COMPATIBILITY_TRAITS = {
  controlling: {
    descriptionKey:
      "ontology.saju.compatibility.traits.controlling.description",
    titleKey: "ontology.saju.compatibility.traits.controlling.title",
  },
  neutral: {
    descriptionKey: "ontology.saju.compatibility.traits.neutral.description",
    titleKey: "ontology.saju.compatibility.traits.neutral.title",
  },
  same: {
    descriptionKey: "ontology.saju.compatibility.traits.same.description",
    titleKey: "ontology.saju.compatibility.traits.same.title",
  },
  supporting: {
    descriptionKey: "ontology.saju.compatibility.traits.supporting.description",
    titleKey: "ontology.saju.compatibility.traits.supporting.title",
  },
};
