import { LocalizedContent } from "@/types/manifest";

export interface BirthSymbol {
  flower: {
    meaning: LocalizedContent;
    name: LocalizedContent;
  };
  month: number;
  star: {
    // Representative star visible or associated with this time
    constellation: LocalizedContent;
    meaning: LocalizedContent;
    name: LocalizedContent;
  };
  stone: {
    meaning: LocalizedContent;
    name: LocalizedContent;
  };
}

export const FATE_SYMBOLS_DATA: BirthSymbol[] = [
  {
    flower: {
      meaning: {
        cn: "奉献、爱和忠诚。",
        en: "Devotion, love, and loyalty.",
        es: "Devoción, amor y lealtad.",
        fr: "Dévouement, amour et loyauté.",
        ja: "献身、愛、忠誠。",
        ko: "헌신, 사랑, 충성.",
      },
      name: {
        cn: "康乃馨",
        en: "Carnation",
        es: "Clavel",
        fr: "Œillet",
        ja: "カーネーション",
        ko: "카네이션",
      },
    },
    month: 1,
    star: {
      constellation: {
        cn: "大犬座",
        en: "Canis Major",
        es: "Canis Major",
        fr: "Grand Chien",
        ja: "おおいぬ座",
        ko: "큰개자리",
      },
      meaning: {
        cn: "最亮的星，象征精神激情。",
        en: "The brightest star, symbolizing spiritual passion.",
        es: "La estrella más brillante, que simboliza la pasión espiritual.",
        fr: "L'étoile la plus brillante, symbolisant la passion spirituelle.",
        ja: "最も明るい星、精神的な情熱を象徴。",
        ko: "가장 밝은 별, 영적인 열정을 상징.",
      },
      name: {
        cn: "天狼星",
        en: "Sirius",
        es: "Sirio",
        fr: "Sirius",
        ja: "シリウス",
        ko: "시리우스",
      },
    },
    stone: {
      meaning: {
        cn: "保护、友谊和信任。",
        en: "Protection, friendship, and trust.",
        es: "Protección, amistad y confianza.",
        fr: "Protection, amitié et confiance.",
        ja: "保護、友情、信頼。",
        ko: "보호, 우정, 신뢰.",
      },
      name: {
        cn: "石榴石",
        en: "Garnet",
        es: "Granate",
        fr: "Grenat",
        ja: "ガーネット",
        ko: "가넷 (석류석)",
      },
    },
  },
  {
    flower: {
      meaning: {
        cn: "谦虚、忠诚和美德。",
        en: "Modesty, faithfulness, and virtue.",
        es: "Modestia, fidelidad y virtud.",
        fr: "Modestie, fidélité et vertu.",
        ja: "謙虚、誠実、美徳。",
        ko: "겸손, 성실, 미덕.",
      },
      name: {
        cn: "紫罗兰",
        en: "Violet",
        es: "Violeta",
        fr: "Violette",
        ja: "スミレ",
        ko: "제비꽃",
      },
    },
    month: 2,
    star: {
      constellation: {
        cn: "船底座",
        en: "Carina",
        es: "Carina",
        fr: "Carène",
        ja: "りゅうこつ座",
        ko: "용골자리",
      },
      meaning: {
        cn: "导航之星，象征指引。",
        en: "The navigator's star, symbolizing guidance.",
        es: "La estrella del navegante, que simboliza la guía.",
        fr: "L'étoile du navigateur, symbolisant le guide.",
        ja: "航海士の星、導きを象徴。",
        ko: "항해사의 별, 인도를 상징.",
      },
      name: {
        cn: "老人星",
        en: "Canopus",
        es: "Canopus",
        fr: "Canopus",
        ja: "カノープス",
        ko: "카노푸스",
      },
    },
    stone: {
      meaning: {
        cn: "智慧、治愈和清晰。",
        en: "Wisdom, healing, and clarity.",
        es: "Sabiduría, curación y claridad.",
        fr: "Sagesse, guérison et clarté.",
        ja: "知恵、癒し、明晰さ。",
        ko: "지혜, 치유, 명료함.",
      },
      name: {
        cn: "紫水晶",
        en: "Amethyst",
        es: "Amatista",
        fr: "Améthyste",
        ja: "アメジスト",
        ko: "자수정",
      },
    },
  },
  {
    flower: {
      meaning: {
        cn: "重生、新的开始和希望。",
        en: "Rebirth, new beginnings, and hope.",
        es: "Renacimiento, nuevos comienzos y esperanza.",
        fr: "Renaissance, nouveaux départs et espoir.",
        ja: "再生、新しい始まり、希望。",
        ko: "부활, 새로운 시작, 희망.",
      },
      name: {
        cn: "水仙",
        en: "Daffodil",
        es: "Narciso",
        fr: "Jonquille",
        ja: "ラッパスイセン",
        ko: "수선화",
      },
    },
    month: 3,
    star: {
      constellation: {
        cn: "牧夫座",
        en: "Boötes",
        es: "Boyero",
        fr: "Bouvier",
        ja: "うしかい座",
        ko: "목동자리",
      },
      meaning: {
        cn: "守护熊，象征保护。",
        en: "The guardian bear, symbolizing protection.",
        es: "El oso guardián, que simboliza la protección.",
        fr: "L'ours gardien, symbolisant la protection.",
        ja: "守護する熊、保護を象徴。",
        ko: "수호 곰, 보호를 상징.",
      },
      name: {
        cn: "大角星",
        en: "Arcturus",
        es: "Arturo",
        fr: "Arcturus",
        ja: "アークトゥルス",
        ko: "아크투루스",
      },
    },
    stone: {
      meaning: {
        cn: "宁静、勇气和青春。",
        en: "Serenity, courage, and youth.",
        es: "Serenidad, coraje y juventud.",
        fr: "Sérénité, courage et jeunesse.",
        ja: "静けさ、勇気、若さ。",
        ko: "평온, 용기, 젊음.",
      },
      name: {
        cn: "海蓝宝",
        en: "Aquamarine",
        es: "Aguamarina",
        fr: "Aigue-marine",
        ja: "アクアマリン",
        ko: "아쿠아마린",
      },
    },
  },
  {
    flower: {
      meaning: {
        cn: "天真、纯洁和真爱。",
        en: "Innocence, purity, and true love.",
        es: "Inocencia, pureza y amor verdadero.",
        fr: "Innocence, pureté et véritable amour.",
        ja: "無邪気、純粋、真実の愛。",
        ko: "순수, 청결, 진정한 사랑.",
      },
      name: {
        cn: "雏菊",
        en: "Daisy",
        es: "Margarita",
        fr: "Pâquerette",
        ja: "ヒナギク",
        ko: "데이지",
      },
    },
    month: 4,
    star: {
      constellation: {
        cn: "金牛座",
        en: "Taurus",
        es: "Tauro",
        fr: "Taureau",
        ja: "おうし座",
        ko: "황소자리",
      },
      meaning: {
        cn: "公牛之眼，象征坚持。",
        en: "The eye of the bull, symbolizing persistence.",
        es: "El ojo del toro, que simboliza la persistencia.",
        fr: "L'œil du taureau, symbolisant la persistance.",
        ja: "雄牛の目、粘り強さを象徴。",
        ko: "황소의 눈, 끈기를 상징.",
      },
      name: {
        cn: "毕宿五",
        en: "Aldebaran",
        es: "Aldebarán",
        fr: "Aldébaran",
        ja: "アルデバラン",
        ko: "알데바란",
      },
    },
    stone: {
      meaning: {
        cn: "永恒的爱、力量和光辉。",
        en: "Eternal love, strength, and brilliance.",
        es: "Amor eterno, fuerza y brillo.",
        fr: "Amour éternel, force et éclat.",
        ja: "永遠の愛、強さ、輝き。",
        ko: "영원한 사랑, 힘, 광채.",
      },
      name: {
        cn: "钻石",
        en: "Diamond",
        es: "Diamante",
        fr: "Diamant",
        ja: "ダイヤモンド",
        ko: "다이아몬드",
      },
    },
  },
  {
    flower: {
      meaning: {
        cn: "谦逊、甜蜜和幸福的回归。",
        en: "Humility, sweetness, and return of happiness.",
        es: "Humildad, dulzura y retorno de la felicidad.",
        fr: "Humilité, douceur et retour du bonheur.",
        ja: "謙虚、甘さ、幸福の再来。",
        ko: "겸손, 달콤함, 행복의 귀환.",
      },
      name: {
        cn: "铃兰",
        en: "Lily of the Valley",
        es: "Lirio de los valles",
        fr: "Muguet",
        ja: "スズラン",
        ko: "은방울꽃",
      },
    },
    month: 5,
    star: {
      constellation: {
        cn: "御夫座",
        en: "Auriga",
        es: "Auriga",
        fr: "Cocher",
        ja: "ぎょしゃ座",
        ko: "마차부자리",
      },
      meaning: {
        cn: "山羊星，象征滋养丰富。",
        en: "The goat star, symbolizing nurturing abundance.",
        es: "La estrella de la cabra, que simboliza la abundancia nutritiva.",
        fr: "L'étoile de la chèvre, symbolisant l'abondance nourricière.",
        ja: "ヤギの星、豊かな育みを象徴。",
        ko: "염소 별,풍요로운 양육을 상징.",
      },
      name: {
        cn: "五车二",
        en: "Capella",
        es: "Capella",
        fr: "Capella",
        ja: "カペラ",
        ko: "카펠라",
      },
    },
    stone: {
      meaning: {
        cn: "生育、重生和爱。",
        en: "Fertility, rebirth, and love.",
        es: "Fertilidad, renacimiento y amor.",
        fr: "Fertilité, renaissance et amour.",
        ja: "肥沃、再生、愛。",
        ko: "다산, 부활, 사랑.",
      },
      name: {
        cn: "祖母绿",
        en: "Emerald",
        es: "Esmeralda",
        fr: "Émeraude",
        ja: "エメラルド",
        ko: "에메랄드",
      },
    },
  },
  {
    flower: {
      meaning: {
        cn: "爱、激情和美。",
        en: "Love, passion, and beauty.",
        es: "Amor, pasión y belleza.",
        fr: "Amour, passion et beauté.",
        ja: "愛、情熱、美。",
        ko: "사랑, 열정, 아름다움.",
      },
      name: {
        cn: "玫瑰",
        en: "Rose",
        es: "Rosa",
        fr: "Rose",
        ja: "バラ",
        ko: "장미",
      },
    },
    month: 6,
    star: {
      constellation: {
        cn: "猎户座",
        en: "Orion",
        es: "Orión",
        fr: "Orion",
        ja: "オリオン座",
        ko: "오리온자리",
      },
      meaning: {
        cn: "巨人之手，象征力量。",
        en: "The hand of the giant, symbolizing strength.",
        es: "La mano del gigante, que simboliza la fuerza.",
        fr: "La main du géant, symbolisant la force.",
        ja: "巨人の手、強さを象徴。",
        ko: "거인의 손, 힘을 상징.",
      },
      name: {
        cn: "参宿四",
        en: "Betelgeuse",
        es: "Betelgeuse",
        fr: "Bételgeuse",
        ja: "ベテルギウス",
        ko: "베텔게우스",
      },
    },
    stone: {
      meaning: {
        cn: "纯洁、正直和通过经验获得的智慧。",
        en: "Purity, integrity, and wisdom acquired through experience.",
        es: "Pureza, integridad y sabiduría adquirida a través de la experiencia.",
        fr: "Pureté, intégrité et sagesse acquise par l'expérience.",
        ja: "純粋、誠実、経験を通じて得た知恵。",
        ko: "순수, 성실, 경험을 통해 얻은 지혜.",
      },
      name: {
        cn: "珍珠",
        en: "Pearl",
        es: "Perla",
        fr: "Perle",
        ja: "真珠",
        ko: "진주",
      },
    },
  },
  {
    flower: {
      meaning: {
        cn: "轻盈、轻浮和爱的纽带。",
        en: "Lightness, levity, and strong bond of love.",
        es: "Ligereza, frivolidad y fuerte lazo de amor.",
        fr: "Légèreté, frivolité et lien d'amour fort.",
        ja: "軽快さ、浮気心、愛の強い絆。",
        ko: "경쾌함, 경솔, 사랑의 강한 유대.",
      },
      name: {
        cn: "飞燕草",
        en: "Larkspur",
        es: "Espuela de caballero",
        fr: "Pied-d'alouette",
        ja: "ヒエンソウ",
        ko: "제비고깔",
      },
    },
    month: 7,
    star: {
      constellation: {
        cn: "小犬座",
        en: "Canis Minor",
        es: "Canis Minor",
        fr: "Petit Chien",
        ja: "こいぬ座",
        ko: "작은개자리",
      },
      meaning: {
        cn: "犬前星，象征准备。",
        en: "Before the dog, symbolizing preparation.",
        es: "Antes del perro, que simboliza la preparación.",
        fr: "Avant le chien, symbolisant la préparation.",
        ja: "犬の前、準備を象徴。",
        ko: "개의 앞, 준비를 상징.",
      },
      name: {
        cn: "南河三",
        en: "Procyon",
        es: "Procyon",
        fr: "Procyon",
        ja: "プロキオン",
        ko: "프로키온",
      },
    },
    stone: {
      meaning: {
        cn: "激情、保护和繁荣。",
        en: "Passion, protection, and prosperity.",
        es: "Pasión, protección y prosperidad.",
        fr: "Passion, protection et prospérité.",
        ja: "情熱、保護、繁栄。",
        ko: "열정, 보호, 번영.",
      },
      name: {
        cn: "红宝石",
        en: "Ruby",
        es: "Rubí",
        fr: "Rubis",
        ja: "ルビー",
        ko: "루비",
      },
    },
  },
  {
    flower: {
      meaning: {
        cn: "性格的力量、真诚和正直。",
        en: "Strength of character, sincerity, and integrity.",
        es: "Fuerza de carácter, sinceridad e integridad.",
        fr: "Force de caractère, sincérité et intégrité.",
        ja: "人格の強さ、誠実、高潔。",
        ko: "성격의 강함, 성실, 정직.",
      },
      name: {
        cn: "剑兰",
        en: "Gladiolus",
        es: "Gladiolo",
        fr: "Glaïeul",
        ja: "グラジオラス",
        ko: "글라디올러스",
      },
    },
    month: 8,
    star: {
      constellation: {
        cn: "狮子座",
        en: "Leo",
        es: "Leo",
        fr: "Lion",
        ja: "しし座",
        ko: "사자자리",
      },
      meaning: {
        cn: "狮子之心，象征皇权。",
        en: "The heart of the lion, symbolizing royalty.",
        es: "El corazón del león, que simboliza la realeza.",
        fr: "Le cœur du lion, symbolisant la royauté.",
        ja: "ライオンの心臓、王権を象徴。",
        ko: "사자의 심장, 왕권을 상징.",
      },
      name: {
        cn: "轩辕十四",
        en: "Regulus",
        es: "Regulus",
        fr: "Régulus",
        ja: "レグルス",
        ko: "레굴루스",
      },
    },
    stone: {
      meaning: {
        cn: "力量、保护和治愈。",
        en: "Strength, protection, and healing.",
        es: "Fuerza, protección y curación.",
        fr: "Force, protection et guérison.",
        ja: "強さ、保護、癒し。",
        ko: "힘, 보호, 치유.",
      },
      name: {
        cn: "橄榄石",
        en: "Peridot",
        es: "Peridoto",
        fr: "Péridot",
        ja: "ペリドット",
        ko: "페리도트",
      },
    },
  },
  {
    flower: {
      meaning: {
        cn: "智慧、勇气和信仰。",
        en: "Wisdom, valor, and faith.",
        es: "Sabiduría, valor y fe.",
        fr: "Sagesse, vaillance et foi.",
        ja: "知恵、勇気、信仰。",
        ko: "지혜, 용맹, 믿음.",
      },
      name: {
        cn: "紫宛",
        en: "Aster",
        es: "Aster",
        fr: "Aster",
        ja: "アスター",
        ko: "과꽃",
      },
    },
    month: 9,
    star: {
      constellation: {
        cn: "室女座",
        en: "Virgo",
        es: "Virgo",
        fr: "Vierge",
        ja: "おとめ座",
        ko: "처녀자리",
      },
      meaning: {
        cn: "谷穗，象征丰收。",
        en: "The ear of grain, symbolizing harvest.",
        es: "La espiga de grano, que simboliza la cosecha.",
        fr: "L'épi de blé, symbolisant la moisson.",
        ja: "穀物の穂、収穫を象徴。",
        ko: "곡식의 이삭, 수확을 상징.",
      },
      name: {
        cn: "角宿一",
        en: "Spica",
        es: "Espiga",
        fr: "Spica",
        ja: "スピカ",
        ko: "스피카",
      },
    },
    stone: {
      meaning: {
        cn: "智慧、美德和好运。",
        en: "Wisdom, virtue, and good fortune.",
        es: "Sabiduría, virtud y buena fortuna.",
        fr: "Sagesse, vertu et bonne fortune.",
        ja: "知恵、美徳、幸運。",
        ko: "지혜, 미덕, 행운.",
      },
      name: {
        cn: "蓝宝石",
        en: "Sapphire",
        es: "Zafiro",
        fr: "Saphir",
        ja: "サファイア",
        ko: "사파이어",
      },
    },
  },
  {
    flower: {
      meaning: {
        cn: "激情、创造力和温暖。",
        en: "Passion, creativity, and warmth.",
        es: "Pasión, creatividad y calidez.",
        fr: "Passion, créativité et chaleur.",
        ja: "情熱、創造性、暖かさ。",
        ko: "열정, 창의성, 따뜻함.",
      },
      name: {
        cn: "万寿菊",
        en: "Marigold",
        es: "Caléndula",
        fr: "Souci",
        ja: "マリーゴールド",
        ko: "메리골드 (금잔화)",
      },
    },
    month: 10,
    star: {
      constellation: {
        cn: "天蝎座",
        en: "Scorpius",
        es: "Escorpio",
        fr: "Scorpion",
        ja: "さそり座",
        ko: "전갈자리",
      },
      meaning: {
        cn: "火星的对手，象征强烈。",
        en: "The rival of Mars, symbolizing intensity.",
        es: "El rival de Marte, que simboliza la intensidad.",
        fr: "Le rival de Mars, symbolisant l'intensité.",
        ja: "火星のライバル、激しさを象徴。",
        ko: "화성의 라이벌, 강렬함을 상징.",
      },
      name: {
        cn: "心宿二",
        en: "Antares",
        es: "Antares",
        fr: "Antarès",
        ja: "アンタレス",
        ko: "안타레스",
      },
    },
    stone: {
      meaning: {
        cn: "创造力、灵感和希望。",
        en: "Creativity, inspiration, and hope.",
        es: "Creatividad, inspiración y esperanza.",
        fr: "Créativité, inspiration et espoir.",
        ja: "創造性、インスピレーション、希望。",
        ko: "창의성, 영감, 희망.",
      },
      name: {
        cn: "蛋白石",
        en: "Opal",
        es: "Ópalo",
        fr: "Opale",
        ja: "オパール",
        ko: "오팔",
      },
    },
  },
  {
    flower: {
      meaning: {
        cn: "忠诚、诚实和乐观。",
        en: "Loyalty, honesty, and optimism.",
        es: "Lealtad, honestidad y optimismo.",
        fr: "Loyauté, honnêteté et optimisme.",
        ja: "忠誠、正直、楽観主義。",
        ko: "충성, 정직, 낙관주의.",
      },
      name: {
        cn: "菊花",
        en: "Chrysanthemum",
        es: "Crisantemo",
        fr: "Chrysanthème",
        ja: "菊",
        ko: "국화",
      },
    },
    month: 11,
    star: {
      constellation: {
        cn: "南鱼座",
        en: "Piscis Austrinus",
        es: "Piscis Austrinus",
        fr: "Poisson austral",
        ja: "みなみのうお座",
        ko: "남쪽물고기자리",
      },
      meaning: {
        cn: "南方的观察者，象征魔法。",
        en: " The watcher of the south, symbolizing magic.",
        es: "El vigilante del sur, que simboliza la magia.",
        fr: "Le gardien du sud, symbolisant la magie.",
        ja: "南の監視者、魔法を象徴。",
        ko: "남쪽의 감시자, 마법을 상징.",
      },
      name: {
        cn: "北落师门",
        en: "Fomalhaut",
        es: "Fomalhaut",
        fr: "Fomalhaut",
        ja: "フォーマルハウト",
        ko: "포말하우트",
      },
    },
    stone: {
      meaning: {
        cn: "爱、亲情和好运。",
        en: "Love, affection, and good luck.",
        es: "Amor, afecto y buena suerte.",
        fr: "Amour, affection et bonne chance.",
        ja: "愛、愛情、幸運。",
        ko: "사랑, 애정, 행운.",
      },
      name: {
        cn: "黄玉",
        en: "Topaz",
        es: "Topacio",
        fr: "Topaze",
        ja: "トパーズ",
        ko: "토파즈",
      },
    },
  },
  {
    flower: {
      meaning: {
        cn: "尊重、谦虚和忠诚。",
        en: "Respect, modesty, and faithfulness.",
        es: "Respeto, modestia y fidelidad.",
        fr: "Respect, modestie et fidélité.",
        ja: "尊敬、謙虚、誠実。",
        ko: "존경, 겸손, 성실.",
      },
      name: {
        cn: "水仙",
        en: "Narcissus",
        es: "Narciso",
        fr: "Narcisse",
        ja: "スイセン",
        ko: "수선화 (나르시스)",
      },
    },
    month: 12,
    star: {
      constellation: {
        cn: "天琴座",
        en: "Lyra",
        es: "Lyra",
        fr: "Lyre",
        ja: "こと座",
        ko: "거문고자리",
      },
      meaning: {
        cn: "坠落的鹰，象征艺术天赋。",
        en: "The falling eagle, symbolizing artistic talent.",
        es: "El águila que cae, que simboliza el talento artístico.",
        fr: "L'aigle tombant, symbolisant le talent artistique.",
        ja: "落ちる鷲、芸術的才能を象徴。",
        ko: "떨어지는 독수리, 예술적 재능을 상징.",
      },
      name: {
        cn: "织女星",
        en: "Vega",
        es: "Vega",
        fr: "Véga",
        ja: "ベガ",
        ko: "베가 (직녀성)",
      },
    },
    stone: {
      meaning: {
        cn: "智慧、宁静和保护。",
        en: "Wisdom, tranquility, and protection.",
        es: "Sabiduría, tranquilidad y protección.",
        fr: "Sagesse, tranquillité et protection.",
        ja: "知恵、静けさ、保護。",
        ko: "지혜, 평온, 보호.",
      },
      name: {
        cn: "绿松石",
        en: "Turquoise",
        es: "Turquesa",
        fr: "Turquoise",
        ja: "ターコイズ",
        ko: "터키석",
      },
    },
  },
];
