import type { CountryPreferenceType as _CountryPreferenceType } from "./types";

export const COUNTRY_PREFERENCE_QUESTIONS = {
  en: [
    {
      emoji: "🌤️",
      id: "climate",
      options: [
        {
          emoji: "❄️",
          id: "cold_crisp",
          scores: { modern: 1, mountainous: 2, nordic: 3 },
          text: "Cold, crisp winters with mild summers",
        },
        {
          emoji: "☀️",
          id: "warm_sunny",
          scores: { coastal: 2, mediterranean: 3, tropical: 2 },
          text: "Warm, sunny weather most of the year",
        },
        {
          emoji: "🌴",
          id: "hot_humid",
          scores: { coastal: 1, tropical: 3 },
          text: "Hot and humid with lush greenery",
        },
        {
          emoji: "🍂",
          id: "four_seasons",
          scores: { cosmopolitan: 1, cultural: 2, modern: 2 },
          text: "Four distinct seasons with variety",
        },
      ],
      text: "What type of climate do you thrive in?",
    },
    {
      emoji: "⏰",
      id: "lifestyle",
      options: [
        {
          emoji: "🧘",
          id: "slow_mindful",
          scores: { mediterranean: 2, mountainous: 2, nordic: 3, tropical: 2 },
          text: "Slow, mindful living with strong work-life balance",
        },
        {
          emoji: "🏃",
          id: "fast_dynamic",
          scores: { cosmopolitan: 3, modern: 3 },
          text: "Fast-paced, dynamic urban energy",
        },
        {
          emoji: "👥",
          id: "community_social",
          scores: { cultural: 3, mediterranean: 3, tropical: 1 },
          text: "Community-focused with strong social bonds",
        },
        {
          emoji: "🆓",
          id: "independent_flexible",
          scores: { cosmopolitan: 2, modern: 2, mountainous: 1 },
          text: "Independent with flexible routines and remote work",
        },
      ],
      text: "What lifestyle pace appeals to you most?",
    },
    {
      emoji: "🗺️",
      id: "geography",
      options: [
        {
          emoji: "⛰️",
          id: "mountains_forests",
          scores: { mountainous: 3, nordic: 2 },
          text: "Majestic mountains and pristine forests",
        },
        {
          emoji: "🏖️",
          id: "coastline_beaches",
          scores: { coastal: 3, mediterranean: 2, tropical: 2 },
          text: "Beautiful coastlines and pristine beaches",
        },
        {
          emoji: "🏙️",
          id: "urban_skylines",
          scores: { cosmopolitan: 3, modern: 3 },
          text: "Impressive skylines and urban landscapes",
        },
        {
          emoji: "🌾",
          id: "rolling_countryside",
          scores: { cultural: 3, mediterranean: 1 },
          text: "Rolling hills and peaceful countryside",
        },
      ],
      text: "Which geographical feature draws you most?",
    },
    {
      emoji: "🎭",
      id: "culture",
      options: [
        {
          emoji: "🚀",
          id: "innovation_progress",
          scores: { cosmopolitan: 2, modern: 3, nordic: 1 },
          text: "Innovation, technology, and progress",
        },
        {
          emoji: "🏛️",
          id: "tradition_heritage",
          scores: { cultural: 3, mediterranean: 2 },
          text: "Rich traditions and cultural heritage",
        },
        {
          emoji: "⚖️",
          id: "equality_welfare",
          scores: { cosmopolitan: 1, nordic: 3 },
          text: "Social equality and strong welfare systems",
        },
        {
          emoji: "🌍",
          id: "diversity_fusion",
          scores: { cosmopolitan: 3, modern: 1, tropical: 1 },
          text: "Cultural diversity and a melting pot of ideas",
        },
      ],
      text: "What cultural aspect is most important to you?",
    },
    {
      emoji: "🍽️",
      id: "food_cuisine",
      options: [
        {
          emoji: "🐟",
          id: "simple_fresh",
          scores: { coastal: 2, mediterranean: 1, nordic: 2 },
          text: "Simple, fresh, high-quality ingredients",
        },
        {
          emoji: "🥘",
          id: "complex_flavorful",
          scores: { cultural: 3, mediterranean: 2 },
          text: "Complex flavors and rich culinary traditions",
        },
        {
          emoji: "🌮",
          id: "fusion_international",
          scores: { cosmopolitan: 3, modern: 1, tropical: 1 },
          text: "International fusion and diverse street food",
        },
        {
          emoji: "🥬",
          id: "organic_sustainable",
          scores: { mountainous: 1, nordic: 2 },
          text: "Organic, sustainable, and locally sourced",
        },
      ],
      text: "What type of cuisine excites you most?",
    },
    {
      emoji: "🏛️",
      id: "social_system",
      options: [
        {
          emoji: "🏥",
          id: "universal_healthcare",
          scores: { cultural: 1, nordic: 3 },
          text: "Universal healthcare and strong public services",
        },
        {
          emoji: "💼",
          id: "entrepreneurial_freedom",
          scores: { cosmopolitan: 3, modern: 2 },
          text: "Entrepreneurial freedom and economic opportunities",
        },
        {
          emoji: "👨‍👩‍👧‍👦",
          id: "family_community",
          scores: { cultural: 2, mediterranean: 3 },
          text: "Strong family ties and tight-knit community support",
        },
        {
          emoji: "🌱",
          id: "environmental_protection",
          scores: { mountainous: 2, nordic: 3, tropical: 1 },
          text: "Strict environmental protection and sustainability focus",
        },
      ],
      text: "What social system do you value most?",
    },
    {
      emoji: "🏠",
      id: "housing",
      options: [
        {
          emoji: "🏢",
          id: "minimalist_functional",
          scores: { modern: 2, nordic: 3 },
          text: "Minimalist, functional, and well-designed (e.g., Scandinavian)",
        },
        {
          emoji: "🏘️",
          id: "charming_historical",
          scores: { cultural: 3, mediterranean: 2 },
          text: "Charming historical buildings with character",
        },
        {
          emoji: "🌲",
          id: "nature_integrated",
          scores: { coastal: 2, mountainous: 3, tropical: 2 },
          text: "Integrated with natural surroundings (e.g., cabin, beach house)",
        },
        {
          emoji: "🏗️",
          id: "high_tech_modern",
          scores: { cosmopolitan: 2, modern: 3 },
          text: "High-tech smart homes with ultra-modern amenities",
        },
      ],
      text: "What type of living environment appeals to you?",
    },
    {
      emoji: "🚲",
      id: "transportation",
      options: [
        {
          emoji: "🚴",
          id: "cycling_walking",
          scores: { coastal: 1, nordic: 3 },
          text: "Cycling and walking in bike-friendly cities",
        },
        {
          emoji: "🚇",
          id: "public_transport",
          scores: { cosmopolitan: 2, cultural: 1, modern: 3 },
          text: "Efficient, clean, and modern public transportation",
        },
        {
          emoji: "🚗",
          id: "car_flexibility",
          scores: { cosmopolitan: 1, mountainous: 2 },
          text: "Personal car for maximum flexibility and road trips",
        },
        {
          emoji: "⛵",
          id: "boat_water",
          scores: { coastal: 3, mediterranean: 1, tropical: 1 },
          text: "Boats, ferries, and water-based transportation",
        },
      ],
      text: "How do you prefer to get around?",
    },
    {
      emoji: "💸",
      id: "budget",
      options: [
        {
          emoji: "🪙",
          id: "budget_guardian",
          scores: { mediterranean: 1, tropical: 3 },
          text: "Keep expenses minimal, even if amenities are simple",
        },
        {
          emoji: "⚖️",
          id: "balanced_value",
          scores: { coastal: 1, cultural: 2 },
          text: "Balanced costs with reliable public services and good value",
        },
        {
          emoji: "💎",
          id: "premium_quality",
          scores: { cosmopolitan: 1, modern: 2, nordic: 3 },
          text: "Invest more for world-class infrastructure and quality of life",
        },
        {
          emoji: "📈",
          id: "growth_hub",
          scores: { cosmopolitan: 3, modern: 2 },
          text: "Higher costs are fine if career and growth opportunities are abundant",
        },
      ],
      text: "Which cost of living trade-off feels right for you?",
    },
    {
      emoji: "🗣️",
      id: "language",
      options: [
        {
          emoji: "🗽",
          id: "english_primary",
          scores: { cosmopolitan: 3, modern: 2 },
          text: "I need strong English support everywhere for work and daily life",
        },
        {
          emoji: "🌐",
          id: "multilingual_mix",
          scores: { cosmopolitan: 2, cultural: 1 },
          text: "Happy in global hubs with multiple languages spoken",
        },
        {
          emoji: "📚",
          id: "local_immersion",
          scores: { cultural: 3, mediterranean: 2 },
          text: "I want to dive deep into the local language and customs",
        },
        {
          emoji: "🧠",
          id: "language_challenge",
          scores: { mountainous: 1, nordic: 1 },
          text: "I enjoy a language challenge if the culture is inspiring",
        },
      ],
      text: "How much local language support do you need day to day?",
    },
    {
      emoji: "💼",
      id: "career",
      options: [
        {
          emoji: "🚀",
          id: "innovation_tech",
          scores: { cosmopolitan: 2, modern: 3 },
          text: "Thriving in a major innovation and tech ecosystem",
        },
        {
          emoji: "🎨",
          id: "creative_culture",
          scores: { cultural: 3, mediterranean: 2 },
          text: "Growing in a vibrant creative, arts, and culinary scene",
        },
        {
          emoji: "🌱",
          id: "green_sustainability",
          scores: { mountainous: 2, nordic: 3 },
          text: "Working in sustainability, green energy, or outdoor industries",
        },
        {
          emoji: "🏝️",
          id: "hospitality_tourism",
          scores: { coastal: 3, tropical: 2 },
          text: "Building a career in hospitality, tourism, or remote work",
        },
      ],
      text: "Which career landscape excites you the most?",
    },
    {
      emoji: "🔮",
      id: "future",
      options: [
        {
          emoji: "🏡",
          id: "family_roots",
          scores: { cultural: 2, mediterranean: 3 },
          text: "Settling down with deep community and family roots",
        },
        {
          emoji: "💼",
          id: "career_acceleration",
          scores: { cosmopolitan: 3, modern: 2 },
          text: "Fast-tracking my career and building a global network",
        },
        {
          emoji: "🧘‍♀️",
          id: "slow_living",
          scores: { mountainous: 2, nordic: 2, tropical: 1 },
          text: "Designing a slower, wellness-focused life close to nature",
        },
        {
          emoji: "✈️",
          id: "global_nomad",
          scores: { coastal: 2, modern: 1 },
          text: "Staying mobile as a digital nomad with global opportunities",
        },
      ],
      text: "What future vision are you planning toward?",
    },
    {
      emoji: "🥂",
      id: "social_activity",
      options: [
        {
          emoji: "🌃",
          id: "vibrant_nightlife",
          scores: { cosmopolitan: 3, mediterranean: 1 },
          text: "Exploring vibrant nightlife, bars, and late-night events",
        },
        {
          emoji: "🍻",
          id: "cozy_gatherings",
          scores: { cultural: 2, nordic: 3 },
          text: "Cozy gatherings with close friends at home or a local pub",
        },
        {
          emoji: "🖼️",
          id: "cultural_events",
          scores: { cultural: 3, modern: 1 },
          text: "Attending concerts, theater, or gallery openings",
        },
        {
          emoji: "🌳",
          id: "outdoor_evenings",
          scores: { coastal: 3, mountainous: 1, tropical: 2 },
          text: "Relaxed evenings outdoors, like beach bonfires or park picnics",
        },
      ],
      text: "What is your ideal social evening?",
    },
    {
      emoji: "⚖️",
      id: "risk_tolerance",
      options: [
        {
          emoji: "🛡️",
          id: "stability_first",
          scores: { modern: 2, nordic: 3 },
          text: "I prioritize stability, safety, and predictable systems",
        },
        {
          emoji: "🎢",
          id: "embrace_chaos",
          scores: { cosmopolitan: 2, tropical: 1 },
          text: "I thrive in dynamic, sometimes chaotic, but exciting environments",
        },
        {
          emoji: "🧭",
          id: "balanced_risk",
          scores: { coastal: 2, cultural: 1 },
          text: "I like a balance - stable society with room for adventure",
        },
        {
          emoji: "🏰",
          id: "tradition_stability",
          scores: { cultural: 3, mediterranean: 2 },
          text: "I find comfort in the stability of long-standing traditions",
        },
      ],
      text: "How do you feel about stability vs. unpredictability?",
    },
    {
      emoji: "🏙️",
      id: "urban_density",
      options: [
        {
          emoji: "🌆",
          id: "bustling_metropolis",
          scores: { cosmopolitan: 3, modern: 2 },
          text: "A bustling, dense metropolis where everything is at my doorstep",
        },
        {
          emoji: "🏞️",
          id: "spacious_city",
          scores: { coastal: 1, nordic: 3 },
          text: "A well-designed, spacious city with plenty of green space",
        },
        {
          emoji: "🏘️",
          id: "charming_town",
          scores: { cultural: 3, mediterranean: 2 },
          text: "A smaller, charming town with a strong sense of community",
        },
        {
          emoji: "🏕️",
          id: "remote_nature",
          scores: { mountainous: 3, tropical: 1 },
          text: "Living remotely, surrounded by nature and few people",
        },
      ],
      text: "What is your ideal population density?",
    },
    {
      emoji: "🧘‍♂️",
      id: "work_life_balance",
      options: [
        {
          emoji: "🕰️",
          id: "strict_separation",
          scores: { cultural: 1, nordic: 3 },
          text: "Very important. Work is for work, personal time is sacred.",
        },
        {
          emoji: "💻",
          id: "flexible_integration",
          scores: { coastal: 1, modern: 2 },
          text: "I prefer flexibility to integrate work and life, like a digital nomad.",
        },
        {
          emoji: "🍻",
          id: "social_work",
          scores: { cosmopolitan: 2, mediterranean: 1 },
          text: "I enjoy when my work and social life blend together.",
        },
        {
          emoji: "❤️‍🔥",
          id: "passion_driven",
          scores: { cosmopolitan: 1, modern: 1 },
          text: "If I love my work, I don't mind it blending into my personal time.",
        },
      ],
      text: "How important is a clear separation between work and personal life?",
    },
  ],
  ko: [
    {
      emoji: "🌤️",
      id: "climate",
      options: [
        {
          emoji: "❄️",
          id: "cold_crisp",
          scores: { modern: 1, mountainous: 2, nordic: 3 },
          text: "춥고 상쾌한 겨울과 온화한 여름",
        },
        {
          emoji: "☀️",
          id: "warm_sunny",
          scores: { coastal: 2, mediterranean: 3, tropical: 2 },
          text: "일년 내내 따뜻하고 화창한 날씨",
        },
        {
          emoji: "🌴",
          id: "hot_humid",
          scores: { coastal: 1, tropical: 3 },
          text: "덥고 습하며 푸른 녹음이 우거진 곳",
        },
        {
          emoji: "🍂",
          id: "four_seasons",
          scores: { cosmopolitan: 1, cultural: 2, modern: 2 },
          text: "뚜렷한 사계절이 있는 곳",
        },
      ],
      text: "어떤 기후에서 가장 잘 지낼 수 있나요?",
    },
    {
      emoji: "⏰",
      id: "lifestyle",
      options: [
        {
          emoji: "🧘",
          id: "slow_mindful",
          scores: { mediterranean: 2, mountainous: 2, nordic: 3, tropical: 2 },
          text: "느리고 여유로운 삶과 확실한 워라밸",
        },
        {
          emoji: "🏃",
          id: "fast_dynamic",
          scores: { cosmopolitan: 3, modern: 3 },
          text: "빠른 속도의 역동적인 도시 생활",
        },
        {
          emoji: "👥",
          id: "community_social",
          scores: { cultural: 3, mediterranean: 3, tropical: 1 },
          text: "공동체 중심의 강한 사회적 유대감",
        },
        {
          emoji: "🆓",
          id: "independent_flexible",
          scores: { cosmopolitan: 2, modern: 2, mountainous: 1 },
          text: "독립적이고 유연한 일상과 원격 근무",
        },
      ],
      text: "어떤 생활 패턴이 가장 매력적인가요?",
    },
    {
      emoji: "🗺️",
      id: "geography",
      options: [
        {
          emoji: "⛰️",
          id: "mountains_forests",
          scores: { mountainous: 3, nordic: 2 },
          text: "장엄한 산맥과 울창한 숲",
        },
        {
          emoji: "🏖️",
          id: "coastline_beaches",
          scores: { coastal: 3, mediterranean: 2, tropical: 2 },
          text: "아름다운 해안선과 깨끗한 해변",
        },
        {
          emoji: "🏙️",
          id: "urban_skylines",
          scores: { cosmopolitan: 3, modern: 3 },
          text: "인상적인 스카이라인과 도시 경관",
        },
        {
          emoji: "🌾",
          id: "rolling_countryside",
          scores: { cultural: 3, mediterranean: 1 },
          text: "완만한 언덕과 평화로운 시골",
        },
      ],
      text: "어떤 지형적 특징이 가장 매력적인가요?",
    },
    {
      emoji: "🎭",
      id: "culture",
      options: [
        {
          emoji: "🚀",
          id: "innovation_progress",
          scores: { cosmopolitan: 2, modern: 3, nordic: 1 },
          text: "혁신, 기술, 그리고 발전",
        },
        {
          emoji: "🏛️",
          id: "tradition_heritage",
          scores: { cultural: 3, mediterranean: 2 },
          text: "풍부한 전통과 문화 유산",
        },
        {
          emoji: "⚖️",
          id: "equality_welfare",
          scores: { cosmopolitan: 1, nordic: 3 },
          text: "사회적 평등과 강력한 복지 시스템",
        },
        {
          emoji: "🌍",
          id: "diversity_fusion",
          scores: { cosmopolitan: 3, modern: 1, tropical: 1 },
          text: "문화적 다양성과 아이디어의 용광로",
        },
      ],
      text: "가장 중요하게 생각하는 문화적 요소는 무엇인가요?",
    },
    {
      emoji: "🍽️",
      id: "food_cuisine",
      options: [
        {
          emoji: "🐟",
          id: "simple_fresh",
          scores: { coastal: 2, mediterranean: 1, nordic: 2 },
          text: "간단하고 신선한 고품질 재료",
        },
        {
          emoji: "🥘",
          id: "complex_flavorful",
          scores: { cultural: 3, mediterranean: 2 },
          text: "복잡한 맛과 풍부한 요리 전통",
        },
        {
          emoji: "🌮",
          id: "fusion_international",
          scores: { cosmopolitan: 3, modern: 1, tropical: 1 },
          text: "다양한 길거리 음식과 인터내셔널 퓨전",
        },
        {
          emoji: "🥬",
          id: "organic_sustainable",
          scores: { mountainous: 1, nordic: 2 },
          text: "유기농, 지속가능한, 지역 생산 식재료",
        },
      ],
      text: "어떤 종류의 요리가 가장 흥미로운가요?",
    },
    {
      emoji: "🏛️",
      id: "social_system",
      options: [
        {
          emoji: "🏥",
          id: "universal_healthcare",
          scores: { cultural: 1, nordic: 3 },
          text: "보편적 의료보험과 강력한 공공 서비스",
        },
        {
          emoji: "💼",
          id: "entrepreneurial_freedom",
          scores: { cosmopolitan: 3, modern: 2 },
          text: "기업가적 자유와 경제적 기회",
        },
        {
          emoji: "👨‍👩‍👧‍👦",
          id: "family_community",
          scores: { cultural: 2, mediterranean: 3 },
          text: "강한 가족 유대와 끈끈한 공동체 지원",
        },
        {
          emoji: "🌱",
          id: "environmental_protection",
          scores: { mountainous: 2, nordic: 3, tropical: 1 },
          text: "엄격한 환경 보호와 지속가능성에 대한 집중",
        },
      ],
      text: "가장 중시하는 사회 제도는 무엇인가요?",
    },
    {
      emoji: "🏠",
      id: "housing",
      options: [
        {
          emoji: "🏢",
          id: "minimalist_functional",
          scores: { modern: 2, nordic: 3 },
          text: "미니멀하고 실용적이며 세련된 디자인 (예: 스칸디나비아)",
        },
        {
          emoji: "🏘️",
          id: "charming_historical",
          scores: { cultural: 3, mediterranean: 2 },
          text: "매력적인 역사적 건물과 특별한 분위기",
        },
        {
          emoji: "🌲",
          id: "nature_integrated",
          scores: { coastal: 2, mountainous: 3, tropical: 2 },
          text: "자연과 조화된 환경 (예: 통나무집, 해변의 집)",
        },
        {
          emoji: "🏗️",
          id: "high_tech_modern",
          scores: { cosmopolitan: 2, modern: 3 },
          text: "최첨단 스마트홈과 초현대적 편의시설",
        },
      ],
      text: "어떤 주거 환경이 가장 매력적인가요?",
    },
    {
      emoji: "🚲",
      id: "transportation",
      options: [
        {
          emoji: "🚴",
          id: "cycling_walking",
          scores: { coastal: 1, nordic: 3 },
          text: "자전거 친화적인 도시에서 사이클링과 걷기",
        },
        {
          emoji: "🚇",
          id: "public_transport",
          scores: { cosmopolitan: 2, cultural: 1, modern: 3 },
          text: "효율적이고 깨끗하며 현대적인 대중교통",
        },
        {
          emoji: "🚗",
          id: "car_flexibility",
          scores: { cosmopolitan: 1, mountainous: 2 },
          text: "최대한의 유연성을 위한 자가용과 도로 여행",
        },
        {
          emoji: "⛵",
          id: "boat_water",
          scores: { coastal: 3, mediterranean: 1, tropical: 1 },
          text: "보트, 페리 등 수상 교통",
        },
      ],
      text: "선호하는 이동 방법은 무엇인가요?",
    },
    {
      emoji: "💸",
      id: "budget",
      options: [
        {
          emoji: "🪙",
          id: "budget_guardian",
          scores: { mediterranean: 1, tropical: 3 },
          text: "편의는 단순해도 생활비를 최소로 유지하고 싶어요",
        },
        {
          emoji: "⚖️",
          id: "balanced_value",
          scores: { coastal: 1, cultural: 2 },
          text: "안정적인 공공서비스와 적당한 비용의 균형을 원해요",
        },
        {
          emoji: "💎",
          id: "premium_quality",
          scores: { cosmopolitan: 1, modern: 2, nordic: 3 },
          text: "세계적인 인프라와 삶의 질을 위해서라면 더 투자할 수 있어요",
        },
        {
          emoji: "📈",
          id: "growth_hub",
          scores: { cosmopolitan: 3, modern: 2 },
          text: "커리어와 성장 기회가 많다면 높은 비용도 감수할 수 있어요",
        },
      ],
      text: "생활비 면에서 어떤 선택이 가장 현실적인가요?",
    },
    {
      emoji: "🗣️",
      id: "language",
      options: [
        {
          emoji: "🗽",
          id: "english_primary",
          scores: { cosmopolitan: 3, modern: 2 },
          text: "업무와 일상생활 전반에 영어 지원이 잘 되는 곳이 필요해요",
        },
        {
          emoji: "🌐",
          id: "multilingual_mix",
          scores: { cosmopolitan: 2, cultural: 1 },
          text: "여러 언어가 공존하는 글로벌 허브 환경이 좋아요",
        },
        {
          emoji: "📚",
          id: "local_immersion",
          scores: { cultural: 3, mediterranean: 2 },
          text: "현지 언어와 문화를 깊게 배우고 싶어요",
        },
        {
          emoji: "🧠",
          id: "language_challenge",
          scores: { mountainous: 1, nordic: 1 },
          text: "매력적인 문화라면 어려운 언어도 도전해보고 싶어요",
        },
      ],
      text: "일상에서 어느 정도의 현지어 지원이 필요하나요?",
    },
    {
      emoji: "💼",
      id: "career",
      options: [
        {
          emoji: "🚀",
          id: "innovation_tech",
          scores: { cosmopolitan: 2, modern: 3 },
          text: "주요 혁신 및 기술 생태계에서 성장하고 싶어요",
        },
        {
          emoji: "🎨",
          id: "creative_culture",
          scores: { cultural: 3, mediterranean: 2 },
          text: "활기찬 창작, 예술, 미식 씬에서 커리어를 쌓고 싶어요",
        },
        {
          emoji: "🌱",
          id: "green_sustainability",
          scores: { mountainous: 2, nordic: 3 },
          text: "지속가능성, 친환경 에너지, 아웃도어 산업에서 일하고 싶어요",
        },
        {
          emoji: "🏝️",
          id: "hospitality_tourism",
          scores: { coastal: 3, tropical: 2 },
          text: "관광, 호스피탈리티 산업 또는 원격 근무로 커리어를 만들고 싶어요",
        },
      ],
      text: "어떤 커리어 환경이 가장 설레나요?",
    },
    {
      emoji: "🔮",
      id: "future",
      options: [
        {
          emoji: "🏡",
          id: "family_roots",
          scores: { cultural: 2, mediterranean: 3 },
          text: "깊은 공동체 속에서 가족과 함께 안정적으로 정착하고 싶어요",
        },
        {
          emoji: "💼",
          id: "career_acceleration",
          scores: { cosmopolitan: 3, modern: 2 },
          text: "커리어를 빠르게 발전시키고 글로벌 네트워크를 쌓고 싶어요",
        },
        {
          emoji: "🧘‍♀️",
          id: "slow_living",
          scores: { mountainous: 2, nordic: 2, tropical: 1 },
          text: "자연과 가까운 곳에서 건강과 균형을 중시하는 느린 삶을 꿈꿔요",
        },
        {
          emoji: "✈️",
          id: "global_nomad",
          scores: { coastal: 2, modern: 1 },
          text: "디지털 노마드로서 전 세계를 무대로 유연하게 살고 싶어요",
        },
      ],
      text: "앞으로 어떤 삶의 방향을 그리고 있나요?",
    },
    {
      emoji: "🥂",
      id: "social_activity",
      options: [
        {
          emoji: "🌃",
          id: "vibrant_nightlife",
          scores: { cosmopolitan: 3, mediterranean: 1 },
          text: "활기찬 밤문화, 바, 심야 이벤트 탐방하기",
        },
        {
          emoji: "🍻",
          id: "cozy_gatherings",
          scores: { cultural: 2, nordic: 3 },
          text: "집이나 동네 술집에서 가까운 친구들과 아늑한 모임 갖기",
        },
        {
          emoji: "🖼️",
          id: "cultural_events",
          scores: { cultural: 3, modern: 1 },
          text: "콘서트, 연극, 갤러리 오프닝 등 문화 행사 참석하기",
        },
        {
          emoji: "🌳",
          id: "outdoor_evenings",
          scores: { coastal: 3, mountainous: 1, tropical: 2 },
          text: "해변의 모닥불이나 공원 피크닉 같은 편안한 야외 저녁",
        },
      ],
      text: "이상적인 저녁 사교 활동은 무엇인가요?",
    },
    {
      emoji: "⚖️",
      id: "risk_tolerance",
      options: [
        {
          emoji: "🛡️",
          id: "stability_first",
          scores: { modern: 2, nordic: 3 },
          text: "안정성, 안전, 예측 가능한 시스템을 최우선으로 생각해요",
        },
        {
          emoji: "🎢",
          id: "embrace_chaos",
          scores: { cosmopolitan: 2, tropical: 1 },
          text: "역동적이고 때로는 혼란스럽지만 흥미로운 환경에서 성장해요",
        },
        {
          emoji: "🧭",
          id: "balanced_risk",
          scores: { coastal: 2, cultural: 1 },
          text: "안정적인 사회와 모험의 여지가 균형을 이루는 것을 좋아해요",
        },
        {
          emoji: "🏰",
          id: "tradition_stability",
          scores: { cultural: 3, mediterranean: 2 },
          text: "오랜 전통이 주는 안정감에서 편안함을 느껴요",
        },
      ],
      text: "안정성과 예측 불가능성에 대해 어떻게 생각하시나요?",
    },
    {
      emoji: "🏙️",
      id: "urban_density",
      options: [
        {
          emoji: "🌆",
          id: "bustling_metropolis",
          scores: { cosmopolitan: 3, modern: 2 },
          text: "문만 열면 모든 것이 있는 북적이는 대도시",
        },
        {
          emoji: "🏞️",
          id: "spacious_city",
          scores: { coastal: 1, nordic: 3 },
          text: "녹지 공간이 충분하고 잘 설계된 여유로운 도시",
        },
        {
          emoji: "🏘️",
          id: "charming_town",
          scores: { cultural: 3, mediterranean: 2 },
          text: "공동체 의식이 강한 작고 매력적인 마을",
        },
        {
          emoji: "🏕️",
          id: "remote_nature",
          scores: { mountainous: 3, tropical: 1 },
          text: "사람이 거의 없는 자연에 둘러싸여 외딴 곳에 사는 것",
        },
      ],
      text: "이상적인 인구 밀도는 어느 정도인가요?",
    },
    {
      emoji: "🧘",
      id: "work_life_balance",
      options: [
        {
          emoji: "🕰️",
          id: "strict_separation",
          scores: { cultural: 1, nordic: 3 },
          text: "매우 중요해요. 일은 일이고, 개인 시간은 신성해요.",
        },
        {
          emoji: "💻",
          id: "flexible_integration",
          scores: { coastal: 1, modern: 2 },
          text: "디지털 노마드처럼 일과 삶을 유연하게 통합하는 것을 선호해요.",
        },
        {
          emoji: "🍻",
          id: "social_work",
          scores: { cosmopolitan: 2, mediterranean: 1 },
          text: "일과 사교 생활이 자연스럽게 어우러지는 것을 즐겨요.",
        },
        {
          emoji: "❤️",
          id: "passion_driven",
          scores: { cosmopolitan: 1, modern: 1 },
          text: "제 일을 사랑한다면, 개인 시간에 일이 들어오는 것은 신경 쓰지 않아요.",
        },
      ],
      text: "일과 개인 생활의 명확한 분리가 얼마나 중요한가요?",
    },
  ],
};

export const COUNTRIES_DATABASE = {
  en: {
    argentina: {
      bestFor: ["Creatives", "Meat Lovers", "Dancers"],
      climate: "Temperate; arid in southeast",
      cons: [
        "Chronic economic instability and high inflation",
        "Bureaucracy is slow and can be unpredictable",
        "Safety is a concern in large cities",
        "Political volatility is a fact of life",
      ],
      continent: "South America",
      currency: "Argentine Peso (ARS)",
      flag: "🇦🇷",
      language: ["Spanish"],
      metrics: {
        costOfLiving: "Low",
        healthcare: 7.9,
        internetSpeed: 35,
        qualityOfLife: 7.5,
        safety: 6.8,
      },
      name: "Argentina",
      population: "45 million",
      pros: [
        "Stunning natural wonders from Patagonia to Iguazu Falls",
        "Vibrant cultural life, especially in Buenos Aires (tango, theater)",
        "European-style architecture and cafe culture",
        "World-famous steak and Malbec wine at affordable prices",
      ],
      vibe: "Passionate, European, and dramatic",
    },
    canada: {
      bestFor: ["Families", "Outdoor Adventurers", "Immigrants"],
      climate: "Four seasons with cold winters",
      cons: [
        "Very cold and long winters in most of the country",
        "High cost of living in major cities like Vancouver and Toronto",
        "Vast distances make domestic travel expensive and time-consuming",
        "Job market can be competitive, especially for newcomers",
      ],
      continent: "North America",
      currency: "Canadian Dollar (CAD)",
      flag: "🇨🇦",
      language: ["English", "French"],
      metrics: {
        costOfLiving: "High",
        healthcare: 8.8,
        internetSpeed: 150,
        qualityOfLife: 9.0,
        safety: 9.0,
      },
      name: "Canada",
      population: "38 million",
      pros: [
        "Welcoming immigration policies and multicultural cities",
        "Universal healthcare system",
        "Vast, stunning natural landscapes from coast to coast",
        "Stable, safe, and tolerant society",
      ],
      vibe: "Multicultural, vast, and polite",
    },
    // Tropical
    costa_rica: {
      bestFor: ["Nature Lovers", "Eco-tourists", "Retirees"],
      climate: "Tropical, year-round warmth",
      cons: [
        "Higher cost of living than other Central American countries",
        "Infrastructure can be challenging, especially roads",
        "Rainy season can be intense (May-Nov)",
        "Petty crime can be an issue in tourist areas",
      ],
      continent: "Central America",
      currency: "Costa Rican Colón (CRC)",
      flag: "🇨🇷",
      language: ["Spanish", "English"],
      metrics: {
        costOfLiving: "Medium",
        healthcare: 7.5,
        internetSpeed: 50,
        qualityOfLife: 8.0,
        safety: 7.8,
      },
      name: "Costa Rica",
      population: "5.1 million",
      pros: [
        "Incredible biodiversity and protected nature reserves",
        '"Pura Vida" (pure life) relaxed lifestyle',
        "Politically stable and has no standing army",
        "Leader in renewable energy",
      ],
      vibe: "Lush, adventurous, and eco-conscious",
    },
    denmark: {
      bestFor: ["Cyclists", "Design Lovers", "Entrepreneurs"],
      climate: "Mild winters, cool summers",
      cons: [
        "One of the highest tax rates in the world",
        "Housing in Copenhagen is expensive and scarce",
        "Often windy and overcast weather",
        "Danish language is notoriously difficult to learn",
      ],
      continent: "Europe",
      currency: "Danish Krone (DKK)",
      flag: "🇩🇰",
      language: ["Danish", "English"],
      metrics: {
        costOfLiving: "Very High",
        healthcare: 9.1,
        internetSpeed: 150,
        qualityOfLife: 9.3,
        safety: 9.4,
      },
      name: "Denmark",
      population: "5.8 million",
      pros: [
        "World-class cycling infrastructure",
        'Emphasis on "hygge" (coziness) and work-life balance',
        "High degree of trust in society and government",
        "Strong startup scene",
      ],
      vibe: "Cozy, progressive, and design-focused",
    },
    // Modern
    germany: {
      bestFor: ["Engineers", "Students", "History Buffs"],
      climate: "Temperate, four seasons",
      cons: [
        "Bureaucracy is notoriously slow and paper-based",
        "German directness can be perceived as rude",
        "Shops are closed on Sundays",
        "High taxes, though they fund strong social services",
      ],
      continent: "Europe",
      currency: "Euro (EUR)",
      flag: "🇩🇪",
      language: ["German"],
      metrics: {
        costOfLiving: "Medium",
        healthcare: 9.2,
        internetSpeed: 100,
        qualityOfLife: 9.1,
        safety: 9.0,
      },
      name: "Germany",
      population: "83 million",
      pros: [
        "Strong economy and leader in engineering/manufacturing",
        "Excellent public transport and central European location",
        "High value on work-life balance and ample vacation time",
        "Affordable (or free) high-quality university education",
      ],
      vibe: "Efficient, historic, and green",
    },
    // New Additions
    ireland: {
      bestFor: ["Tech Professionals", "Writers", "Musicians"],
      climate: "Temperate maritime",
      cons: [
        "High cost of living, especially housing in Dublin",
        "Frequently rainy and overcast weather",
        "Public transport can be unreliable outside of Dublin",
        "Healthcare system faces challenges with long wait times",
      ],
      continent: "Europe",
      currency: "Euro (EUR)",
      flag: "🇮🇪",
      language: ["English", "Irish"],
      metrics: {
        costOfLiving: "High",
        healthcare: 8.0,
        internetSpeed: 90,
        qualityOfLife: 8.7,
        safety: 8.5,
      },
      name: "Ireland",
      population: "5 million",
      pros: [
        'Extremely friendly and welcoming "craic" culture',
        "European hub for many major tech companies",
        "Stunning green landscapes and dramatic coastline",
        "Rich literary and musical history",
      ],
      vibe: "Friendly, historic, and green",
    },
    // Mediterranean
    italy: {
      bestFor: ["Foodies", "History Buffs", "Artists"],
      climate: "Mediterranean, warm summers",
      cons: [
        "Bureaucracy can be slow and frustrating",
        "Economic instability and high youth unemployment",
        "Significant north-south economic divide",
        "Tourist crowds in major cities",
      ],
      continent: "Europe",
      currency: "Euro (EUR)",
      flag: "🇮🇹",
      language: ["Italian"],
      metrics: {
        costOfLiving: "Medium",
        healthcare: 8.5,
        internetSpeed: 60,
        qualityOfLife: 8.2,
        safety: 8.0,
      },
      name: "Italy",
      population: "59 million",
      pros: [
        "World-renowned cuisine and wine",
        "Incomparable art, history, and architecture",
        'Relaxed "La Dolce Vita" lifestyle',
        "Diverse and beautiful landscapes",
      ],
      vibe: "Historic, passionate, and delicious",
    },
    // Cultural
    japan: {
      bestFor: ["Foodies", "Tech Enthusiasts", "Urban Explorers"],
      climate: "Four seasons, varied by region",
      cons: [
        "Significant language barrier; English is not widely spoken",
        "Hierarchical work culture with long hours is common",
        "Can be difficult to integrate into local social circles",
        "High cost of living, especially in Tokyo",
      ],
      continent: "Asia",
      currency: "Japanese Yen (JPY)",
      flag: "🇯🇵",
      language: ["Japanese"],
      metrics: {
        costOfLiving: "High",
        healthcare: 9.3,
        internetSpeed: 180,
        qualityOfLife: 8.8,
        safety: 9.7,
      },
      name: "Japan",
      population: "125 million",
      pros: [
        "Unique blend of deep tradition and futuristic technology",
        "One of the safest countries in the world with low crime",
        "World-class cuisine, from street food to Michelin stars",
        "Incredibly efficient and clean public transportation",
      ],
      vibe: "Traditional, modern, and orderly",
    },
    mexico: {
      bestFor: ["Digital Nomads", "Foodies", "History Lovers"],
      climate: "Varies from tropical to desert",
      cons: [
        "Safety can be a major concern in certain regions",
        "Bureaucracy and corruption can be challenging",
        "Infrastructure and public services are lacking in many areas",
        "Variable internet reliability outside of major cities",
      ],
      continent: "North America",
      currency: "Mexican Peso (MXN)",
      flag: "🇲🇽",
      language: ["Spanish"],
      metrics: {
        costOfLiving: "Low",
        healthcare: 7.2,
        internetSpeed: 40,
        qualityOfLife: 7.0,
        safety: 6.0,
      },
      name: "Mexico",
      population: "126 million",
      pros: [
        "Incredibly rich culture, history, and traditions",
        "World-class cuisine that varies by region",
        "Low cost of living allows for a high quality of life on a budget",
        "Geographically diverse, from deserts to jungles and beaches",
      ],
      vibe: "Colorful, festive, and diverse",
    },
    netherlands: {
      bestFor: ["Cyclists", "Tech Professionals", "International Students"],
      climate: "Temperate, mild summers",
      cons: [
        "High income taxes and cost of living",
        "Persistent housing shortage, making renting difficult",
        "Frequently rainy and overcast weather",
        "Direct Dutch communication style can seem blunt",
      ],
      continent: "Europe",
      currency: "Euro (EUR)",
      flag: "🇳🇱",
      language: ["Dutch", "English"],
      metrics: {
        costOfLiving: "High",
        healthcare: 9.0,
        internetSpeed: 140,
        qualityOfLife: 9.0,
        safety: 9.2,
      },
      name: "Netherlands",
      population: "17.4 million",
      pros: [
        "Excellent work-life balance is culturally ingrained",
        "Highest English proficiency in a non-native country",
        "Liberal, tolerant, and open-minded society",
        "Centrally located in Europe with great travel links",
      ],
      vibe: "Liberal, innovative, and bike-friendly",
    },
    new_zealand: {
      bestFor: ["Adrenaline Junkies", "Nature Photographers", "Remote Workers"],
      climate: "Temperate, mild",
      cons: [
        "Geographically isolated from the rest of the world",
        "Higher cost of living for goods and services",
        "Limited job market and career progression in some sectors",
        "Slower pace of life may not suit everyone",
      ],
      continent: "Oceania",
      currency: "New Zealand Dollar (NZD)",
      flag: "🇳🇿",
      language: ["English", "Māori"],
      metrics: {
        costOfLiving: "High",
        healthcare: 8.7,
        internetSpeed: 95,
        qualityOfLife: 8.9,
        safety: 9.3,
      },
      name: "New Zealand",
      population: "5.1 million",
      pros: [
        "World-class landscapes, from fjords to beaches",
        "Focus on work-life balance and outdoor lifestyle",
        "Friendly, down-to-earth, and welcoming culture",
        "Relatively safe and politically stable",
      ],
      vibe: "Adventurous, laid-back, and stunning",
    },
    // Nordic
    norway: {
      bestFor: ["Nature Lovers", "Families", "Outdoor Enthusiasts"],
      climate: "Cold winters, mild summers",
      cons: [
        "Extremely high cost of living",
        "Long, dark, and cold winters",
        "Reserved social culture can be hard for newcomers",
        "Limited job market outside of specific sectors (oil, tech, marine)",
      ],
      continent: "Europe",
      currency: "Norwegian Krone (NOK)",
      flag: "🇳🇴",
      language: ["Norwegian", "English"],
      metrics: {
        costOfLiving: "Very High",
        healthcare: 9.2,
        internetSpeed: 100,
        qualityOfLife: 9.5,
        safety: 9.8,
      },
      name: "Norway",
      population: "5.4 million",
      pros: [
        "Exceptional work-life balance",
        "Stunning natural beauty (fjords, mountains)",
        "High level of safety and social trust",
        "Strong welfare system",
      ],
      vibe: "Peaceful, majestic, and expensive",
    },
    portugal: {
      bestFor: ["Digital Nomads", "Retirees", "Surfers"],
      climate: "Mediterranean, mild",
      cons: [
        "Lower salaries compared to other EU countries",
        "Bureaucracy can be slow and inefficient",
        "Housing prices in Lisbon and Porto are rising rapidly",
        "Older infrastructure in some rural areas",
      ],
      continent: "Europe",
      currency: "Euro (EUR)",
      flag: "🇵🇹",
      language: ["Portuguese"],
      metrics: {
        costOfLiving: "Medium",
        healthcare: 8.1,
        internetSpeed: 110,
        qualityOfLife: 8.3,
        safety: 8.9,
      },
      name: "Portugal",
      population: "10.3 million",
      pros: [
        "Relatively low cost of living for Western Europe",
        "Beautiful Atlantic coastline and beaches",
        "Friendly, welcoming culture and growing expat community",
        "Favorable visa options for remote workers and retirees",
      ],
      vibe: "Charming, affordable, and coastal",
    },
    // Cosmopolitan
    singapore: {
      bestFor: [
        "Finance Professionals",
        "Expats with Families",
        "Tech Innovators",
      ],
      climate: "Tropical, hot and humid",
      cons: [
        "One of the most expensive cities in the world",
        "Strict laws and regulations (e.g., on speech, chewing gum)",
        "Constantly hot and humid weather",
        "Highly competitive work and school environments",
      ],
      continent: "Asia",
      currency: "Singapore Dollar (SGD)",
      flag: "🇸🇬",
      language: ["English", "Mandarin", "Malay", "Tamil"],
      metrics: {
        costOfLiving: "Very High",
        healthcare: 8.9,
        internetSpeed: 250,
        qualityOfLife: 9.0,
        safety: 9.8,
      },
      name: "Singapore",
      population: "5.9 million",
      pros: [
        "Extremely safe and clean",
        "World-class infrastructure and public transport",
        "Global business and finance hub with high English proficiency",
        "A melting pot of Asian cultures and cuisines",
      ],
      vibe: "Modern, efficient, and multicultural",
    },
    south_korea: {
      bestFor: ["Tech Professionals", "Pop Culture Fans", "Entrepreneurs"],
      climate: "Four seasons, continental",
      cons: [
        "Intense and competitive work and education culture",
        "High social pressure to conform to trends",
        "Significant air pollution, especially in spring",
        "Language barrier can be challenging outside of Seoul",
      ],
      continent: "Asia",
      currency: "South Korean Won (KRW)",
      flag: "🇰🇷",
      language: ["Korean"],
      metrics: {
        costOfLiving: "High",
        healthcare: 8.9,
        internetSpeed: 220,
        qualityOfLife: 8.2,
        safety: 8.8,
      },
      name: "South Korea",
      population: "52 million",
      pros: [
        "World-leading internet speeds and tech infrastructure",
        "Vibrant K-pop, film, and fashion scene",
        'Dynamic "pali-pali" (hurry-hurry) culture gets things done',
        "Safe, with excellent public transport and delicious food",
      ],
      vibe: "Dynamic, trendy, and high-tech",
    },
    spain: {
      bestFor: ["Social Butterflies", "Retirees", "Digital Nomads"],
      climate: "Mediterranean, hot summers",
      cons: [
        "High unemployment rate, especially for youth",
        "Bureaucracy can be slow, especially for residency",
        "Very hot summers in the south",
        "Siesta culture can disrupt business hours",
      ],
      continent: "Europe",
      currency: "Euro (EUR)",
      flag: "🇪🇸",
      language: ["Spanish"],
      metrics: {
        costOfLiving: "Medium",
        healthcare: 8.8,
        internetSpeed: 90,
        qualityOfLife: 8.5,
        safety: 8.2,
      },
      name: "Spain",
      population: "47 million",
      pros: [
        "Affordable cost of living compared to other Western EU countries",
        'Vibrant nightlife and social "tapas" culture',
        "Excellent public healthcare system",
        "Sunny weather and beautiful beaches",
      ],
      vibe: "Vibrant, social, and sunny",
    },
    sweden: {
      bestFor: ["Tech Professionals", "Designers", "Families"],
      climate: "Cold winters, pleasant summers",
      cons: [
        "High income taxes",
        "Competitive job and housing markets, especially in cities",
        "Social circles can be difficult to break into",
        "Long winters with limited daylight",
      ],
      continent: "Europe",
      currency: "Swedish Krona (SEK)",
      flag: "🇸🇪",
      language: ["Swedish", "English"],
      metrics: {
        costOfLiving: "High",
        healthcare: 9.0,
        internetSpeed: 120,
        qualityOfLife: 9.2,
        safety: 9.5,
      },
      name: "Sweden",
      population: "10.4 million",
      pros: [
        "Major hub for tech and innovation (e.g., Spotify)",
        "Strong social benefits and parental leave",
        "Emphasis on sustainability and equality",
        "High English proficiency",
      ],
      vibe: "Innovative, stylish, and reserved",
    },
    // Mountainous
    switzerland: {
      bestFor: ["Finance Professionals", "Outdoor Enthusiasts", "Engineers"],
      climate: "Alpine, cold winters",
      cons: [
        "Extremely high cost of living, among the world's highest",
        "Culture can be perceived as reserved and hard to integrate into",
        "Strict rules and regulations for many aspects of daily life",
        "Stores close early, and there is a quiet social life in many areas",
      ],
      continent: "Europe",
      currency: "Swiss Franc (CHF)",
      flag: "🇨🇭",
      language: ["German", "French", "Italian"],
      metrics: {
        costOfLiving: "Very High",
        healthcare: 9.4,
        internetSpeed: 160,
        qualityOfLife: 9.8,
        safety: 9.9,
      },
      name: "Switzerland",
      population: "8.7 million",
      pros: [
        "Breathtaking Alpine scenery and pristine nature",
        "Extremely high standard of living, salaries, and safety",
        "Efficient and punctual public transportation",
        "Politically stable and neutral",
      ],
      vibe: "Pristine, punctual, and prosperous",
    },
    thailand: {
      bestFor: ["Budget Travelers", "Digital Nomads", "Foodies"],
      climate: "Tropical, hot and humid",
      cons: [
        "Hot and humid climate year-round",
        "Significant language barrier outside tourist zones",
        "Political instability and coups are a recurring issue",
        "Traffic in Bangkok is notoriously bad",
      ],
      continent: "Asia",
      currency: "Thai Baht (THB)",
      flag: "🇹🇭",
      language: ["Thai"],
      metrics: {
        costOfLiving: "Low",
        healthcare: 7.8,
        internetSpeed: 200,
        qualityOfLife: 7.5,
        safety: 7.6,
      },
      name: "Thailand",
      population: "70 million",
      pros: [
        "Extremely low cost of living",
        "World-famous street food and cuisine",
        "Stunning beaches and ornate temples",
        'Friendly and welcoming local culture ("Land of Smiles")',
      ],
      vibe: "Vibrant, spiritual, and budget-friendly",
    },
  },
  ko: {
    argentina: {
      bestFor: ["창작가", "육류 애호가", "댄서"],
      climate: "온대, 남동부는 건조함",
      cons: [
        "만성적인 경제 불안정과 높은 인플레이션",
        "관료주의가 느리고 예측 불가능할 수 있음",
        "대도시에서는 안전이 우려됨",
        "정치적 변동성은 삶의 일부임",
      ],
      continent: "남아메리카",
      currency: "아르헨티나 페소 (ARS)",
      flag: "🇦🇷",
      language: ["스페인어"],
      metrics: {
        costOfLiving: "낮음",
        healthcare: 7.9,
        internetSpeed: 35,
        qualityOfLife: 7.5,
        safety: 6.8,
      },
      name: "아르헨티나",
      population: "4,500만",
      pros: [
        "파타고니아에서 이과수 폭포까지 멋진 자연 경관",
        "특히 부에노스아이레스의 활기찬 문화 생활 (탱고, 연극)",
        "유럽 스타일의 건축과 카페 문화",
        "세계적으로 유명한 스테이크와 말벡 와인을 저렴한 가격에 즐길 수 있음",
      ],
      vibe: "열정적이고, 유럽풍이며, 드라마틱한",
    },
    canada: {
      bestFor: ["가족", "아웃도어 모험가", "이민자"],
      climate: "추운 겨울이 있는 사계절",
      cons: [
        "대부분의 지역에서 매우 춥고 긴 겨울",
        "밴쿠버와 토론토 같은 주요 도시의 높은 생활비",
        "광대한 거리로 인해 국내 여행이 비싸고 시간이 많이 걸림",
        "특히 신규 이민자에게 취업 시장이 경쟁적일 수 있음",
      ],
      continent: "북아메리카",
      currency: "캐나다 달러 (CAD)",
      flag: "🇨🇦",
      language: ["영어", "프랑스어"],
      metrics: {
        costOfLiving: "높음",
        healthcare: 8.8,
        internetSpeed: 150,
        qualityOfLife: 9.0,
        safety: 9.0,
      },
      name: "캐나다",
      population: "3,800만",
      pros: [
        "환영하는 이민 정책과 다문화 도시",
        "보편적 의료 시스템",
        "해안에서 해안까지 광대하고 멋진 자연 경관",
        "안정적이고, 안전하며, 관용적인 사회",
      ],
      vibe: "다문화적이고, 광대하며, 정중한",
    },
    // Tropical
    costa_rica: {
      bestFor: ["자연 애호가", "생태 관광객", "은퇴자"],
      climate: "열대, 연중 따뜻함",
      cons: [
        "다른 중앙 아메리카 국가보다 높은 생활비",
        "특히 도로 등 인프라가 어려울 수 있음",
        "우기가 매우 강할 수 있음 (5월-11월)",
        "관광지에서 소매치기 범죄가 문제가 될 수 있음",
      ],
      continent: "중앙 아메리카",
      currency: "코스타리카 콜론 (CRC)",
      flag: "🇨🇷",
      language: ["스페인어", "영어"],
      metrics: {
        costOfLiving: "중간",
        healthcare: 7.5,
        internetSpeed: 50,
        qualityOfLife: 8.0,
        safety: 7.8,
      },
      name: "코스타리카",
      population: "510만",
      pros: [
        "놀라운 생물 다양성과 보호된 자연 보호 구역",
        '"푸라 비다"(순수한 삶)라는 여유로운 라이프스타일',
        "정치적으로 안정되어 있고 상비군이 없음",
        "재생 에너지 분야의 선두 주자",
      ],
      vibe: "무성하고, 모험적이며, 친환경적인",
    },
    denmark: {
      bestFor: ["자전거 애호가", "디자인 애호가", "기업가"],
      climate: "온화한 겨울, 시원한 여름",
      cons: [
        "세계 최고 수준의 세율",
        "코펜하겐의 주택은 비싸고 구하기 어려움",
        "바람이 많이 불고 흐린 날씨가 잦음",
        "덴마크어는 배우기 어렵기로 악명 높음",
      ],
      continent: "유럽",
      currency: "덴마크 크로네 (DKK)",
      flag: "🇩🇰",
      language: ["덴마크어", "영어"],
      metrics: {
        costOfLiving: "매우 높음",
        healthcare: 9.1,
        internetSpeed: 150,
        qualityOfLife: 9.3,
        safety: 9.4,
      },
      name: "덴마크",
      population: "580만",
      pros: [
        "세계적 수준의 자전거 인프라",
        '"휘게"(아늑함)와 일과 삶의 균형 강조',
        "사회와 정부에 대한 높은 신뢰도",
        "강력한 스타트업 생태계",
      ],
      vibe: "아늑하고, 진보적이며, 디자인 중심적인",
    },
    // Modern
    germany: {
      bestFor: ["엔지니어", "학생", "역사 애호가"],
      climate: "온대, 사계절",
      cons: [
        "악명 높게 느리고 서류 기반인 관료주의",
        "독일인의 직설적인 화법이 무례하게 보일 수 있음",
        "일요일에는 상점이 문을 닫음",
        "높은 세금, 그러나 강력한 사회 서비스를 제공함",
      ],
      continent: "유럽",
      currency: "유로 (EUR)",
      flag: "🇩🇪",
      language: ["독일어"],
      metrics: {
        costOfLiving: "중간",
        healthcare: 9.2,
        internetSpeed: 100,
        qualityOfLife: 9.1,
        safety: 9.0,
      },
      name: "독일",
      population: "8,300만",
      pros: [
        "강력한 경제와 엔지니어링/제조업의 선두 주자",
        "훌륭한 대중교통과 중앙 유럽의 위치",
        "워라밸과 충분한 휴가 시간을 중시함",
        "저렴하거나 무료인 고품질 대학 교육",
      ],
      vibe: "효율적이고, 역사적이며, 친환경적인",
    },
    // New Additions
    ireland: {
      bestFor: ["기술 전문가", "작가", "음악가"],
      climate: "온대 해양성",
      cons: [
        "높은 생활비, 특히 더블린의 주택",
        "자주 비가 오고 흐린 날씨",
        "더블린 외곽에서는 대중교통이 불안정할 수 있음",
        "의료 시스템이 긴 대기 시간 문제에 직면해 있음",
      ],
      continent: "유럽",
      currency: "유로 (EUR)",
      flag: "🇮🇪",
      language: ["영어", "아일랜드어"],
      metrics: {
        costOfLiving: "높음",
        healthcare: 8.0,
        internetSpeed: 90,
        qualityOfLife: 8.7,
        safety: 8.5,
      },
      name: "아일랜드",
      population: "500만",
      pros: [
        '극도로 친절하고 환영하는 "크랙" 문화',
        "많은 주요 기술 회사의 유럽 허브",
        "멋진 녹색 풍경과 드라마틱한 해안선",
        "풍부한 문학 및 음악 역사",
      ],
      vibe: "친절하고, 역사적이며, 푸르른",
    },
    // Mediterranean
    italy: {
      bestFor: ["미식가", "역사 애호가", "예술가"],
      climate: "지중해성, 따뜻한 여름",
      cons: [
        "느리고 답답할 수 있는 관료주의",
        "경제적 불안정성과 높은 청년 실업률",
        "상당한 남북 경제 격차",
        "주요 도시의 관광객 인파",
      ],
      continent: "유럽",
      currency: "유로 (EUR)",
      flag: "🇮🇹",
      language: ["이탈리아어"],
      metrics: {
        costOfLiving: "중간",
        healthcare: 8.5,
        internetSpeed: 60,
        qualityOfLife: 8.2,
        safety: 8.0,
      },
      name: "이탈리아",
      population: "5,900만",
      pros: [
        "세계적으로 유명한 요리와 와인",
        "비교할 수 없는 예술, 역사, 건축",
        '여유로운 "라 돌체 비타" 라이프스타일',
        "다양하고 아름다운 풍경",
      ],
      vibe: "역사적이고, 열정적이며, 맛있는",
    },
    // Cultural
    japan: {
      bestFor: ["미식가", "기술 애호가", "도시 탐험가"],
      climate: "사계절, 지역별로 다양함",
      cons: [
        "상당한 언어 장벽, 영어가 널리 사용되지 않음",
        "장시간 근무가 일반적인 계층적 직장 문화",
        "현지 사회에 통합되기 어려울 수 있음",
        "특히 도쿄의 높은 생활비",
      ],
      continent: "아시아",
      currency: "일본 엔 (JPY)",
      flag: "🇯🇵",
      language: ["일본어"],
      metrics: {
        costOfLiving: "높음",
        healthcare: 9.3,
        internetSpeed: 180,
        qualityOfLife: 8.8,
        safety: 9.7,
      },
      name: "일본",
      population: "1억 2,500만",
      pros: [
        "깊은 전통과 미래 기술의 독특한 조화",
        "낮은 범죄율을 자랑하는 세계에서 가장 안전한 국가 중 하나",
        "길거리 음식부터 미슐랭 스타까지 세계적 수준의 요리",
        "믿을 수 없을 정도로 효율적이고 깨끗한 대중교통",
      ],
      vibe: "전통적이고, 현대적이며, 질서 있는",
    },
    mexico: {
      bestFor: ["디지털 노마드", "미식가", "역사 애호가"],
      climate: "열대에서 사막까지 다양함",
      cons: [
        "특정 지역에서는 안전이 주요 관심사일 수 있음",
        "관료주의와 부패가 어려울 수 있음",
        "많은 지역에서 인프라와 공공 서비스가 부족함",
        "주요 도시 밖에서는 인터넷 안정성이 가변적임",
      ],
      continent: "북아메리카",
      currency: "멕시코 페소 (MXN)",
      flag: "🇲🇽",
      language: ["스페인어"],
      metrics: {
        costOfLiving: "낮음",
        healthcare: 7.2,
        internetSpeed: 40,
        qualityOfLife: 7.0,
        safety: 6.0,
      },
      name: "멕시코",
      population: "1억 2,600만",
      pros: [
        "믿을 수 없을 정도로 풍부한 문화, 역사, 전통",
        "지역별로 다양한 세계적 수준의 요리",
        "저렴한 생활비로 예산 내에서 높은 삶의 질 가능",
        "사막에서 정글, 해변까지 지리적으로 다양함",
      ],
      vibe: "다채롭고, 축제 분위기이며, 다양한",
    },
    netherlands: {
      bestFor: ["자전거 이용자", "기술 전문가", "유학생"],
      climate: "온대, 온화한 여름",
      cons: [
        "높은 소득세와 생활비",
        "임대를 어렵게 만드는 지속적인 주택 부족",
        "자주 비가 오고 흐린 날씨",
        "직설적인 네덜란드식 소통 방식이 무례하게 보일 수 있음",
      ],
      continent: "유럽",
      currency: "유로 (EUR)",
      flag: "🇳🇱",
      language: ["네덜란드어", "영어"],
      metrics: {
        costOfLiving: "높음",
        healthcare: 9.0,
        internetSpeed: 140,
        qualityOfLife: 9.0,
        safety: 9.2,
      },
      name: "네덜란드",
      population: "1,740만",
      pros: [
        "문화적으로 자리 잡은 뛰어난 워라밸",
        "비영어권 국가 중 가장 높은 영어 구사 능력",
        "자유롭고, 관용적이며, 개방적인 사회",
        "유럽 중심에 위치하여 훌륭한 여행 접근성",
      ],
      vibe: "자유롭고, 혁신적이며, 자전거 친화적인",
    },
    new_zealand: {
      bestFor: ["아드레날린 중독자", "자연 사진작가", "원격 근무자"],
      climate: "온대, 온화함",
      cons: [
        "세계의 나머지 지역과 지리적으로 고립됨",
        "상품 및 서비스에 대한 높은 생활비",
        "일부 부문에서 제한된 취업 시장 및 경력 발전",
        "느린 삶의 속도가 모든 사람에게 적합하지 않을 수 있음",
      ],
      continent: "오세아니아",
      currency: "뉴질랜드 달러 (NZD)",
      flag: "🇳🇿",
      language: ["영어", "마오리어"],
      metrics: {
        costOfLiving: "높음",
        healthcare: 8.7,
        internetSpeed: 95,
        qualityOfLife: 8.9,
        safety: 9.3,
      },
      name: "뉴질랜드",
      population: "510만",
      pros: [
        "피오르드에서 해변까지 세계적 수준의 풍경",
        "워라밸과 아웃도어 라이프스타일에 중점",
        "친절하고, 소박하며, 환영하는 문화",
        "상대적으로 안전하고 정치적으로 안정됨",
      ],
      vibe: "모험적이고, 여유로우며, 멋진",
    },
    // Nordic
    norway: {
      bestFor: ["자연 애호가", "가족", "아웃도어 활동가"],
      climate: "추운 겨울, 온화한 여름",
      cons: [
        "극도로 높은 생활비",
        "길고 어두운 추운 겨울",
        "특정 분야(석유, 기술, 해양) 외 제한된 고용 시장",
        "새로운 이민자가 적응하기 어려운 내성적인 사회 문화",
      ],
      continent: "유럽",
      currency: "노르웨이 크로네 (NOK)",
      flag: "🇳🇴",
      language: ["노르웨이어", "영어"],
      metrics: {
        costOfLiving: "매우 높음",
        healthcare: 9.2,
        internetSpeed: 100,
        qualityOfLife: 9.5,
        safety: 9.8,
      },
      name: "노르웨이",
      population: "540만",
      pros: [
        "뛰어난 일과 삶의 균형",
        "피오르드와 산 등 멋진 자연 경관",
        "높은 수준의 안전과 사회적 신뢰",
        "강력한 복지 시스템",
      ],
      vibe: "평화롭고, 장엄하며, 물가가 비싼",
    },
    portugal: {
      bestFor: ["디지털 노마드", "은퇴자", "서퍼"],
      climate: "지중해성, 온화함",
      cons: [
        "다른 EU 국가에 비해 낮은 급여",
        "느리고 비효율적일 수 있는 관료주의",
        "리스본과 포르투의 주택 가격 급등",
        "일부 시골 지역의 노후된 인프라",
      ],
      continent: "유럽",
      currency: "유로 (EUR)",
      flag: "🇵🇹",
      language: ["포르투갈어"],
      metrics: {
        costOfLiving: "중간",
        healthcare: 8.1,
        internetSpeed: 110,
        qualityOfLife: 8.3,
        safety: 8.9,
      },
      name: "포르투갈",
      population: "1,030만",
      pros: [
        "서유럽에서 비교적 저렴한 생활비",
        "아름다운 대서양 해안선과 해변",
        "친절하고 환영하는 문화와 성장하는 외국인 커뮤니티",
        "원격 근무자 및 은퇴자를 위한 유리한 비자 옵션",
      ],
      vibe: "매력적이고, 저렴하며, 해안의",
    },
    // Cosmopolitan
    singapore: {
      bestFor: ["금융 전문가", "가족 단위 외국인", "기술 혁신가"],
      climate: "열대, 덥고 습함",
      cons: [
        "세계에서 가장 비싼 도시 중 하나",
        "엄격한 법률 및 규제 (예: 언론, 껌 씹기)",
        "지속적으로 덥고 습한 날씨",
        "경쟁이 치열한 직장 및 학교 환경",
      ],
      continent: "아시아",
      currency: "싱가포르 달러 (SGD)",
      flag: "🇸🇬",
      language: ["영어", "중국어", "말레이어", "타밀어"],
      metrics: {
        costOfLiving: "매우 높음",
        healthcare: 8.9,
        internetSpeed: 250,
        qualityOfLife: 9.0,
        safety: 9.8,
      },
      name: "싱가포르",
      population: "590만",
      pros: [
        "극도로 안전하고 깨끗함",
        "세계적 수준의 인프라와 대중교통",
        "높은 영어 구사 능력을 갖춘 글로벌 비즈니스 및 금융 허브",
        "아시아 문화와 요리의 용광로",
      ],
      vibe: "현대적이고, 효율적이며, 다문화적인",
    },
    south_korea: {
      bestFor: ["기술 전문가", "대중문화 팬", "기업가"],
      climate: "사계절, 대륙성",
      cons: [
        "치열하고 경쟁적인 직장 및 교육 문화",
        "유행에 따르라는 높은 사회적 압력",
        "특히 봄철의 심각한 대기 오염",
        "서울을 벗어나면 언어 장벽이 어려울 수 있음",
      ],
      continent: "아시아",
      currency: "대한민국 원 (KRW)",
      flag: "🇰🇷",
      language: ["한국어"],
      metrics: {
        costOfLiving: "높음",
        healthcare: 8.9,
        internetSpeed: 220,
        qualityOfLife: 8.2,
        safety: 8.8,
      },
      name: "대한민국",
      population: "5,200만",
      pros: [
        "세계 최고 수준의 인터넷 속도와 기술 인프라",
        "활기찬 K팝, 영화, 패션계",
        '"빨리빨리" 문화가 일 처리를 빠르게 함',
        "안전하고, 훌륭한 대중교통과 맛있는 음식이 있음",
      ],
      vibe: "역동적이고, 유행을 선도하며, 첨단 기술의",
    },
    spain: {
      bestFor: ["사교적인 사람", "은퇴자", "디지털 노마드"],
      climate: "지중해성, 더운 여름",
      cons: [
        "특히 청년층의 높은 실업률",
        "느린 관료주의, 특히 거주 허가 관련",
        "남부의 매우 더운 여름",
        '"시에스타" 문화가 업무 시간에 지장을 줄 수 있음',
      ],
      continent: "유럽",
      currency: "유로 (EUR)",
      flag: "🇪🇸",
      language: ["스페인어"],
      metrics: {
        costOfLiving: "중간",
        healthcare: 8.8,
        internetSpeed: 90,
        qualityOfLife: 8.5,
        safety: 8.2,
      },
      name: "스페인",
      population: "4,700만",
      pros: [
        "다른 서유럽 국가에 비해 저렴한 생활비",
        '활기찬 밤문화와 사교적인 "타파스" 문화',
        "우수한 공공 의료 시스템",
        "화창한 날씨와 아름다운 해변",
      ],
      vibe: "활기차고, 사교적이며, 햇살 가득한",
    },
    sweden: {
      bestFor: ["기술 전문가", "디자이너", "가족"],
      climate: "추운 겨울, 쾌적한 여름",
      cons: [
        "높은 소득세",
        "특히 도시에서의 경쟁적인 취업 및 주택 시장",
        "사회적 관계망에 진입하기 어려울 수 있음",
        "일조량이 적은 긴 겨울",
      ],
      continent: "유럽",
      currency: "스웨덴 크로나 (SEK)",
      flag: "🇸🇪",
      language: ["스웨덴어", "영어"],
      metrics: {
        costOfLiving: "높음",
        healthcare: 9.0,
        internetSpeed: 120,
        qualityOfLife: 9.2,
        safety: 9.5,
      },
      name: "스웨덴",
      population: "1,040만",
      pros: [
        "기술 및 혁신의 주요 허브(예: 스포티파이)",
        "강력한 사회 보장 및 육아 휴직 제도",
        "지속 가능성 및 평등 강조",
        "높은 영어 구사력",
      ],
      vibe: "혁신적이고, 스타일리시하며, 내성적인",
    },
    // Mountainous
    switzerland: {
      bestFor: ["금융 전문가", "아웃도어 활동가", "엔지니어"],
      climate: "알프스, 추운 겨울",
      cons: [
        "세계 최고 수준의 극도로 높은 생활비",
        "보수적이고 통합하기 어려운 사회 문화",
        "일상의 여러 측면에 대한 엄격한 규칙과 규제",
        "상점이 일찍 닫고 많은 지역에서 조용한 사교 생활",
      ],
      continent: "유럽",
      currency: "스위스 프랑 (CHF)",
      flag: "🇨🇭",
      language: ["독일어", "프랑스어", "이탈리아어"],
      metrics: {
        costOfLiving: "매우 높음",
        healthcare: 9.4,
        internetSpeed: 160,
        qualityOfLife: 9.8,
        safety: 9.9,
      },
      name: "스위스",
      population: "870만",
      pros: [
        "숨 막히는 알프스 풍경과 깨끗한 자연",
        "극도로 높은 생활 수준, 급여 및 안전",
        "효율적이고 시간을 잘 지키는 대중교통",
        "정치적으로 안정되고 중립적임",
      ],
      vibe: "깨끗하고, 시간을 잘 지키며, 부유한",
    },
    thailand: {
      bestFor: ["저예산 여행자", "디지털 노마드", "미식가"],
      climate: "열대, 덥고 습함",
      cons: [
        "연중 덥고 습한 기후",
        "관광 지역을 벗어나면 상당한 언어 장벽",
        "정치적 불안정과 쿠데타가 반복되는 문제",
        "방콕의 교통 체증은 악명 높음",
      ],
      continent: "아시아",
      currency: "태국 바트 (THB)",
      flag: "🇹🇭",
      language: ["태국어"],
      metrics: {
        costOfLiving: "낮음",
        healthcare: 7.8,
        internetSpeed: 200,
        qualityOfLife: 7.5,
        safety: 7.6,
      },
      name: "태국",
      population: "7,000만",
      pros: [
        "극도로 저렴한 생활비",
        "세계적으로 유명한 길거리 음식과 요리",
        "아름다운 해변과 화려한 사원",
        '친절하고 환영하는 현지 문화 ("미소의 나라")',
      ],
      vibe: "활기차고, 영적이며, 예산 친화적인",
    },
  },
};
