import type { Locale } from "@/i18n";

import type { FoodPersonalityQuestion } from "./types";

export const FOOD_PERSONALITY_QUESTIONS: Record<
  Locale,
  FoodPersonalityQuestion[]
> = {
  zh: [],
  en: [
    {
      emoji: "🍽️",
      id: "1",
      options: [
        {
          emoji: "🌍",
          id: "a",
          scores: {
            adventurer: 3,
            minimalist: 0,
            perfectionist: 1,
            social: 1,
            traditionalist: 0,
          },
          text: "A cuisine I've never tried before",
        },
        {
          emoji: "🏠",
          id: "b",
          scores: {
            adventurer: 0,
            minimalist: 1,
            perfectionist: 2,
            social: 1,
            traditionalist: 3,
          },
          text: "Familiar dishes done really well",
        },
        {
          emoji: "⭐",
          id: "c",
          scores: {
            adventurer: 1,
            minimalist: 0,
            perfectionist: 3,
            social: 2,
            traditionalist: 1,
          },
          text: "Excellent reviews and high ratings",
        },
        {
          emoji: "👥",
          id: "d",
          scores: {
            adventurer: 1,
            minimalist: 0,
            perfectionist: 1,
            social: 3,
            traditionalist: 1,
          },
          text: "Great atmosphere for sharing with friends",
        },
        {
          emoji: "🥬",
          id: "e",
          scores: {
            adventurer: 0,
            minimalist: 3,
            perfectionist: 2,
            social: 0,
            traditionalist: 1,
          },
          text: "Simple, fresh, quality ingredients",
        },
      ],
      text: "When choosing a restaurant, what's most important to you?",
    },
    {
      emoji: "👩‍🍳",
      id: "2",
      options: [
        {
          emoji: "🧪",
          id: "a",
          scores: {
            adventurer: 3,
            minimalist: 0,
            perfectionist: 1,
            social: 1,
            traditionalist: 0,
          },
          text: "Experimenting with new recipes from different countries",
        },
        {
          emoji: "📜",
          id: "b",
          scores: {
            adventurer: 0,
            minimalist: 1,
            perfectionist: 1,
            social: 2,
            traditionalist: 3,
          },
          text: "Making family recipes passed down through generations",
        },
        {
          emoji: "🔪",
          id: "c",
          scores: {
            adventurer: 1,
            minimalist: 1,
            perfectionist: 3,
            social: 0,
            traditionalist: 1,
          },
          text: "Perfecting techniques and using the finest ingredients",
        },
        {
          emoji: "❤️",
          id: "d",
          scores: {
            adventurer: 1,
            minimalist: 1,
            perfectionist: 1,
            social: 3,
            traditionalist: 2,
          },
          text: "Preparing meals to share with loved ones",
        },
        {
          emoji: "⚡",
          id: "e",
          scores: {
            adventurer: 0,
            minimalist: 3,
            perfectionist: 0,
            social: 0,
            traditionalist: 0,
          },
          text: "Quick, healthy meals with minimal preparation",
        },
      ],
      text: "Your ideal cooking style is:",
    },
    {
      emoji: "🤔",
      id: "3",
      options: [
        {
          emoji: "🚀",
          id: "a",
          scores: {
            adventurer: 3,
            minimalist: 0,
            perfectionist: 1,
            social: 2,
            traditionalist: 0,
          },
          text: "Order it immediately - you love trying new things!",
        },
        {
          emoji: "🛡️",
          id: "b",
          scores: {
            adventurer: 0,
            minimalist: 2,
            perfectionist: 1,
            social: 1,
            traditionalist: 3,
          },
          text: "Stick with something you know you'll enjoy",
        },
        {
          emoji: "🧐",
          id: "c",
          scores: {
            adventurer: 1,
            minimalist: 1,
            perfectionist: 3,
            social: 1,
            traditionalist: 1,
          },
          text: "Research it first or ask the server detailed questions",
        },
        {
          emoji: "🗣️",
          id: "d",
          scores: {
            adventurer: 1,
            minimalist: 0,
            perfectionist: 1,
            social: 3,
            traditionalist: 1,
          },
          text: "Ask your dining companions what they think",
        },
        {
          emoji: "🌱",
          id: "e",
          scores: {
            adventurer: 1,
            minimalist: 3,
            perfectionist: 1,
            social: 0,
            traditionalist: 0,
          },
          text: "Only try it if the ingredients are simple and natural",
        },
      ],
      text: "When you see an unusual dish on a menu, you:",
    },
    {
      emoji: "🔍",
      id: "4",
      options: [
        {
          emoji: "✈️",
          id: "a",
          scores: {
            adventurer: 3,
            minimalist: 0,
            perfectionist: 2,
            social: 1,
            traditionalist: 0,
          },
          text: "Traveling to different countries and eating local food",
        },
        {
          emoji: "👨‍👩‍👧‍👦",
          id: "b",
          scores: {
            adventurer: 0,
            minimalist: 1,
            perfectionist: 1,
            social: 2,
            traditionalist: 3,
          },
          text: "Getting recommendations from family and longtime friends",
        },
        {
          emoji: "📰",
          id: "c",
          scores: {
            adventurer: 1,
            minimalist: 0,
            perfectionist: 3,
            social: 1,
            traditionalist: 1,
          },
          text: "Reading professional food reviews and critics",
        },
        {
          emoji: "📱",
          id: "d",
          scores: {
            adventurer: 2,
            minimalist: 0,
            perfectionist: 1,
            social: 3,
            traditionalist: 0,
          },
          text: "Following food influencers and social media recommendations",
        },
        {
          emoji: "🥕",
          id: "e",
          scores: {
            adventurer: 1,
            minimalist: 3,
            perfectionist: 2,
            social: 1,
            traditionalist: 1,
          },
          text: "Shopping at farmers markets and seasonal produce",
        },
      ],
      text: "Your favorite way to discover new food is:",
    },
    {
      emoji: "🎉",
      id: "5",
      options: [
        {
          emoji: "🌶️",
          id: "a",
          scores: {
            adventurer: 3,
            minimalist: 0,
            perfectionist: 1,
            social: 2,
            traditionalist: 0,
          },
          text: "Bring an exotic dish from a culture you recently discovered",
        },
        {
          emoji: "🏆",
          id: "b",
          scores: {
            adventurer: 0,
            minimalist: 1,
            perfectionist: 1,
            social: 2,
            traditionalist: 3,
          },
          text: "Bring your famous family recipe that everyone loves",
        },
        {
          emoji: "👨‍🍳",
          id: "c",
          scores: {
            adventurer: 1,
            minimalist: 0,
            perfectionist: 3,
            social: 1,
            traditionalist: 1,
          },
          text: "Prepare something beautifully presented and perfectly executed",
        },
        {
          emoji: "🍕",
          id: "d",
          scores: {
            adventurer: 1,
            minimalist: 0,
            perfectionist: 1,
            social: 3,
            traditionalist: 2,
          },
          text: "Focus on foods that bring people together and start conversations",
        },
        {
          emoji: "🥗",
          id: "e",
          scores: {
            adventurer: 0,
            minimalist: 3,
            perfectionist: 2,
            social: 1,
            traditionalist: 1,
          },
          text: "Bring a simple but high-quality dish with fresh ingredients",
        },
      ],
      text: "At a dinner party, you're most likely to:",
    },
    {
      emoji: "🌎",
      id: "6",
      options: [
        {
          emoji: "🍜",
          id: "a",
          scores: {
            adventurer: 3,
            minimalist: 0,
            perfectionist: 1,
            social: 2,
            traditionalist: 0,
          },
          text: "A street food tour through Southeast Asia",
        },
        {
          emoji: "🏰",
          id: "b",
          scores: {
            adventurer: 1,
            minimalist: 1,
            perfectionist: 1,
            social: 2,
            traditionalist: 3,
          },
          text: "Visiting your ancestral homeland and learning family recipes",
        },
        {
          emoji: "🌟",
          id: "c",
          scores: {
            adventurer: 2,
            minimalist: 0,
            perfectionist: 3,
            social: 1,
            traditionalist: 1,
          },
          text: "A Michelin star restaurant tour in France",
        },
        {
          emoji: "🍷",
          id: "d",
          scores: {
            adventurer: 2,
            minimalist: 0,
            perfectionist: 2,
            social: 3,
            traditionalist: 1,
          },
          text: "A wine and food festival with friends",
        },
        {
          emoji: "🚜",
          id: "e",
          scores: {
            adventurer: 1,
            minimalist: 3,
            perfectionist: 2,
            social: 1,
            traditionalist: 2,
          },
          text: "A farm-to-table retreat in the countryside",
        },
      ],
      text: "Your dream food vacation would be:",
    },
    {
      emoji: "🌶️",
      id: "7",
      options: [
        {
          emoji: "🔥",
          id: "a",
          scores: {
            adventurer: 3,
            minimalist: 0,
            perfectionist: 1,
            social: 1,
            traditionalist: 0,
          },
          text: "The spicier the better - bring on the heat!",
        },
        {
          emoji: "🧂",
          id: "b",
          scores: {
            adventurer: 0,
            minimalist: 2,
            perfectionist: 1,
            social: 1,
            traditionalist: 3,
          },
          text: "Mild spices that enhance familiar flavors",
        },
        {
          emoji: "⚖️",
          id: "c",
          scores: {
            adventurer: 1,
            minimalist: 1,
            perfectionist: 3,
            social: 1,
            traditionalist: 1,
          },
          text: "Carefully balanced spices that complement the dish perfectly",
        },
        {
          emoji: "🤝",
          id: "d",
          scores: {
            adventurer: 1,
            minimalist: 1,
            perfectionist: 1,
            social: 3,
            traditionalist: 2,
          },
          text: "Whatever the group can handle - you adapt to others",
        },
        {
          emoji: "🌿",
          id: "e",
          scores: {
            adventurer: 0,
            minimalist: 3,
            perfectionist: 2,
            social: 0,
            traditionalist: 1,
          },
          text: "Simple herbs and natural flavors without overwhelming heat",
        },
      ],
      text: "When it comes to spice levels, you prefer:",
    },
    {
      emoji: "✨",
      id: "8",
      options: [
        {
          emoji: "💎",
          id: "a",
          scores: {
            adventurer: 3,
            minimalist: 0,
            perfectionist: 2,
            social: 1,
            traditionalist: 1,
          },
          text: "Discovering a hidden gem with authentic local cuisine",
        },
        {
          emoji: "🏠",
          id: "b",
          scores: {
            adventurer: 0,
            minimalist: 2,
            perfectionist: 1,
            social: 2,
            traditionalist: 3,
          },
          text: "A cozy meal that reminds you of home and childhood",
        },
        {
          emoji: "🎩",
          id: "c",
          scores: {
            adventurer: 1,
            minimalist: 0,
            perfectionist: 3,
            social: 1,
            traditionalist: 1,
          },
          text: "Impeccable service and expertly crafted dishes",
        },
        {
          emoji: "🎊",
          id: "d",
          scores: {
            adventurer: 2,
            minimalist: 0,
            perfectionist: 1,
            social: 3,
            traditionalist: 1,
          },
          text: "Lively atmosphere with great company and shareable dishes",
        },
        {
          emoji: "🍃",
          id: "e",
          scores: {
            adventurer: 0,
            minimalist: 3,
            perfectionist: 2,
            social: 0,
            traditionalist: 1,
          },
          text: "Fresh ingredients prepared simply without unnecessary fuss",
        },
      ],
      text: "Your ideal dining experience includes:",
    },
    {
      emoji: "🛒",
      id: "9",
      options: [
        {
          emoji: "🌏",
          id: "a",
          scores: {
            adventurer: 3,
            minimalist: 0,
            perfectionist: 1,
            social: 1,
            traditionalist: 0,
          },
          text: "Explore international aisles and try new products",
        },
        {
          emoji: "📝",
          id: "b",
          scores: {
            adventurer: 0,
            minimalist: 2,
            perfectionist: 1,
            social: 1,
            traditionalist: 3,
          },
          text: "Stick to your regular list of tried-and-true ingredients",
        },
        {
          emoji: "🏅",
          id: "c",
          scores: {
            adventurer: 1,
            minimalist: 1,
            perfectionist: 3,
            social: 0,
            traditionalist: 1,
          },
          text: "Seek out the highest quality brands and artisanal products",
        },
        {
          emoji: "🎁",
          id: "d",
          scores: {
            adventurer: 1,
            minimalist: 0,
            perfectionist: 1,
            social: 3,
            traditionalist: 2,
          },
          text: "Buy ingredients for dishes you can share with others",
        },
        {
          emoji: "🥕",
          id: "e",
          scores: {
            adventurer: 1,
            minimalist: 3,
            perfectionist: 2,
            social: 0,
            traditionalist: 1,
          },
          text: "Focus on fresh, seasonal, and minimally processed foods",
        },
      ],
      text: "When grocery shopping, you:",
    },
    {
      emoji: "💭",
      id: "10",
      options: [
        {
          emoji: "🎢",
          id: "a",
          scores: {
            adventurer: 3,
            minimalist: 0,
            perfectionist: 1,
            social: 2,
            traditionalist: 0,
          },
          text: "Food is an adventure - life's too short for boring meals",
        },
        {
          emoji: "💝",
          id: "b",
          scores: {
            adventurer: 0,
            minimalist: 1,
            perfectionist: 1,
            social: 2,
            traditionalist: 3,
          },
          text: "Food should comfort the soul and connect us to our roots",
        },
        {
          emoji: "🎨",
          id: "c",
          scores: {
            adventurer: 2,
            minimalist: 1,
            perfectionist: 3,
            social: 0,
            traditionalist: 1,
          },
          text: "Food is an art form that deserves respect and excellence",
        },
        {
          emoji: "🤗",
          id: "d",
          scores: {
            adventurer: 1,
            minimalist: 1,
            perfectionist: 1,
            social: 3,
            traditionalist: 2,
          },
          text: "Food brings people together and creates lasting memories",
        },
        {
          emoji: "💪",
          id: "e",
          scores: {
            adventurer: 0,
            minimalist: 3,
            perfectionist: 2,
            social: 0,
            traditionalist: 1,
          },
          text: "Food should nourish the body with pure, simple ingredients",
        },
      ],
      text: "Your food philosophy is:",
    },
  ],
  es: [],
  fr: [],
  ja: [],
  ko: [
    {
      emoji: "🍽️",
      id: "1",
      options: [
        {
          emoji: "🌍",
          id: "a",
          scores: {
            adventurer: 3,
            minimalist: 0,
            perfectionist: 1,
            social: 1,
            traditionalist: 0,
          },
          text: "한 번도 시도해본 적 없는 요리",
        },
        {
          emoji: "🏠",
          id: "b",
          scores: {
            adventurer: 0,
            minimalist: 1,
            perfectionist: 2,
            social: 1,
            traditionalist: 3,
          },
          text: "익숙한 음식을 정말 잘 만드는 곳",
        },
        {
          emoji: "⭐",
          id: "c",
          scores: {
            adventurer: 1,
            minimalist: 0,
            perfectionist: 3,
            social: 2,
            traditionalist: 1,
          },
          text: "훌륭한 리뷰와 높은 평점",
        },
        {
          emoji: "👥",
          id: "d",
          scores: {
            adventurer: 1,
            minimalist: 0,
            perfectionist: 1,
            social: 3,
            traditionalist: 1,
          },
          text: "친구들과 함께 나누기 좋은 분위기",
        },
        {
          emoji: "🥬",
          id: "e",
          scores: {
            adventurer: 0,
            minimalist: 3,
            perfectionist: 2,
            social: 0,
            traditionalist: 1,
          },
          text: "간단하고 신선하며 고품질의 재료",
        },
      ],
      text: "식당을 선택할 때 가장 중요한 것은?",
    },
    {
      emoji: "👩‍🍳",
      id: "2",
      options: [
        {
          emoji: "🧪",
          id: "a",
          scores: {
            adventurer: 3,
            minimalist: 0,
            perfectionist: 1,
            social: 1,
            traditionalist: 0,
          },
          text: "다양한 나라의 새로운 레시피 실험하기",
        },
        {
          emoji: "📜",
          id: "b",
          scores: {
            adventurer: 0,
            minimalist: 1,
            perfectionist: 1,
            social: 2,
            traditionalist: 3,
          },
          text: "대대로 내려오는 가족 레시피 만들기",
        },
        {
          emoji: "🔪",
          id: "c",
          scores: {
            adventurer: 1,
            minimalist: 1,
            perfectionist: 3,
            social: 0,
            traditionalist: 1,
          },
          text: "기술을 완벽하게 하고 최고급 재료 사용하기",
        },
        {
          emoji: "❤️",
          id: "d",
          scores: {
            adventurer: 1,
            minimalist: 1,
            perfectionist: 1,
            social: 3,
            traditionalist: 2,
          },
          text: "사랑하는 사람들과 나누기 위한 음식 준비하기",
        },
        {
          emoji: "⚡",
          id: "e",
          scores: {
            adventurer: 0,
            minimalist: 3,
            perfectionist: 0,
            social: 0,
            traditionalist: 0,
          },
          text: "최소한의 준비로 빠르고 건강한 식사",
        },
      ],
      text: "당신의 이상적인 요리 스타일은:",
    },
    {
      emoji: "🤔",
      id: "3",
      options: [
        {
          emoji: "🚀",
          id: "a",
          scores: {
            adventurer: 3,
            minimalist: 0,
            perfectionist: 1,
            social: 2,
            traditionalist: 0,
          },
          text: "즉시 주문해요 - 새로운 걸 시도하는 걸 좋아해요!",
        },
        {
          emoji: "🛡️",
          id: "b",
          scores: {
            adventurer: 0,
            minimalist: 2,
            perfectionist: 1,
            social: 1,
            traditionalist: 3,
          },
          text: "확실히 맛있을 걸 아는 음식을 선택해요",
        },
        {
          emoji: "🧐",
          id: "c",
          scores: {
            adventurer: 1,
            minimalist: 1,
            perfectionist: 3,
            social: 1,
            traditionalist: 1,
          },
          text: "먼저 조사하거나 서버에게 자세히 물어봐요",
        },
        {
          emoji: "🗣️",
          id: "d",
          scores: {
            adventurer: 1,
            minimalist: 0,
            perfectionist: 1,
            social: 3,
            traditionalist: 1,
          },
          text: "함께 식사하는 사람들의 의견을 물어봐요",
        },
        {
          emoji: "🌱",
          id: "e",
          scores: {
            adventurer: 1,
            minimalist: 3,
            perfectionist: 1,
            social: 0,
            traditionalist: 0,
          },
          text: "재료가 간단하고 자연스러울 때만 시도해요",
        },
      ],
      text: "메뉴에서 이상한 음식을 보면, 당신은:",
    },
    {
      emoji: "🔍",
      id: "4",
      options: [
        {
          emoji: "✈️",
          id: "a",
          scores: {
            adventurer: 3,
            minimalist: 0,
            perfectionist: 2,
            social: 1,
            traditionalist: 0,
          },
          text: "다른 나라를 여행하며 현지 음식 먹기",
        },
        {
          emoji: "👨‍👩‍👧‍👦",
          id: "b",
          scores: {
            adventurer: 0,
            minimalist: 1,
            perfectionist: 1,
            social: 2,
            traditionalist: 3,
          },
          text: "가족과 오래된 친구들의 추천 받기",
        },
        {
          emoji: "📰",
          id: "c",
          scores: {
            adventurer: 1,
            minimalist: 0,
            perfectionist: 3,
            social: 1,
            traditionalist: 1,
          },
          text: "전문가의 음식 리뷰와 평론 읽기",
        },
        {
          emoji: "📱",
          id: "d",
          scores: {
            adventurer: 2,
            minimalist: 0,
            perfectionist: 1,
            social: 3,
            traditionalist: 0,
          },
          text: "푸드 인플루언서와 소셜미디어 추천 따라가기",
        },
        {
          emoji: "🥕",
          id: "e",
          scores: {
            adventurer: 1,
            minimalist: 3,
            perfectionist: 2,
            social: 1,
            traditionalist: 1,
          },
          text: "농산물 직판장과 계절 농산물에서 쇼핑하기",
        },
      ],
      text: "새로운 음식을 발견하는 가장 좋은 방법은:",
    },
    {
      emoji: "🎉",
      id: "5",
      options: [
        {
          emoji: "🌶️",
          id: "a",
          scores: {
            adventurer: 3,
            minimalist: 0,
            perfectionist: 1,
            social: 2,
            traditionalist: 0,
          },
          text: "최근에 발견한 이국적인 요리 가져오기",
        },
        {
          emoji: "🏆",
          id: "b",
          scores: {
            adventurer: 0,
            minimalist: 1,
            perfectionist: 1,
            social: 2,
            traditionalist: 3,
          },
          text: "모두가 좋아하는 유명한 가족 레시피 가져오기",
        },
        {
          emoji: "👨‍🍳",
          id: "c",
          scores: {
            adventurer: 1,
            minimalist: 0,
            perfectionist: 3,
            social: 1,
            traditionalist: 1,
          },
          text: "아름답게 플레이팅하고 완벽하게 만든 요리 준비하기",
        },
        {
          emoji: "🍕",
          id: "d",
          scores: {
            adventurer: 1,
            minimalist: 0,
            perfectionist: 1,
            social: 3,
            traditionalist: 2,
          },
          text: "사람들이 모이고 대화를 시작할 수 있는 음식에 집중하기",
        },
        {
          emoji: "🥗",
          id: "e",
          scores: {
            adventurer: 0,
            minimalist: 3,
            perfectionist: 2,
            social: 1,
            traditionalist: 1,
          },
          text: "신선한 재료로 간단하지만 고품질의 요리 가져오기",
        },
      ],
      text: "만찬에서 당신이 할 가능성이 가장 높은 것은:",
    },
    {
      emoji: "🌎",
      id: "6",
      options: [
        {
          emoji: "🍜",
          id: "a",
          scores: {
            adventurer: 3,
            minimalist: 0,
            perfectionist: 1,
            social: 2,
            traditionalist: 0,
          },
          text: "동남아시아 길거리 음식 투어",
        },
        {
          emoji: "🏰",
          id: "b",
          scores: {
            adventurer: 1,
            minimalist: 1,
            perfectionist: 1,
            social: 2,
            traditionalist: 3,
          },
          text: "조상의 고향을 방문해서 가족 레시피 배우기",
        },
        {
          emoji: "🌟",
          id: "c",
          scores: {
            adventurer: 2,
            minimalist: 0,
            perfectionist: 3,
            social: 1,
            traditionalist: 1,
          },
          text: "프랑스 미슐랭 스타 레스토랑 투어",
        },
        {
          emoji: "🍷",
          id: "d",
          scores: {
            adventurer: 2,
            minimalist: 0,
            perfectionist: 2,
            social: 3,
            traditionalist: 1,
          },
          text: "친구들과 함께하는 와인 및 음식 축제",
        },
        {
          emoji: "🚜",
          id: "e",
          scores: {
            adventurer: 1,
            minimalist: 3,
            perfectionist: 2,
            social: 1,
            traditionalist: 2,
          },
          text: "시골의 농장에서 식탁까지 리트릿",
        },
      ],
      text: "당신의 꿈의 음식 여행은:",
    },
    {
      emoji: "🌶️",
      id: "7",
      options: [
        {
          emoji: "🔥",
          id: "a",
          scores: {
            adventurer: 3,
            minimalist: 0,
            perfectionist: 1,
            social: 1,
            traditionalist: 0,
          },
          text: "매울수록 좋아요 - 열기를 가져와요!",
        },
        {
          emoji: "🧂",
          id: "b",
          scores: {
            adventurer: 0,
            minimalist: 2,
            perfectionist: 1,
            social: 1,
            traditionalist: 3,
          },
          text: "익숙한 맛을 향상시키는 순한 향신료",
        },
        {
          emoji: "⚖️",
          id: "c",
          scores: {
            adventurer: 1,
            minimalist: 1,
            perfectionist: 3,
            social: 1,
            traditionalist: 1,
          },
          text: "요리를 완벽하게 보완하는 균형 잡힌 향신료",
        },
        {
          emoji: "🤝",
          id: "d",
          scores: {
            adventurer: 1,
            minimalist: 1,
            perfectionist: 1,
            social: 3,
            traditionalist: 2,
          },
          text: "그룹이 감당할 수 있는 정도 - 다른 사람들에게 맞춰요",
        },
        {
          emoji: "🌿",
          id: "e",
          scores: {
            adventurer: 0,
            minimalist: 3,
            perfectionist: 2,
            social: 0,
            traditionalist: 1,
          },
          text: "압도적인 열기 없이 간단한 허브와 자연스러운 맛",
        },
      ],
      text: "매운맛에 대해서는:",
    },
    {
      emoji: "✨",
      id: "8",
      options: [
        {
          emoji: "💎",
          id: "a",
          scores: {
            adventurer: 3,
            minimalist: 0,
            perfectionist: 2,
            social: 1,
            traditionalist: 1,
          },
          text: "정통 현지 요리가 있는 숨겨진 보석 찾기",
        },
        {
          emoji: "🏠",
          id: "b",
          scores: {
            adventurer: 0,
            minimalist: 2,
            perfectionist: 1,
            social: 2,
            traditionalist: 3,
          },
          text: "집과 어린 시절을 떠올리게 하는 아늑한 식사",
        },
        {
          emoji: "🎩",
          id: "c",
          scores: {
            adventurer: 1,
            minimalist: 0,
            perfectionist: 3,
            social: 1,
            traditionalist: 1,
          },
          text: "완벽한 서비스와 전문적으로 만들어진 요리",
        },
        {
          emoji: "🎊",
          id: "d",
          scores: {
            adventurer: 2,
            minimalist: 0,
            perfectionist: 1,
            social: 3,
            traditionalist: 1,
          },
          text: "훌륭한 사람들과 나눌 수 있는 요리가 있는 활기찬 분위기",
        },
        {
          emoji: "🍃",
          id: "e",
          scores: {
            adventurer: 0,
            minimalist: 3,
            perfectionist: 2,
            social: 0,
            traditionalist: 1,
          },
          text: "불필요한 번거로움 없이 간단하게 조리된 신선한 재료",
        },
      ],
      text: "당신의 이상적인 식사 경험은:",
    },
    {
      emoji: "🛒",
      id: "9",
      options: [
        {
          emoji: "🌏",
          id: "a",
          scores: {
            adventurer: 3,
            minimalist: 0,
            perfectionist: 1,
            social: 1,
            traditionalist: 0,
          },
          text: "국제 식품 코너를 탐색하고 새로운 제품을 시도해요",
        },
        {
          emoji: "📝",
          id: "b",
          scores: {
            adventurer: 0,
            minimalist: 2,
            perfectionist: 1,
            social: 1,
            traditionalist: 3,
          },
          text: "검증된 정기 재료 목록에 충실해요",
        },
        {
          emoji: "🏅",
          id: "c",
          scores: {
            adventurer: 1,
            minimalist: 1,
            perfectionist: 3,
            social: 0,
            traditionalist: 1,
          },
          text: "최고 품질의 브랜드와 수제 제품을 찾아요",
        },
        {
          emoji: "🎁",
          id: "d",
          scores: {
            adventurer: 1,
            minimalist: 0,
            perfectionist: 1,
            social: 3,
            traditionalist: 2,
          },
          text: "다른 사람들과 나눌 수 있는 요리를 위한 재료를 사요",
        },
        {
          emoji: "🥕",
          id: "e",
          scores: {
            adventurer: 1,
            minimalist: 3,
            perfectionist: 2,
            social: 0,
            traditionalist: 1,
          },
          text: "신선하고 계절적이며 최소한으로 가공된 식품에 집중해요",
        },
      ],
      text: "식료품을 쇼핑할 때, 당신은:",
    },
    {
      emoji: "💭",
      id: "10",
      options: [
        {
          emoji: "🎢",
          id: "a",
          scores: {
            adventurer: 3,
            minimalist: 0,
            perfectionist: 1,
            social: 2,
            traditionalist: 0,
          },
          text: "음식은 모험이다 - 인생은 지루한 식사하기에 너무 짧다",
        },
        {
          emoji: "💝",
          id: "b",
          scores: {
            adventurer: 0,
            minimalist: 1,
            perfectionist: 1,
            social: 2,
            traditionalist: 3,
          },
          text: "음식은 영혼을 위로하고 우리를 뿌리와 연결해야 한다",
        },
        {
          emoji: "🎨",
          id: "c",
          scores: {
            adventurer: 2,
            minimalist: 1,
            perfectionist: 3,
            social: 0,
            traditionalist: 1,
          },
          text: "음식은 존중과 우수성을 받을 자격이 있는 예술 형태다",
        },
        {
          emoji: "🤗",
          id: "d",
          scores: {
            adventurer: 1,
            minimalist: 1,
            perfectionist: 1,
            social: 3,
            traditionalist: 2,
          },
          text: "음식은 사람들을 모으고 지속적인 기억을 만든다",
        },
        {
          emoji: "💪",
          id: "e",
          scores: {
            adventurer: 0,
            minimalist: 3,
            perfectionist: 2,
            social: 0,
            traditionalist: 1,
          },
          text: "음식은 순수하고 간단한 재료로 몸을 영양분을 공급해야 한다",
        },
      ],
      text: "당신의 음식 철학은:",
    },
  ],
};

// Map missing locales to English for questions
["ja", "zh", "es", "fr"].forEach((loc) => {
  (FOOD_PERSONALITY_QUESTIONS as any)[loc] = FOOD_PERSONALITY_QUESTIONS.en;
});

export const getFoodPersonalityQuestions = (
  locale: Locale = "en",
): FoodPersonalityQuestion[] => {
  const questions =
    (
      FOOD_PERSONALITY_QUESTIONS as Record<
        string,
        FoodPersonalityQuestion[] | undefined
      >
    )[locale] || FOOD_PERSONALITY_QUESTIONS.en;
  return questions;
};
